#!/usr/bin/env bash
#####################################################################
# Script Name  : z-backup
# Description  : local backup of /etc, /home, and /data/installations
#              : to a designated folder on a second internal drive.
# Dependencies : rsync
# Arguments    : none
# Author       : Copyright (C) 2020, Richard Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 07 Jun 2020
# Updated      : 27 Dec 2025
# Version      : 2.1.25361
# Comment      : Automatically limits log size to 30 entries.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
#####################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#####################################################################

trim_log() {
  local log_dir="$1"
  local log_file="$2"
  local log_len
  log_len=$(wc -l < "$log_dir/$log_file")
  while [[ "$log_len" -gt 30 ]]; do
    sed -i '1d' "$log_dir/$log_file"
    (( log_len-- ))
  done
}

local_backup() {
  local log_dir="/var/log"
  local log_file="backup.log"
  local backup_dir="/data/backup"
  local error_log="/error.log"

  [[ -d "$backup_dir" ]] || mkdir -p "$backup_dir"
  [[ -d "$log_dir" ]] || mkdir -p "$log_dir"
  [[ -f "$backup_dir/$error_log" ]] && rm "$backup_dir/$error_log"

  {
    printf "%(%a|%F|%R)T|"
    if rsync -aH --delete --exclude="/backup/backup/" /etc /home /data "$backup_dir/" 2>> "$backup_dir/$error_log"; then
      printf "successful\n"
      printf "%(%a, %F %R)T - Local Backup was successful.\n" >> "$backup_dir/$error_log"
    else
      printf "had errors (%d)\n" "$?"
      printf "%(%a, %F %R)T - Local Backup had errors.\n" >> "$backup_dir/$error_log"
    fi
    sync
  } >> "$log_dir/$log_file"
  trim_log "$log_dir" "$log_file"
}

main() {
  local_backup
  exit
}

main "$@"
