#!/usr/bin/env bash
##########################################################################
# Script Name  : z-clean-tmp v1.3
# Description  : Removes files from /tmp accessed more than 2 days prior
# Dependencies : find
# Arguments    : None
# Author       : Copyright (C) 2019, Richard B. Romig, MosfaNet
# Email        : rick.romig@gmail.com
# Comments     : Only deletes files in /tmp that are not owned by root.
# Created      : 31 July 2019
# Last updated : 21 Jul 2025
# Version      : 1.1.25202
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

set -eu

/usr/bin/find /tmp -type f \( ! -user root \) -atime +2 -delete 2>/dev/null

exit
