#!/usr/bin/env bash
###############################################################################
# Script Name  : z-defrag
# Description  : Script to check defrag condition on spinning drives.
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2021-2025, Richard B. Romig
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 01 Jan 2021
# Updated      : 15 Feb 2025
# Comments     : Do not run e4defrag on SSD or NVME drives.
#              : anacron job: Copy to /etc/cron.monthly as root (or sudo) user
#              : cron job: Copy to /usr/local/bin or /opt/bin as root (or sudo) user
# License      : GNU General Public License, version 2.0
###############################################################################

set -eu

# shellcheck disable=SC2001
over_line() {
  local char len line title
  title="$1"
  char="${2:--}"
  len=${#char}
  (( len > 1 )) && char=${char::1}
  line=$(echo "$title" | sed "s/./$char/g")
  printf "%s\n%s\n"  "$line" "$title"
}

main() {
	local log_dir="/var/log"
	local log_file="defrag.log"
	local host_name="${HOSTNAME:-$(hostname)}"
  local script="${0##*/}"
  local version="2.11.25189"
	{
		printf "Defrag Report for %s: %(%a %F %R)\n\n" -1 "$host_name"
		case "$host_name" in
			hp-800-g1-usdt|hp-probook-6570|e-475m|hp-mini-110 )
				printf "SSD - e4defrag not run.\n"
			;;
			hp-850-g3 )
				printf "NVMe - e4defrag not run.\n"
			;;
			hp-6005 )
				/usr/sbin/e4defrag -c / /home /data
			;;
			hp-800g2-sff )
				printf "/dev/sda is an SSD, e4defrag not run.\n\n"
				/usr/sbin/e4defrag -c /home
			;;
			* )
				/usr/sbin/e4defrag -c / /home
		esac
		over_line "$script $version"
	} > "$log_dir/$log_file" 2>&1
	[[ -f "$log_dir/$log_file" ]] && sed -i '/^e4defrag/d;/0-30/d;/^ Done/d' "$log_dir/$log_file"
	exit
}

main "$@"
