#!/usr/bin/env bash
###############################################################################
# Script Name  : z-defrag
# Description  : Script to check defrag condition on spinning drives.
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2021-2025, Richard B. Romig
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 01 Jan 2021
# Updated      : 08 Oct 2025
# Comments     : Do not run e4defrag on SSD or NVME drives.
#              : anacron job: Copy to /etc/cron.monthly as root (or sudo) user
#              : cron job: Copy to /usr/local/bin or /opt/bin as root (or sudo) user
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
###############################################################################

# shellcheck disable=SC2001
over_line() {
  local char len line title
  title="$1"
  char="${2:--}"
  len=${#char}
  (( len > 1 )) && char=${char::1}
  line=$(echo "$title" | sed "s/./$char/g")
  printf "%s\n%s\n"  "$line" "$title"
}

main() {
	local rootrota homerota datarota
	local log_file="/var/log/defrag.log"
	local host_name="${HOSTNAME:-$(hostname)}"
	local script="${0##*/}"
  local version="3.1.25281"
	rootrota=$(lsblk -o ROTA,MOUNTPOINT | awk '$NF == "/" {print $1}')
	homerota=$(lsblk -o ROTA,MOUNTPOINT | awk '$NF == "/home" {print $1}')
	datarota=$(lsblk -o ROTA,MOUNTPOINT | awk '$NF == "/data" {print $1}')

	{
		printf "Defrag Report for %s: %(%a %F %R)T\n\n" "$host_name" -1
		if [[ "$rootrota" -eq 1 && "$homerota" -eq 1 && "$datarota" -eq 1 ]]; then
			/usr/sbin/e4defrag -c / /home /data
		elif [[ "$rootrota" -eq 1 && "$homerota" -eq 1 && "$datarota" -ne 1 ]]; then
			/usr/sbin/e4defrag -c / /home
		elif [[ "$rootrota" -eq 1 && "$homerota" -ne 1 && "$datarota" -eq 1 ]]; then
			/usr/sbin/e4defrag -c / /data
		elif [[ "$rootrota" -eq 1 && "$homerota" -ne 1 && "$datarota" -ne 1 ]]; then
			usr/sbin/e4defrag -c /
		elif [[ "$rootrota" -ne 1 && "$homerota" -eq 1 && "$datarota" -eq 1 ]]; then
			/usr/sbin/e4defrag -c /home /data
		elif [[ "$rootrota" -ne 1 && "$homerota" -eq 1 && "$datarota" -ne 1 ]]; then
			/usr/sbin/e4defrag -c /home
		elif [[ "$rootrota" -ne 1 && "$homerota" -ne 1 && "$datarota" -eq 1 ]]; then
			/usr/sbin/e4defrag -c /data
		else
			printf "No spinning drives - e4defrag not run\n"
		fi
		over_line "$script $version"
	} > "$log_file" 2>&1
	[[ -f "$log_file" ]] && sed -i '/^e4defrag/d;/0-30/d;/^ Done/d' "$log_file"
	exit
}

main "$@"
