#!/usr/bin/env bash
###############################################################################
# Script Name  : z-update
# Description  : Unattended updates using anacron or cron
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2023, Richard B. Romig
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 20 Jun 2023
# Updated      : 06 Sep 2026
# Version      : 2.8.26249
# Comments     : anacron job: Copy to /etc/cron.weekly as root (or sudo) user
#              : cron job: Copy to /usr/local/bin or /opt/bin as root (or sudo) user
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

REBOOT_FLAG=1

# shellcheck disable=SC2001
# See if you can use ${variable//search/replace} instead.
# In this case parameter expansion does not work.
over_line() {
	local char line
	local -r title="$1"
	char="${2:--}"
	char="${char::1}"
	line=$(sed "s/./$char/g" <<< "$title")
	printf "%s\n%s\n"  "$line" "$title"
	return 0
}

check_disk_space() {
	local df_stats r_size r_used r_perc r_avail
	df_stats=$(awk 'NR==2 {print $2,$3,$4,$5}' <(df -h /))
	r_size=$(cut -d ' ' -f1 <<< "$df_stats")
	r_used=$(cut -d ' ' -f2 <<< "$df_stats")
	r_avail=$(cut -d ' ' -f3 <<< "$df_stats")
	r_perc=$(cut -d ' ' -f4 <<< "$df_stats")
	printf "\nDisk space used (root): %s/%s %s used, %s available.\n" "$r_used" "$r_size" "$r_perc" "$r_avail"
	return 0
}

check_flatpaks() {
	local -i fp_count
	if ! command -v flatpak >/dev/null 2>&1; then
		printf "Flatpak is not installed.\n" >&2
		return "$E_NOT_INSTALLED"
	fi
	fp_count=$(wc -l < <(flatpak list))
	if [[ $fp_count -eq 0 ]]; then
		printf "No Flatpak packages installed.\n" >&2
		return "$E_NOT_INSTALLED"
	fi
	update_flatpaks
	return 0
}

update_flatpaks() {
	printf "Flatpak updates:\n"
	sed '/^$/d' < <(flatpak update --system --noninteractive --force-remove --assumeyes 2>/dev/null)
	return "$?"
}

get_updates() {
	local nupd fields field1 field2 field3
	/usr/bin/apt-get update
	fields=$(awk '$2 == "upgraded," {print $1,$3,$6,$(NF-2)}' <(apt-get dist-upgrade -s))
	field1=$(cut -d' ' -f1 <<< "$fields")
	field2=$(cut -d' ' -f2 <<< "$fields")
	field3=$(cut -d' ' -f3 <<< "$fields")
	nupd=$((field1 + field2 + field3))
	if [[ "$nupd" -eq 0 ]]; then
		printf "\nPackages are up to date.\n"
		return 0
	fi
	printf "\n*** Installing updates ***\n"
	DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get dist-upgrade -yy
	return "$?"
}

autoremove_packages() {
	local -i npkgs
	npkgs=$(awk '$2 == "upgraded," {print $6}' <(apt-get autoremove -s))
	if [[ "$npkgs" -eq 0 ]]; then
		printf "No packages to be removed.\n"
		return 0
	fi
	DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get autoremove --purge -yy
	return "$?"
}

system_reboot() {
	[[ -f /var/run/reboot-required.pkgs ]] && cat /var/run/reboot-required.pkgs
	printf "\n*** REBOOT REQUIRED ***\n"
	REBOOT_FLAG=0
	return 0
}

main() {
	local -r script="${0##*/}"
	local -r version="2.8.26249"
	local -r lhost="${HOSTNAME:-$(hostname)}"
	local -r log_file=/var/log/update.log
	local -r sed_file=/usr/share/misc/updatelog.sed
	{
		printf "%s weekly update\n" "$lhost"
		printf "Date: %(%a %F %R)T\n"
		check_disk_space
		printf "\n*** Checking for updates ***\n"
		get_updates
		printf "\n*** Cleaning APT cache ***\n"
		/usr/bin/apt-get autoclean
		printf "\n*** Removing orphaned packages ***\n"
		autoremove_packages
		printf "\n*** Flatpak updates ***\n"
		check_flatpaks
		check_disk_space
		[[ -f /var/run/reboot-required || -f /run/reboot-required ]]  && system_reboot
		over_line "$script $version"
	} > "$log_file" 2>&1
	sed -i -f "$sed_file" "$log_file"
	(( REBOOT_FLAG == 0 )) && systemctl reboot || exit
}

main "$@"
