#!/usr/bin/env bash
##########################################################################
# Script Name  : z-ytdlp-update
# Description  : Updates youtube-dl automatically using anacron
# Dependencies : yt-dlp (downloaded from GitHub)
# Arguments    : None
# Author       : Copyright (C) 2023, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 20 Jun 2023
# Last updated : 21 Jul 2025
# Comments     : copy as root to /etc/cron.daily
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

set -eu

main() {
	local update_status
	local log_dir="/var/log"
	local log_file="ytdlpup.log"
	# local sed_file="/usr/share/misc/ytdlp-uplog.sed"
	update_status=$(/usr/local/bin/yt-dlp --update | awk '/Latest version/ {print $3}' | sed 's/stable@//')
	[[ "$update_status" ]] || update_status="unavailable"
	printf "%(%F|%R)T|%s\n" -1 "$update_status" >> "$log_dir/$log_file" 2>&1
	# sed -i -f "$sed_file" "$log_dir/$log_file"
	# Remove top entry if more than 30 entries.
	log_len=$(wc -l < "$log_dir/$log_file")
	[[ "$log_len" -gt 30 ]] && sed -i '1d' "$log_dir/$log_file"
	exit
}

main "$@"
