#!/usr/bin/env bash
##########################################################################
# Script Name  : zz-clean
# Description  : Clean apt cache and remove orphaned packages & obsolete config files.
# Dependencies : None
# Arguments    : None
# Author       : Copyright © 2024, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
# Created      : 28 Dec 2024
# Updated      : 05 Sep 2026
# Version      : 1.5.26248
# Comments     : Anacron - copy to /etc/cron.monthly/
#              : Cron - copy to /usr/local/bin/ or /opt/bin/
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

# shellcheck disable=SC2001
# See if you can use ${variable//search/replace} instead.
# In this case parameter expansion does not work.
over_line() {
	local char line
	local -r title="$1"
	char="${2:--}"
	char="${char::1}"
	line=$(sed "s/./$char/g" <<< "$title")
	printf "%s\n%s\n"  "$line" "$title"
	return 0
}

autoremove_packages() {
	local -i npkgs
	npkgs=$(grep "^[[:digit:]]\+ upgraded" < <(apt-get autoremove -s) | cut -d' ' -f6)
	if [[ "$npkgs" -gt 0 ]]; then
		DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get autoremove  --purge -yy
	else
		printf "No packages to be removed.\n"
	fi
	return "$?"
}

main() {
	local -r script="${0##*/}"
	local -r version="1.5.26248"
	local -i code=0
	{
		printf "Autoclean log: %(%a %F %R)T\n"
		printf "\nCleaning APT cache...\n"
		DEBIAN_FRONTEND=noninteractive apt-get autoclean
		printf "\nRemoving orphaned packages...\n"
		autoremove_packages
		code="$?"
		over_line "$script $version"
	} > /var/log/clean.log 2>&1
	exit "$code"
}

main "$@"
