#!/usr/bin/env bash
##########################################################################
# Script Name  : zz-clean
# Description  : Clean apt cache and remove orphaned packages & obsolete config files.
# Dependencies : None
# Arguments    : None
# Author       : Copyright © 2024, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
# Created      : 28 Dec 2024
# Last updated : 11 Oct 2025
# Comments     : Anacron - copy to /etc/cron.monthly/
#              : Cron - copy to /usr/local/bin/ or /opt/bin/
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

autoremove_packages() {
  local npkgs
  npkgs=$(apt-get autoremove -s | grep "^[[:digit:]]\+ upgraded" | cut -d' ' -f6)
  if [[ "$npkgs" -gt 0 ]]; then
    DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get autoremove  --purge -yy
  else
    printf "No packages to be removed.\n"
  fi
}

# shellcheck disable=SC2001
over_line() {
  local char len line title
  title="$1"
  char="${2:--}"
  len=${#char}
  (( len > 1 )) && char=${char::1}
  line=$(echo "$title" | sed "s/./$char/g")
  printf "%s\n%s\n"  "$line" "$title"
}

main() {
  local script="${0##*/}"
  local version="1.2.25284"

  {
    printf "Autoclean log: %(%a %F %R)T\n"
    printf "\nCleaning APT cache...\n"
    DEBIAN_FRONTEND=noninteractive apt-get autoclean
    printf "\nRemoving orphaned packages...\n"
    autoremove_packages
    over_line "$script $version"
  } > /var/log/clean.log 2>&1
  exit
}

main "$@"
