#!/usr/bin/env bash
###############################################################################
# Script Name  : apt-search
# Description  : Uses fuzzy-finder (fzf) to list and select apps to install.
# Dependencies : fzf
# Arguments    : [query-term]
# Author       : Copyright © 2023, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
# Created      : 22 Nov 2023
# Last updated : 22 Nov 2023, version 0.1.0
# Comments     : Kris Occipinti, https://filmsbykris.com/v7/
#              : https://gitlab.com/metalx1000/MyBin/-/blob/master/linux/shell/apt-search
# TODO (Rick)  : 
# License      : GNU General Public License, version 2.0
###############################################################################

command -v fzf > /dev/null 2>&1 || { echo "fzf is not installed." >&2; exit 1; }

if [[ "$1" ]]; then
	query="$1"
else
	read -rp "Enter search query: " query
fi
[[ "$query" ]] || exit

pkg="$(aptitude search "$query" | fzf --prompt "Select packages: " -m | awk '{print $2}' | tr "\n" " ")"
[[ "$pkg" ]] || exit
sudo apt install "$pkg"
exit
