#!/usr/bin/env bash
###############################################################################
# Script Name  : apt-search
# Description  : Uses fuzzy-finder (fzf) to list and select apps to install.
# Dependencies : fzf
# Arguments    : [query-term]
# Author       : Copyright © 2023, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
# Created      : 22 Nov 2023
# Last updated : 04 Apr 2026
# Comments     : Based on a script by Kris Occipinti, https://filmsbykris.com/v7/
#              : https://gitlab.com/metalx1000/MyBin/-/blob/master/linux/shell/apt-search
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
###############################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib
source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

## Funtions ##

run_query() {
	local query="$1"
	local pkg
	pkg="$(aptitude search "$query" | fzf --prompt "Select packages: " -m | awk '{print $2}' | tr -d '\n')"
	if [[ -z "$pkg" ]]; then
		printf "No package selected.\n" >&2
		return
	fi
	if default_no	"Install ${pkg}?"; then
		sudo_login 2
		sudo apt install "$pkg"
	else
		printf "%s selected but not installed.\n" "$pkg"
	fi
}

main() {
	local script="${0##*/}"
	local version="4.0.26094"
	local query="$1"
	check_package fzf

	[[ "$query" ]] || read -rp "Enter search query: " query

	if [[ "$query" ]]; then
		run_query "$query"
	else
		printf "No search query entered.\n"
	fi
	over_line "$script $version"
	exit
}

## Execution ##

main "$@"
