#!/usr/bin/env bash
###############################################################################
# Script Name  : apt-search
# Description  : Uses fuzzy-finder (fzf) to list and select apps to install.
# Dependencies : fzf
# Arguments    : [query-term]
# Author       : Copyright © 2023, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
# Created      : 22 Nov 2023
# Last updated : 25 Jun 2025
# Comments     : Kris Occipinti, https://filmsbykris.com/v7/
#              : https://gitlab.com/metalx1000/MyBin/-/blob/master/linux/shell/apt-search
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

check_fzf() {
	command -v fzf > /dev/null 2>&1 && return 0 || return 1
}

leave() {
	local script="${0##*/}"
	local version="2.1.25176"
	printf "%s %s\n" "$script" "$version"
	exit
}

run_query() {
	local pkg
	pkg="$(aptitude search "$query" | fzf --prompt "Select packages: " -m | awk '{print $2}' | tr "\n" " ")"
	[[ "$pkg" ]] || leave
	sudo apt install "$pkg"
}

main() {
	local query
	check_fzf || { echo "fzf is not installed." >&2; leave; }
	if [[ "$1" ]]; then
		query="$1"
	else
		read -rp "Enter search query: " query
	fi
	[[ "$query" ]] || leave
	run_query
	leave
}

main "$@"