#!/usr/bin/env bash
##########################################################################
# Script Name  : boxes-spice
# Description  : Installs Spice Tools Guest Additions to a Gnome Boxes VM
# Dependencies : none
# Arguments    : none
# Author       : Copyright (C) 2021, Richard B. Romig, 16 Sep 2021
# Created      : 16 Sep 2021
# Updated      : 23 Jun 2024
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     : Supports Arch and Debian-based operating systems.
# TODO (Rick)  :
# License      : GNU General Public License, version 2
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

## Functions ##

main() {
  local script version
  script="${0##*/}"
  version="1.5.25174"
  sudo_login 2
  box "$script $version"
  printf "Installs Spice Tools Guest Additions to a Gnome Boxes VM\n"
  if is_arch; then
    sudo pacman -Sy
    sudo pacman -S spice-vdagent spice-webdavd
  elif debian_based; then
    sudo apt-get update
    sudo apt-get install -y spice-vdagent spice-webdavd
  else
    die "Unsupported operating system." 1
  fi
  leave "Spice Tools Guest Additions installed."
}

## Execution ##

main
