#!/usr/bin/env bash
#####################################################################
# Script Name  : brasero-bug-fix
# Description  : Ubuntu 18.04/Linux Mint 19.x bug fix
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2019, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 12 Feb 2019
# Updated      : 30 Sep 2024
# Comments     : Bug in Brasero where you can't burn CDs
#              : When a blank CD or DVD is inserted but pop-up screen, but
#              : gives no application to select or options are greyed out:
#              : From Joe Collins & Matt Hartley
# TODO (Rick)  :
# License      : GNU General Public License, version 2
#####################################################################

## Global Variables ##

## Functions ##

intro () {
  cat << _INTRO_
  There is a bug in Brasero in Ubuntu 18.04 and in distributions derived from it
  (Linux Mint 19.x) that prevents the user from writng an audio CD. This script
  will set the permissions on the files necessary to enable this functionality.
  Thanks to Joe Collins and Matt Hartley for the information.

_INTRO_
}

set_permissions() {
  echo "Setting permissions..."
  sudo chmod -v 4711 /usr/bin/cdrdao
  sudo chmod -v 4711 /usr/bin/wodim
  sudo chmod -v 0755 /usr/bin/growisofs
}

mimeapps_list_add() {
  local mimeapps_list="$HOME/.local/share/applications/mimeapps.list"
  if [[ -f "$HOME/$mimeapps_list" ]]; then
    if grep -qw 'brasero' "$HOME/$mimeapps_list"; then
      echo "Updating mimeapps.iist..."
      {
        echo "x-content/blank-cd=brasero.desktop;"
        echo "x-content/blank-dvd=brasero.desktop;"
      } >> "$mimeapps_list"
    fi
  fi
}

main() {
  local script version
  script=$(basename "$0")
  version="3.0.24274"
  echo "$script v$version"
  if command -v brasero > /dev/null 2>&1; then
    intro
    set_permissions
    mimeapps_list_add
  else
    printf "Brasero is not installed.\nNothing to do.\n"
  fi
  exit
}

## Execution ##

main "$@"