#!/usr/bin/env bash
#####################################################################
# Script Name  : Brasero-bug-fix
# Description  : Ubuntu 18.04/Linux Mint 19.x bug fix
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2019, Richard B. Romig, 12 February 2019
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     : Bug in Brasero where you can't burn CDs
#              : When a blank CD or DVD is inserted but pop-up screen, but
#              : gives no application to select or options are greyed out:
#              : From Joe Collins & Matt Hartley
# TODO (Rick)  :
# License      : GNU General Public License, version 2
#####################################################################

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.2.2"
readonly _updated="10 Nov 2023"

## Functions ##

intro () {
  cat <<- EOF
  There is a bug in Brasero in Ubuntu 18.04 and in distributions derived from it
  (Linux Mint 19.x) that prevents the user from writng an audio CD. This script
  will set the permissions on the files necessary to enable this functionality.
EOF
}

set_permissions() {
  echo "Setting permissions..."
  sudo chmod -v 4711 /usr/bin/cdrdao
  sudo chmod -v 4711 /usr/bin/wodim
  sudo chmod -v 0755 /usr/bin/growisofs
}

mimeapps_list_add() {
  local mimeapps_list=".local/share/applications/mimeapps.list"
  if [[ -f "$HOME/$mimeapps_list" ]]; then
    if grep -qw 'brasero' "$HOME/$mimeapps_list"; then
      {
        echo "x-content/blank-cd=brasero.desktop;"
        echo "x-content/blank-dvd=brasero.desktop;"
      } >> "$HOME/$mimeapps_list"
    fi
  fi
}

## Execution ##

echo "$_script v$_version ($_updated)"
intro

if exists brasero; then
  set_permissions
  mimeapps_list_add
fi

exit
