#!/usr/bin/env bash
##########################################################################
# Script Name  : bu-cinnkeys
# Description  : Backup Cinnamon keybindings to a file.
# Dependencies : none
# Arguments    : none
# Author       : Copyright (C) 2021, Richard B. Romig, 12 May 2021
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
# Comments     : Backs up Cinnamon keybindings to ~/.config
#              : Tested with Cinnamon DE on Mint 19.x & 20.x, LMDE 5, Debian 10/11
# TODO (Rick)  :
# License      : GNU General Public License, version 2
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.1.6"
readonly _updated="04 Feb 2023"
readonly bu_file="keybindings-backup.dconf"

## Execution ##

clear
echo "$_script v$_version ($_updated)"
echo "Creates a backup of the current Cinnamon desktop keybindings."
if is_cinnamon; then
  dconf dump /org/cinnamon/desktop/keybindings/ > "$HOME/.config/$bu_file"
  leave "Cinnamon Keybindings backed up to $HOME/.config/$bu_file."
else
  leave "The desktop environment is not Cinnamon."
fi
