#!/usr/bin/env bash
###############################################################################
# Script Name  : check-updates
# Description  : check for updates and install if necessary.
# Dependencies : apt-get (optional: nala, flatpak, cinnamon-spice-updater)
# Arguments    : see help()
# Author       : Copyright (C) 2018, Richard Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Crated       : 08 Dec 2018
# Updated      : 26 Jan 2026
# Comments     : For Debian/Ubuntu-based Linux distributions
#              : apt-get is better suited than apt for use in scripts.
#              : Lists available updates. Updates can be deferred.
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details.
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 81
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="10.0.26026"
SECONDS=0

## Functions ##

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
cleanup() {
  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
}

help() {
	local errcode="${1:-1}"
  local updated="26 Jan 2026"
	cat << _HELP_
${orange}$script${normal} $version, Upated: $updated
Performs a system update using either Apt-get or Nala.

${green}Usage:${normal} $script [-ahn]
${orange}Available options:${normal}
  -a  Perform a system upgrade using apt-get
  -c  Check for updates (No upgrade)
  -h  Show this help message and exit
  -n  Perform a system upgrade using nala
${orange}Notes:${normal}
  If nala is not installed, -n defers to using apt-get
_HELP_
  exit "$errcode"
}

check_disk_space() {
	local df_stats r_size r_used r_perc r_avail
	df_stats=$(awk 'NR==2 {print $2,$3,$4,$5}' <(df -h /))
	r_size=$(cut -d ' ' -f1 <(echo "$df_stats"))
	r_used=$(cut -d ' ' -f2 <(echo "$df_stats"))
	r_avail=$(cut -d ' ' -f3 <(echo "$df_stats"))
	r_perc=$(cut -d ' ' -f4 <(echo "$df_stats"))
  printf "\nDisk space used (root): %s / %s %s used, %s available.\n" "$r_used" "$r_size" "$r_perc" "$r_avail"
}

reboot_system() {
  cat /var/run/reboot-required.pkgs
  printf "\n%s*** REBOOT REQUIRED ***%s\n" "$orange" "$normal"
  if default_no "Do you want to reboot now?"; then
    printf "Rebooting the system...\n"
    sleep 10
    sudo systemctl reboot
  else
    printf "\n%s Please reboot your system as soon as possible.\n" "$RED_WARNING"
  fi
}

update_apt_cache() {
  local cache_file current_time updated_time time_diff threshold
  cache_file="/var/cache/apt/pkgcache.bin"
  current_time=$(date +%s)
  updated_time=$(stat -c%Y "$cache_file")
  time_diff=$(( current_time - updated_time ))
  # threshold values: 86400 = 24 hours, 43200 = 12 hours, 21600 = 6 hours 10800 = 3 hours
  threshold=10800
  if [[ "$time_diff" -le "$threshold" ]]; then
    printf "%sApt cache is up to date.%s\n" "$orange" "$normal"
  else
    printf "%sUpdating apt cache...%s\n" "$orange" "$normal"
    sudo apt-get update
  fi
}

install_updates() {
  printf "\n%sInstalling updates...%s\n" "$orange" "$normal"
  sudo apt-get dist-upgrade -yy
}

clean_apt_cache() {
  printf "\n%sCleaning up apt cache...%s\n" "$orange" "$normal"
  sudo apt-get autoclean
}

remove_orphans() {
  local npkgs
  npkgs=$(awk '$2 == "upgraded," {print $6}' <(apt-get autoremove -s))
  printf "\n%sRemoving orphaned packages...%s\n" "$orange" "$normal"
  if [[ "$npkgs" -gt 0 ]]; then
    sudo apt-get autoremove --purge -yy
  else
    printf "No packages to be removed.\n"
  fi
}

update_complete() {
  local num_updates="$1"
  printf "\n%sUpdate complete. %d" "$orange" "$num_updates"
  (( num_updates > 1 )) && printf  " updates were" || printf  " update was"
  printf " installed.%s\n" "$normal"
}

defer_updates() {
  local num_updates="$1"
  printf "\n%sNo updates installed. %d" "$orange" "$num_updates"
  (( num_updates > 1 )) && printf " updates were" || printf " update was"
  printf " deferred.%s\n" "$normal"
}

update_flatpaks() {
  local fp_updates
  fp_updates=$(grep -c 'updatable' <(flatpak update --app --noninteractive))
  if [[ "$fp_updates" -eq 0 ]]; then
    printf "No flatpak updates currently available\n"
  else
    printf "Updating flatpaks...\n"
    printf "User installations...\n"
    flatpak update --user --noninteractive --force-remove --assumeyes | sed '/^$/d'
    printf "System-wide installations...\n"
    sudo flatpak update --system --noninteractive --force-remove --assumeyes  2> /dev/null | sed '/^$/d'
  fi
}

check_flatpak() {
  local fp_count
  if exists flatpak; then
    fp_count=$(flatpak list | wc -l)
    [[ "$fp_count" -eq 0 ]] && { printf "No Flatpak packages installed.\n"; return; }
    update_flatpaks
  else
    printf "Flatpak is not installed.\n"
  fi
}

update_spices() {
  printf "\n%sCinnamon Spices:%s\n" "$orange" "$normal"
  cinnamon-spice-updater --update-all
}

nala_update() {
  printf "%sChecking for updates...%s\n" "$orange" "$normal"
  sudo nala upgrade
  if default_no "Run autoremove/autopurge?"; then
    printf "\n%sRemoving orphaned packages...%s\n" "$orange" "$normal"
    sudo nala autoremove
    printf "\n%sPurging obsolete configuration files..%s\n" "$orange" "$normal"
    sudo nala autopurge --config
  else
    printf "Autoremove and autopurge deferred.\n"
  fi
  printf "\n"
}

apt_update() {
  local nupd
  printf "%sChecking for updates...%s\n" "$orange" "$normal"
  update_apt_cache
  apt-get dist-upgrade -s > "$tmp_file"
  nupd=$(count_updates)
  if (( nupd > 0 )); then
    printf "%sSummary:%s\n" "$orange" "$normal"
    sed -ne '/^Calculating/,/newly/p' "$tmp_file" | sed '1d'
    apt_menu "$nupd"
  else
    printf "%sSummary:%s\n" "$orange" "$normal"
    sed -ne '/^Calculating/,/newly/p' "$tmp_file" | sed '1d'
    printf "\nPackages are up to date\n"
  fi
}

count_updates() {
	local field1 field2 field3
	local -i count=0
	field1=$(awk '$8 == "remove" {print $1}' "$tmp_file")
	field2=$(awk '$8 == "remove" {print $3}' "$tmp_file")
	field3=$(awk '$8 == "remove" {print $6}' "$tmp_file")
	count=$((field1 + field2 + field3))
	echo "$count"
}

apt_menu() {
  local nupd options _opt
	nupd="$1"
	COLUMNS=40
	printf "\n%s%sUpdate options:%s\n" "$underline" "$green" "$normal"
	PS3="Choose an option: "
	options=(
		"Install updates."
		"Install updates and clean cache."
		"Install updates and remove orphaned packages."
		"Install updates, clean cache, and remove orphaned packages."
		"Defer updates until later."
	)
	select _opt in "${options[@]}"; do
		case $REPLY in
			1 )
				install_updates
				update_complete "$nupd"
				break
			  ;;
			2 )
				install_updates
				clean_apt_cache
				update_complete "$nupd"
				break
			  ;;
			3 )
				install_updates
				remove_orphans
				update_complete "$nupd"
				break
			  ;;
			4 )
				install_updates
				clean_apt_cache
				remove_orphans
				update_complete "$nupd"
				break
			  ;;
			5 )
				defer_updates "$nupd"
				break
			  ;;
			* )
				printf "%sInvalid option!%s Select 1..%d\n" "$lightred" "$normal" "${#options[@]}" >&2
		esac
	done
}

show_header() {
  local local_host="${HOSTNAME:-$(hostname)}"
  clear
  cat << _HEADER_
${bold}${orange}$script $version
System: $local_host (ip: $(local_ip))
Distro: $(get_distribution)
Kernel: $(uname -sr)${normal}
_HEADER_
}

check_spice_updates() {
  local type types num
  types=(applet desklet extension theme)
  for type in "${types[@]}"; do
    num=$(cinnamon-spice-updater --list-simple "$type" | wc -l)
    printf "%d spice %s " "$num" "$type"
    [[ "$num" -ne 1 ]] && printf "updates " || printf "uppdate "
    printf "available\n"
  done
}

check_flatpak_updates() {
  local fp_updates
  fp_updates=$(grep -c 'updatable' <(flatpak update --app --noninteractive))
  printf "%d flatpak " "$fp_updates"
  [[ "$fp_updates" -ne 1 ]] && printf "updates " || printf "uppdate "
  printf "available\n"
}

check_for_updates() {
  local upgrades
  upgrades=$(tail -n1 <(sudo apt update 2>/dev/null))
  printf "%s\nChecking for updates...%s\n" "$orange" "$normal"
  awk -F'.' '{print $1"."}' <(printf "%s\n" "$upgrades")
}

other_checks() {
  exists cinnamon-spice-updater && update_spices
  printf "\n%sFlatpak:%s\n" "$orange" "$normal"
  check_flatpak
  check_disk_space
  over_line "Update completed in $(format_time $SECONDS)"
}

main() {
  local noOpt opt optstr OPTARG OPTIND
	noOpt=1
	optstr=":achn"
	while getopts "$optstr" opt; do
    case "$opt" in
      a )
        tmp_file=$(mktemp -q) || die "Failed to create temporary file." "$E_TEMP_DIR"
        trap cleanup EXIT
        show_header
        check_disk_space
        sudo_login 1
        apt_update
        other_checks
        ;;
      c )
        show_header
        sudo_login 1
        check_for_updates
        check_flatpak_updates
        check_spice_updates
        ;;
      h )
        help 0
        ;;
      n )
        show_header
        check_disk_space
        sudo_login 1
        if exists nala; then
          nala_update
        else
          tmp_file=$(mktemp -q) || die "Failed to create temporary file." "$E_TEMP_DIR"
          trap cleanup EXIT
          printf "Nala is not installed. Reverting to apt-get ...\n"
          apt_update
        fi
        other_checks
        ;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help "$E_INVALID_ARG"
		esac
		noOpt=0
  done
	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
	shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  [[ -f /var/run/reboot-required || -f /run/reboot-required ]] && reboot_system
  exit
}

## Execution ##

main "$@"
