#!/usr/bin/env bash
##########################################################################
# Script Name  : cinnkeys
# Description  : Backup/Restore Cinnamon keybindings to/from a file.
# Dependencies : none
# Arguments    : none
# Author       : Copyright (C) 2021, Richard B. Romig, MosfaNet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
# Created      : 12 May 2021
# Updated      : 14 Jun 2024
# Comments     : Backup of Cinnamon keybindings in ~/.config
#              : Tested with Cinnamon DE on Mint 19.x & 20.x, 21.x, LMDE 5/6, Debian 10/11/12
# TODO (Rick)  :
# License      : GNU General Public License, version 2
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="2.3.24166"
readonly _updated="14 Jun 2024"
readonly kb_bu="keybindings-backup.dconf"
readonly cfg_dir="$HOME/.config"
verbose_mode="$FALSE"

## Functions ##

help() {
  local errcode="${1:-1}"
  cat << _END_HELP_
${orange}$_script${normal} $_version, Upated: $_updated
Creates a backup file of Cinnamon keybindings and restores from a backup file.

${green}Usage:${normal} $_script [OPTION]

${orange}Available options:${normal}
  -d  Dumps Cinnamon keybindings to a backup file in ~/.config.
  -h  Displays this help text.
  -l  Loads Cinnamon keybindings from the backup file.
  -v  Enable verbose mode
_END_HELP_
  exit "$errcode"
}

show_message() {
	local message="$1"
	[[ "$verbose_mode" == "$TRUE" ]] && echo "$message"
}

## Execution ##

if is_cinnamon; then
  noOpt=1
  optstr=":dhlv"
  while getopts "$optstr" opt; do
    case "$opt" in
      d )
        show_message "Dumping keybindings to backup file."
        dconf dump /org/cinnamon/desktop/keybindings/ > "$cfg_dir/$kb_bu"
        printf "Cinnamon Keybindings dumped to %s\n" "$cfg_dir/$kb_bu"
      ;;
      h )
        help 0
      ;;
      l )
        if [[ -f "$cfg_dir/$kb_bu" ]]; then
          show_message "loading keybindings from backup file."
          dconf load /org/cinnamon/desktop/keybindings/ < "$HOME/.config/$kb_bu"
          printf "Cinnamon Keybindings loaded from %s\n" "$cfg_dir/$kb_bu"
        else
          pirntf "%s does not exist. Creating it...\n" "$kb_bu" >&2
          show_message "Dumping keybindings to backup file."
          dconf dump /org/cinnamon/desktop/keybindings/ > "$cfg_dir/$kb_bu"
          printf "Cinnamon Keybindings dumped to %s\n" "$cfg_dir/$kb_bu"
        fi
      ;;
      v )
        verbose_mode="$TRUE"
        show_message "Verbose mode enabled."
      ;;
      ? )
        printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
        help 2
    esac
    noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
else
  pirntf "The desktop environment is not Cinnamon.\n" >&2
  exit 1
fi
leave "$_script v$_version"