#!/bin/bash
###############################################################################
# Script Name  : clean-bin
# Description  : cleans ~/bin of *~ backup files and synchronizes scripts with 
#              : the script repository.
# Dependencies : find, rsync
# Arguments    : none
# Author       : Copyright (C) 2019, Richard Romig, 18 January 2019
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     : Script is retired.
#              : Only runs on primary computer.
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="2.2.3"
readonly _updated="12 Mar 2023"

## Functions ##

rm_tilde() {
  local bin_dir="$HOME/bin"
  # Find and remove files ending wih ~ (tilde)
  nbu=$(find ~/bin -type f -regex '\./.*~$' | wc -l)
  if  (( nbu > 0 )); then
    find "$bin_dir" -type f -regex '\./.*~$' -print -exec rm {} \;
    printf "\nRemoved %s '~' backup " "$nbu"
    (( nbu == 1 )) && printf "file" || printf "files"
    printf " in %s.\n" "$bin_dir"
  fi
}

check_host() {
  local loc_host="hp-800g2-sff"
  # Ensure script is only run from hp-800g2-ssf
  [[ "$loc_host" != "$(uname -n)" ]] && die "$_script must be run from ${loc_host}!"
}

sync_scripts() {
  local bin_dir="$HOME/bin"
  local script_repo="$HOME/gitea/scripts"
  printf "\nSynchronizing %s with %s ...\n" "$bin_dir" "$script_repo"
  rsync -av --delete --exclude '.git' "$bin_dir/" "$script_repo"/
}

## Execution ##

printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
printf "Cleans up and synchonizes scripts with the repo...\n"
check_host
rm_tilde
sync_scripts
exit
