#!/usr/bin/env bash
##########################################################################
# Script Name  : clean-apt-cache
# Description  : Cleans APT cache after 400 Bad Request or Hash Sum Mismatch error
# Dependencies : None
# Arguments    : See help() function for available options.
# Author       : Copyright © 2026, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail | rick.romig@mymetronet.net
# Created      : 10 Apr 2026
# Last updated : 10 Apr 2026
# Version      : 1.0.26100
# Comments     : https://oneuptime.com/blog/post/2026-03-02-troubleshoot-hash-sum-mismatch-errors-apt-ubuntu/
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib
source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

## Functions ##

clean_apt_cache() {
  sudo_login 1
  printf "Removing all cached package lists...\n"
  sudo rm -rf /var/lib/apt/lists/*
  printf "Clearing the downloaded package cache...\n"
  sudo apt clean
  printf "Updating and reloading the APT cache...\n"
  sudo apt update
}

main() {
  local -r script="${0##*/}"
  local -r version="1.0.26100"
  clean_apt_cache
  over_line "$script $version"
	exit
}

## Execution ##

main "$@"
