#!/usr/bin/env bash
###############################################################################
# Script Name  : clean-c
# Description  : Cleans up C programing in the current working directory
# Dependencies : none
# Arguments    : none
# Author       : Copyright (C) 2019, Richard Romig, 8 February 2019
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comment      : removes *~, *.o, and a.out in the current working directory
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

# Variables

_script=$(basename "$0"); readonly _script
readonly _version="0.1.0"
readonly _updated="04 Feb 2023"

readonly work_dir=$(dirname "$(readlink -f "$0")")

# Clean up current working directory, removing a.out, *.o *~ files

clear
box "$_script v$_version ($_updated)"
echo $'\n'$"Cleaning up $work_dir..."
find . -maxdepth 1 -type f \( -name "a.out" -o -iname "*.o" -o -iname "*~" \) -print -exec rm {} \;

exit
