#!/usr/bin/env bash
##########################################################################
# Script Name  : clone-repo
# Description  : Clone a git repository from local Gitea server or GitHub
# Dependencies : git
# Arguments    : See help() function for getopts flags
# Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 19 Oct 2022
# Updated      : 19 Apr 2026
# Comments     : clone_repo() is contained in functionlib
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Load function library ##
# shellcheck source=/home/rick/bin/functionlib
source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

## Global Variables ##

readonly script="${0##*/}"
readonly version="4.3.26109"
EC=0

## Functions ##

help() {
	local errcode="${1:-1}"
	local -r updated="19 Apr 2026"
	cat << _HELP_
${orange}$script${normal} $version, Upated: $updated
Clone a git repository from GitHub or the local Gitea server

${green}Usage:${normal} $script [-cfghipsw]
${orange}Available options:${normal}
  -c  Clone configs repository
  -f  Clone fnloc repository
  -g  Clone gitea server repository
  -h  Show this help message and exit
  -i  Clone i3wm-debian repository
  -p  Clone homepage repository
  -s  Clone scripts repository
  -w  Clone fnloc-win repository
_HELP_
  exit "$errcode"
}

check_repo() {
  local -r git_repo="$1"
  local -r dl_dir="$HOME/Downloads"
  if [[ ! $(find "$dl_dir/$git_repo" -type f 2>/dev/null) ]]; then
    clone_repo "$git_repo"
    return
  fi
  printf "%s is not empty. Updating the repository clone...\n" "$dl_dir/$git_repo"
  pushd "$dl_dir/$git_repo" || { EC="$E_POPD_PUSHD"; return; }
  git checkout .
  git pull
  popd || { EC="$E_POPD_PUSHD"; return; }
}

main() {
  local noOpt opt optstr OPTARG OPTIND
  noOpt=1
  optstr=":cfghilsw"
  check_package git
  while getopts "$optstr" opt; do
    case "$opt" in
      c )
        check_repo "configs" ;;
      f )
        check_repo "fnloc" ;;
      g )
        check_repo "gitea-server" ;;
      h )
        help 0 ;;
      i )
        check_repo "i3wm-debian" ;;
      p )
        check_repo "homepage" ;;
      s )
        check_repo "scripts" ;;
      w )
        check_repo "fnloc-win" ;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help "$E_INVALID_ARG"
    esac
		noOpt=0
  done
	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
	shift "$(( OPTIND - 1 ))"
	over_line "$script $version"
	exit "$EC"
}

## Execution ##

main "$@"
