#!/usr/bin/env bash
##########################################################################
# Script Name  : clone-repo
# Description  : Clone a git repository from local Gitea server
# Dependencies : git
# Arguments    : None
# Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 19 Oct 2022
# Updated      : 18 Aug 2024
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Global Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="3.2.24231"

## Functions ##

exist_git() {
  if command -v git > /dev/null 2>&1; then
    printf "git - [OK]\n"
    sleep 2
    printf '\e[A\e[K'
  else
    sudo apt-get install git -yyq
  fi
}

clone_repo() {
  local dl_dir git_repo gitea_svr
  git_repo="$1"
  gitea_svr="http://192.168.0.16:3000/Nullifidian"
  dl_dir="$HOME/Downloads"
  git clone "$gitea_svr/$git_repo.git" "$dl_dir/$git_repo"
}

main() {
  local index _repo
  printf "Available repositories:\n"
  COLUMNS=40
  PS3="Choose a repository to clone: "
  declare -a -r repos=( scripts configs i3debian deb12wm-scripts deb12wm-dotfiles gitea-server openboxdebian fnloc fnloc-win homepage )
  select _repo in "${repos[@]}" "Exit"; do
	  if (( REPLY == 1 + ${#repos[@]} )); then
		  printf "Exiting. No repository selected or cloned.\n"
		  break
	  elif (( REPLY > 0 && REPLY <= ${#repos[@]} )); then
      index=$((( REPLY - 1 )))
      printf "Cloning the %s repository...\n" "${repos[index]}"
		  clone_repo "${repos[index]}"
		  break
	  else
		  printf "Invalid option. Choose 1 - %d\n" "${#repos[@]}"
	  fi
  done
}

## Execution ##

exist_git

printf "%s v%s\n" "$_script" "$_version"
printf "Clone a repository from the local Gitea server.\n\n"
main
exit
