#!/bin/bash
#############################################################################
# Script Name  : cmp-bin-repo
# Description  : Compares file in ~/bin with file in ~/Projects/ repository.
# Dependencies : none
# Arguments    : Script to be compared
# Author       : Copyright (C) 2020 Richard B. Romig, 30 Mar 2020
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     : less will truncate lines longer than the column width.
#              : Script retired as of 04 Feb 2023
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
#############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091,SC2034

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.1.9"
readonly _updated="12 Mar 2023"
readonly bin_dir=$HOME"/bin"
readonly repo_dir=$HOME"/Projects"

readonly tcol=$(tput cols)   # number of columns in the terminal

## Functions ##

usage() {
  local errcode="${1:-2}"
  echo "Usage: $_script <script>"
  echo "Example: $_script my-script.sh"
  exit "$errcode"
}

introduction() {
  cat << EOF

  $_script v$_version (Updated: $_updated)

  Displays a side by comparison of two scripts.
  The version of the script in the ~/bin diirectory is on the left and the
  version of the same script in the local repository is displayed on the right.
  Line numbers will appear on the left. A pipe symbol "|" on the left side of
  the right column indicates a line that is different.

  After noting the line numbers that differ, the scripts can be viewed side by
  side in a text editor that supports a split screen display or in a CLI editor
  in a terminal such as Terminator where you can open the files side by side.

  It should be noted that the lines in the scripts may be truncated. Maximizing
  your terminal will aid in readability.
EOF
}

## Check arguments ##

if  [[ $# -eq 0 ]]; then
  echo "${lightred}ERROR:${normal} No argument passed." >&2
  usage 2
elif [[ ! -f "$bin_dir/$1" ]]; then
  echo "${lightred}ERROR:${normal} $1 not found in ~/bin." >&2
  usage 2
else
  fname="$1"
fi

## Execution ##

clear
introduction

echo $'\n'$"${green}Local repositories${normal}"
options=( "bash scripts" "homebank archive" "yt-dl utilities" "Quit" )
PS3="Select the repository: "
select opt in "${options[@]}"; do
  case $REPLY in
    1 ) repo="bashscripts"; break ;;
    2 ) repo="homebankarchive"; break ;;
    3 ) repo="yt-dl-utilities"; break ;;
    4 ) leave ""; break ;;
    * ) echo "${lightred}Invalid selection.${normal} Try again." ;;
  esac
done

[[ -f "$repo_dir/$repo/$fname" ]] || die "$fname does not exist in $repo_dir/$repo/" 1

clear
diff -y -W "$tcol" "$bin_dir/$fname" "$repo_dir/$repo/$fname" | less -N

leave "$_script v$_version ($_updated)"
