#!/usr/bin/env bash
#############################################################################
# Script Name  : corona-world
# Description  : Displays a world-wide chart of COVID-19 statistics
# Dependencies : curl, less, sed
# Arguments    :
# Author       : Richard B. Romig, 05 May 2020
# Email        : rick.romig@gmail.com
# Comments     : Code: https://github.com/sagarkarira/coronavirus-tracker-cli
#              : Twitter: https://twitter.com/ekrysi
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
#############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091,SC2034

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Variables ##

readonly _script=$(basename "$0")
readonly _version="0.1.7"
readonly _updated="29 Aug 2022"
readonly url="https://corona-stats.online/?minimal=true"

readonly today=$(date '+%d %b %Y')
readonly now=$(date '+%R %Z')
tmp_file=$(mktemp) || die "Failed to create temporary file." 1

## Functions ##

cleanup() {
  [[ -f "$tmp_file" ]] && rm "$tmp_file"
}

corona_data() {
  tfile="$1"
  cfile=$HOME/"Documents/corona-world-$(date '+%F').txt"
  cp "$tfile" "$cfile"
  chmod 664 "$cfile"
  echo "Corona data copied to $cfile"
}

## Execution ##

trap cleanup EXIT

check_package curl

curl -s -o "$tmp_file" "$url"   # Download the data to a temporary file
sed -i 's/\x1b\[[0-9;]*m//g' "$tmp_file"    # Remove the color codes

clear
echo -n "${bold}${blue}World Corona (COVID-19) virus stats for "
echo "$today, $now EDT${normal}"
less "$tmp_file"
echo -e "Data downloaded $today, $now\n"
echo "Save today's Corona data?"
PS3="Choice: "
select opt in "Yes" "No"; do
  case $REPLY in
    1 ) corona_data "$tmp_file"; break ;;
    2 ) echo "Corona data not copied."; break ;;
    * ) echo "${lightred}Invalid choice.${normal} 1 - Yes or 2 - No" ;;
  esac
done
echo $'\n'$"${orange}Stay safe.  Wear a mask! Wash your hands! Practice physical distancing.${normal}"
leave "[$_script v$_version ($_updated)]"
