#!/usr/bin/env bash
###############################################################################
# Script Name  : corona
# Description  : Status update for Corona (COVID-19) cases (selected countries)
# Dependencies : curl
# Arguments    : none
# Author       : Copyright (C) 2020, Richard B. Romig, 21 Mar 2020
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 21 Mar 2020
# Updated      : 01 Jul 2024
# Comments     : Code: https://github.com/sagarkarira/coronavirus-tracker-cli
#              : Twitter: https://twitter.com/ekrysi
# TODO (Rick)  : Create a version for public dissemination.
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="3.9.24183"
readonly url="https://corona-stats.online/?minimal=true"
today=$(date '+%d %b %Y'); readonly today
now=$(date '+%R %Z'); readonly now
tmp_file=$(mktemp) || die "Failed to create temporary file." 1

## Functions ##

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
cleanup() {
  [[ -f "$tmp_file" ]] && rm "$tmp_file"
}

corona_data() {
  local cfile tfile
  tfile="$1"
  cfile=$HOME/"Documents/corona-world-$(date '+%F').txt"
  cp "$tfile" "$cfile"
  chmod 664 "$cfile"
  echo "Corona data copied to $cfile"
}

## Execution ##

trap cleanup EXIT

check_package curl

# Download the data to a temporary file
curl -s -o "$tmp_file" "$url"
# Remove the color codes
sed -i 's/\x1b\[[0-9;]*m//g' "$tmp_file"

clear
echo -e "${bold}${blue}Corona (COVID-19) virus statistics - $today${normal}\n"

awk '/^Rank/' "$tmp_file"   # Header line
print_line "=" 140
awk '/USA/' "$tmp_file"
print_line "-" 140
awk '/Canada/' "$tmp_file"
print_line "-" 140
awk '/Mexico/' "$tmp_file"
print_line "-" 140
awk '/Philippines/' "$tmp_file"
print_line "-" 140
awk '/^ /' "$tmp_file"    # World totals
print_line "-" 140
echo -e "Data downloaded $today, $now\n"
default_no "Save today's Corona data?" && corona_data "$tmp_file" || echo "Corona data not copied."
echo $'\n'$"${orange}Stay safe. Wear a mask! Wash your hands! Practice physical distancing.${normal}"
leave "$_script v$_version"
