#!/usr/bin/env bash
###############################################################################
# Script Name  : create_script
# Description  : Creates script file with header information
# Dependencies : bat, micro (used by edit_view_quit function)
# Arguments    : See  help() function
# Author       : Copyright (C) 2023, Richard Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 01 Jan 2023
# Last updated : 07 Jul 2026
# Comments     : Creates script in the current working directory
#              : Templates include GNU GPL v2 license
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib
source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

VERBOSE_MODE="$FALSE"

help() {
  local -r script="$1"
  local -r version="$2"
  local errcode="${3:-1}"
  local updated="07 Jul 2026"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Creates a shell script with header comments (getopts optional)

${green}Usage:${normal} $script [-h] [-vb script-name] [-vg script-name]
${orange}Available options:${normal}
  -b  Create a standard BASH script
      $script -b <script-name>
  -h  Show this help message and exit
  -g  Create a BASH script using getopts
      $script -g <script-name>
  -v  Enable verbose mode (Must precede -b or -g flags)
      $script -vb <script-name>
_HELP_
  exit "$errcode"
}

show_message() {
	local message="$1"
	[[ "$VERBOSE_MODE" == "$TRUE" ]] && echo "$message"
	return 0
}

script_exists() {
	local -r scriptname="$1"
	if [[ -f "$scriptname" ]]; then
		printf "%s %s already exists.\n" "$RED_ERROR" "$scriptname" >&2
		return "$TRUE"
	fi
	return "$FALSE"
}

import_metadata() {
	local cur_yr init_ver today script_dir
	local -r script_name="$1"
	local -r template_file="$2"
	script_dir=$(dirname "$(readlink -f "${0}")")
	local -r template_dir="$script_dir/Templates"
	today=$(date +"%d %b %Y")
	cur_yr=$(printf "\UA9 %(%Y)T")
	init_ver="1.0.$(date +%y%j)"

	show_message "Creating the $script_name script:"
	show_message "Entering metadata..."

	sed -e '1d' \
		-e "s/<FILE>/$script_name/" \
		-e "s/<YEAR>/$cur_yr/" \
		-e "s/<TODAY>/$today/" \
		-e "s/<VERSION>/$init_ver/" "$template_dir/$template_file" > "$script_name"

	show_message "Setting file permissions to 755 (rwxr-xr-x)."
	chmod 755 "$script_name"
	printf "The %s script has been created." "$script_name"
	return 0
}

main() {
  local -r script="${0##*/}"
  local -r version="4.10.26188"
	local opt script_name template_file OPTARG OPTIND
	local -i noOpt=1
	local -r optstr=":b:hg:v"
	while getopts "$optstr" opt; do
		case "$opt" in
			b )
				script_name="$OPTARG"
				script_exists "$script_name" && help "$script" "$version" "$E_FILE_EXISTS"
				show_message "Script name: $script_name"
				template_file="bash-template.txt"
				show_message "Template: ${template_file##*/}"
			;;
			h )
				help 0
				;;
			g )
				script_name="$OPTARG"
				script_exists "$script_name" && help "$script" "$version" "$E_FILE_EXISTS"
				show_message "Script name: $script_name"
				template_file="bash-getopts.txt"
				show_message "Template: ${template_file##*/}"
				;;
			v )
				VERBOSE_MODE="$TRUE"
				show_message "Verbose mode enabled."
				;;
			: )
				printf "%s Must supply an argument to -%s.\n" "$RED_ERROR" "$OPTARG" >&2
				help "$script" "$version" "$E_MISSING_ARG"
			;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help "$script" "$version" "$E_INVALID_ARG"
		esac
		noOpt=0
	done
	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
	shift "$(( OPTIND - 1 ))"
	import_metadata "$script_name" "$template_file"
	edit_view_quit "$script_name"
	over_line "$script $version"
	printf "MOTD: "; leave ""
}

main "$@"
