#!/usr/bin/env bash
##########################################################################
# Script Name  : cronscripts
# Description  : Copies cron scripts to the appropriate directories.
# Dependencies : None
# Arguments    : See help function for list of arguments.
# Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Crated       : 17 Feb 2022
# Updated      : 08 Feb 2026
# Comments     : For jobs needinng root access, checks if repo script is
#              : newer than the one run by anacron/cron
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 81
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="10.0.26039"
localip="$(local_ip)"; readonly localip
# path variables
script_dir=$(dirname "$(readlink -f "${0}")"); readonly script_dir
readonly job_dir="$script_dir/cronjobs"
readonly files_dir="$script_dir/files"
readonly user_cron_path="$HOME/.local/bin/"
readonly opt_cron_path="/opt/bin/"
readonly sed_path="/usr/share/misc/"

## Functions ##

help() {
  local errcode="${1:-1}"
  local updated="08 Feb 2026"
  cat << _HELP_
${orange}$script${normal} $version, Updated: $updated
Copies cronjob scripts to the appropriate directories.

${green}Usage:${normal} $script [-abdfghmrstuv]
${orange}Available options:${normal}
  -a    Copy all applicable scripts.
  -c    Copy cloned repo update script.
  -d    Copy defrag script.
  -f    Copy Finance backup scripts.
  -g    Copy Git repository backup scripts.
  -h    Show this help message and exit.
  -m    Copy Main PC backup scripts.
  -r    Copy Redshift notification script.
  -s    Copy script archive script.
  -t    Copy empty trash script.
  -u    Copy system update script.
  -y    Copy yt-dlp update script.
  NOTE: Multiple arguments may be passed to the script.
_HELP_
  exit "$errcode"
}

is_older() {
  local cron_script="$1"
  local cron_path="$2"
  [[ "$cron_path/$cron_script" -ot "$job_dir/$cron_script" ]] && return "$TRUE" || return "$FALSE"
}

no_copy() {
  local message="$1"
  printf "%s not applicable to this system and was not copied.\n" "$message"
}

cp_clone_update() {
  case "$localip" in
    10|16|22 )
      no_copy "Cloned repository updates are" ;;
    * )
      is_older "clone-update.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/clone-update.sh" "$user_cron_path")
  esac
}

cp_git_bu() {
  case "$localip" in
    10|16 )
      is_older "git-dwm.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/git-dwm.sh" "$user_cron_path")
      is_older "git-bu.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/git-bu.sh" "$user_cron_path")
      ;;
    * )
      no_copy "Repository archives are"
  esac
}

cp_main_bu() {
  local buscript buscripts
  buscripts=(sync-nas.sh sync6005.sh journal-bu.sh passwdsync.sh repo-backup.sh)
  case "$localip" in
  10 )
      for buscript in "${buscripts[@]}"; do
        is_older "$buscript" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/$buscript" "$user_cron_path")
      done
      ;;
    * )
      no_copy "Main system sync scripts are"
  esac
}

cp_finance_bu() {
  case "$localip" in
    10 )
      is_older "fin-bu.sh" "$user_cron_path" &&  awk '{print "==> "$NF}' <(cp -pv "$job_dir/fin-bu.sh" "$user_cron_path")
      is_older "hb-archive.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/hb-archive.sh" "$user_cron_path")
      ;;
    * )
      no_copy "Finance archives are"
  esac
}

cp_scriptarchive() {
  case "$localip" in
    17|21|22|24 )
      no_copy "scriptarchive.sh is" ;;
    * )
      is_older "scriptarchive.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/scriptarchive.sh" "$user_cron_path")
  esac
}

cp_empty_trash() {
  is_older "empty-trash.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/empty-trash.sh" "$user_cron_path")
}

cp_redshift_notify() {
  case "$localip" in
    10|11|14|15|17|19|20|21 )
      no_copy "redshift-notify.sh is" ;;
    * )
      is_older "redshift-notify.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/redshift-notify.sh" "$user_cron_path")
  esac
}

cp_zdefrag() {
  local -r anacron_path="/etc/cron.monthly/"
  case "$localip" in
    10|12|13|14|15|17|19|20|21|22|23|24 )
      if [[ ! -f "$anacron_path/z-defrag" ]]; then
        sudo_login 1
        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-defrag" "$anacron_path")
      elif is_older "z-defrag" "$anacron_path"; then
        sudo_login 1
        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-defrag" "$anacron_path")
      fi
      ;;
    11|16 )
      [[ -d "$opt_cron_path" ]] || { sudo_login 1; sudo mkdir -p "$opt_cron_path"; }
      if [[ -f "$opt_cron_path/z-defrag" ]]; then
        sudo_login 1
        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-defrag" "$opt_cron_path")
      elif is_older "z-defrag" "$opt_cron_path"; then
        sudo_login 1
        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-defrag" "$opt_cron_path")
      fi
      ;;
    * )
      no_copy "z-defrag is"
  esac
}

cp_zupdate() {
  local -r sed_file="updatelog.sed"
  local -r anacron_path="/etc/cron.weekly/"
  case "$localip" in
    10|12|13|14|15|17|19|20|21|22|23|24|25 )
      if [[ -f "$anacron_path/z-update" ]]; then
        sudo_login 1
        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-update" "$anacron_path")
      elif is_older "z-update" "$anacron_path"; then
        sudo_login 1
        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-update" "$anacron_path")
      fi
      ;;
    11|16 )
      [[ -d "$opt_cron_path" ]] || { sudo_login 1; sudo mkdir -p "$opt_cron_path"; }
      if [[ -f "$sed_path/$sed_file" ]]; then
        sudo_login 1
        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-update" "$opt_cron_path")
      elif s_older "z-update" "$opt_cron_path"; then
        sudo_login 1
        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-update" "$opt_cron_path")
      fi
      ;;
  esac
  if [[ -f "$sed_path/$sed_file" ]]; then
    sudo_login 1
    awk '{print "==> "$NF}' <(sudo cp -v "$files_dir/$sed_file" "$sed_path")
  elif [[ "$sed_path/$sed_file" -ot "$files_dir/$sed_file" ]]; then
    sudo_login 1
    awk '{print "==> "$NF}' <(sudo cp -v "$files_dir/$sed_file" "$sed_path")
  fi
}

cp_zytdlpupdate() {
	local -r sed_file="ytdlp-uplog.sed"
  local -r anacron_path="/etc/cron.daily/"
  case "$localip" in
    10|15|17 )
      if [[ -f "$anacron_path/z-ytdlp-update" ]]; then
        sudo_login 1
        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-ytdlp-update" "$anacron_path")
      elif is_older "z-ytdlp-update" "$anacron_path"; then
        sudo_login 1
        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-ytdlp-update" "$anacron_path")
      fi
      if [[ -f "$sed_path/$sed_file" ]]; then
        sudo_login 1
        awk '{print "==> "$NF}' <(sudo cp -v "$files_dir/$sed_file" "$sed_path")
      elif [[ "$sed_path/$sed_file" -ot "$files_dir/$sed_file" ]]; then
        sudo_login 1
        sudo_login 1
        awk '{print "==> "$NF}' <(sudo cp -v "$files_dir/$sed_file" "$sed_path")
      fi
      ;;
    * )
      no_copy "z-ytdlp-update is"
  esac
}

main() {
  local noOpt opt optstr OPTARG OPTIND
  [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
  noOpt=1
  optstr=":acdfghmrstuy"
  printf "Copying updated cron scripts...\n"
  while getopts "$optstr" opt; do
    case "$opt" in
      a )
        cp_finance_bu
        cp_git_bu
        cp_scriptarchive
        cp_empty_trash
        cp_clone_update
        cp_zupdate
        cp_zdefrag
        cp_zytdlpupdate
        ;;
      c )
        cp_clone_update ;;
      d )
        cp_zdefrag ;;
      f )
        cp_finance_bu ;;
      g )
        cp_git_bu ;;
      h )
        help 0 ;;
      m )
        cp_main_bu ;;
      r )
        cp_redshift_notify ;;
      s )
        cp_scriptarchive ;;
      t )
        cp_empty_trash ;;
      u )
        cp_zupdate ;;
      y )
        cp_zytdlpupdate ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$E_INVALID_ARG"
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No arguments passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
