#!/usr/bin/env bash
#####################################################################
# Script Name  : devtoolchk
# Description  : Check if C development tools are installed
# Dependencies : none
# Arguments    : none
# Author       : Copyright © 2017 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail | rick.romig@mymetronet.net
# Created      : 01 Jan 2017
# Updated      : 10 Mar 2025
# Comment      :
# License      : GNU General Public License, version 2.0
#####################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

check_tools() {
	local package packages
	packages=( binutils build-essential gcc mingw )
	for package in "${packages[@]}"; do
		printf "%s is " "$package"
		if dpkg -l "$package" > /dev/null 2>&1; then
			printf "installed.\n"
		else
			printf "not installed.\n"
		fi
	done
}

check_glibc() {
	printf "The GNU C standard library (glibc) is "
	if exists ldd; then
		printf "installed.\n"
	else
		printf "not installed.\n"
	fi
}

main() {
	local script version
	script=$(basename "$0")
	version="2.0.24274"
	printf "Checking for deveolopment tools...\n"
	check_tools
	check_glibc
	over_line "$script $version"
	exit
}

# Execution

main "$@"
