#!/usr/bin/env bash
#####################################################################
# Script Name  : devtoolinst
# Description  : Installs C development tools if not installed
# Dependencies : apt
# Arguments    : none
# Author       : Copyright (C), Richard Romig
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Updated      : 30 Sep 2024
# Comment      :
# License      : GNU General Public License, version 2.0
#####################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

check_tools() {
  local package packages
  packages=( binutils build-essential gcc )
	for package in "${packages[@]}"; do
		if dpkg -l "$package" > /dev/null 2>&1; then
			printf "%s installed.\n" "$package"
		else
			printf "Installing %s.\n" "$package"
      sudo apt-get install -y "$package"
		fi
	done
}

main() {
  local script version updated
	script=$(basename "$0")
	version="2.0.24274"
	updated="30 Sep 2024"
	box "$script v$version ($updated)"
  printf "Checking and installing C devlopment tools...\n"
  check_tools
  exit
}

## Execution ##

main "$@"
