#!/usr/bin/env bash
#####################################################################
# Script Name  : devtoolchk
# Description  : Check if C development tools are installed
# Dependencies : none
# Arguments    : none
# Author       : Copyright © 2017 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail | rick.romig@mymetronet.net
# Created      : 01 Jan 2017
# Updated      : 24 Jul 2025
# Comment      :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#####################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

check_tools() {
	local package packages
	packages=( binutils build-essential gcc )
	for package in "${packages[@]}"; do
		printf "%s is " "$package"
		if dpkg -l "$package" > /dev/null 2>&1; then
			printf "installed.\n"
		else
			printf "not installed.\n"
		fi
	done
}

check_glibc() {
	printf "The GNU C standard library (glibc) is "
	if exists ldd; then
		printf "installed.\n"
	else
		printf "not installed.\n"
	fi
}

main() {
	local script version
	script="${0##*/}"
	version="2.1.25205"
	printf "Checking for deveolopment tools...\n"
	check_tools
	check_glibc
	over_line "$script $version"
	exit
}

# Execution

main "$@"
