#!/usr/bin/env bash
#####################################################################
# Script Name  : devtoolinst
# Description  : Installs C development tools if not installed
# Dependencies : apt
# Arguments    : none
# Author       : Copyright (C), Richard Romig
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 01 Jan 2017
# Updated      : 24 Jul 2025
# Comment      :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#####################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

check_tools() {
  local package packages
  packages=( binutils build-essential gcc )
	for package in "${packages[@]}"; do
		if dpkg -l "$package" > /dev/null 2>&1; then
			printf "%s installed.\n" "$package"
		else
			printf "Installing %s.\n" "$package"
      sudo apt-get install -y "$package"
		fi
	done
}

main() {
	local script="${0##*/}"
	local version="2.1.25205"
  printf "Checking and installing C devlopment tools...\n"
  check_tools
	over_line "$script $version"
  exit
}

## Execution ##

main "$@"
