#!/usr/bin/env bash
#####################################################################
# Script Name  : devtoolchk
# Description  : Check if C development tools are installed
# Dependencies : n/a
# Arguments    : none
# Author       : Richard Romig
# Email        : rick.romig@gmail.com
# Comment      :
# License      : GNU General Public License, version 2.0
#####################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

check_tools() {
	local package packages
	packages=( binutils build-essential gcc mingw )
	for package in "${packages[@]}"; do
		printf "%s is " "$package"
		if dpkg -l "$package" > /dev/null 2>&1; then
			printf "installed.\n"
		else
			printf "not installed.\n"
		fi
	done
}

check_glibc() {
	printf "The GNU C standard library (glibc) is "
	if exists ldd; then
		printf "installed.\n"
	else
		printf "not installed.\n"
	fi
}

main() {
	local _script _version _updated
	_script=$(basename "$0")
	_version="2.0.24274"
	_updated="30 Sep 2024"
	box "$_script v$_version ($_updated)"
	printf "Checking for deveolopment tools...\n"
	check_tools
	check_glibc
	exit
}

# Execution

main "$@"