#!/bin/bash
##########################################################################
# Script Name  : dl-scripts
# Description  : Downloads bash scripts and templates from HP 6004 server
# Dependencies : rsync
# Arguments    : None
# Author       : Copyright (C) 2020, Richard B. Romig, 07 Jun 2020
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     : Downloads from 192.168.0.11:/data/installation to local machine.
#              : Retired 12 Mar 2023. Can clone script repo from Gitea server.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.2.9"
readonly _updated="12 Mar 2023"
readonly server_ip="192.168.0.11"
readonly server_dir="data/installation"

## Execution ##
clear
printf "%s v%s (%s)\n"  "$_script" "$_version" "$_updated"
printf "Downloads bash scripts and templates from the HP 6005 server\n\n"

dpkg -l | grep -gw rsync || sudo apt-get install rsync -yy

printf "$\e[33mCopying bin directory...\e[0m\n"
[[ -d "$HOME/bin" ]] || mkdir -p "$HOME/bin"
rsync -avz --delete "rick@${server_ip}:/${server_dir}/bin/" "$HOME/bin/"
printf "\e[33mScripts copied from $server_ip.\e[0m\n"

exit
