#!/usr/bin/env bash
#############################################################################
# Script Name  : dl-webpage
# Description  : Downloads a page from the web to the current directory.
# Dependencies : wget
# Arguments    : URL of page to be downloaded
# Author       : Copyright (C) 2019, Richard B. Romig, 02 Nov 2019
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 02 Nov 2019
# Updated      : 05 May 2026
# Comments     :
# TODO (Rick)  : Array of wget exit codes
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#############################################################################

## Load function library ##
# shellcheck source=/home/rick/bin/functionlib
source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

## Global Variables ##

readonly script="${0##*/}"
readonly version="2.4.26125"
EC=0

## Functions ##

help() {
  local errcode="${1:-1}"
  local updated="05 May 2026"
  cat << _HELP_
${orange}$script${normal} $version, Updated: $updated
Downloads a web page to the current directory.

${green}Usage:  ${normal} $script [URL | OPTION]
${green}Example:${normal} $script https://example.com/index.html
${orange}Available options:${normal}
  -h | --help  Show this help message and exit.
_HELP_
  exit "$errcode"
}

download_page() {
  local -r url="$1"
  local domain
  domain=$(sed 's|^[^/]*//||; s|^www\.||; s|/.*$||' <<< "$url")
  printf "Downloading %s to %s\n" "$url" "$PWD"
  wget --quiet --recursive --page-requisites --html-extension --convert-links --restrict-file-names=windows --domains "$domain" --no-parent "$url"
  EC="$?"
  print_status
}

print_status() {
  exitcodes=(
    "No problems occurred"
    "Generic error code"
    "Parse error"
    "File I/O error"
    "Network Failure"
    "SSL verification error"
    "Username/password authentication failure"
    "Protocol errors"
    "Server issued an error response"
  )
  if [[ "$EC" -eq 0 ]]; then
    printf "Page succesfully downloaded.\n"
  else
    printf "Download failed with exit code: %s.\n" "$EC"
    printf "Error: %s\n" "${exitcodes[EC]}"
  fi
}

main() {
  local url
  local re="^https?:\/\/.*"
  check_package wget
  if [[ "$#" -eq 0 ]]; then
    printf "%s No argument passed.\n" "$RED_ERROR" >&2
    help "$E_MISSING_ARG"
  elif [[ "$1" = "--help" || "$1" = "-h" ]]; then
    help 0
  elif [[ $1 =~ $re ]]; then
    url="$*"
    download_page "$url"
    over_line "$script $version"
    exit "$EC"
  else
    printf "%s Invalid argument - %s\n" "$RED_ERROR" "$1" >&2
    help "$E_INVALID_ARG"
  fi
}

## Execution ##

main "$@"
