#!/usr/bin/env bash
#####################################################################
# Script Name  : dos2linux
# Description  : converts DOS text files to Linux format
# Dependencies : none
# Arguments    : file to be converted
# Author       : Copyright (C) 2019, Richard Romig, 24 Jan 2019
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 24 Jan 2019
# Updated      : 30 Sep 2024
# TODO (Rick)  :
# Comment      : removes DOS carriage return ('\r') characters
# License      : GNU General Public License, version 2.0
#####################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

script=$(basename "$0"); readonly script
readonly version="1.2.24274"

## Functions ##

help() {
	local errcode updated
	errcode="${1:-2}"
	updated="30 Sep 2024"
  cat << _HELP_
${orange}$script${normal} $version, Updated: $updated
Utility to convert DOS text files to Linux format by removing carriage returns.

${green}Usage:${normal} $script [OPTION]

${orange}Available options:${normal}
  -h | --help  Show help
NOTE: Converts files in the current working directory.
_HELP_
  exit "$errcode"
}

convert_file() {
  local filename="$1"
  printf "Removing the carriage return characters from %s\n" "$filename"
  printf "and creating a backup (%s.bak) of the orginal file."  "$filename"
  sed -i.bak 's/\r//g' "$filename"
}

main() {
  local filename

  if [[ "$#" -eq 0 ]]; then
    printf "%s No argument passed.\n" "$RED_ERROR" >&2
    help 1
  elif [[ "$1" == "-h" || "$1" == "--help" ]]; then
    help 0
  elif [[ ! -f "$1" ]]; then
    printf "%s %s not found.\n" "$RED_ERROR" "$1" >&2
    help 2
  else
    filename="$1"
    convert_file "$filename"
  fi
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"