#!/usr/bin/env bash
##########################################################################
# Script Name  : greset
# Description  : Reset a commit to the previous version before it's pushed to repo
# Dependencies : git
# Arguments    : none
# Author       : Copyright © 2024 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 19 May 2024
# Last updated : 19 May 2024
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

set -eu

_script=$(basename "$0"); readonly _script
readonly _version="1.0.24140"

head=$(git log --oneline | head -n 1 | cut -d' ' -f1)
git reset "$head"
git log --oneline | head -n 2
echo "$_script v$_version"
exit
