#!/usr/bin/env bash
##########################################################################
# Script Name  : greset
# Description  : Reset most recent commit to the previous version before it's pushed to repo
# Dependencies : git
# Arguments    : none
# Author       : Copyright © 2024 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 19 May 2024
# Last updated : 13 Oct 2024
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

git_reset() {
	local hash
	hash=$(git log --oneline | head -n 1 | cut -d' ' -f1)
	printf "Resettng the most recent commit that has not been pushed to the remote repository to the previous version.\n"
	git reset "$hash"
	git log --oneline | head -n 2
}

main() {
	local script version
	script=$(basename "$0")
	version="2.0.24287"
	check_package git
	[[ -d "$PWD/.git" ]] || die "You are not in the main directory of a git repositiory." 1
	git_reset
	over_line "$script v$version"
}

main "$@"
