#!/usr/bin/env bash
##########################################################################
# Script Name  : gretire
# Description  : remove a file from a git repo and archive it.
# Dependencies : git zip
# Arguments    : file to be removed
# Author       : Copyright © 2024 Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 04 Jul 2024
# Last updated : 10 Oct 2024
# Comments     : Must be run from the main directory of a git repo.
#              : For files in subdirectories, include the path from the repo directory.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

## Functions ##

check_dependencies() {
  local packages=( git zip )
  check_packages "${packages[@]}"
}

retire_script() {
  local filename retired archive archive_d
  filename="$1"
  retired="${filename}.$(date +'%y%j')"
  archive="retired-scripts.zip"
  archive_d="$HOME//Downloads/archives"
  git mv "$filename" "$retired"
  git commit -m "$filename renamed to $retired to be retired and archived." --no-verify # && git push
  zip -u "$archive_d/$archive" "$retired"
  git rm "$retired"
  git commit -m "$retired was retired and archived." --no-verify # && git push
  git push
}

main() {
  local current_d filename script version
  current_d="$PWD"
  script=$(basename "$0")
  version="2.0.24284"

  [[ -d "$current_d/.git" ]] || die "You are not in the main directory of a git repositiory." 1

  if [[ "$#" -eq "0" ]]; then
    read -rp "Enter the name of the script to be retired: " filename
  else
    filename="$1"
  fi

  if [[ -f "$1" ]]; then
    check_dependencies
    retire_script "$filename"
  else
    die "$1 not found." 1
  fi

  leave "$script $version"
}

## Execution ##

main "$@"
