#!/usr/bin/env bash
##########################################################################
# Script Name  : grevert
# Description  : Revert most recent commit to the previous version after it's been pushed to repo
# Dependencies : git
# Arguments    : none
# Author       : Copyright © 2024 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 19 May 2024
# Last updated : 01 Aug 2024
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

set -eu

_script=$(basename "$0"); readonly _script
readonly _version="1.2.24214"

printf "Reverting the most recent commit to the previous version.\n"
hash=$(git log --oneline | head -n 1 | cut -d' ' -f1)
git revert "$hash" --no-edit
git log --oneline | head -n 2
echo "$_script v$_version"
exit
