#!/usr/bin/env bash
###############################################################################
# Script Name  : grevert
# Description  : Revert most recent commit to the previous version after it's been pushed to repo
# Dependencies : git
# Arguments    : none
# Author       : Copyright © 2024 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 19 May 2024
# Updated      : 07 Aug 2026
# Version      : 3.1.26219"
# Comments     : Revert most recent commit that has been pushed to the repository.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

# shellcheck source=/home/rick/bin/functionlib.bash
source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

is_git_repo() {
  [[ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" == "true" ]]  && return "$TRUE" || return "$FALSE"
}

unpushed_commits() {
	[[ $(grep -c 'Author:' < <(git log --branches --not --remotes)) -gt 0 ]] && return "$TRUE" || return "$FALSE"
}

git_revert() {
	local hash
	hash="$(awk 'NR==1 {print $1}' < <(git log --oneline))"
	printf "Reverting the most recent pushed commit (%s) to the previous version.\n" "$hash"
	git revert "$hash" --no-edit
	local -i result="$?"
	head -n 2 < <(git log --oneline)
	git push
	return "$result"
}

revert_commit() {
	local -i result=0
	if unpushed_commits; then
		printf "There are unpushed commits in the local repositiory. Revert operation canceled.\n"
		return "$result"
	fi
	if y_or_n "Reset last pushed commit to the previous version?"; then
		git_revert
		result="$?"
	else
		printf "Last pushed commit unchanged.\n"
	fi
	return "$result"
}

main() {
  local -r script="${0##*/}"
	local -r version="3.1.26219"
  local -i exit_code=0
	check_package git
	is_git_repo || die "You are not in a git repositiory Revert operation canceled." "$E_UNSUPPORTED"
	revert_commit
	exit_code="$?"
	over_line "$script $version"
  exit "$exit_code"
}

main "$@"
