#!/usr/bin/env bash
##########################################################################
# Script Name  : i3deb-cleanup
# Description  : Clean up cloned directories after a Debian i3 install.
# Dependencies : none
# Arguments    : none
# Author       : Copyright (C) 2023 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 22 Mar 2023
# Updated      : 10 Oct 2024
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

clean_i3debian_clone() {
	printf "Removing ~/i3debian\n"
	rm -rf "$HOME"/i3debian/
}

clean_scripts_clone() {
	printf "Removing ~/Downloads/scripts\n"
	rm -rf "$HOME"/Downloads/scripts/
}

clean_configs_clone() {
	printf "Removing ~/Downloads/configs\n"
	rm -rf "$HOME"/Downloads/configs/
}

main() {
	local script version
	script=$(basename "$0")
	version="2.0.24184"
	printf "Cleaning up after installing i3-gaps on minimal Debian.\n\n"
	[[ -d "$HOME"/i3debian/ ]] && clean_i3debian_clone
	[[ -d "$HOME"/Downloads/scripts/ ]] && clean_scripts_clone
	[[ -d "$HOME"/Downloads/configs/ ]] && clean_configs_clone
	printf "\nCloned installation directories removed.\n"
	leave "$script v$version"
}

## Execution ##

main "$@"