#!/usr/bin/env bash
##########################################################################
# Script Name  : i3kb
# Description  : Displays i3 keybindings
# Dependencies : None
# Arguments    : None
# Author       : Copyright © 2023 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 16 Apr 2023
# Updated      : 31 Oct 2024
# Comments     : Install with bindings.list in ~/.config/i3/
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

readonly i3_dir="$HOME/.config/i3"
readonly bindings="bindings.list"

## Functions ##

copy_bindings() {
	local repository
	repository=$(assign_cfg_repo)
	printf "Copying i3 keyboard bindings...\n"
	cp -v "$repository/$bindings" "$i3_dir/$bindings"
}

show_bindings() {
	[[ -f "$i3_dir/$bindings" ]] || copy_bindings
	printf "i3wm keybindings:\n"
	column -t -s "|" -N Binding,Action,Binding,Action "$i3_dir/$bindings"
}

main() {
	local -r script="${0##*/}"
	local -r version="1.9.25205"
	if exists i3; then
		clear
		show_bindings
	else
		printf "i3wm is not installed." >&2
	fi
	over_line "$script $version"
	exit
}

## Execution ##

main "$@"