#!/usr/bin/env bash
##########################################################################
# Script Name  : i3kb
# Description  : Displays i3 keybindings
# Dependencies : curl
# Arguments    : None
# Author       : Copyright © 2023 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 16 Apr 2023
# Updated      : 11 Sep 2024
# Comments     : Install with bindings.list in ~/.config/i3/
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="1.6.241255"
readonly i3_dir=$HOME"/.config/i3"
readonly bindings="bindings.list"

## Functions ##

copy_bindings() {
	local repository="configs/raw/branch/main/"
	check_package curl
	curl -so "$i3_dir/$bindings" "$Gitea_URL/$repository/$bindings"
}

show_bindings() {
	[[ -f "$i3_dir/$bindings" ]] || copy_bindings
	(printf "Binding|Action|Binding|Action\n"; less "$i3_dir/$bindings") | column -ts "|"
}

## Execution ##

exists i3 || leave "i3wm is not installed."
clear
printf "%s v%s\n" "$_script" "$_version"
show_bindings
exit
