#!/usr/bin/env bash
###############################################################################
# Script Name  : insert-license
# Description  : Insert a license into a shell script or C source code.
# Dependencies : bat, micro (nano)
# Arguments    : Shell script or C source file
# Author       : Copyright (C) 2019, Richard B. Romig, 05 June 2019
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     : Inserts the license immediately after the file's header.
#              : bat - https://github.com/sharkdp/bat/releases/
#              : less or cat can be substituted for bat
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091,SC2034

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="3.1.1"
readonly _updated="09 Oct 2023"
readonly conf_dir="$HOME/.config/scripts"
readonly conf_file="$_script.conf"
cur_yr=$(echo -e "\UA9 $(date +%Y)"); readonly cur_yr

## Functions ##

create_conf() {
  [[ -d "$conf_dir" ]] || mkdir -p "$conf_dir"
  echo "Complete all fields"
  read -rp "Full name: " copy_holder
  read -rp "Primary email: " email_addr
  read -rp "Template diretory (full path): " template_dir

  echo "
  copy_holder='$copy_holder'
  email_addr='$email_addr'
  template_dir='$template_dir'
  " > "$conf_dir/$conf_file"
}

usage() {
  local errcode="${1:-2}"
  cat << END_HELP
${green}Usage:${normal} $_script [OPTION]
${orange}OPTIONS:${normal}
  -c  C code
      $_script -c <c-source.c>
  -e  Edit $_script.conf
  -p  C++ code
      $_script -p <c-source.cpp>
  -s  Shell script
      $_script -s <shell-script>
  -u  Usage instructions
END_HELP
  exit "$errcode"
}

cleanup() {
  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
}

## Execution ##

noOpt=1
optstr=":c:ep:s:u"
while getopts "$optstr" opt; do
  case "$opt" in
    c )
			code_file="$OPTARG"
			[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$red_error" "$code_file" >&2; usage 2; }
      code_type="C"
    ;;
    e )
			micro "$conf_dir/$conf_file"
			printf "%s edited.\n" "$_script"
			leave "$_script v$_version ($_updated)"
    ;;
    p )
			code_file="$OPTARG"
			[[ -f "$filename" ]] || { printf "%s %s not found\n" "$red_error" "$code_file" >&2; usage 2; }
      code_type="C++"
    ;;
    s )
			code_file="$OPTARG"
			[[ -f "$filename" ]] || { printf "%s %s not found\n" "$red_error" "$code_file" >&2; usage 2; }
      code_type="Shell"
    ;;
    u )
      usage 0
    ;;
    : )
      printf "%s Must supply an argument to -%s.\n" "$red_error" "$OPTARG" >&2
      usage 2
    ;;
    ? )
			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
			usage 2
  esac
	noOpt=0
done
[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; usage 1; }

## Source script configuration file ##

[[ -f "$conf_dir/$conf_file" ]] || create_conf
source "$conf_dir/$conf_file"

tmp_file=$(mktemp -q) || die "Failed to create temporary file." 1
trap cleanup EXIT

clear
box "$_script v$_version (Updated $_updated)"
printf "Inserts an Open Source license into a shell script or a c/C++ source code file.\n"
printf "Licensed under the GNU General Public License, version 2.\n"
printf "Copyright \UA9 2019-2023, Richard B. Romig\n"

# Select the type of license

printf "\n%sLicense type:%s\n" "$orange" "$normal"
options=("GPL v1" "GPL v2" "GPL v3" "MIT")
PS3="Select the type of license: "
select opt in "${options[@]}"; do
  case $REPLY in
    1 )
      lic_type="$opt"
      lic_file="gpl_v1"
      break
    ;;
    2 )
      lic_type="$opt"
      lic_file="gpl_v2"
      break
    ;;
    3 )
      lic_type="$opt"
      lic_file="gpl_v3"
      break
    ;;
    4 )
      lic_type="$opt"
      lic_file="mit_lic"
      break
    ;;
    * )
      printf "%sInvalid option. Try again.%s\n" "$lightred" "$normal" >&2
  esac
done

# Insert the license into the source file

printf "%sInserting %s license into %s...%s\n" "$orange" "$lic_type" "$code_file" "$normal"
case $code_type in
  "C" )
    sed -e '1d' \
        -e "s/<YEAR>/$cur_yr/" \
        -e "s/<COPYRIGHT HOLDER>/$copy_holder/" \
        -e "s/<EMAIL>/$email_addr/" \
        -e "s/^/ * /" "$template_dir/$lic_file" > "$tmp_file"
    sed -i -e "21r ${tmp_file}" "$code_file"
  ;;
  "C++" )
    sed -e '1d' \
        -e "s/<YEAR>/$cur_yr/" \
        -e "s/<COPYRIGHT HOLDER>/$copy_holder/" \
        -e "s/<EMAIL>/$email_addr/" \
        -e "s/^/\/\/ /" "$template_dir/$lic_file" > "$tmp_file"
    sed -i -e "20r ${tmp_file}" "$code_file"
  ;;
  "Shell" )
    sed -e '1d' \
        -e "s/<YEAR>/$cur_yr/" \
        -e "s/<COPYRIGHT HOLDER>/$copy_holder/" \
        -e "s/<EMAIL>/$email_addr/" \
        -e "s/^/# /" "$template_dir/$lic_file" > "$tmp_file"
    sed -i -e "12r ${tmp_file}" "$code_file"
  ;;
  * )
    die "Invalid code type. Exiting the script." 1
esac

printf "\n%s license has been inserted into %s.\n" "$lic_type" "$code_file"
edit_view_quit "$code_file"

printf "\n"
leave ""
