#!/usr/bin/env bash
##########################################################################
# Script Name  : install-nerdfonts
# Description  : installs nerdfonts
# Dependencies : wget unzip
# Arguments    : none
# Author       : Copyright © 2023 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 28 Sep 2023
# Last updated : 23 Jun 2025
# Comments     : system install directory = /usr/local/share/fonts
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

## Functions ##

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
cleanup() {
    [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
}

install_nerd_fonts() {
  local -r font_repo="https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0"
  local -r symbols_font="SymbolsNerdFontMono-Regular.ttf"
  local -r symbols_archive="NerdFontsSymbolsOnly.tar.xz"
  local -r font_dir="$HOME/.local/share/fonts"
  local -r fonts=( "CascadiaCode" "FiraCode" "Go-Mono" "Hack" "Inconsolata" "Iosevka" "JetBrainsMono" "Mononoki" "RobotoMono" "SourceCodePro" )
  local font
  [[ -d "$font_dir" ]] || mkdir -p "$font_dir"
  for font in "${fonts[@]}"; do
    wget -P "$tmp_dir" "$font_repo/$font.tar.xz"
    tar xvf "$tmp_dir/$font.tar.xz" -C "$font_dir/$font/"
  done
  wget -P "$tmp_dir" "$font_repo/$symbols_archive"
  tar xvf "$tmp_dir/$symbols_archive" "$font_dir/$symbols_font"
  fc-cache
  printf "Nerd fonts installed.\n"
}

main() {
  local -r script="${0##*/}"
  local -r version="1.6.25174"
  sudo_login 2
  check_packages wget
  tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
  trap cleanup EXIT
  install_nerd_fonts
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
