#!/usr/bin/env bash
##########################################################################
# Script Name  : install-zoom
# Description  : Install/Remove Zoom 
# Dependencies : none
# Arguments    : See help function
# Author       : Copyright (C) 2022, Richard B. Romig, 10 Nov 2022
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.2.0"
readonly _updated="18 Jul 2023"

## Functions ##

check_dependencies() {
	local packages=( gdebi wget )
	check_packages "${packages[@]}"
}

cleanup() {
	[[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
}

help() {
	errcode="${1:-2}"
	cat << END_HELP
Installs or removes the Zoom video conferencing software.
${green}Usage:${normal} $_script [OPTION]
${orange}OPTIONS:${normal}
	-f	Install Zoom (Flatpak)
	-h 	Display help
	-i 	Install Zoom (deb package)
	-r 	Remove Zoom
END_HELP
	printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
  exit "$errcode"
}

zoom_version() {
	dpkg -l | awk '$2 == "zoom" {print $3}'
}

zoom_flat_ver() {
	flatpak list | awk '/Zoom/ {print $3}'
}

install_zoom() {
	local url="https://zoom.us/client/latest"
	local pkg="zoom_amd64.deb"
	printf "Dowloading Zoom ..."
  dots "."
	wget -q -P "$tmp_dir" "$url/$pkg"
  kill "$!"
	printf "done\nInstalling the latest version of Zoom...\n"
	tput cnorm
	sudo gdebi -n "$tmp_dir/$pkg"
	sudo apt-get install -f
	printf "Zoom %s is installed.\n" "$(zoom_version)"
}

remove_zoom() {
	printf "Removing Zoom ...\n"
	if [[ -d "$HOME/.var/app/ us.zoom.Zoom" ]]; then
		flatpak uninstall --noninteractive --assumeyes  us.zoom.Zoom
	else
		sudo apt-get remove --purge zoom -yy
	fi
	printf "Zoom has been removed.\n"
}

flathub_zoom() {
	flatpak install flathub us.zoom.Zoom
	printf "Zoom %s installed from Flathub.\n" "$(zoom_flat_ver)"
}

webcam_info() {
	if /usr/bin/lsusb | grep -qw Webcam; then
		printf "Attached webcam(s):\n"
		/usr/bin/lsusb | grep -w Webcam | cut -d' ' -f7-
	else
		printf "No webcam attached. Attach a Webcam and try again.\n"
		exit 1
	fi
}

## Execution ##

noOpt=1
optstr=":fhir"
while getopts "$optstr" opt; do
	case "$opt" in
		f )
			exists flatpak || leave "Flatpak is not isntalled."
			flatpak list | grep -qw Zoom && leave "Zoom $(zoom_flat_ver) is installed."
			exists zoom && remove_zoom
			flathub_zoom
		;;
		h )
			help 0
		;;
		i )
			exists zoom && printf "Zoom %s is installed.\n" "$(zoom_version)"
			flatpak list | grep -qw Zoom && leave "Zoom $(zoom_flat_ver) is installed."
			webcam_info
			tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
			trap cleanup EXIT
			user_in_sudo
			check_dependencies
			install_zoom
		;;
		r )
			exists zoom || leave "Zoom is not installed."
			user_in_sudo
			remove_zoom
		;;
		? )
			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
			help 2
	esac
	noOpt=0
done
[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
exit
