#!/usr/bin/env bash
##########################################################################
# Script Name  : install-librewolf
# Description  : install/remove LibreWolf browser
# Dependencies : extrepo
# Arguments    : See help() function for available options.
# Author       : Copyright © 2025 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail | rick.romig@mymetronet.net
# Created      : 01 Mar 2025
# Updated      : 03 Feb 2026
# Comments     : instructions from https://librewolf.net/
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 81
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="1.6.26034"
verbose_mode="$FALSE"
EC=0

## Functions ##

help() {
	local errcode="${1:-1}"
	local -r updated="03 Feb 2026"
	cat << _HELP_
${orange}$script${normal} $version, Upated: $updated
Installs/removes LibreWolf browser.

${green}Usage:${normal} $script [-h] [-vi] [-vr]
${orange}Available options:${normal}
  -h  Show this help message and exit.
  -i  Install LibreWolf.
  -r  Remove LibreWolf.
  -v  Enable verbose mode. If used, must prccede -i and -r.
_HELP_
  exit "$errcode"
}

lw_version() {
	# awk '{print $NF}' <(librewolf --version)
	awk '/^ii/ {print $3}' <(dpkg -l librewolf)
}

show_message() {
	local message="$1"
	[[ "$verbose_mode" == "$TRUE" ]] && echo "$message"
}

check_extrepo() {
	if exists extrepo; then
		printf "extrepo [OK]\n"
		sleep 1
		printf '\e[A\e[K'
	else
		show_message "Updating cache and checking/installing extrepo..."
		sudo apt update && sudo apt install extrepo -y
	fi
	sudo extrepo enable librewolf && sudo extrepo update librewolf
	printf "extrepo installed and librewolf repo enabled.\n"
}

install_librewolf() {
	sudo_login 2
	printf "Installing LibreWolf browser...\n"
	show_message "Checking extrepo..."
	check_extrepo
	show_message "Installing LibreWolf..."
	sudo apt update && sudo apt install librewolf -y
  if ! grep -q '^ii' <(dpkg -l librewolf 2>/dev/null); then
    printf "%s LibreWolf installation failed.\n" "$RED_ERROR" >&2
    EC="$E_INSTALLATION"
    return
  fi
	printf "LibreWolf browser version %s installed.\n" "$(lw_version)"
}

remove_librewolf() {
	printf "Removing LibreWolf browser %s...\n" "$(lw_version)"
	sudo_login 2
	show_message "Removing LibreWolf..."
	sudo extrepo disable librewolf
	# sudo apt remove -y librewolf
	show_message "Removing LibreWolf local configuration files..."
	find ~/ -maxdepth 2 -type d -name "*librewolf*" -exec rm -rf {} \;
	show_message "Removing LibreWolf system directories, files, and links..."
	[[ -L /usr/bin/librewolf ]] && sudo unlink /usr/bin/librewolf
	sudo find /etc -msxdepth 3 -type f -name "librewolf*" -exec sudo rm {} \;
	sudo find /usr -msxdepth 3 -type d -name "librewolf*" -exec sudo rm -rf {} \;
	sudo find /var -maxdepth 4 -type d -name "librewolf*" -exec sudo rm -rf {} \;
	printf "LibreWolf has been removed.\n"
}

main() {
	local noOpt opt optstr OPTARG OPTIND
	noOpt=1
	optstr=":hirv"
	while getopts "$optstr" opt; do
		case "$opt" in
			h )
				help 0
				;;
			i )
				if exists librewolf; then
					printf "LibreWolf %s is already installed.\n" "$(lw_version)"
				else
					install_librewolf
				fi
				;;
			r )
				if exists librewolf; then
					remove_librewolf
				else
					printf "LibreWolf is not installed.\n"
				fi
				;;
			v )
				verbose_mode="$TRUE"
				show_message "Verbose mode enabled."
				;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$E_INVALID_ARG"
		esac
		noOpt=0
	done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
	shift "$(( OPTIND - 1 ))"
	over_line "$script $version"
	exit "$EC"
}

## Execution ##

main "$@"
