#!/usr/bin/env bash
###############################################################################
# Script Name  : install-cnatrix
# Description  : installs/removes cmatrix & cmatrix-xfont
# Dependencies : none
# Arguments    : none
# Author       : Copyright © 2024, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 2024
# Updated      : 02 Sep 2026
# Version      : 1.14.26245
# Comment      :
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

# shellcheck source=/home/rick/bin/functionlib.bash
source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

help() {
  local -r script="$1"
  local -r version="$2"
  local -ri errcode="${3:=-1}"
  local -r updated="02 Sep 2026"
  cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs/Removes C-Matrix

${green}Usage:${normal} $script [-hir]
${orange}Available options:${normal}
  -h  Show this help message and exit.
  -i  Install C-Matrix.
  -r  Remove C-Matrix.
_HELP_
  exit "$errcode"
}

install_cmatrix() {
  if installed cmatrix; then
    printf "C-Matrix already installed.\n"
    return 2
  fi
  sudo_login 2
  printf "Installing C-Matrix...\n"
  sudo apt-get update -qq
  sudo apt-get install cmatrix cmatrix-xfont -yy
  if ! installed cmatrix || ! installed matrix-xfont; then
    printf "%s Installation failed.\n" "$RED_ERROR" >&2
    return "$E_INSTALLATION"
  fi
  printf "C-Matrix installed.\n"
  return 0
}

remove_cmatrix() {
  if ! installed cmatrix; then
    printf "C-Matrix is not installed.\n"
    return "$E_NOT_INSTALLED"
  fi
  printf "Removing C-Matrix...\n"
  sudo_login 2
  sudo apt-get remove cmatrix cmatrix-xfont -yy
  printf "C-Matrix removed.\n"
  return 0
}

main() {
  local -r script="${0##*/}"
  local -r version="1.14.26245"
	local -i exit_code=0
  local opt OPTARG OPTIND
  local -i noOpt=1
  local -r optstr=":hir"
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        help "$script" "$version" 0 ;;
      i )
        install_cmatrix ;;
      r )
        remove_cmatrix ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$script" "$version" "$E_INVALID_ARG"
    esac
    exit_code="$?"
    noOpt=0
  done
	if (( noOpt == 1 )); then
		printf "%s No argument passed.\n" "$RED_ERROR" >&2
		help "$script" "$version" "$E_MISSING_ARG"
	fi
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit "$exit_code"
}

main "$@"
