#!/usr/bin/env bash
###############################################################################
# Script Name  : install-audacious
# Description  : Installs/Removes Audacious audio player
# Dependencies : none
# Arguments    : none
# Author       : Copyright (C) 2020, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 23 Mar 2020
# Updated      : 06 Jul 2026
# Comments     : Does not support installation from Ubuntu PPAs or flatpak.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib
source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

help() {
  local -r script="$1"
  local -r version="$2"
  local errcode="${3:-1}"
  local updated="06 Jul 2026"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Install or remove Audacious audio player

${green}Usage:${normal} $script [OPTION]
${orange}Available options:${normal}
  -h  Show this help message and exit.
  -i  Install Audacious audio player.
  -r  Remove Audacious audio player.
_HELP_
  exit "$errcode"
}

install_audacious() {
  if ! in_repos audacious; then
    printf "Audacious is not in repositories. Audacious audio player not installed.\n"
    return 1
  fi
  sudo_login 2
  printf "Installing Audacious audio player...\n"
  sudo apt update -qq
  sudo apt install audacious audacious-plugins -yy
  if ! installed audacious; then
    printf "%s Audacious installation failed.\n" "$RED_ERROR" >&2
    return "$E_INSTALLATION"
  fi
  printf "Audacious audio player installed from distro repository.\n"
  return 0
}

remove_audacious() {
  sudo_login 2
  printf "Removing Audacious audio player....\n"
  sudo apt remove --autoremove audacious audacious-plugins
  printf "Audacious audio player removed.\n"
  return 0
}

main() {
  local -r script="${0##*/}"
  local -r version="2.9.26187"
  local exit_code
  local opt  OPTARG OPTIND
  local -i noOpt=1
  local -r optstr=":hir"
  while getopts "$optstr" opt; do
	  case "$opt" in
		  h )
			  help 0
		    ;;
      i )
        if installed audacious; then
          printf "Audacious audio player is already installed.\n"
        else
          install_audacious
        fi
        ;;
      r )
        if installed audacious; then
          remove_audacious
        else
          printf "Audacious audio player is not installed."
        fi
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$script" "$version" "$E_INVALID_ARG"
    esac
    exit_code="$?"
    noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit "$exit_code"
}

main "$@"
