#!/usr/bin/env bash
#############################################################################
# Script Name  : install-boxes
# Description  : Installs GNOME boxes.
# Dependencies : none
# Arguments    : none
# Author       : Copyright (C) 2020, Richard B. Romig
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 29 Feb 2020
# Updated      : 11 Apr 2026
# Comments     : Based on instructions from Joe Collins.
# TODO (Rick)  : check entry in flatpak list
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 81
fi

## Global Variables ##
readonly script="${0##*/}"
readonly version="4.0.26101"
readonly E_BIOS_SETTING=100
EC=0

## Functions ##

help() {
	local errcode="${1:-1}"
	local updated="11 Apr 2026"
	cat << _HELP_
${orange}$script${normal} $version, Upated: $updated
Install Gnome Boxes from either distribution repositories or flatpak from Flathub.

${green}Usage:${normal} $script [-dfh]
${orange}Available options:${normal}
	-d	Install Gnome Boxes from distro repo
	-f	Install Gnome Boxes from Flathub
	-h	Show this help message and exit
_HELP_
  exit "$errcode"
}

check_bios() {
  local vcpu vmx_svm
  local -r qemu_conf="/etc/modprobe.d/qemu-system-x86.conf"
  printf "Checking if virtualization is enabled in BIOS...\n"
  vcpu=$(grep -Ec 'vmx|svm' /proc/cpuinfo)
  printf "Virtualization is "
  if [[ $vcpu -eq 0 ]]; then
    printf "not enabled in the BIOS.\n" >&2
    printf "Enable virtualization before installing Gnome Boxes.\n" >&2
    EC="$E_BIOS_SETTING"
    return
  fi
  printf "enabled in the BIOS. (%d threads)\n" "$vcpu"
  vmx_svm=$(grep -E -m 1 'vmx|svm' /proc/cpuinfo )
  case "$vmx_svm" in
    *vmx* )
      # echo "options kvm_intel nested=1" | sudo tee -a "$qemu_conf" >/dev/null ;;
      sudo tee -a "$qemu_conf" >/dev/null <<< "options kvm_intel nested=1" ;;
    *svm* )
      # echo "options kvm_amd nested=1" | sudo tee -a "$qemu_conf" >/dev/null ;;
      sudo tee -a "$qemu_conf" >/dev/null <<< "options kvm_amd nested=1"
  esac
  # echo "group=kvm" | sudo tee -a "$qemu_conf" >/dev/null
  sudo tee -a "$qemu_conf" >/dev/null <<< "group=kvm"
}

enable_libvirtd() {
  sudo systemctl enable libvirtd.service
  sudo systemctl start libvirtd.service
  printf "libvirtd started.\n"
}

add_to_kvm_group() {
  local user in_kvm_grp
  user=$(whoami)
  in_kvm_grp=$(awk '/kvm:/ && /'"$user"'/' /etc/group)
  printf "User %s " "$user"
  if [[ "$in_kvm_grp" ]]; then
    printf "is already a member of "
  else
    sudo usermod -a -G kvm "$user"
    printf "added to "
  fi
  printf "the kvm group.\n"

  if [[ ! -f /etc/libvirt/qemu.conf ]]; then
    printf "/etc/libvirt/qemu.conf not found!\n" >&2
    EC="$E_FILENOTFOUND"
    return
  fi
  printf "Allow users in the kvm group to start VMs.\n"
  sudo sed -i.bak 's/\#group\ =\ "root"/group\ =\ "kvm"/' /etc/libvirt/qemu.conf
  enable_libvirtd
}

install_boxes() {
  [[ EC -ne 0 ]] && return
  printf "\nInstalling GNOME Boxes (distro)...\n"
  sudo apt update -qq
  sudo apt install -yy gnome-boxes qemu-kvm
  if ! exists gnome-boxes; then
    printf "%s Gnome-boxes installation failed.\n" "$RED_ERROR" >&2
    EC="$E_INSTALLATION"
    return
  fi
  printf "Gnome-boxes installed.\n"
  add_to_kvm_group
}

install_flatpak() {
  [[ EC -ne 0 ]] && return
  printf "\nInstalling GNOME Boxes (flatpak)...\n"
  flatpak install --user flathub org.gnome.Boxes
  if ! grep -qi 'boxes' <(flatpak list); then
    printf "%s Gnome-boxes installation failed.\n" "$RED_ERROR" >&2
    EC="$E_INSTALLATION"
    return
  fi
  printf "Gnome-Boxes installed.\n"
  add_to_kvm_group
}

main() {
  local noOpt opt optstr OPTARG OPTIND
	noOpt=1
	optstr=":dfh"
	while getopts "$optstr" opt; do
    case "$opt" in
      d )
        sudo_login 2
        check_bios
        install_boxes
        ;;
      f )
        sudo_login 2
        check_bios
        install_flatpak
        ;;
      h )
        help 0
        ;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$E_INVALID_ARG"
    esac
    noOpt=0
  done
	[[ $noOpt -eq 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
	shift "$(( OPTIND - 1 ))"
  [[ $EC -eq 0 ]] && printf "Gnome boxes installed and configured.\n"
  over_line "$script $version"
  exit "$EC"
}

## Execution ##

main "$@"
