#!/usr/bin/env bash
##########################################################################
# Script Name  : install-glow
# Description  : Installs and removes the Glow markdown reader.
# Dependencies : curl
# Arguments    : See help function
# Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 10 Jan 2022
# Updated      : 25 May 2026
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib
source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

help() {
  local errcode="${1:-1}"
  local updated="25 May 2026"
  cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs/Removed Glow Markdown reader

${green}Usage:${normal} $script [-hir]
${orange}Available options:${normal}
  -c  Apply Glow configuration.
  -h  Show this help message and exit.
  -i  Installs the glow markdown reader.
  -r  Removes the glow markdown reader from the system.
_HELP_
  exit "$errcode"
}

glow_version() {
  cut -d' ' -f3 <(glow --version)
	return 0
}

set_gpg_key() {
  local -r charm_url="$1"
  local -r charm_key="$2"
  printf "Adding the Charm GPG key...\n"
  [[ -d /etc/apt/keyrings ]] || sudo mkdir -p /etc/apt/keyrings
  check_package curl
  # sudo doesn't affect redirects. [SC2024]
  curl -fsSL "$charm_url/gpg.key" | sudo gpg --dearmor -o "$charm_key"
  printf "Charm GPG key applied.\n"
	return 0
}

set_sources() {
  local -r charm_url="$1"
  local -r charm_key="$2"
  local -r charm_sources="/etc/apt/sources.list.d/charm.sources"
  printf "Creating the the Charm apt source list...\n"
  sudo tee "$charm_sources" <<< \
"Types: deb
URIs: $charm_url
Suites: *
Components: *
Signed-By: $charm_key"
	return 0
}

install_glow() {
  local -r charm_url="https://repo.charm.sh/apt"
  local -r charm_key="/etc/apt/keyrings/charm.gpg"
  printf "Installing the Glow markdown reader...\n"
  sudo_login 2
  set_gpg_key "$charm_url" "$charm_key"
  set_sources "$charm_url" "$charm_key"
  sudo apt update && sudo apt install -y glow
  if ! grep -q '^ii' <(dpkg -l glow 2>/dev/null); then
    printf "%s Glow installation failed.\n" "$RED_ERROR" >&2
    return "$E_INSTALLATION"
  fi
  printf "Glow %s successfully installed.\n" "$(glow_version)"
  glow_config
	return 0
}

remove_glow() {
  printf "Removing the Glow markdown reader...\n"
  sudo_login 2
  sudo apt-get -y purge glow
  find /etc/apt -type f -name "charm*" -exec sudo rm -f {} \;
  [[ -f /usr/share/man/man1/glow.1.gz ]] && sudo rm -f /usr/share/man/man1/glow.1.gz
  find ~/ -maxdepth 3 -type d -path "$HOME/Downloads" -prune -o -path "$HOME/gitea" -prune -o -type d -name glow -exec rm -rf {} \;
  printf "Glow markdown reader has been removed.\n"
	return 0
}

glow_config() {
  if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
		printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
		return "$E_FILENOTFOUND"
	fi
  printf "Installing glow.yml...\n"
  [[ -d ~/.config/glow ]] || mkdir -p ~/.config/glow
  [[ -f ~/.config/glow/glow.yml ]] && rm ~/.config/glow/glow.yml
  [[ -d ~/gitea/configs ]] && ln -sv ~/gitea/configs/glow/glow.yml ~/.config/glow/glow.yml
  [[ -d ~/Downloads/configs ]] && ln -sv ~/Downloads/configs/glow/glow.yml ~/Downloads/configs/glow/glow.yml
  printf "Glow configuration applied.\n"
	return 0
}

main() {
	local -r script="${0##*/}"
	local -r version="5.0.26196"
	local -i exit_code=0
  local opt OPTARG OPTIND
	local -i noOpt=1
  local -r optstr=":chir"
  while getopts "$optstr" opt; do
    case "$opt" in
      c )
        if installed glow; then
          glow_config
        else
          printf "Glow is not installed.\n"
        fi
        ;;
      h )
        help 0
        ;;
      i )
        if installed glow; then
          printf "Glow %s is already installed.\n" "$(glow_version)"
        else
          install_glow
        fi
        ;;
      r )
        if installed glow; then
          remove_glow
        else
          printf "Glow is not installed.\n"
        fi
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$E_INVALID_ARG"
    esac
		exit_code="$?"
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit "$exit_code"
}

main "$@"
