#!/usr/bin/env bash
##########################################################################
# Script Name  : install-nerdfonts
# Description  : installs nerdfonts
# Dependencies : wget unzip
# Arguments    : none
# Author       : Copyright © 2023 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 28 Sep 2023
# Last updated : 22 Oct 2025
# Comments     : system install directory = /usr/local/share/fonts
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
cleanup() {
  [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
}

install_NerdFonts() {
  local -r font_repo="https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0"
  local -r font_dir="$HOME/.local/share/fonts"
  local -r fonts=( "FiraCode" "Go-Mono" "Hack" "Inconsolata" "Iosevka" "JetBrainsMono" "Mononoki" "RobotoMono" "SourceCodePro" )
  local font
  [[ -d "$font_dir" ]] || mkdir -p "$font_dir"
  for font in "${fonts[@]}"; do
    printf "\e[03mInstalling %s ...\e[0m\n" "$font"
    wget -q -P "$tmp_dir" "$font_repo/$font.tar.xz"
    mkdir -p "$font_dir/$font/"
    tar xvf "$tmp_dir/$font.tar.xz" -C "$font_dir/$font/"
  done
  printf "Nerd fonts installed.\n"
}

install_SymbolNerdFonts() {
  local -r font_dir="$HOME/.local/share/fonts"
  local -r symbols_archive="NerdFontsSymbolsOnly.tar.xz"
  [[ -d ~/Downloads/configs ]] && cp -v ~/Downloads/configs/local/NerdFontsSymbolsOnly.tar.xz "$font_dir/"
  [[ -d ~/gitea/configs ]] && cp -v ~/gitea/configs/local/NerdFontsSymbolsOnly.tar.xz "$font_dir/"
  tar xvf "$font_dir/$symbols_archive" -C "$font_dir/${symbols_archive%%.*}"
}

main() {
  local -r script="${0##*/}"
  local -r version="1.8.25295"
  sudo_login 2
  check_packages wget
  tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
  trap cleanup EXIT
  install_NerdFonts
  install_SymbolNerdFonts
  fc-cache
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
