#!/usr/bin/env bash
################################################################################
# Script Name  : install-codium
# Description  : installs vscodium from a repo using apt-get
# Dependencies : git wget
# Arguments    : see help function for options
# Author       : Copyright © 2023 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 04 Aug 2023
# Updated      : 19 Jul 2026
# Comments     : Alternative to downloading directly from GitHub repo.
# TODO (Rick)  : add flatpak installation...
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
################################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# OR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
################################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib.bash
source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

help() {
	local -r script="$1"
	local -r version="$2"
	local -r errcode="${3:-1}"
	local -f updated="19 Jul 2026"
	cat << _HELP_
${orange}$script${normal} $version, updated: ($updated)
Install/Remove VSCodium and apply settings

${green}Usage:${normal} $script [-h] [-vairs]
${orange}Available options:${normal}
  -a  Set apt gpg key and source list.
  -h  Show this help message and exit.
  -i  Install VSCodium via apt.
  -r  Remove VSCodium.
  -s  Apply VSCodium settings.
  -v  Enable verbose mode. If used, must precede other flags.
_HELP_
  exit "$errcode"
}

check_dependencies() {
  [[ $(uname -m) == "x86_64" ]] || die "System architecture is not 64-bit." 1
  local packages=( git wget )
  check_packages "${packages[@]}"
	return 0
}

codium_version() {
	head -n1 < <(codium --version)
	return 0
}

set_gpg_key() {
	local -r key_file="$1"
	local -r key_url="https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg"
	show_message "Setting the GPG key..."
	sudo wget "$key_url" -O "$key_file"
	show_message "GPG key is set."
	return 0
}

set_sources() {
	local -r key_file="$1"
	local -r sources_file=/etc/apt/sources.list.d/vscodium.sources
	local -r sources_uri="https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs"
	if [[ -f /etc/apt/sources.list.d/vscodium.list ]]; then
		show_message "Renaming old source list file..."
		sudo mv /etc/apt/sources.list.d/vscodium.list /etc/apt/sources.list.d/vscodium.list.bak
	fi
	show_message "Creating the VSCodium sources file..."
	sudo tee $sources_file <<< \
"Types: deb
Architectures: amd64 arm64
URIs: $sources_uri
Suites: vscodium
Components: main
Signed-By: $key_file"
	show_message "VCCodium sources has been created."
	return 0
}

install_vscodium() {
	local -r key_file="$1"
	show_message "Installing VSCodium..."
	set_gpg_key "$key_file"
	set_sources "$key_file"
	show_message "Updating apt cache and installing VSCodium..."
	sudo apt-get update
	sudo apt-get install codium
	if ! installed codium; then
		printf "%s VSCodium installation failed.\n" "$RED_ERROR" >&2
		return "$E_INSTALLATION"
  fi
	printf "VSCodium %s successfully installed.\n" "$(codium_version)"
	apply_settings
	return "$?"
}

apply_settings() {
	if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
		printf "%s Repository not found!\n" "$RED_WARNING" >&2
		return "$E_FILENOTFOUND"
	fi
	[[ -d ~/.config/VSCodium/User/ ]] || mkdir -p ~/.config/VSCodium/User/
  show_message "Applying VSCodium settings..."
	[[ -f ~/.config/VSCodium/User/settings.json ]] && rm ~/.config/VSCodium/User/settings.json
	[[ -d ~/gitea/configs ]] && ln -sv ~/gitea/configs/VSCodium/User/settings.json ~/.configVSCodium/User/settings.json
	[[ -d ~/Downloads/configs ]] && ln -sv ~/Downloads/configs/VSCodium/User/settings.json ~/.config/VSCodium/User/settings.json
  show_message "VSCodium settings applied."
	return 0
}

remove_vscodium() {
	show_message "Removing VSCodium..."
	sudo apt-get purge codium
	show_message "Removing VSCodium configuration files ..."
	[[ -L ~/.config/VSCodium/User/settings.json ]] && unlink ~/.config/VSCodium/User/settings.json
	find ~/.config -maxdepth 2 -type d -name VSCodium -exec rm -rf {} \;
	show_message "Removing VSCodium sources ..."
	find /etc/apt/sources.list.d -maxdepth 1 -type f -name "vscodium*" -exec sudo rm {} \;
	show_message "Removing VSCodium GPG key and insiders files ..."
	find /usr/share -type f -name "*vscodium*" -exec sudo rm {} \;
	printf "VSCodium has been removed.\n"
	return 0
}

show_message() {
  local message="$1"
  [[ "$VERBOSE" == "$TRUE" ]] && echo "$message"
	return 0
}

main() {
	VERBOSE="$FALSE"
	local -r script="${0##*/}"
	local -r version="5.2.26200"
	local -i exit_code=0
	local -r key_file="/usr/share/keyrings/vscodium-archive-keyring.asc"
  local opt OPTARG OPTIND
	local -i noOpt=1
	local -r optstr=":ahirsv"
	while getopts "$optstr" opt; do
		case "$opt" in
			a)
				# Set apt gpg key and source list
				if installed codium; then
					sudo_login 2
					set_gpg_key "$key_file"
					set_sources "$key_file"
				else
					printf "VSCodium is not installed.\n" >&2
				fi
				;;
			h )
				help "$script" "$version" 0
				;;
			i )
				# Install VSCodium via apt
				if installed codium; then
					printf "VSCodium %s is already installed.\n" "$(codium_version)"
				else
					sudo_login 2
					check_dependencies
					install_vscodium "$key_file"
				fi
				;;
			r )
				# Remove VSCodium
				if installed codium; then
					sudo_login 2
					remove_vscodium
				else
					printf "VSCodium is not installed.\n" >&2
				fi
				;;
			s )
				# Apply VSCodium settings
				if installed codium; then
					apply_settings
				else
					printf "VSCodium is not installed.\n" >&2
				fi
				;;
			v )
				VERBOSE="$TRUE"
				show_message "Verbose mode enabled."
				;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help "$script" "$version" "$E_INVALID_ARG"
		esac
		exit_code="$?"
		noOpt=0
	done
	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
	shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit "$exit_code"
}

main "$@"
