#!/usr/bin/env bash
#####################################################################
# Script Name  : install-handbrake
# Description  : Adds repository and installs handbrake
# Dependencies : None
# Arguments    : None
# Author       : Richard B. Romig, 14 February 2019
# Email        : rick.romig@gmail.com
# Comment      : Handbrake rips DVD movies
#              : Available as a flatpak via Flathub and Mint Software Manager
# https://dl.flathub.org/repo/appstream/fr.handbrake.ghb.flatpakref
# flatpak install fr.handbrake.ghb
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091,SC2034

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Variables ##

readonly _script=$(basename "$0")
readonly _version="0.3.3"
readonly _updated="04 May 2022"
readonly handbrake_ppa="ppa:stebbins/handbrake-releases"

## Functions ##

add_ppa() {
  echo "Adding Handbrake PPA..."
  sudo add-apt-repository "$handbrake_ppa"
  sudo apt update -qq
}

remove_ppa() {
  echo "Rmoving Handbake PPA..."
  sudo add-apt-repository --remove "$handbrake_ppa"
}

install_handbrake() {
  exists ghb && leave "Handbrake-GTK already installed."
  user_in_sudo
  support_ppa && add_ppa
  sudo apt install handbrake-gtk handbrake-cli -yy
  leave "Handbrake installed."
}

remove_handbrake() {
  exists ghb || leave "Handbrake is not installed."
  user_in_sudo
  if [[ -x /usr/bin/ghb || -x /usr/bin/HandBrakeCLI ]]; then
    support_ppa && remove_ppa
    sudo apt autoremove handbrake-gtk handbrake-cli -yy
    leave "Handbrake removed from system."
  else
    leave "Handbrake was not installed."
  fi
}

help() {
  local errcode="${1:-2}"
  cat << EOT
${green}Usage:${normal} $_script [-h] [-i] [-r]
${orange}OPTIONS${normal}
  -h  Display help
  -i  Install Handbrake
  -r  Remove Handbrake
EOT
  exit "$errcode"
}

## Execution ##

clear
echo "$_script v$_version ($_updated)"
echo -e "Installs Handbrake multithreaded video transcoder.\n"

if [[ "$#" -eq 0 ]]; then
  echo "${lightred}ERROR:${normal} No argument passed." >&2
  help 2
else
  optstr=":hir"
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        help 0 ;;
      i )
        install_handbrake ;;
      r )
        remove_handbrake ;;
      ? )
        echo "${lightred}ERROR:${normal} Invalid option -$OPTARG" >&2
        help 2 ;;
    esac
  done
fi
