#!/usr/bin/env bash
##########################################################################
# Script Name  : install-glow
# Description  : Installs and removes the Glow markdown reader.
# Dependencies : curl
# Arguments    : See help function
# Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 10 Jan 2022
# Updated      : 25 May 2026
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib
source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

## Global Variables ##

readonly script="${0##*/}"
readonly version="5.8.26145"
EC=0

## Functions ##

help() {
  local errcode="${1:-1}"
  local updated="25 May 2026"
  cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs/Removed Glow Markdown reader

${green}Usage:${normal} $script [-hir]
${orange}Available options:${normal}
  -c  Apply Glow configuration.
  -h  Show this help message and exit.
  -i  Installs the glow markdown reader.
  -r  Removes the glow markdown reader from the system.
_HELP_
  exit "$errcode"
}

glow_version() {
  cut -d' ' -f3 <(glow --version)
}

add_gpg() {
  local -r charm_url="$1"
  local -r charm_key="$2"
  if [[ -f "$charm_key" ]]; then
    printf "%s already exists.\n" "${charm_key##*/}"
    return
  fi
  printf "Adding the Charm GPG key...\n"
  [[ -d /etc/apt/keyrings ]] || sudo mkdir -p /etc/apt/keyrings
  check_package curl
  curl -fsSL "$charm_url/gpg.key" | sudo gpg --dearmor -o "$charm_key"
  printf "Charm GPG key applied.\n"
}

add_src_list() {
  local -r charm_url="$1"
  local -r charm_key="$2"
  local -r src_list="/etc/apt/sources.list.d/charm.list"
  if [[ -f "$src_list" ]]; then
    printf "%s already exists.\n" "${src_list##*/}"
    return
  fi
  printf "Creating the the Charm apt source list...\n"
  sudo tee "$src_list" <<< "deb [signed-by=$charm_key] $charm_url/ * *"
  printf "Charm apt source list created.\n"
}

install_glow() {
  local -r charm_url="https://repo.charm.sh/apt"
  local -r charm_key="/etc/apt/keyrings/charm.gpg"
  printf "Installing the Glow markdown reader...\n"
  sudo_login 2
  add_gpg "$charm_url" "$charm_key"
  add_src_list "$charm_url" "$charm_key"
  sudo apt update && sudo apt install -y glow
  if ! grep -q '^ii' <(dpkg -l glow 2>/dev/null); then
    printf "%s Glow installation failed.\n" "$RED_ERROR" >&2
    EC="$E_INSTALLATION"
    return
  fi
  printf "Glow %s successfully installed.\n" "$(glow_version)"
  glow_config
}

remove_glow() {
  printf "Removing the Glow markdown reader...\n"
  sudo_login 2
  sudo apt-get -y purge glow
  find /etc/apt -type f -name "charm*" -exec sudo rm -f {} \;
  [[ -f /usr/share/man/man1/glow.1.gz ]] && sudo rm -f /usr/share/man/man1/glow.1.gz
  find ~/ -maxdepth 3 -type d -path "$HOME/Downloads" -prune -o -path "$HOME/gitea" -prune -o -type d -name glow -exec rm -rf {} \;
  printf "Glow markdown reader has been removed.\n"
}

glow_config() {
  if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
		printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
    EC="$E_FILENOTFOUND"
		return
	fi
  printf "Installing glow.yml...\n"
  [[ -d ~/.config/glow ]] || mkdir -p ~/.config/glow
  [[ -f ~/.config/glow/glow.yml ]] && rm ~/.config/glow/glow.yml
  [[ -d ~/gitea/configs ]] && ln -sv ~/gitea/configs/glow/glow.yml ~/.config/glow/glow.yml
  [[ -d ~/Downloads/configs ]] && ln -sv ~/Downloads/configs/glow/glow.yml ~/Downloads/configs/glow/glow.yml
  printf "Glow configuration applied.\n"
}

main() {
  local noOpt opt optstr OPTARG OPTIND
	noOpt=1
  optstr=":chir"
  while getopts "$optstr" opt; do
    case "$opt" in
      c )
        if installed glow; then
          glow_config
        else
          printf "Glow is not installed.\n"
        fi
        ;;
      h )
        help 0
        ;;
      i )
        if installed glow; then
          printf "Glow %s is already installed.\n" "$(glow_version)"
        else
          install_glow
        fi
        ;;
      r )
        if installed glow; then
          remove_glow
        else
          printf "Glow is not installed.\n"
        fi
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$E_INVALID_ARG"
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit "$EC"
}

## Execution ##

main "$@"