#!/usr/bin/env bash
###############################################################################
# Script Name  : install-chrome
# Description  : Download and install the Google Chrome browser
# Dependencies : wget
# Arguments    : -h -i -r (See help function)
# Author       : Copyright (C) 2019 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 18 Jul 2019
# Updated      : 29 Jun 2026
# Comments     : Google Chrome updates through apt from source list
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
###############################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib
source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

## Variables ##

readonly script="${0##*/}"
readonly version="6.0.26180"
EC=0

## Functions ##

help() {
	local errcode="${1:-1}"
	local -r updated="29 Jun 2026"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs, updated, or removes Google Chrome.

${green}Usage:${normal} $script [-hir]
${orange}Available options:${normal}
  -h  Show this help message and exit
  -i  Install Google Chrome
  -r  Remove Google Chrome
  -u  Update Google Chrome (normally through apt updates)
_HELP_
  exit "$errcode"
}

chrome_version() {
  google-chrome-stable --version
}

set_gpg_key() {
  local -r trusted_key="$1"
  local -r trusted_key_url="https://dl.google.com/linux/linux_signing_key.pub"
  if [[ -f "$trusted_key" ]]; then
    printf "%s already exists.\n" "${trusted_key##*/}"
    return
  fi
  printf "Setting the trusted key...\n"
  gpg --dearmor < <(curl -fSsL "$trusted_key_url") | sudo tee "$trusted_key"
}

set_src_list(){
  local -r trusted_key="$1"
  local -r chrome_list="/etc/apt/sources.list.d/google-chrome.list"
  local -r source_list="deb [arch=amd64 signed-by=$trusted_key] http://dl.google.com/linux/chrome/deb/ stable main"
  if [[ -f "$chrome_list" ]]; then
		printf "%s already exists.\n" "${chrome_list##*/}"
		return
  fi
  printf "Creating the source list file...\n"
  sudo tee "$chrome_list" <<< "$source_list"
}

install_chrome() {
  local -r trusted_key="/usr/share/keyrings/google-chrome.gpg"
  printf "Updating apt cache and installing Google Chrome...\n"
  set_gpg_key "$trusted_key"
  set_src_list "$trusted_key"
  sudo apt update -qq
  sudo apt-get install -y google-chrome-stable
  if ! installed google-chrome-stable; then
    printf "%s Google Chrome installation failed.\n" "$RED_ERROR" >&2
    EC="$E_INSTALLATION"
    return
  fi
  printf "%s successfully installed.\n" "$(chrome_version)"
}

purge_chrome() {
  printf "Removing Google Chrome...\n"
  sudo apt purge google-chrome-stable
  find /etc/apt -type f -iname "google*" -exec sudo rm {} \;
  find /usr/share -type d -iname "google*" -exec sudo rm -rf {} \;
  find ~/ -maxdepth 2 -type d -name google-chrome -exec rm -rf {} \;
  printf "Google Chrome removed from this computer.\n"
}

main() {
  local noOpt opt optstr OPTARG OPTIND
  noOpt=1
  optstr=":hir"
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        help 0
        ;;
      i )
        if installed google-chrome-stable; then
          printf "%s is already installed.\n" "$(chrome_version)"
        else
          sudo_login 2
          check_package wget
          install_chrome
        fi
        ;;
      r )
        if installed google-chrome-stable; then
          sudo_login 2
          purge_chrome
        else
          printf "Google Chrome is not installed.\n"
        fi
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$E_INVALID_ARG"
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit "$EC"
}

## Execution ##

main "$@"
