#!/usr/bin/env bash
##########################################################################
# Script Name  : install-zram
# Description  : installs and configures Zram swap file.
# Dependencies : none
# Arguments    : none
# Author       : Copyright © 2025 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 18 Jan 2025
# Last updated : 18 Jan 2025
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

set -eu

## Functions ##

install_zram() {
	sudo apt install -y zram-tools
	sed -i.bak '/ALGO/s/^#//;/PERCENT/s/^#//;s/50$/25/' /etc/default/zramswap
	printf "Zram swap file installed.\n"
}

get_swap_type() {
  local s_type
  s_type=$(/usr/bin/lsblk | grep -w SWAP | awk '{print $6}')
  echo "$s_type"
}

die() {
  local errmsg errcode
  errmsg="${1:-Undefined error}"
  errcode="${2:-1}"
  printf "\e[91mERROR:\e[0m %s\n" "$errmsg" >&2
  exit "$errcode"
}

sudo_login() {
  local delay="${1:-2}"
  if id -nG "$USER" | grep -qw sudo; then
    if ! sudo -vn 2>/dev/null; then
      sudo ls > /dev/null 2>&1
      if [[ "$delay" -gt 0 ]]; then
        sleep "$delay"
        printf '\e[A\e[K'
      fi
    fi
 else
    die "$USER is not a member of the sudo group. Access denied."
  fi
}

# shellcheck disable=SC2001
over_line() {
  local char len line title
  title="$1"
  char="${2:--}"
  len=${#char}
  (( len > 1 )) && char=${char::1}
  line=$(echo "$title" | sed "s/./$char/g")
  printf "%s\n%s\n"  "$line" "$title"
}

main() {
  local script version swap_type
  script=$(basename "$0")
  version="1.0.25018"
  swap_type=$(get_swap_type)
  case "$swap_type" in
    disk )
      printf "Swap file already exists.\n" ;;
    part )
      printf "Swap partition already exists.\n" ;;
    * )
      printf  "No swap exists. Installing Zram swap file...\n"
      sudo_login 2
      install_zram
  esac
  /usr/bin/lsblk
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
