#!/usr/bin/env bash
###############################################################################
# Script Name  : install-timeshift
# Description  : installs and configures timeshift
# Dependencies : none
# Arguments    : none
# Author       : Copyright © 2024, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
# Created      : 03 Jun 2024
# Last updated : 03 Jun 2024
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Global variables ##
_script=$(basename "$0"); readonly _script
_version="1.0.24155"

## Execution ##

sudo_login 2
echo "$_script v$_version"
# Install timeshift
sudo apt-get -y timeshift
# configure timeshift
[[ -f /etc/timeshift/timeshift.json ]] || sudo cp /etc/timeshift/default.json /etc/timeshift/timeshift.json
sudo sed -i -f "$HOME/bin/files/timeshift.sed" /etc/timeshift/timeshift.json
sudo sed -i 's/^"/    "/' /etc/timeshift/timeshift.json
echo "Timeshift installed and configured."
exit
