#!/usr/bin/env bash
###############################################################################
# Script Name  : install-chrome
# Description  : Download and install the Google Chrome browser
# Dependencies : wget
# Arguments    : -h -i -r (See help function)
# Author       : Copyright (C) 2019 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 18 Jul 2019
# Updated      : 19 Jul 2026
# Comments     : Google Chrome updates through apt from the sources file
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the# GNU General Public License for more details.
###############################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib.bash
source functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

help() {
  local -r script="$1"
  local -r version="$2"
	local -r errcode="${3:-1}"
	local -r updated="19 Jul 2026"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs, updated, or removes Google Chrome.

${green}Usage:${normal} $script [-hir]
${orange}Available options:${normal}
  -h  Show this help message and exit
  -i  Install Google Chrome
  -r  Remove Google Chrome
_HELP_
  exit "$errcode"
}

chrome_version() {
  google-chrome-stable --version
  return 0
}

set_gpg_key() {
  local -r trusted_key="$1"
  local -r trusted_key_url="https://dl.google.com/linux/linux_signing_key.pub"
  printf "Setting the trusted key...\n"
  gpg --dearmor < <(curl -fSsL "$trusted_key_url") | sudo tee "$trusted_key"
  return 0
}

set_sources() {
  local -r key_file="$1"
  local -r sources_file=/etc/apt/sources.list.d/google-chrome.sources
	local -r sources_uri="https://dl.google.com/linux/chrome-stable/deb/"
  [[ -d /etc/apt/sources.list.d/google-chrome.list ]] && sudo mv /etc/apt/sources.list.d/google-chrome.list /etc/apt/sources.list.d/google-chrome.list.bak
  printf "Creating the source list file...\n"
	tee $sources_file <<< \
"X-Repolib-Name: Google Chrome
Types: deb
URIs: $sources_uri
Suites: stable
Components: main
Architectures: amd64
Signed-By: $key_file"
  return 0
}

install_chrome() {
  local -r trusted_key="/usr/share/keyrings/google-chrome.gpg"
  printf "Updating apt cache and installing Google Chrome...\n"
  set_gpg_key "$trusted_key"
  set_sources "$trusted_key"
  sudo apt update -qq
  sudo apt-get install -y google-chrome-stable
  if ! installed google-chrome-stable; then
    printf "%s Google Chrome installation failed.\n" "$RED_ERROR" >&2
    return "$E_INSTALLATION"
  fi
  printf "%s successfully installed.\n" "$(chrome_version)"
  return 0
}

purge_chrome() {
  printf "Removing %s...\n" "$(chrome_version)"
  sudo apt purge google-chrome-stable
  find /etc/apt -maxdepth 2 -type f -iname "google*" -exec sudo rm {} \;
  find /usr/share -maxdepth 3 -type d -iname "google*" -exec sudo rm -rf {} \;
  find ~/ -maxdepth 2 -type d -name google-chrome -exec rm -rf {} \;
  printf "Google Chrome removed from this computer.\n"
}

main() {
  local -r script="${0##*/}"
  local -r version="6.0.26200"
  local -i exit_code=0
  local opt OPTARG OPTIND
  local -i noOpt=1
  local -r optstr=":hir"
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        help "$script" "$version" 0
        ;;
      i )
        if installed google-chrome-stable; then
          printf "%s is already installed.\n" "$(chrome_version)"
        else
          sudo_login 2
          check_package wget
          install_chrome
        fi
        ;;
      r )
        if installed google-chrome-stable; then
          sudo_login 2
          purge_chrome
        else
          printf "Google Chrome is not installed.\n"
        fi
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$script" "$version" "$E_INVALID_ARG"
    esac
    exit_code="$?"
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit "$exit_code"
}

main "$@"
