#!/usr/bin/env bash
#############################################################################
# Script Name  : install-audacious
# Description  : Installs/Removes Audacious audio player
# Dependencies : none
# Arguments    : none
# Author       : Copyright (C) 2020, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 23 Mar 2020
# Updated      : 16 Jul 2025
# Comments     : Does not support installation from Ubuntu PPAs or flatpak.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
#############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

set -eu

## Global Variables ##

readonly script="${0##*/}"
readonly version="2.4.25197"

## Functions ##

help() {
	local -r errcode="${1:-2}"
  local -r updated="16 Jul 2025"

	cat << _HELP_
${orange}$script${normal} $version ($updated)
Install or remove Audacious audio player

${green}Usage:${normal} $script [OPTION]
${orange}Available options:${normal}
  -h  Show this help message and exit
  -i  Install Audacious audio player
  -r  Remove Audacious audio player
_HELP_
  exit "$errcode"
}

install_audacious() {
  if in_repos audacious; then
    sudo_login 2
    printf "Installing Audacious audio player...\n"
    sudo apt update -qq
    sudo apt install audacious audacious-plugins -yy
    printf "Audacious audio player installed from distro repository.\n"
  else
    printf "Audacious is not in repositories. Audacious audio player not installed.\n"
  fi
}

remove_audacious() {
  sudo_login 2
  printf "Removing Audacious audio player....\n"
  sudo apt remove --autoremove audacious audacious-plugins
  printf "Audacious audio player removed.\n"
}

main() {
  local noOpt opt optstr
  noOpt=1
  optstr=":hir"
  while getopts "$optstr" opt; do
	  case "$opt" in
		  h )
			  help 0
		    ;;
      i )
        if exists audacious; then
          printf "Audacious audio player is already installed.\n" >&2
        else
          install_audacious
        fi
        ;;
      r )
        if exists audacious; then
          remove_audacious
        else
          printf "Audacious audio player is not installed." >&2
        fi
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help 2
    esac
    noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
