#!/usr/bin/env bash
#####################################################################
# Script Name  : install-homebank
# Description  : Installs Homebank from PPA or distribution reposistory
# Dependencies : none
# Arguments    : none
# Author       : Copyright (C) 2018, Richard Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 29 Nov 2018
# Updated      : 13 Oct 2024
# Comments     : Available as a flatpak (preferred method)
#              : https://flathub.org/apps/details/fr.free.Homebank
#              : Linux Mint Sofware Manager
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

script=$(basename "$0"); readonly script
readonly version="5.1.24287"

## Functions ##

homebank_version() {
  local hb_ver
  if exists homebank; then
    hb_ver=$(homebank --version | cut -d' ' -f2)
  elif flatpak list | grep -q 'Homebank';then
    hb_ver=$(flatpak list | awk '/Homebank/ {print $(NF-2)}')
  fi
  printf "%s" "$hb_ver"
}

# flatpak_version() {
#   flatpak list | awk '/HomeBank/ {print $3}'
# }

flatpak_homebank() {
  exists flatpak || return "$FALSE"
  flatpak list | grep -qw HomeBank && return "$TRUE" || return "$FALSE"
}

install_flatpak_hombank() {
  printf "Install the HomeBank flatpak...\n"
  sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  # flatpak install --user flathub fr.free.Homebank
  printf "HomeBank flatpak (%s) installed.\n" "$(homebank_version)"
}

remove_flatpak_homebank() {
  printf "Removing HomeBank flatpak (%s)...\n" "$(homebank_version)"
  flatpak uninstall --oninteractive --assumeyes fr.free.Homebank
  remove_configs
  printf "HomeBank has been removed.\n"
}

add_ppa() {
  printf "Adding PPA repository...\n"
  sudo add-apt-repository ppa:mdoyen/homebank
}

remove_ppa() {
  sudo add-apt-repository --remove ppa:mdoyen/homebank
}

install_homebank() {
  sudo_login 2
  support_ppa && add_ppa
  sudo apt-get install homebank -yyq
  printf "HomeBank %s installed.\n" "$(homebank_version)"
}

remove_homebank() {
  printf "Removing HomeBank %s...\n" "$(homebank_version)"
  sudo_login 2
  support_ppa && remove_ppa
  sudo apt-get remove homebank -yy > /dev/null 2>&1
  remove_configs
  printf "HomeBank has been removed.\n"
}

purge_homebank() {
  printf "Removing HomeBank %s and purging configuration files.\n" "$(homebank_version)"
  sudo_login 2
  support_ppa && remove_ppa
  sudo apt-get purge homebank -yy > /dev/null 2>&1
  remove_configs
  printf "HomeBank and its configuration files have been removed.\n"
}

remove_configs() {
  local cfg_d="$HOME/.config/homebank"
  if default_no "Remove user configuration files?"; then
    printf "Removing user configuration files...\n"
    [[ -d "$cfg_d" ]] && rm -rf "$cfg_d"
    printf "User configuration files removed.\n"
  else
    printf "User configuations files left intact.\n"
  fi
}

help() {
  local errcode updated
	errcode="${1:-2}"
	updated="13 Oct 2024"
  cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs/Removes HomeBank Personal Finance Software.

${green}Usage:${normal} $script [option]

${orange}Available options:${normal}
  -f  install HomeBank from Flathub
  -h  Display help
  -i  Install HomeBank from PPA or repository
  -p  Remove HomeBank and purge configuration files (PPA or repository)
  -r  Remove HomeBank (PPA or repository)
HomeBank is also available as a Flatpak (Flathub or Mint Software Manager)
_HELP_
  exit "$errcode"
}

main() {
  local noOpt opt optstr
  noOpt=1
  optstr=":fhipr"
  while getopts "$optstr" opt; do
    case "$opt" in
      f )
        exists homebank && leave "HomeBank $(homebank_version) is already installed."
        flatpak_homebank && leave "HomeBank $(homebank_version) (flatpak) is installed."
        install_flatpak_hombank
      ;;
      h )
        help 0
      ;;
      i )
        exists homebank && leave "HomeBank $(homebank_version) is already installed."
        flatpak_homebank && leave "HomeBank $(homebank_version) (flatpak) is installed."
        sudo_login 2
        install_homebank
      ;;
      p )
        exists hombank || leave "HomeBank (.deb) is not installed."
        sudo_login 2
        purge_homebank
      ;;
      r )
        if flatpak_homebank; then
          remove_flatpak_homebank
        elif exists hombank; then
          sudo_login 2
          remove_homebank
        else
          leave "HomeBank is not installed.\n"
        fi
      ;;
      ? )
        printf "%s Invalid option: -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help 2
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  printf "%s v%s\n" "$script" "$version"
  exit
}

## Execution ##

main "$@"
