#!/bin/bash
##########################################################################
# Script Name  : install-glow
# Description  : Installs, updates, and removes the Glow markdown reader.
# Dependencies : curl, gdebi
# Arguments    : [-h] [-i] [-r] (See help function)
# Author       : Copyright (C) 2022, Richard B. Romig, 10 Jan 2022
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.4.8"
readonly _updated="29 Mar 2023"
readonly src_list="/etc/apt/sources.list.d/charm.list"
readonly keyring_dir="/etc/apt/keyrings"

## Functions ##

src_gpg() {
  echo "Adding the Charm GPG key..."
  [[ -d "$keyring_dir" ]] || sudo mkdir -p "$keyring_dir"
  curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
  echo "Creating the the Charm apt source list..."
  echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee "$src_list"
}

install_glow() {
  echo "Installing the Glow markdown reader..."
  src_gpg
  sudo apt update && sudo apt install glow -yy
  echo "glow $(glow_ver) successfully installed."
}

remove_glow() {
  echo "Removing the Glow markdown reader..."
  sudo apt-get remove glow
  [[ -f "$src_list" ]] && rm -v "$src_list"
  [[ -f "$keyring_dir/charm.gpg" ]] && rm -v "$keyring_dir/charm.gpg"
  echo "Glow markdown reader has been removed."
}

glow_ver() {
  glow --version | awk '{print $3}' | sed 's/v//'
}

check_dependencies() {
  local packages=( curl gdebi )
  check_packages "${packages[@]}"
}

exists_glow() {
  dpkg -l | grep -qw glow && return "$TRUE" || return "$FALSE"
}

help() {
  local errcode="${1:-2}"
  cat << END_HELP
${green}Usage:${normal} $_script [OPTION]
${orange}OPTIONS:${normal}
  -h    Displays help.
  -i    Installs the glow markdown reader.
  -r    Removes the glow markdown reader from the system.
  -s    Apply charm.list and gpg key
END_HELP
  printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
  exit "$errcode"
}

## Execution ##

check_dependencies
printf "Installs or removes the Glow markdown reader.\n"

noOpt=1
optstr=":hirs"
while getopts "$optstr" opt
do
  case "$opt" in
    h )
      help 0
      ;;
    i )
      exists_glow && leave "Glow $(glow_ver) is already installed."
      user_in_sudo
      echo "${lightyellow}Installing Glow markdown reader...${normal}"
      install_glow
      ;;
    r )
      exists_glow || leave "Glow is not installed."
      user_in_sudo
      remove_glow
      ;;
    s )
      exists_glow || leave "Glow is not installed."
      user_in_sudo
      src_gpg
      echo "charm.list created, gpg key applied."
      ;;
    ? )
      echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
      help 2
      ;;
  esac
	noOpt=0
done
if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
exit