#!/usr/bin/env bash
##########################################################################
# Script Name  : install-codium
# Description  : installs vscodium from a repo using apt-get
# Dependencies : wget
# Arguments    : see help function for options
# Author       : Copyright © 2023 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 04 Aug 2023
# Updated      : 05 Jun 2024
# Comments     : Alternative to downloading directly from GitHub repo.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="1.10.24157"
readonly _updated="05 Jun 2024"
readonly key_file="/usr/share/keyrings/vscodium-archive-keyring.asc"
readonly src_list="/etc/apt/sources.list.d/vscodium.list"
verbose_mode="$FALSE"

## Functions ##

help() {
	errcode="${1:-2}"
	cat << END_HELP
${green}Usage:${normal} $_script [OPTION]
${orange}OPTIONS:${normal}
	-a	Set apt gpg key and source list
	-h	Display help
	-i	Install VSCodium via apt
	-r	Remove VSCodium
	-s	Apply VSCodium settings
  -v  Enable verbose mode
END_HELP
	printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
  exit "$errcode"
}

codium_version() {
	codium --version | head -n 1
}

apply_settings() {
	local localip repository cfg_dir json_file
	localip=$(local_ip)
  cfg_dir="${HOME}/.config/VSCodium/User"
  json_file="settings.json"
  [[ -d "$cfg_dir" ]] || mkdir -p "$cfg_dir"
  show_me "Applying VSCodium settings..."
	if [[ "$localip" == "16" ]]; then
		show_me "Copying $json_file from local repository..."
		repository="$HOME/gitea/configs/VSCodium/User"
		cp -v "$repository/$json_file" "$cfg_dir/"
	else
		show_me "Downloading $json_file from Gitea server..."
		repository="configs/raw/branch/main/VSCodium/User"
		wget -P "$cfg_dir" "$Gitea_URL/$repository/$json_file"
	fi
  show_me "VSCodium settings applied."
}

set_key() {
	local key_url="https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg"
	wget "$key_url"
	show_me "Setting the GPG key..."
	sudo mv pub.gpg "$key_file"
}

set_src() {
	local src_url="https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main"
	show_me "Creating the source list file..."
	echo "deb [ signed-by=$key_file ] $src_url" | sudo tee "$src_list" > /dev/null
}

install_vscodium() {
	show_me "Installing VSCodium..."
	set_key
	set_src
	sudo apt-get update
	sudo apt-get install codium
	apply_settings
	printf "VSCodium %s successfully installed.\n" "$(codium_version)"
}

remove_vscodium() {
	local cfg_dir="${HOME}/.config/VSCodium"
	show_me "Removing VSCodium..."
	sudo apt-get purge codium
	[[ -f "$key_file" ]] && sudo rm -v "$key_file"
	[[ -f "$src_list" ]] && sudo rm -v "$src_list"
  [[ -d "$cfg_dir" ]] && rm -rf "$cfg_dir"
	printf "VSCodium has been removed.\n"
}

show_me() {
  local message="$1"
  [[ "$verbose_mode" == "$TRUE" ]] && echo "$message"
}

## Execution ##

box "$_script v$_version"
printf "Installs or removes VSCodium\n"
sudo_login 2
check_package wget
noOpt=1
optstr=":ahirsv"
while getopts "$optstr" opt; do
	case "$opt" in
		a)
			exists codium || leave "VSCodium is not installed."
			show_me "Setting the GPG key and creating the source list file."
			set_key
			set_src
		;;
		h )
			help 0
		;;
		i )
			exists codium && leave "VSCodium $(codium_version) is already installed."
			install_vscodium
		;;
		r )
			exists codium || leave "VSCodium is not installed."
			remove_vscodium
		;;
		s )
		  exists codium || leave "VSCodium is not installed."
    	apply_settings
		;;
		v )
      verbose_mode="$TRUE"
      show_me "Verbose mode enabled."
		;;
		? )
			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
			help 2
	esac
	noOpt=0
done
[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
shift "$(( OPTIND - 1 ))"
exit
