#!/usr/bin/env bash
##########################################################################
# Script Name  : install-rtorrent
# Description  : installs and configures rtorrent ncurses BitTorrent client
# Dependencies : none
# Arguments    : none
# Author       : Copyright (C) 2022, Richard B. Romig, 29 Jan 2022
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 29 Jan 2022
# Updated      : 06 Jun 2024
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="1.6.24158"

## Functions ##

make_dirs() {
  local default_dir session_dir watch_dir
  default_dir="$HOME/Downloads/torrents"
  session_dir="$HOME/session"
  watch_dir="$HOME/watch"
  echo "Creating rtorrent working directories ..."
  [[ -d "$default_dir" ]] || mkdir -pv "$default_dir"
  [[ -d "$session_dir" ]] || mkdir -pv "$session_dir"
  [[ -d "$watch_dir" ]] || mkdir -pv "$watch_dir"
}

make_rc() {
  local rtorrent_gz rtorrent_sed
  rtorrent_sed="$HOME/bin/files/rtorrentrc.sed"
  rtorrent_gz="/usr/share/doc/rtorrent/examples/rtorrent.rc.gz"
  echo "Creating and configuring .rtorrent.rc ..."
  cp -v "$rtorrent_gz" "$HOME/"
  gunzip "$HOME/rtorrent.rc.gz"
  mv -v "$HOME/rtorrent.rc" "$HOME/.rtorrent.rc"
  sed -i -f "$rtorrent_sed" "$HOME/.rtorrent.rc"
  echo ".rtorrent.rc configured."
}

install_rtorrent() {
  sudo_login 2
  echo "Installing rtorrent bit torrent client ..."
  sudo apt install rtorrent -yy
  make_dirs
  make_rc
}

## Execution ##

clear
box "$_script v$_version"
echo "Installs rtorrent ncurses BitTorrent client and configures .rtorrent.rc"
install_rtorrent
# rt_ver=$(dpkg -l | awk '$2 == "rtorrent" {print $3}' | sed 's/[+-].*//')
leave "rtorrent BitTorrent client (version $(dpkg -l | awk '$2 == "rtorrent" {print $3}' | sed 's/[+-].*//')) installed and configured."
