#!/usr/bin/env bash
###############################################################################
# Script Name  : install-timeshift
# Description  : installs and configures timeshift
# Dependencies : ~/bin/files/timeshift.sed
# Arguments    : none
# Author       : Copyright © 2024, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
# Created      : 03 Jun 2024
# Last updated : 01 Dec 2025
# Comments     : My default configuration is 5 daily, 3 weekly, & 2 monthly snapshots.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Functions ##

get_home_uuid() {
  local target_uuid
  target_uuid=$(lsblk -f | awk '/home/ {print $4}')
  [[ "$target_uuid" ]] || target_uuid=$(lsblk -f | awk '$NF ~ /\/$/ {print $4}')  # root partition if no /home partition
  printf "%s" "$target_uuid"
}

configure_timeshift() {
  local ts_uuid script_dir
  ts_uuid=$(get_home_uuid)
  script_dir=$(dirname "$(readlink -f "${0}")")
  local -r ts_dir="/etc/timeshift"
  local -r ts_json="timeshift.json"
  local -r ts_sed="$script_dir/files/timeshift.sed"
  if [[ ! -f "$ts_sed" ]]; then
    printf "%s was not found. Configure using the GUI application.\n"  "${ts_sed##*/}" >&2
    return
  fi
  printf "Configuring Timeshift...\n"
  sudo cp -v "$ts_dir/default.json" "$ts_dir/$ts_json"  # copy default json file
  sudo sed -i -f "$ts_sed" "$ts_dir/$ts_json" # apply settings
  sudo sed -i "/backup_device_uuid/ s/\",/$ts_uuid\",/" "$ts_dir/$ts_json"  # insert UUID for snapshots
  sudo sed -i 's/^"\//    "\//;s/^"/  "/' "$ts_dir/$ts_json"  # to get leading spaces right in json file
}

install_timeshift() {
  printf "Installing Timeshift...\n"
  sudo apt-get install -y timeshift
  exists timeshift || die "Timeshift installation failed." 1
  configure_timeshift
  printf "%s installed and configured.\n" "$(timeshift --version)"
}

main() {
  local -r script="${0##*/}"
  local -r version="3.4.25296"
  if exists timeeshift; then
    printf "%s is already installed.\n" "$(timeshift --version)"
  elif in_repos timeshift; then
    sudo_login 2
    install_timeshift
  else
    printf "Timeshift is not available in %s repositories.\n" "$(get_distribution)"
  fi
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
