#!/usr/bin/env bash
##########################################################################
# Script Name  : install-xrdp
# Description  : Installs xrdp to Debian-based systems
# Dependencies : ufw
# Arguments    : none
# Author       : Copyright © 2024 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 24 Aug 2024
# Last updated : 03 Dec 2025
# Comments     : Working with i3 & Xfce4, no desktop background on Cinnamon.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

add_to_sslcert() {
	printf "Adding xrdp user to the SSL-Cert group...\n"
	getent group ssl-cert || sudo groupadd ssl-cert > /dev/null 2>&1
	[[ $(awk '/ssl-cert:/ && /xrdp/' /etc/group) ]] || sudo adduser xrdp ssl-cert
}

cinn_xsessionrc() {
	cat << _CINNX_  > "$HOME"/.xsessionrc
if [ $DISPLAY != ":0" ]; then
  export XAUTHORITY=${HOME}/.Xauthority
fi
_CINNX_
}

install_xdrp() {
	printf "Installing xrdp...\n"
	sudo apt-get install -y xrdp xorgxrdp
	add_to_sslcert
	printf "Enabling and starting xrdp sevice...\n"
	sudo systemctl enable --now xrdp
	printf "Allow xrdp port (3389/tcp) on UFW...\n"
	sudo ufw status | grep -q 'inactive' && sudo ufw enable
	sudo ufw status | grep -q '3389' || sudo ufw allow 3389/tcp
}

setup_xsession() {
	local xsessions_d="/usr/share/xsessions"
	if [[ -f "$xsessions_d/i3.desktop" ]]; then
		printf "Setting up i3 session...\n"
		echo "exec i3 >>~/.local/share/logs/i3log 2>&1" | tee "$HOME/.xsessionrc"
	elif [[ -f "$xsessions_d/xfce.desktop" ]]; then
		printf "Setting up Xfce session...\n"
		echo "xfce4-session" | tee "$HOME/.xsession"
	elif [[ -f "$xsessions_d/cinnamon.desktop" ]]; then
		printf "Setting up Cinnamon session...\n"
		echo "env -u SESSION_MANAGER -u DBUS_SESSION_BUS_ADDRESS cinnamon-session" | tee "$HOME/.xsession"
		cinn_xsessionrc
		# echo "exec cinnamon2d >>~/.local/share/logs/cinnamon.log 2>&1" | tee "$HOME/.xsession"
	fi
}

main() {
  local -r script="${0##*/}"
  local -r version="2.2.25337"
	sudo_login 2
	check_package ufw
	install_xdrp
	setup_xsession
	printf "XRDP server installed. Please reboot the system.\n"
	over_line "$script $version"
	exit 0
}

## Execution ##

main "$@"
