#!/usr/bin/env bash
##########################################################################
# Script Name  : install-dsh
# Description  : Installs & configures DSH
# Dependencies : git curl
# Arguments    : none
# Author       : Copyright © 2024 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 08 Apr 2024
# Last updated : 01 Oct 2024
# Comments     : Intended for main system
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

## Global Variables ##

readonly dsh_path="/etc/dsh"
localip=$(local_ip); readonly localip

## Functions ##

check_dependencies() {
  local packages=( curl git)
  check_packages "${packages[@]}"
}

copy_group_list() {
  local file repository
  file="$1"
  printf "Copying DSH machines list to the %s group...\n" "$file"
  if [[ "$localip" == "16" ]]; then
    repository="$HOME/gitea/configs/dsh/group"
    sudo cp "$repository/$file" "$dsh_path/group"
  else
    repository="configs/raw/branch/main/dsh/group"
    sudo curl -so "$dsh_path/group/$file" "$Gitea_URL/$repository/$file"
  fi
  printf "%s installed to %s/group/\n" "$file" "$dsh_path"
}

copy_machine_list() {
    local file repository
  file="machines.list"
  printf "Copying %s to %s...\n" "$file" "$dsh_path"
  if [[ "$localip" == "16" ]]; then
    repository="$HOME/gitea/configs/dsh"
    sudo cp "$repository/$file" "$dsh_path/"
  else
    repository="configs/raw/branch/main/dsh"
    sudo curl -so "$dsh_path/$file" "$Gitea_URL/$repository/$file"
  fi
  printf "%s copied to %s/\n" "$file" "$dsh_path"
  printf "Creating symbolic link from %s to %s/group/all.\n" "$file"  "$dsh_path"
  sudo ln -s /etc/dsh/machines.list /etc/dsh/group/all
}

install_dsh() {
  local group groups
  groups=( desktops i3wm laptops )
  sudo apt-get -yy install dsh
  printf "Changing remote shell to ssh.\n"
  sudo sed -i '/remoteshell/s/rsh/ssh/' "$dsh_path/dsh.conf"
  copy_machine_list
  for group in "${groups[@]}"; do
    copy_group_list "$group"
  done
}

main() {
  local script version
  script=$(basename "$0")
  version="1.2.24275"
  sudo_login 2
  check_dependencies
  install_dsh
  leave "$script $version"
}

## Execution ##

main "$@"
