#!/usr/bin/env bash
#############################################################################
# Script Name  : install-brave
# Description  : installs the Brave broswer
# Dependencies : apt-transport-https, curl, libu2f-udev
# Arguments    : --help, --install, --remove
# Author       : Copyright (C) 2019 Richard B. Romig, 12 Dec 2019
# Email        : rick.romig@gmail.com
# Comments     : For Debian, Ubuntu, Mint ... (Code from Brave's instructions)
#              : Brave is only supported on 64-bit AMD/Intel architectures (amd64/x86_64).
# 23 Feb 2022  : Added 'getopts' to handle command-line options.
# 21 Mar 2022  : Changed usage function to Here-doc format.
# 25 Mar 2022  : Changed OpenGPG repo signing key method (apt-key deprecated).
# 26 Mar 2022  : Reverted to previous signing method.
# 29 Mar 2022  : Added $OPTARG to Invalid option message.
# 04 May 2022  : Added error code upon exit via usage function.
# 10 Jul 2022  : Added optstr and opt variables to getopts routine.
# 11 Oct 2022  : Cleaned up the script.
# 07 Nov 2022  : Added brave_ver function.
# 08 Nov 2022  : Changed to OpenGPG repo signing key method per Brave's instructions.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
#############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

readonly _script=$(basename "$0")
readonly _version="0.4.0"
readonly _updated="08 Nov 2022"
readonly red_error="${lightred}ERROR:${normal}"
readonly brave_key="/usr/share/keyrings/brave-browser-archive-keyring.gpg"
readonly brave_list="/etc/apt/sources.list.d/brave-browser-release.list"

## Functions ##

brave_ver() {
  brave-browser --version | awk '{print $NF}'
}

install_brave() {
  local key_url="https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
  local list_url="https://brave-browser-apt-release.s3.brave.com/ stable main"
  # Install curl, apt-transport-https, libu2f-udev, if not installed
  check_dependencies
  printf "Installing the Brave Browser ...\n"
  # Import the public key for verification of the APT repository
  sudo curl -fsSLo "$brave_key" "$key_url"
  # Add the repository
  echo "deb [signed-by=$brave_key arch=amd64] $list_url" | sudo tee "$brave_list"
  # Install Brave
  sudo apt update -qq
  sudo apt install brave-browser brave-keyring -yy
  printf "Brave browser %s successfully installed.\n" "$(brave_ver)"
}

remove_brave() {
	local apt_key="/etc/apt/trusted.gpg.d/brave-browser-release.gpg"
  printf "Uninstalling the Brave Browser...\n"
  sudo apt-get remove brave-browser brave-keyring -yy
  # Remove trusted keys
  if [[ -f "$apt_key" ]]; then
    sudo rm "$apt_key"
    sudo apt-key del C3D4E821 2>/dev/null #apt-key deprecated
  elif [[ -f "$brave_key" ]]; then
    sudo rm "$brave_key"
  fi
  # Remove brave-browser-release.list
  [[ -f "$brave_list" ]] && sudo rm "$brave_list"
  printf "Brave browser has been uninstalled.\n"
}

remove_configs() {
  printf "Removing local configuration and cache files...\n"
  [[ -d "$HOME/.config/BraveSoftware" ]] && rm -rf "$HOME/.config/BraveSoftware"
  [[ -d "$HOME/.cache/BraveSoftware" ]] && rm -rf "$HOME/.cache/BraveSoftware"
  printf "Brave local configuration and cache files have been removed.\n"
}

usage() {
  local errcode="${1:-2}"
  cat << END_HELP
${orange}Usage:${normal} $_script [-h] [-i] [-r]
Options:
  -h   help
  -i   Install the Brave Browser.
  -p   Purge the Brave Browser & configuration files.
  -r   Remove the Brave Browser & leave configuration files.
END_HELP
  printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
  exit "$errcode"
}

check_dependencies() {
  check_package curl
  check_package apt-transport-https
  check_package libu2f-udev
}

## Execution ##

printf "Installs/Removes the Brave browser.\n\n"

if [[ $# -eq 0 ]]; then
  printf "%s No argument passed.\n" "$red_error" >&2
  usage 2
else
  optstr=":hipr"
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        usage 0 ;;
      i )
        exists brave-browser && leave "Brave browser $(brave_ver) is already installed."
        user_in_sudo
        install_brave ;;
      p )
        exists brave-browser || leave "Brave browser is not installed."
        user_in_sudo
        remove_brave
        remove_configs ;;
      r )
        exists brave-browser || leave "Brave browser is not installed."
        user_in_sudo
        remove_brave ;;
      ? )
        printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
        usage 2 ;;
    esac
  done
fi
printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
exit
