#!/usr/bin/env bash
##########################################################################
# Script Name  : install-keepassxc
# Description  : Installs/removes KeePassXC from Flathub or distro repos
# Dependencies : wget
# Arguments    : -c -d -f -h -r (see help function)
# Author       : Copyright (C) 2021, Richard B. Romig, LudditeGeek
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 26 Jan 2021
# Updated      : 04 Jun 20254
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Variables ##

readonly script="${0##*/}"
readonly version="3.18.25155"
readonly cfg_dir="$HOME/.config/keepassxc"

## Functions ##

help() {
  local errcode updated
	errcode="${1:-2}"
	updated="03 Mar 2025"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs/Removed KeePassXC password manager

${green}Usage:${normal} $script [OPTION]

${orange}Available options:${normal}
  -c  Apply KeePassXC configuration.
  -d  Install KeePassXC from distribution repositories.
  -f  Install KeePassXC from flathub repositories.
  -h  Show this help message and exit.
  -r  Remove KeePassXC from the system.
_HELP_
  exit "$errcode"
}

keepass_version() {
  if exists keepassxc; then
    dpkg -l keepassxc | awk '/ii/ {print $3}' | sed 's/[+-].*//'
  elif flatpak list | grep -qw KeePassXC; then
    flatpak list | awk '/KeePassXC/ {print $3}'
  fi
}

install_flathub_keepassxc() {
  sudo_login 2
  sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  flatpak install --user flathub org.keepassxc.KeePassXC
  printf "KeePassXC %s installed from flathub.\n" "$(keepass_version)"
}

install_distro_keepassxc() {
  sudo_login 2
  sudo apt-get install keepassxc -yy
  create_ini
  printf "Keepassxc %s installed from distro repositories.\n" "$(keepass_version)"
}

remove_flatpak_keepassxc() {
  printf "Removing the KeePassXC flatpak...\n"
  [[ -d "HOME/.var/app/org.keepassxc.KeePassXC" ]] && flatpak uninstall --noninteractive --assumeyes org.keepassxc.KeePassXC
  printf "KeePassXC flatpak removed.\n"
}

remove_distro_keeepassxc() {
  sudo_login 2
  printf "Removing the KeePassXC DEB package...\n"
  sudo apt-get remove --purge keepassxc -yy
  find "$HOME/.config/" -maxdepth 2 -type d -name keepassxc -exec rm -rf {} \;
  printf "KeePassXC DEB package removed.\n"
}

create_ini() {
	local repository ini_file
  repository=$(assign_cfg_repo)
  ini_file="keepassxc.ini"
  [[ -d "$cfg_dir" ]] || mkdir -p "$cfg_dir"
  printf "Applying %s ...\n" "$ini_file"
  cp -v "$repository/keepassxc/$ini_file" "$cfg_dir/"
  printf "%s applied.\n" "$ini_file"
}

main() {
  local noOpt opt optstr
  noOpt=1
  optstr=":cdfhr"
  while getopts "$optstr" opt; do
    case "$opt" in
      c )
        create_ini
      ;;
      d )
        if exists keepassxc; then
          printf "KeePassXC version %s is already installed from distro.\n" "$(keepass_version)"
        elif  flatpak list | grep -qw KeePassXC; then
          printf "KeePassXC %s is already installed from flatpak.\n" "$(keepass_version)"
        else
          install_distro_keepassxc
        fi
      ;;
      f )
        if exists keepassxc; then
          printf "KeePassXC version %s is already installed from distro.\n" "$(keepass_version)"
        elif  flatpak list | grep -qw KeePassXC; then
          printf "KeePassXC %s is already installed from flatpak.\n" "$(keepass_version)"
        else
          install_flathub_keepassxc
        fi
      ;;
      h )
        help 0
      ;;
      r )
        if flatpak list | grep -qw KeePassXC; then
          remove_flatpak_keepassxc
        elif exists keepassxc; then
          remove_distro_keeepassxc
        else
          leave "KeePassXC is not installed."
        fi
      ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help 2
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
