#!/usr/bin/env bash
##########################################################################
# Script Name  : install-terminator
# Description  : Installs the Terminator terminal emulator from repos.
# Dependencies : curl
# Arguments    : See help function
# Author       : Copyright (C) 2020 Richard B. Romig, MosfaNet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 14 Dec 2020
# Updated      : 26 Jun 2025
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

## Global Variables ##

readonly script="${0##*/}"
readonly version="6.17.25177"

## Functions ##

help() {
	local errcode="${1:-2}"
	local -r updated="26 Jun 2025"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs/Removes/Configures Terminator terminal emulator

${orange}Usage:${normal} $script [-c] [-h] [-i] [-r]
${green}OPTIONS:${normal}
  -c  Apply configuration file.
  -h  Show this help message and exit.
  -i  Install Terminator & configuration files.
  -r  Remove Terminator & configuration files.
${bold}NOTES:${normal}
  1. Script will not overwrite Terminator config for BunsenLabs installations. Configuration changes should be made through Terminator Preferences.
  2. For Debian and Debian-based distributions (Antix, MX Linux, LMDE),Terminator will be configured as a login shell.
_HELP_
  exit "$errcode"
}

terminator_version() {
  dpkg -l terminator | awk '/ii/ {print $3}' | sed 's/-.*//'
}

install_terminator() {
  printf "Installing terminator...\n"
  sudo_login 2
  sudo apt-get -yq update
  sudo apt-get install -y terminator
  printf "Terminator %s installed.\n" "$(terminator_version)"
  if bunsenlabs; then
    printf "BunsenLabs uses its own profiles based on the version of the distribution.\n"
  else
    apply_config
    printf "Terminator %s configured.\n" "$(terminator_version)"
  fi
}

remove_terminator() {
  printf "Removing terminator %s and configuration files...\n" "$(terminator_version)"
  sudo_login 2
  sudo apt-get purge terminator
  [[ -L "$HOME/.config/terminator/config" ]] && unlink "$HOME/.config/terminator/config"
  find "$HOME/.config/" -maxdepth 2 -type d -name terminator -exec rm -rf {} \;
  printf "Terminator and its configuration files have been removed.\n"
}

apply_config() {
  local repository term_cfg_d
  term_cfg_d="$HOME/.config/terminator"
  repository=$(assign_cfg_repo)
  [[ -d "$term_cfg_d" ]] && mkdir -p "$term_cfg_d"
  printf "Applying Terminator configuration...\n"
  if is_debian; then
    [[ -f "$term_cfg_d/config" ]] && rm "$term_cfg_d/config"
    ln -s "$repository/terminator/config" "$term_cfg_d/config"
  else
    cp -v "$repository/terminator/config" "$$term_cfg_d/"
    sed -i '/login_shell/s/True/False/' "$term_cfg_d/config"
  fi
  printf "Terminator configuration file applied.\n"
}

main() {
  local noOpt opt optstr
  noOpt=1
  optstr=":chir"
  while getopts "$optstr" opt; do
    case "$opt" in
      c )
        if exists terminator; then
          if bunsenlabs; then
            printf "Terminator configuration for BunsenLabs was not overwritten.\n"
            printf "Configuration changes should be made through the Terminator Preferences menu.\n"
          else
            apply_config
          fi
        else
          printf "Terminator is not installed.\nConfiguration cannot be applied.\n" >&2
        fi
        ;;
      h )
        help 0
        ;;
      i )
        if exists terminator; then
          printf "Terminator %s is installed.\nInstallation canceled.\n" "$(terminator_version)" >&2
        else
          install_terminator
        fi
        ;;
      r )
        if exists terminator; then
          remove_terminator
        else
          printf "Terminator is not installed.\nOperation canceled.\n" >&2
        fi
        ;;
      ? )
      printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
      help 2
    esac
    noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
