#!/usr/bin/env bash
#############################################################################
# Script Name  : install-brave
# Description  : installs the Brave broswer
# Dependencies : apt-transport-https, curl, libu2f-udev
# Arguments    : see help function
# Author       : Copyright (C) 2019, Richard B. Romig
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 12 Dec 2019
# Updated      : 23 May 2026
# Comments     : For Debian, Ubuntu, Mint ... (Code from Brave's instructions)
#              : Brave is only supported on 64-bit AMD/Intel architectures (amd64/x86_64).
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#############################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib
source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

## Global Variables ##

readonly script="${0##*/}"
readonly version="7.0.26143"
verbose_mode="FALSE"
EC=0

## Functions ##

help() {
  local errcode="${1:-1}"
  local updated="23 May 2026"
  cat << _HELP_
${orange}$script${normal} $version, Updated: ($updated)
Installs/Removes the Brave browser

${green}Usage:${normal} $script [-h] [-vir]
${orange}Available options:${normal}
  -h  Show this help message and exit.
  -i  Install the Brave Browser.
  -r  Remove the Brave Browser & leave configuration files.
  -v  Enable verbose mode. Must precede other flags.
_HELP_
  exit "$errcode"
}

check_dependencies() {
  local E_MISSING_DEPENDENCY=108
  [[ $(uname -m) == "x86_64" ]] || die "System architecture is not 64-bit." "$E_MISSING_DEPENDENCY"
  local packages=( apt-transport-https curl libu2f-udev )
  check_packages "${packages[@]}"
}

show_message() {
	local message="$1"
	[[ "$verbose_mode" == "$TRUE" ]] && echo "$message"
}

brave_ver() {
  brave-browser --version
}

set_gpg_key() {
  local -r brave_key="$1"
  local -r key_url="https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
  if [[ -f "$brave_key" ]]; then
    printf "%s already exists.\n" "${brave_key##*/}"
    return
  fi
  show_message "Importing public key for verification of the APT repository"
  sudo curl -fsSLo "$brave_key" "$key_url"
	show_message "GPG key is set."
}

set_src_list() {
  local -r brave_key="$1"
  local -r list_url="https://brave-browser-apt-release.s3.brave.com/ stable main"
  local -r brave_list="/etc/apt/sources.list.d/brave-browser-release.list"
  if [[ -f "$brave_list" ]]; then
    printf "%s already exists.\n" "${brave_list##*/}"
    return
  fi
	show_message "Creating the source list file..."
  sudo tee "$brave_list" <<< "deb [signed-by=$brave_key arch=amd64] $list_url"
  show_message "${brave_list##*/} has been created."
}

install_brave() {
  local -r brave_key="/usr/share/keyrings/brave-browser-archive-keyring.gpg"
  printf "Installing the Brave Browser ...\n"
  set_gpg_key "$brave_key"
  set_src_list "$brave_key"
  show_message "Updating apt cache and isntalling the Brave browser"
  sudo apt-get update -qq
  sudo apt-get install brave-browser brave-keyring -yy
  if ! installed brave-browser; then
    printf "%s Brave browser installation failed.\n" "$RED_ERROR" >&2
    EC="$E_INSTALLATION"
    return
  fi
  printf "%s successfully installed.\n" "$(brave_ver)"
}

remove_brave() {
  printf "Uninstalling %s...\n" "$(brave_ver)"
  sudo apt-get remove brave-browser brave-keyring -yy
  show_message "Removing Brave sources..."
  find /etc/apt/ -maxdepth 2 -type f -iname "brave*" -exec sudo rm {} \;
  show_message "Removing the Brave keyring and system files..."
  find /usr/share -type d -iname "brave*" -exec rm -rf {} \;
  show_message "Removing local configuration and cache files..."
  find ~/ -maxdepth 2 -type d -name BraveSoftware -exec rm -rf {} \;
  printf "Brave browser has been uninstalled.\n"
}

main(){
  local noOpt opt optstr OPTARG OPTIND
  noOpt=1
  optstr=":hirv"
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        help 0
        ;;
      i )
        if installed brave-browser; then
          printf "%s is already installed." "$(brave_ver)"
        else
          sudo_login 2
          check_dependencies
          install_brave
        fi
        ;;
      r )
        if installed brave-browser; then
          sudo_login 2
          remove_brave
        else
          printf "Brave Browser is not installed.\n"
        fi
        ;;
			v )
				verbose_mode="$TRUE"
				show_message "Verbose mode enabled."
			  ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$E_INVALID_ARG"
    esac
    noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit "$EC"
}

## Execution ##

main "$@"
