#!/usr/bin/env bash
###############################################################################
# Script Name  : install-librewolf
# Description  : install/remove LibreWolf browser
# Dependencies : extrepo
# Arguments    : See help() function for available options.
# Author       : Copyright © 2025 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail | rick.romig@mymetronet.net
# Created      : 01 Mar 2025
# Updated      : 20 Jul 2026
# Comments     : instructions from https://librewolf.net/
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib.bash
source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

help() {
  local -r script="$1"
  local -r version="$2"
	local errcode="${3:-1}"
	local -r updated="20 Jul 2026"
	cat << _HELP_
${orange}$script${normal} $version, Upated: $updated
Installs/removes LibreWolf browser.

${green}Usage:${normal} $script [-h] [-vi] [-vr]
${orange}Available options:${normal}
  -h  Show this help message and exit.
  -i  Install LibreWolf.
  -r  Remove LibreWolf.
  -v  Enable verbose mode. If used, must prccede -i and -r.
_HELP_
  exit "$errcode"
}

lw_version() {
	awk '{print $NF}' < <(librewolf --version)
  return 0
}

show_message() {
	local message="$1"
	[[ "$VERBOSE" == "$TRUE" ]] && echo "$message"
  return 0
}

check_extrepo() {
	if installed extrepo; then
		printf "extrepo [OK]\n"
		sleep 1
		printf '\e[A\e[K'
		return 0
	else
		show_message "Updating cache and checking/installing extrepo..."
		sudo apt update && sudo apt install extrepo -y
	fi
	sudo extrepo enable librewolf && sudo extrepo update librewolf
	printf "extrepo installed and librewolf repo enabled.\n"
  return 0
}

install_librewolf() {
	sudo_login 2
	printf "Installing LibreWolf browser...\n"
	show_message "Checking for extrepo..."
	check_extrepo
	show_message "Installing LibreWolf..."
	sudo apt update && sudo apt install librewolf -y
  if ! installed librewolf; then
    printf "%s LibreWolf installation failed.\n" "$RED_ERROR" >&2
    return "$E_INSTALLATION"
  fi
	printf "LibreWolf browser version %s installed.\n" "$(lw_version)"
}

remove_librewolf() {
	printf "Removing LibreWolf browser %s...\n" "$(lw_version)"
	sudo_login 2
	show_message "Removing LibreWolf..."
	sudo extrepo disable librewolf
	sudo apt remove -y librewolf
	show_message "Removing LibreWolf local configuration files..."
	find ~/ -maxdepth 2 -type d -name "*librewolf*" -exec rm -rf {} \;
	show_message "Removing LibreWolf system directories, files, and links..."
	[[ -L /usr/bin/librewolf ]] && sudo unlink /usr/bin/librewolf
	sudo find /etc -maxdepth 3 -type f -name "*librewolf*" -exec sudo rm {} \;
	sudo find /usr -maxdepth 3 -type d -name "librewolf*" -exec sudo rm -rf {} \;
	# sudo find /var -maxdepth 4 -type d -name "librewolf*" -exec sudo rm -rf {} \;
	printf "LibreWolf has been removed.\n"
	return 0
}

main() {
	VERBOSE="$FALSE"
	local -r script="${0##*/}"
	local -r version="1.9.26201"
  local -i exit_code=0
	local opt OPTARG OPTIND
	local -i noOpt=1
	local -r optstr=":hirv"
	while getopts "$optstr" opt; do
		case "$opt" in
			h )
				help "$script" "$version" 0
				;;
			i )
				if installed librewolf; then
					printf "LibreWolf %s is already installed.\n" "$(lw_version)"
				else
					install_librewolf
					exit_code="$?"
				fi
				;;
			r )
				if installed librewolf; then
					remove_librewolf
					exit_code="$?"
				else
					printf "LibreWolf is not installed.\n"
				fi
				;;
			v )
				VERBOSE="$TRUE"
				show_message "Verbose mode enabled."
				;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$script" "$version" "$E_INVALID_ARG"
		esac
		noOpt=0
	done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
	shift "$(( OPTIND - 1 ))"
	over_line "$script $version"
	exit "$exit_code"
}

## Execution ##

main "$@"
