#!/usr/bin/env bash
##########################################################################
# Script Name  : install-keepassxc
# Description  : Installs KeePassXC from Flathub or distro repos
# Dependencies : none
# Arguments    : -d -f -h -m (see help function)
# Author       : Copyright (C) 2021 Richard B. Romig, 26 Jan 2021
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Variables ##

readonly _script=$(basename "$0")
readonly _version="0.2.2"
readonly _updated="12 Jan 2023"
readonly rederror="${lightred}ERROR:${normal} "

## Functions ##

kpxc_ver() {
  dpkg -l | awk '$2 == "keepassxc" {print $3}' | sed 's/[+-].*//'
}

keepass_ver() {
  flatpack list | awk '/KeePassXC/ {print $3}'
}

flathub_keepassxc() {
  exists flatpak || sudo apt install flatpak -yy
  sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  flatpak install --user flathub org.keepassxc.KeePassXC
  printf "KeePassXC %s installed from flathub.\n" "$(keepass_ver)"
}

distro_keepassxc() {
  # Installs from distribution repo
  user_in_sudo
  install_debian
  printf "Keepassxc %s installed from distro repositories.\n" "$(kpxc_ver)"
}

move_vault() {
  local vault_dir="$HOME/Documents"
  printf "Moving password databases to ~/Documents...\n"
  find "$HOME/Documents/mosfanet/" -maxdepth 1 -type f -iname "*.kdbx" -print -exec mv {} "$vault_dir/" \;
  find "$HOME/Documents/mosfanet/" -maxdepth 1 -type f -iname "Rick_pwds*" -print -exec mv {} "$vault_dir/" \;
}

help() {
  errcode="${1:-2}"
  cat << END_HELP
Usage: $_script [OPTIONS]
OPTIONS:
  -d  Install KeePassXC from distribution repositories.
  -f  Install KeePassXC from flathub repositories.
  -h  Display help.
  -m  Move password vaults from ~/Documents/mosfanet to ~/Documents.
END_HELP
  exit "$errcode"
}

## Execution ##

echo "$_script v$_version ($_updated)"
echo "Installs KeePassXC password manager"
if [[ "$#" -eq 0 ]]; then
  printf "%sNo argument passed." "$rederror" >&2
  help 1
else
  optstr=":dfhm"
  while getopts "$optstr" opt; do
    case "$opt" in
      d )
        exists keepassxc && leave "KeePassXC $(kpxc_ver) already installed."
        distro_keepassxc
        ;;
      f )
        flatpak list | grep -qw KeePassXC && leave "KeePassXC $(keepass_ver) flatpak installed."
        flathub_keepassxc
        ;;
      h )
        help 0
        ;;
      m )
        move_vault
        ;;
      ? )
        printf "%sInvalid option -%s\n" "$rederror" "$OPTARG" >&2
        help 2
    esac
  done
fi