#!/usr/bin/env bash
###############################################################################
# Script Name  : install-audioapps
# Description  : installs audio applications and utilities
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2019, Richard B. Romig, MosfaNet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 01 Mar 2019
# Updated      : 21 Dee 2024
# Comments     :
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Functions ##

install_from_repo() {
  printf "\nInstalling audio applications and utilities from repositories.\n"
  sudo apt-get install -yy asunder lame easytag audacity
}

install_mp3gain() {
  if in_repos mp3gain; then
    printf "Installing mp3gain...\n"
    sudo apt-get install -yy mp3gain
  else
    printf "mp3gain is not available in distribution repository.\n"
  fi
}

list_installed_apps() {
  local app apps
  apps=( asunder audacity easytag lame mp3gain )
  printf "Audio applications installed:\n"
  for app in "${apps[@]}"; do
    exists "$app" && printf "\t%s\n" "${app^}"
  done
}

main() {
  local script version
  script=$(basename "$0")
  version="v1.3.24356"

  sudo_login 2
  sudo apt update -qq
  printf "Installs audio applications on Debian/Ubuntu-based systems.\n"
  install_from_repo
  install_mp3gain
  list_installed_apps
  over_line "$script $version"
}

## Execution ##

main "$@"
