#!/usr/bin/env bash
###############################################################################
# Script Name  : install-multisystem
# Description  : Imstalls MultiSystem from PPA
# Dependencies : apt-add-repository, apt, wget
# Arguments    : none
# Author       : Copyright (C) 2018, Richard Romig, 29 November 2018
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comment      : Multiple ISO images on a USB drive
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="1.1.0"
readonly _updated="04 Feb 2023"

## Execution ##

check_package wget

echo "$_script v$_version ($_updated)"
echo "Installs Multisystem USB ISO installer."

exists multisystem && leave "Multisystem USB ISO installer is already installed."
user_in_sudo
echo "Installing MultiSystem USB ISO installer..."
echo "Adding MultiSystem repository..."
sudo apt-add-repository -y "deb http://liveusb.info/multisystem/depot all main"
wget -q -O - http://liveusb.info/multisystem/depot/multisystem.asc | sudo apt-key add - 2>/dev/null #apt-key deprecated
sudo apt update -qq
echo "Installing Multisystem USB ..."
if sudo apt install multisystem -yyq; then
  leave "MultiSystem installed."
else
  die "Multisystem USB Installation failed."
fi
