#!/usr/bin/env bash
##########################################################################
# Script Name  : install-geany
# Description  : Installs the Geany editor/IDE with themes.
# Dependencies : git
# Arguments    : -h -i -r -t -v (See help function)
# Author       : Copyright (C) 2022, Richard B. Romig,Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 25 Dec 2022
# Updated      : 23 Oct 2025
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x ~/bin/functionlib ]]; then
  source ~/bin/functionlib
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="3.0.25296"
verbose_mode="$FALSE"

## Functions ##

help() {
	local errcode="${1:-2}"
	local updated="23 Oct 2025"
  cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs/Removes Geany text editor and themes

${green}Usage:${normal} $script [-h] [-vi] [-vit] [-vr] [-vt]
${orange}Available options:${normal}
  -h  Show this help message and exit.
  -i  Install Geany editor.
  -r  Remove Geany editor.
  -t  Install Geany themes.
  -v  Enable verbose mode. If used, must precede other flags.
_HELP_
  exit "$errcode"
}

geany_version() {
  geany --version | cut -d' ' -f2
}

clone_themes() {
  local -r themes_url="https://github.com/geany/geany-themes.git"
  local -r colorschemes_dir=~/.config/geany/colorschemes
  local -r cloned_dir=~/Downloads/geany-themes
  [[ -d "$colorschemes_dir" ]] || mkdir -p "$colorschemes_dir"
  show_message "Cloning Geany themes..."
  git clone "$themes_url" "$cloned_dir"
  show_message "Copying Geany colorschemes..."
  cp -av "$cloned_dir"/colorschemes/. "$colorschemes_dir/" | awk -F"/" '{print "=> " $NF}' | sed "s/'//"
  printf "Geany themes installed.\n"
}

install_geany() {
  show_message "Installing Geany from repositories..."
  sudo apt-get install -y geany libvte9
  exists geany || die "Geany installation failed." 1
  printf "Geany %s installed.\n" "$(geany_version)"
}

geany_config() {
  local repository=~/Downloads/configs/geany
  [[ -d ~/gitea/configs/geany ]] && repository=~/gitea/configs/geany
  if ! [[ -d "$repository" ]]; then
    printf "%s Configs repository not found!\n" "$RED_WARNING" >&2
    return
  fi
  [[ -d ~/.config/geany ]] || mkdir -p ~/.config/geany
  show_message "Applying configuration files."
  cp -v "$repository"/geany.conf ~/.config/geany/
  cp -v "$repository"/keybindings.conf ~/.config/geany/
  printf "Geany configuration files applied.\n"
}

remove_geany() {
  show_message "Removing Geany $(geany_version)..."
  sudo apt-get remove -y geany
  show_message "Removing Geany configuration files ..."
  find ~/.config -type d -name geany -exec rm -rf {} \;
  printf "Geany and configuration files removed.\n"
}

show_message() {
	local message="$1"
	[[ "$verbose_mode" == "$TRUE" ]] && echo "$message"
}

main() {
  local noOpt opt optstr
  noOpt=1
  optstr=":hirtv"
  check_package git
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        help 0
        ;;
      i )
        if exists geany; then
          printf "Geany %s is already installed.\n" "$(geany_version)"
        else
          sudo_login 2
          install_geany
          clone_themes
          geany_config
        fi
        ;;
      r )
        if exists geany; then
          sudo_login 2
          remove_geany
        else
          printf "Geany is not installed.\n"
        fi
        ;;
      t )
        if exists geany; then
          clone_themes
        else
          printf "Geany is not installed.\n"
        fi
        ;;
      v )
        verbose_mode="$TRUE"
			  show_message "Verbose mode enabled."
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help 2
    esac
    noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
