#!/usr/bin/env bash
##########################################################################
# Script Name  : install-handbrake
# Description  : Installs handbrake
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2019, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 14 Feb 2019
# Updated      : 16 Nov 2025
# Comment      : Handbrake rips DVD movies
#              : Available as a flatpak via Flathub and Mint Software Manager
#              : https://dl.flathub.org/repo/appstream/fr.handbrake.ghb.flatpakref
#              : flatpak install fr.handbrake.ghb
#              : flakpak may not be able to access certain codecs for DRM.
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="3.13.25320"

## Functions ##

help() {
	local errcode="${1:-2}"
	local updated="16 Nov 2025"
  cat << _HELP_
${orange}$script${normal} $version ($updated)
Install/Remove Handbrake video transcorder

${green}Usage:${normal} $script [OPTION]
${orange}Available options:${normal}
  -h  Show this help message and exit
  -i  Install Handbrake
  -r  Remove Handbrake
_HELP_
  exit "$errcode"
}

install_handbrake() {
  sudo_login 2
  sudo apt install handbrake-gtk handbrake-cli -yy
  exists ghb || die "Handbrake installation failed!" 1
  echo "Handbrake installed."
}

remove_handbrake() {
  sudo_login 2
  sudo apt autoremove handbrake-gtk handbrake-cli -yy
  echo "Handbrake removed from system."
}

main() {
  local noOpt opt optstr OPTARG OPTIND
  noOpt=1
  optstr=":hir"
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        help 0
        ;;
      i )
        exists ghb && leave "Handbrake-GTK already installed."
        install_handbrake
        ;;
      r )
        exists ghb || leave "Handbrake is not installed."
        remove_handbrake
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help 2
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  leave "$script v$version"
}

## Execution ##

main "$@"
