#!/usr/bin/env bash
##########################################################################
# Script Name  : install-polybar
# Description  : Installs polybar on Debian i3wm systems.
# Dependencies : git (for assign_cfg_repo() in functionlib)
# Arguments    : None
# Author       : Copyright © 2023 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 16 Nov 2023
# Updated      : 04 Jun 2025
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

## Functions ##

copy_polybar_config() {
  local repository polybar_d
	repository=$(assign_cfg_repo)
	polybar_d="$1"
	[[ -d "$polybar_d" ]] || mkdir -p "$polybar_d"
	printf "Copying the Polybar configuration file ...\n"
	cp -v "$repository/polybar/config.ini" "$polybar_d/"
	printf "Polybar configuration file copied from the Gitea server.\n"
	printf "Installing the Polybar launcher...\n"
	cp -v "$repository/polybar/polybar-i3" "$polybar_d/"
	[[ -x "$polybar_d/polybar-i3" ]] || chmod +x "$polybar_d/polybar-i3"
	printf "polybar-i3 installed.\n"
}

configure_polybar() {
	local cfg_file b_name e_name w_name polybar_d
	polybar_d="$1"
	cfg_file="config.ini"
	# Get device names from system.
	e_name=$(/usr/bin/nmcli dev | awk '/ethernet/ {print $1}')
	w_name=$(/usr/bin/nmcli dev | awk '/wifi/ {print $1}')
	b_name=$(find /sys/class/power_supply/ -name "BAT*" | awk -F/ '/BAT/ {print $NF}')
	# Apply device names or exlude modules as required.
	if [[ "$w_name" ]]; then
		sed -i "s/wlan0/$w_name/" "$polybar_d/$cfg_file"
	else
		sed -i '/^modules-right/s/ wlan//' "$polybar_d/$cfg_file"
	fi
	if [[ "$e_name" ]]; then
		sed -i "s/eth0/$e_name/" "$polybar_d/$cfg_file"
	else
		sed -i '/^modules-right/s/ eth//' "$polybar_d/$cfg_file"
	fi
	if [[ "$b_name" ]]; then
		sed -i "s/BAT0/$b_name/" "$polybar_d/$cfg_file"
	else
		sed -i '/^modules-right/s/ battery//' "$polybar_d/$cfg_file"
	fi
}

install_polybar() {
	local polybar_d="$HOME/.config/polybar"
	sudo_login 2
	sudo apt-get install -y polybar
	copy_polybar_config "$polybar_d"
	configure_polybar "$polybar_d"
}

main() {
  check_package git
  local script="${0##*/}"
  local version="2.6.25155"
	printf "Installs Polybar on Debian with i3wm.\n"
	exists polybar && leave "Polybar is already installed."
	install_polybar
	over_line "$script $version"
}

## Execution ##

main "$@"
