#!/usr/bin/env bash
################################################################################
# Script Name  : install-conky
# Description  : Install and configure Conky
# Dependencies : curl network-manager wget
# Arguments    : None
# Author       : Copyright (C) 2018, Richard Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 26 Dec 2018
# Updated      : 01 Oct 2024
# Comment      : copies .conkyrc to conkyrc-hostname for archiving purposes.
# TODO (rick)  :
# License      : GNU General Public License, version 2
###############################################################################

# Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

script=$(basename "$0"); readonly script
readonly version="6.4.24275"
readonly repository="configs/raw/branch/main/"
readonly localbin_d="$HOME/.local/bin"
readonly autostart_d="$HOME/.config/autostart"
readonly conf_d="$HOME/.config/conky"
verbose_mode="$FALSE"

## Functions ##

help() {
  local errcode updated
	errcode="${1:-2}"
  updated="01 Oct 2024"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs and configures Conky

${green}Usage:${normal} $script [OPTION]

${green}Usage:${normal} $script [OPTION]
  -c  Install conky.conf
  -d  Install conky.desktop & start-conky.sh
  -e  Edit conky.comf
  -h  Display help
  -i  Install conky
  -r  Remove conky & configuration files
  -v  Enable verbose mode
${bold}NOTES${normal}
1. Conky is pre-installed on BunsenLabs, antiX, and MX Linux.
   Use the distibution's Conky Manager to configure conky.
2. This installation of Conky is not necessry on i3wm (info in status bar).
_HELP_
  exit "$errcode"
}

bl_antix_mx_i3() {
  if bunsenlabs || antix_mx; then
    printf "Conky is pre-installed on BunsenLabs, antiX, and MX Linux.\n"
    printf "Use the distibution's Conky Manager to configure conky.\n"
    exit
  elif [[ $(/usr/bin/wmctrl -m | awk '/Name:/ {print $2}') == "i3" ]]; then
    printf "Window manager is i3wm. This installation of Conky is not necessry.\n"
    exit
  fi
}

show_message() {
  local message="$1"
  [[ "$verbose_mode" == "$TRUE" ]] && echo "$message"
}

check_dependencies() {
  # wget is called in conky.conf to get public IP address
  local packages=( curl network-manager wget )
  check_packages "${packages[@]}"
}

conky_version() {
  # conky --version | head -n1 | cut -d' ' -f2
  dpkg -l conky | awk '/ii/ {print $3}' | sed 's/-.*//'
}

install_conky() {
  printf "\nInstalling conky...\n"
  show_message "Updating apt cache"
  sudo apt update -qq
  show_message "Installing conky and dependencies"
  sudo apt install -yyq conky
  printf "Conky version %s installed.\n" "$(conky_version)"
}

conky_desktop() {
  [[ -d "$autostart_d" ]] || mkdir -p "$autostart_d"
  if [[ -f "$autostart_d/Conky.desktop" || -f "$autostart_d/conky.desktop" ]]; then
    echo "conky.desktop aleady exists."
    [[ -f "$autostart_d/Conky.desktop" ]] && mv "$autostart_d/Conky.desktop" "$autostart_d/conky.desktop"
  else
    show_message "Downloading conky.desktop from the Gitea server to .config/autostart"
    curl -so "$autostart_d/conky.desktop" "$Gitea_URL/$repository/autostart/conky.desktop"
    echo "conky.desktop configured."
  fi
}

startscript() {
  [[ -d "$localbin_d" ]] || mkdir -p "$localbin_d"
  if [[ ! -f "$localbin_d/start-conky.sh" ]]; then
    show_message "Downloading start-conky.sh from the Gitea server to .local/bin"
    curl -so "$localbin_d/start-conky.sh" "$Gitea_URL/$repository/local/bin/start-conky.sh"
    printf "start-conky.sh installed.\n"
  fi
}

remove_conky() {
  printf "Removing Conky and its configuration files...\n"
  show_message "Removing conky..."
  sudo apt-get remove --purge -yy conky
  show_message "Removing cnnky configuration files..."
  [[ -f "$localbin_d/start-conky.sh" ]] && { show_message "Removing start-conky.sh"; rm "$localbin_d/start-conky.sh"; }
  [[ -f "$autostart_d/conky.desktop" ]] && { show_message "Removing conky.desktop"; rm "$autostart_d/conky.desktop;"; }
  [[ -d "$conf_d" ]] && { show_message "Removing conky.conf"; rm -rf "$conf_d"; }
  [[ -d "$conf_d/backup/conky" ]] && { show_message "Removing conky.conf backup file."; rm "$conf_d/backup/conky"; }
  [[ -f "$HOME/.conkyrc" ]] && { show_message "Removing .conkyrc."; rm "$HOME/.conkyrc"; }
  [[ -d "$conf_d/backup/.conkyrc" ]] && { show_message "Removing conky.conf backup file."; rm "$conf_d/backup/.conkyrc"; }
}

eth_name() {
  local e_name
  e_name=$(/usr/bin/nmcli dev | awk '/ethernet/ {print $1}')
  [[ "$e_name" ]] || e_name="eth0"
  echo "$e_name"
}

wlan_name() {
  local w_name
  w_name=$(/usr/bin/nmcli dev | awk '/wifi/ {print $1}')
  [[ "$w_name" ]] || w_name="wlan0"
  echo "$w_name"
}

bat_name() {
  local b_name
  b_name=$(find /sys/class/power_supply/ -name "BAT*" | awk -F/ '/BAT/ {print $5}')
  [[ "$b_name" ]] || b_name="BAT0"
  echo "$b_name"
}

cpu_cores() {
  local ncpu
  ncpu=$(/usr/bin/nproc --all)
  echo "$ncpu"
}

configure_conky() {
  local b_name e_name ncpu w_name template_d
  template_d="$HOME/bin/Templates"
  b_name="$(bat_name)"
  e_name="$(eth_name)"
  w_name="$(wlan_name)"
  ncpu="$(wlan_name)"
  [[ -d "$conf_d" ]] || mkdir -p "$conf_d"

  # Display network and battery device names and number of cores
  printf "%-24s%s\n" "Battery device name:" "$b_name"
  printf "%-24s%s\n" "Ethernet device name:" "$e_name"
  printf "%-24s%s\n" "Wireless device name:" "$w_name"
  printf "%-24s%s\n" "CPU cores/threads:" "$ncpu"

  show_message "Configuring conky.conf with device names"
  sed -e '1d' \
    -e "s/<BAT>/$b_name/g" \
    -e "s/<EN>/$e_name/g" \
    -e "s/<WL>/$e_name/g" "$template_d/conkyrc" > "$conf_d/conky.conf"

    show_message "Configuring CPU cores/threads"
    case "$ncpu" in
      1 )
        sed -i '57,63d' "$conf_d/.conky.conf"
        show_message "$ncpu core configured."
      ;;
      2 )
        sed -i '58,63d' "$conf_d/.conky.conf"
        show_message "$ncpu cores configured."
      ;;
      3 )
        sed -i '59,63d' "$conf_d/.conky.conf"
        show_message "$ncpu cores configured."
      ;;
      4 )
        sed -i '60,63d' "$conf_d/.conky.conf"
        show_message "$ncpu cores configured."
      ;;
      5 )
        sed -i '61,63d' "$conf_d/.conky.conf"
        show_message "$ncpu cores configured."
      ;;
      6 )
        sed -i '62,63d' "$conf_d/.conky.conf"
        show_message "$ncpu cores configured."
      ;;
      7 )
        sed -i '63d' "$conf_d/.conky.conf"
        show_message "$ncpu cores configured."
      ;;
      8 )
        show_message "$ncpu cores configured."
      ;;
    * )
      printf "%s More cores than template allows for. Modify template to accomodate.\n" "$RED_WARNING"
  esac
  if [[ -f "$HOME/.conkyrc" ]]; then
    show_message "Removing .conkyrc"
    rm "$HOME/.conkyrc"
  fi
  # shellcheck disable=SC2088 # tilde does not expand in quotes
  printf "~/.config/conky/conky.conf configured.\n"
}

main() {
  local noOpt opt optstr
  bl_antix_mx_i3

  noOpt=1
  optstr=":cdehirv"
  while getopts "$optstr" opt; do
	  case "$opt" in
      c )
        exists conky || leave "Conky is not installed."
        configure_conky
        edit_view_quit "$conf_d/conky.conf"
      ;;
      d )
        exists conky || leave "Conky is not installed."
        conky_desktop
        startscript
      ;;
      e )
        "$EDITOR" "$conf_d/conky.conf"
      ;;
		  h )
			  help 0
		  ;;
		  i )
        exists conky && leave "Conky $(conky_version) is already installed."
        sudo_login 2
        check_dependencies
        install_conky
        configure_conky
        conky_desktop
        startscript
        edit_view_quit "$conf_d/conky.conf"
		  ;;
		  r )
        exists conky || leave "Conky is not installed."
	      sudo_login 2
			  remove_conky  # remove conky, conky.conf, conky.desktop, start-conky.sh
		  ;;
		  v )
			  verbose_mode="$TRUE"
			  show_messagessage "Verbose mode enabled."
		  ;;
		  ? )
			  printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
			  help 2
	  esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  box "$script v$version"
  exit
}

## Execution ##

main "$@"