#!/usr/bin/env bash
###############################################################################
# Script Name  : install-mkusb
# Description  : Installs mkusb - app to create USB drive with persistence
# Dependencies : apt
# Arguments    : none
# Author       : Richard B. Romig, 24 May 2019
# Email        : rick.romig@gmail.com
# Comments     : Ubuntu-based Linux distributions only
# https://www.howtogeek.com/howto/14912/create-a-persistent-bootable-ubuntu-usb-flash-drive/
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091,SC2034

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Variables ##

readonly _script=$(basename "$0")
readonly _version="0.2.3"
readonly _updated="05 May 2021"

## Functions ##

install_mkusb() {
  exists mkusb && leave "mkusb is already installed."
  echo "Installing the mkusb tool."
  if support_ppa; then
    sudo add-apt-repository ppa:mkusb/ppa
    sudo apt update -qq
    sudo apt install --install-recommends mkusb mkusb-nox usb-pack-efi -yy
    leave "MkUSB installed"
  else
    die "Distribution does not support PPA. MkUSB not installed."
  fi
}

remove_mkusb() {
  exists mkusb || leave "mkusb is not installed."
  echo "Removing the mkusb tool."
  if support_ppa; then
    sudo add-apt-repository --remove ppa:mkusb/ppa
    sudo apt update -qq
    sudo apt autoremove mkusb mkusb-nox usb-pack-efi -yy
    leave "The mksub tool has been removed."
  else
    leave "The mksub tool was not removed"
  fi
}

## Execution ##

clear
echo "$_script v$_version ($_updated)"
echo "Installs the mkusb tool to create boot drives"

PS3="Selection: "
select opt in "Install MkUSB" "Remove MkUSB" "Quit"
do
  case $REPLY in
    1 ) user_in_sudo; install_mkusb; break ;;
    2 ) user_in_sudo; remove_mkusb; break ;;
    3 ) leave "No action taken. Exiting the script." ;;
    * ) echo "Invalid selection. Try again." ;;
  esac
done
