#!/usr/bin/env bash
#############################################################################
# Script Name  : install-boxes
# Description  : Installs GNOME boxes.
# Dependencies : none
# Arguments    : none
# Author       : Copyright (C) 2020, Richard B. Romig, 29 Feb 2020
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     : Based on instructions from Joe Collins @ Ezeelinux.com
# TODO (Rick)  : Test this. Test for Intel/AMD CPU.
# License      : GNU General Public License, version 2.0
#############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.1.8"
readonly _updated="04 Apr 2023"

## Functions ##

check_cpu() {
  # Check if virtualization is enabled in BIOS (is flag set?)
  vcpu=$(grep -Ec 'vmx|svm' /proc/cpuinfo)  # egrep -c '(vmx|svm)'
  printf "Virtualization is "
  if [[ "$vcpu" -gt 0 ]]; then
    printf "enabled in the BIOS. (%s threads)\n" "$vcpu"
  else
    printf "not enabled in the BIOS.\n"
    printf "Enable virtualization before installing Gnome Boxes.\n"
    exit
  fi
}

enable_libvirtd() {
  sudo systemctl start libvirt
  sudo systemctl restart libvirtd
}

## Execution ##

user_in_sudo

clear
printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
printf "Installs GNOME Boxes.\n"

check_cpu

## Install Gnome Boxes ##

printf "\nInstalling GNOME Boxes ...\n"
sudo apt update -qq
sudo apt install -yy gnome-boxes qemu-kvm libvirt-bin
printf "Adding %s to the kvm group.\n" "$USER"
sudo usermod -a -G kvm "$USER"
if [[ -f "/etc/libvirt/qemu.conf" ]]; then
  printf "Allow users in the kvm group to start VMs.\n"
  sudo sed -i.bak 's/\#group\ =\ "root"/group\ =\ "kvm"/' /etc/libvirt/qemu.conf
  enable_libvirtd
  leave "Gnome boxes installed and configured."
else
  die "/etc/libvirt/qemu.conf not found!" 2
fi

## Not sure if these actions need to be done ##
# Add lines to /etc/modprobe.d/qemu-system-x86.conf
# vcpu=$(egrep -oq '(vmx|svm)' /proc/cpuinfo)
# case $vcpu in
#   vmx )
#     sudo sh -c 'echo "options kvm_intel nested=1" >> /etc/modprobe.d/qemu-system-x86.conf' ;;
#   svm )
#     sudo sh -c 'echo "options kvm_amd nested=1" >> /etc/modprobe.d/qemu-system-x86.conf' ;;
#   * )
#     echo "CPU does not support virtualization." ;;
# esac
# sudo sh -c 'echo "group=kvm" >> /etc/modprobe.d/qemu-system-x86.conf'

# Enable and start libvirt daemon
# sudo systemctl enable libvirtd.service
# sudo systemctl start libvirtd.service

exit
