#!/usr/bin/env bash
###############################################################################
# Script Name  : install-kitty
# Description  : Installs kitty terminal emulator with basic configuration.
# Dependencies : git
# Arguments    : -c -h -i -p -r (see help function for more information)
# Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 26 Sep 2022
# Updated      : 30 Jun 2026
# Comments     : Configures as login terminal for Debian-based distros.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
###############################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib
source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

## Functions ##

help() {
  local -r script="$1"
  local -r version="$2"
	local errcode="${3:-1}"
	local -r updated="30 Jun 2026"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs/Removes/Configures Kitty terminal emulator

${green}Usage:${normal} $script [-hir]
${orange}Available options:${normal}
  -h  Show this help message and exit
  -i  Install Kitty from distro repositories
  -r  Remove Kitty from system
_HELP_
  exit "$errcode"
}

kitty_version() {
  cut -d' ' -f2 < <(kitty --version)
  return 0
}

install_kitty() {
  printf "Installing the kitty terminal emulator.\n"
  sudo apt-get install -y kitty imagemagick
  if ! installed kitty; then
    printf "%s Kitty installation failed.\n" "$RED_ERROR"
    return "$E_INSTALLATION"
  fi
  printf "Kitty %s installed.\n" "$(kitty_version)"
  kitty_config
  return "$?"
}

remove_kitty() {
  printf "Purging the Kitty %s terminal emulator...\n" "$(kitty_version)"
  sudo apt-get purge kitty -yy
  [[ -L ~/.config/kitty/kitty.conf ]] && unlink ~/.config/kitty/kitty.conf
  [[ -L ~/.config/kitty/bindings.list ]] && unlink ~/.config/kitty/bindings.list
  find ~/ -maxdepth 3 -type d -path ~/Downloads -prune -o -path ~/gitea -prune -o -type d -name "kitty*" -exec rm -rf {} \;
  printf "The Kitty terminal emulator and configuration files have been removed.\n"
  return 0
}

kitty_config() {
  local repository=~/Downloads/configs/kitty
  [[ -d ~/gitea/configs/geany ]] && repository=~/gitea/configs/kitty
  if [[ ! -d "$repository" ]]; then
    printf "%s Configs repository not found!\n" "$RED_WARNING" >&2
    return "$E_FILENOTFOUND"
  fi
  [[ -d ~/.config/kitty ]] || mkdir -p ~/.config/kitty
  printf "Applying configuration files ...\n"
  cp -v "$repository"/kitty.conf "$repository"/bindings.list ~/.config/kitty/
  [[ "$DESKTOP_SESSION" != "i3" ]] && sed -i.bak '/hide_window_decorations/s/yes/no/' ~/.config/kitty/kitty.conf
  printf "kitty configuration files applied.\n"
  return 0
}

main() {
  check_package git
  local noOpt opt optstr OPTARG OPTIND
  local -r script="${0##*/}"
  local -r version="2.7.26181"
  local exit_code=0
  noOpt=1
  optstr=":hir"
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        help "$script" "$version" 0
        ;;
      i )
        if installed kitty; then
          printf "Kitty %s already installed.\n" "$(kitty_version)"
        else
          sudo_login 2
          install_kitty
          exit_code="$?"
        fi
        ;;
      r )
        if installed kitty; then
          sudo_login 2
          remove_kitty
          exit_code="$?"
        else
          printf "Kitty is not installed.\n"
        fi
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$script" "$version" "$E_INVALID_ARG"
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit "$exit_code"
}

## Execution ##

main "$@"
