#!/usr/bin/env bash
##########################################################################
# Script Name  : install-zram
# Description  : installs and configures Zram-tools.
# Dependencies : none
# Arguments    : none
# Author       : Copyright © 2025 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 18 Jan 2025
# Updaged      : 27 Jan 2025
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

## Functions ##

install_zram() {
  local sed_file="$HOME/bin/files/zramswap.sed"
	sudo apt install -y zram-tools
	# sudo sed -i.bak '/ALGO/s/^#//;/PERCENT/s/^#//;s/50$/25/' /etc/default/zramswap
  sudo sed -i.bak -f "$sed_file" /etc/default/zramswap
  sudo systemctl restart zramswap.service
	printf "Zram-tools installed and configured.\n"
}

swap_exists() {
  local myswap
  myswap=$(awk '/file/ || /partition/ {print $1}' /proc/swaps)
  [[ "$myswap" ]] && return "$TRUE" || return "$FALSE"
}

main() {
  local script version
  script=$(basename "$0")
  version="2.1.25027"
  sudo_login 2
  if swap_exists; then
    printf "A swap device exists and is enabled.\n"
  else
    printf  "No swap device currently exists. Installing Zram-tools ...\n"
    install_zram
  fi
  printf "Active swap devices:\n"
  sudo swapon --show
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
