#!/usr/bin/env bash
###############################################################################
# Script Name  : install-mozilla-firefox
# Description  : install Firefox .deb package from Mozilla repos
# Dependencies : wget
# Arguments    : none
# Author       : Copyright © 2024 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 24 Jan 2024
# Updated      : 02 Oct 2026
# Version      : 7.4.26275
# Comments     : Remove Distro, Flatpak, or Snap version before installing.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

# shellcheck source=/home/rick/bin/functionlib.bash
source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

VERBOSE="FALSE"

help() {
	local -r script="$1"
	local -r version="$2"
	local -ri errcode="${3:-1}"
	local -r updated=" 02 Oct 2026"
	cat <<- _HELP_
	${orange}$script${normal} $version, Upated: $updated
	Installs/Removes Mozilla repository version of Firefox.

	${green}Usage:${normal} $script [-h] [-vi] [-vr]
	${orange}Available options:${normal}
	-h	Show this help message and exit.
	-i	Install Mozilla Firefox Debian package.
	-r	Remove Mozilla Firefox Debian package.
	-v	Enable verbose mode. If used, must precede other flags.
_HELP_
	exit "$errcode"
}

show_message() {
	local message="$1"
	[[ "$VERBOSE" == "$TRUE" ]] && echo "$message"
	return 0
}

firefox_version() {
	firefox --version
	return 0
}

mozilla_deb() {
	grep -q 'ii.*build' < <(dpkg -l firefox) && return "$TRUE" || return "$FALSE"
}

other_firefox() {
	if grep -q '^ii' < <(dpkg -l firefox-esr); then
		printf "Firefox ESR\n"
		return "$TRUE"
	elif grep -q 'ii.*linuxmint' < <(dpkg -l firefox); then
		printf "Linux Mint Firefox\n"
		return "$TRUE"
	elif installed flatpak || installed snapd; then
		grep -q firefox < <(flatpak list 2>/dev/null) && { printf "Flatpak Firefox\n"; return "$TRUE"; }
		snap list firefox 2>/dev/null && { printf "Snap Firefox\n"; return "$TRUE"; }
	else
		return "$FALSE"
	fi
}

create_preference_file() {
	# Preference file to prioritize packages from Mozilla repository
	local -r mozilla_pref="/etc/apt/preferences.d/mozilla.pref"
	show_message "Creating preference file..."
	sudo tee $mozilla_pref <<< \
"Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000"
	return "$?"
}

set_gpg_key() {
	local -r key_file="$1"
	local -r key_url="https://packages.mozilla.org/apt/repo-signing-key.gpg"
	show_message "Installing keyrings directory..."
	[[ -d /etc/apt/keyrings ]] || sudo install -d -m 0755 /etc/apt/keyrings
	show_message "Importing Mozilla APT repository keys..."
	# Shellcheck SC2024 note: sudo doesn't affect redirects.
	wget -q "$key_url" -O- | sudo tee "$key_file"
	return "$?"
}

set_sources() {
	local -r key_file="$1"
	local -r sources_list=/etc/apt/sources.list.d/mozilla.list
	local -r sources_file=/etc/apt/sources.list.d/mozilla.sources
	local -r sources_uri="https://packages.mozilla.org/apt"
	if [[ -f "$sources_list" ]]; then
		show_message "Renaming old source list file..."
		sudo mv "$sources_list" "$sources_list.bak"
	fi
	show_message "Creating Mozilla APT sources..."
	sudo tee $sources_file <<< \
"Types: deb
URIs: $sources_uri
Suites: mozilla
Components: main
Signed-By: $key_file"
	return 0
}

install_mozilla_firefox() {
	if mozilla_deb; then
		printf "%s DEB package is already installed.\n" "$(firefox_version)" >&2
		return "$E_FILE_EXISTS"
	fi
	if other_firefox; then
		printf "Remove other versions before installing the Mozilla package.\n" >&2
		return "$E_FILE_EXISTS"
	fi
	local -r key_file="/etc/apt/keyrings/packages.mozilla.org.asc"
	printf "Installing the Mozilla Firefox DEB package...\n"
	set_gpg_key "$key_file"
	set_sources "$key_file"
	create_preference_file
	show_message "Updating apt cache..."
	sudo apt-get update
	show_message "Installing Firefox..."
	sudo apt-get install -y firefox
	if ! installed firefox; then
		printf "%s Firefox installation failed.\n" "$RED_ERROR" >&2
    return "$E_INSTALLATION"
	fi
	printf "%s installed.\n" "$(firefox_version)"
	return 0
}

remove_mozilla_firefox() {
	if ! mozilla_deb; then
		printf "Mozilla Firefox DEB package is not installed.\n"
		return "$E_NOT_INSTALLED"
	fi
	printf "Removing %s..." "$(firefox_version)"
	sudo apt-get remove -y firefox
	show_message "Removing source.list, preference, & keyring files..."
	find /etc/apt -maxdepth 2 -type f -name "*mozilla*" -exec sudo rm -f {} \;
	show_message "Removing user configuration files..."
	find ~/ -maxdepth 2 -type d -name "*mozilla*" -exec rm -rf {} \;
	printf "The Mozilla Firefox deb package has been removed.\n"
	return 0
}

main() {
	local -r script="${0##*/}"
	local -r version="7.4.26275"
	local -i exit_code=0
	local opt OPTARG OPTIND
	local -i noOpt=1
	local -r optstr=":hirv"
	while getopts "$optstr" opt; do
		case "$opt" in
			h )
				help "$script" "$version" 0 ;;
			i )
				install_mozilla_firefox ;;
			r )
				remove_mozilla_firefox ;;
			v )
				VERBOSE="$TRUE"
				show_message "Verbose mode enabled." ;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help "$script" "$version" "$E_INVALID_ARG"
		esac
		exit_code="$?"
		noOpt=0
	done
	if (( noOpt == 1 )); then
		printf "%s No argument passed.\n" "$RED_ERROR" >&2
		help "$script" "$version" "$E_MISSING_ARG"
	fi
	shift "$(( OPTIND - 1 ))"
	over_line "$script $version"
	exit "$exit_code"
}

main "$@"
