#!/usr/bin/env bash
##########################################################################
# Script Name  : install-chromium-u
# Description  : Installs the ungoogled-chromium browser
# Dependencies : None
# Arguments    : None
# Author       : Richard B. Romig, 05 Jul 2020
# Email        : rick.romig@gmail.com
# Comments     : Debian bullseye, Ubuntu focal & derivatives.
# TODO (Rick)  : Test
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

readonly _script=$(basename "$0")
readonly _version="0.3.0"
readonly _updated="02 Sep 2022"
readonly source_list="/etc/apt/sources.list.d/home:ungoogled_chromium.list"
readonly trusted_gpg="/etc/apt/trusted.gpg.d/home_ungoogled_chromium.gpg"
readonly repo_url="deb http://download.opensuse.org/repositories/home:/ungoogled_chromium"
readonly key_url="https://download.opensuse.org/repositories/home:/ungoogled_chromium"

## Functions ##

main() {
  printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
  printf "Installs the ungoogled chromium browser on Debian and Ubuntu-based systems./n"
  ver_code=$(lsb_release --codename --short)
  case $ver_code in
    bullseye|elsie )
      user_in_sudo
      # install_bullseye
      install_ungoogled_chrome "Debian_Bullseye"
      ;;
    focal|ulyana|ulyssa|uma|una )
      user_in_sudo
      install_ungoogled_chrome "Ubuntu_Focal"
      ;;
    * )
      leave "$ver_code: Distribution is not supported."
      ;;
  esac
}

install_ungoogled_chrome() {
  local repo_id="$1"
  echo "$repo_url/$repo_id/ /" | sudo tee "$source_list" < /dev/null
  curl -fsSL "$key_url/$repo_id/Release.key" | gpg --dearmor | sudo tee "$trusted_gpg" > /dev/null
  sudo apt update
  sudo apt install ungoogled-chromium
  leave "ungoogled-chromium installed."
}

## Execution ##

main
