#!/usr/bin/env bash
#####################################################################
# Script Name  : install-handbrake
# Description  : Adds repository and installs handbrake
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2019, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 14 Feb 2019
# Updated      : 04 Apr 2025
# Comment      : Handbrake rips DVD movies
#              : Available as a flatpak via Flathub and Mint Software Manager
#              : https://dl.flathub.org/repo/appstream/fr.handbrake.ghb.flatpakref
#              : flatpak install fr.handbrake.ghb
#              : flakpak may not be able to access certain codecs for DRM.
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Global Variables ##

script=$(basename "$0"); readonly script
readonly version="3.11.25094"
readonly handbrake_ppa="ppa:stebbins/handbrake-releases"

## Functions ##

add_ppa() {
  echo "Adding Handbrake PPA..."
  sudo add-apt-repository "$handbrake_ppa"
  sudo apt update -qq
}

remove_ppa() {
  echo "Rmoving Handbake PPA..."
  sudo add-apt-repository --remove "$handbrake_ppa"
}

install_handbrake() {
  sudo_login 2
  support_ppa && add_ppa
  sudo apt install handbrake-gtk handbrake-cli -yy
  echo "Handbrake installed."
}

remove_handbrake() {
  sudo_login 2
  support_ppa && remove_ppa
  sudo apt autoremove handbrake-gtk handbrake-cli -yy
  echo "Handbrake removed from system."
}

help() {
  local errcode updated
	errcode="${1:-2}"
	updated="04 Apr 2025"
  cat << _HELP_
${orange}$script${normal} $version ($updated)
Install/Remove Handbrake video transcorder

${green}Usage:${normal} $script [OPTION]

${orange}Available options:${normal}
  -h  Show this help message and exit
  -i  Install Handbrake
  -r  Remove Handbrake
_HELP_
  exit "$errcode"
}

main() {
  local noOpt opt optstr
  noOpt=1
  optstr=":hir"
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        help 0
      ;;
      i )
        exists ghb && leave "Handbrake-GTK already installed."
        install_handbrake
      ;;
      r )
        exists ghb || leave "Handbrake is not installed."
        remove_handbrake
      ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help 2
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  leave "$script v$version"
}

## Execution ##

main "$@"