#!/usr/bin/env bash
##########################################################################
# Script Name  : install-neofetch
# Description  : Installs and configures neofetch
# Dependencies : git
# Arguments    : -c -h -i -r (See the help function for details.)
# Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 25 Jul 2022
# Updated      : 21 May 2025
# Comments     : NeoFetch is no longer in development. Recommnd using Fastfetch instead.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

script=$(basename "$0"); readonly script
readonly version="2.3.25141"

## Functions ##

help() {
  local errcode updated
	errcode="${1:-2}"
	updated="21 Feb 2025"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs/Configures/Removes Neofetch

${green}Usage:${normal} $script [OPTION]
${orange}Available options:${normal}
  -c  Apply Neofetch configuration
  -h  Show this help message and exit
  -i  Install and configure Neofetch
  -r  Remove Neofetch and configuration
_HELP_
  exit "$errcode"
}

neofetch_version() {
	/usr/bin/neofetch --version | cut -d' ' -f2
}

install_neofetch() {
	local thumbnail_dir="${HOME}/.cache/thumbnails/neofetch"
	printf "%s Neofetch is no longer in developemnt as of 26 April 2024.\n" "$RED_WARNING"
	sudo apt-get updates >/dev/null
	sudo apt-get install -yy neofetch
	[[ -d "$thumbnail_dir" ]] || mkdir -p "$thumbnail_dir"
	printf "Neofetch %s installed.\n" "$(neofetch_version)"
}

apply_config() {
	local repository="$1"
	[[ -d "$HOME/.config/neofetch" ]] && rm -rf "$HOME/.config/neofetch"
  printf "Appying Neofetch configuration...\n"
	ln -s "$repository/neofetch/"  "$HOME/.config/neofetch/"
	printf "Neofetch configuration applied.\n"
}

remove_neofetch() {
	local cfg_bu_dir="${HOME}/.config/backup/neofetch"
	local thumbnail_dir="${HOME}/.cache/thumbnails/neofetch"
	printf "Removing Neofetch %s...\n" "$(neofetch_version)"
	sudo apt-get purge -yy neofetch
	[[ -d "$HOME/.config/neofetch" ]] && rm -rf "$HOME/.config/neofetch"
	[[ -d "$cfg_bu_dir" ]] && rm -rf "$cfg_bu_dir"
	[[ -d "$thumbnail_dir" ]] && rm -rf "$thumbnail_dir"
	[[ -L "$HOME/.config/neofetch" ]] && unlink "$HOME/.config/neofetch"
	printf "Neofetch and configuration files removed.\n"
	sed -i '/neofetch/d' "$HOME/.bashrc"
}

main() {
  local noOpt opt optstr repository
	check_package git
	repository=$(assign_cfg_repo)
	noOpt=1
	optstr=":chir"
	while getopts "$optstr" opt; do
		case "$opt" in
			c )
				exists neofetch || leave "Neofetch is not installed."
				apply_config "$repository"
			;;
			h )
				help 0
			;;
			i )
				exists neofetch && leave "Neofetch $(neofetch_version) is already installed."
				in_repo neofetch || leave "Neofetch is no longer in the repositories."
				sudo_login 2
				install_neofetch
				apply_config "$repository"
			;;
			r )
				exists neofetch || leave "Neofetch is not installed."
				sudo_login 2
				remove_neofetch
			;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help 2
		esac
		noOpt=0
	done
	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
	shift "$(( OPTIND - 1 ))"
	leave "$script v$version"
}

## Execution ##

main "$@"
