#!/usr/bin/env bash
##########################################################################
# Script Name  : install-dsh
# Description  : Installs & configures DSH
# Dependencies : git
# Arguments    : none
# Author       : Copyright © 2024 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 08 Apr 2024
# Last updated : 04 May 2025
# Comments     : Intended for main system
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

## Functions ##

copy_group_list() {
  local file repository
	repository="$1"
  file="$2"
  printf "Copying %s list to /etc/dsh/group ...\n" "$file"
  sudo cp "$repository/dsh/group/$file" /etc/dsh/group/
  printf "%s list added to /etc/dsh/group\n" "$file"
}

copy_machines_list() {
  local file repository
	repository="$1"
  file="machines.list"
  printf "Copying %s to /etc/dsh/ ...\n" "$file"
  sudo cp "$repository/dsh/$file" /etc/dsh/
  printf "%s copied to /etc/dsh/\n" "$file"
  printf "Creating symbolic link from %s to /etc/dsh/group/all.\n" "$file"
  [[ -L /etc/dsh/group/all ]] || sudo ln -s /etc/dsh/machines.list /etc/dsh/group/all
}

install_dsh() {
  local group groups repository
	repository=$(assign_cfg_repo)
  groups=( desktops i3wm laptops )
  sudo apt-get -y install dsh
  printf "Changing remote shell to ssh.\n"
  sudo sed -i '/remoteshell/s/rsh/ssh/' /etc/dsh/dsh.conf
  copy_machines_list "$repository"
  for group in "${groups[@]}"; do
    copy_group_list "$repository" "$group"
  done
}

main() {
  local script version
  script=$(basename "$0")
  version="2.2.25124"
  check_package git
  sudo_login 2
  install_dsh
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
