#!/usr/bin/env bash
##########################################################################
# Script Name  : install-polybar
# Description  : Installs polybar on Debian i3wm systems.
# Dependencies : git (for assign_cfg_repo() in functionlib)
# Arguments    : None
# Author       : Copyright © 2023 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 16 Nov 2023
# Updated      : 03 Feb 2026
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 81
fi

## Functions ##

copy_polybar_config() {
	local repository=~/Downloads/configs/polybar
	[[ -d ~/gitea/configs/polybar ]] && repository=~/gitea/configs/polybar
	if [[ ! -d "$repository" ]]; then
    printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
		EC="$E_FILENOTFOUND"
    return
  fi
	local polybar_d=~/.config/polybar
	[[ -d "$polybar_d" ]] || mkdir -p "$polybar_d"
	printf "Copying the Polybar configuration file ...\n"
	cp -v "$repository/polybar/config.ini" "$polybar_d/"
	printf "Polybar configuration file copied from the Gitea server.\n"
	printf "Installing the Polybar launcher...\n"
	cp -v "$repository/polybar/polybar-i3" "$polybar_d/"
	[[ -x "$polybar_d/polybar-i3" ]] || chmod +x "$polybar_d/polybar-i3"
	configure_modules "$polybar_d"
	printf "polybar-i3 confgured.\n"
}

configure_modules() {
	local polybar_d cfg_file b_name e_name w_name
	polybar_d="$1"
	cfg_file="config.ini"
	# Get device names from system.
	e_name=$(awk '/ethernet/ {print $1}' <(/usr/bin/nmcli dev))
	w_name=$(awk '/wifi/ {print $1}' <(/usr/bin/nmcli dev))
	b_name=$(find /sys/class/power_supply/ -name "BAT*"); b_name="${b_name##*/}"
	# b_name=$(find /sys/class/power_supply/ -name "BAT*" | awk -F/ '/BAT/ {print $NF}')
	# Apply device names or exclude modules as required.
	if [[ "$w_name" ]]; then
		sed -i "s/wlan0/$w_name/" "$polybar_d/$cfg_file"
	else
		sed -i '/^modules-left/s/ wlan//' "$polybar_d/$cfg_file"
	fi
	if [[ "$e_name" ]]; then
		sed -i "s/eth0/$e_name/" "$polybar_d/$cfg_file"
	else
		sed -i '/^modules-left/s/ eth//' "$polybar_d/$cfg_file"
	fi
	if [[ "$b_name" ]]; then
		sed -i "s/BAT0/$b_name/" "$polybar_d/$cfg_file"
	else
		sed -i '/^modules-right/s/ battery//' "$polybar_d/$cfg_file"
	fi
}

install_polybar() {
	sudo_login 2
	sudo apt-get install -y polybar
	if ! grep -q '^ii' <(dpkg -l polybar 2>/dev/null); then
		printf "%s Polybar installation failedn" "$RED_ERROR" >&2
		EC="$E_INSTALLATION"
		return
	fi
	printf "Polybar installed.\n"
	copy_polybar_config
}

main() {
  local script="${0##*/}"
  local version="2.9.26034"
	EC=0
	printf "Installs Polybar on Debian with i3wm.\n"
	if exists polybar; then
		printf "Polybar is already installed.\n"
	else
		install_polybar
	fi
	over_line "$script $version"
  exit "$EC"
}

## Execution ##

main "$@"
