#!/usr/bin/env bash
##########################################################################
# Script Name  : install-firefox-deb
# Description  : install Firefox .deb package from Mozilla repos
# Dependencies : wget
# Arguments    : none
# Author       : Copyright © 2024 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 24 Jan 2024
# Updated      : 30 Jun 2025
# Comments     : Remove Distro, Flatpak, or Snap version before installing.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

## Global Variables ##

readonly script="${0##*/}"
readonly version="5.0.25181"
verbose_mode="$FALSE"

## Functions ##

help() {
	local errcode="${1:-2}"
	local -r updated="30 Jun 2025"
	cat << _HELP_
${orange}$script${normal} $version, Upated: $updated
Installs/Removes Mozilla repository version of Firefox.

${green}Usage:${normal} $script [-h] [-iv] [-vr]
${orange}Available options:${normal}
	-h	Show this help message and exit.
	-i	Install application.
	-r	Remove application.
	-v	Enable verbose mode. If used, must precede other flags.
_HELP_
  exit "$errcode"
}

show_message() {
	local message="$1"
	[[ "$verbose_mode" == "$TRUE" ]] && echo "$message"
}

firefox_version() {
	firefox --version | cut -d' ' -f3
}

mozilla_deb() {
	dpkg -l firefox | grep -q 'Mozilla Firefox' && return "$TRUE" || return "$FALSE"
}

other_firefox() {
	dpkg -l firefox-esr | grep -q 'esr' && return "$TRUE"
	dpkg -l firefox | grep -q 'linuxmint' && return "$TRUE"
	return "$FALSE"
}

make_preference_file() {
	# Preference file to prioritize packages from Mozilla repository
	echo '
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
'| sudo tee /etc/apt/preferences.d/mozilla.pref
}

install_mozilla_deb() {
	local -r keyrings_d="/etc/apt/keyrings"
	local -r asc_file="packages.mozilla.org.asc"
	local -r key_url="https://packages.mozilla.org/apt/repo-signing-key.gpg"
	local -r list_url="https://packages.mozilla.org/apt"
	local -r mozilla_list="/etc/apt/sources.list.d/mozilla.list"

	printf "Installing the Mozilla Firefox DEB package...\n"
	show_message "Installing keyrings directory..."
	[[ -d "$keyrings_d" ]] || sudo install -d -m 0755 "$keyrings_d"
	show_message "Importing Mozilla APT repository keys..."
	wget -q "$key_url" -O- | sudo tee "$keyrings_d/$asc_file" > /dev/null
	show_message "Adding Mozilla APT repository to sources list..."
	echo "deb [signed-by=$keyrings_d/$asc_file] $list_url mozilla main" | sudo tee -a "$mozilla_list" > /dev/null
	show_message "Creating preference file..."
	make_preference_file
	show_message "Updating apt cache..."
	sudo apt-get update
	show_message "Installing Firefox..."
	sudo apt-get install -y firefox
	printf "%s installed.\n" "$(firefox_version)"
}

remove_mozilla_firefox() {
	local -r mozilla_list="/etc/apt/sources.list.d/mozilla.list"
	local -r mozilla_pref="/etc/apt/preferences.d/mozilla.pref"
	local -r mozilla_asc="/etc/apt/keyrings/packages.mozilla.org.asc"
	printf "Firefox version installed: %s\n" "$(firefox_version)"
	show_message "Removing Firefox..."
	sudo apt-get remove -y firefox
	show_message "Removing source.list..."
	[[ -f "$mozilla_list" ]] && sudo rm "$mozilla_list"
	show_message "Removing Mozilla preference file..."
	[[ -f "$mozilla_pref" ]] && sudo rm "$mozilla_pref"
	show_message "Removing keyring..."
	[[ -f "$mozilla_asc" ]] && sudo rm "$mozilla_asc"
	show_message "Removing user configuration files..."
	[[ -d "$HOME/.mozilla" ]] && rm -rf "$HOME/.mozilla"
	printf "The Mozilla Firefox deb package has been removed.\n"
}

main() {
	local noOpt opt optstr
	noOpt=1
	optstr=":hirv"
	while getopts "$optstr" opt; do
		case "$opt" in
			h )
				help 0
				;;
			i )
				if other_firefox; then
					printf "Another version of Firefox is already installed.\n" >&2
					printf "Remove before installing the Mozilla package.\n" >&2
				elif mozilla_deb; then
					printf "Mozilla Firefox %s is already installed.\n" "$(firefox_version)" >&2
				else
					install_mozilla_deb
				fi
				;;
			r )
				if mozilla_deb; then
					remove_mozilla_firefox
				else
					printf "Mozilla Firefox DEB package is not installed.\n" >&2
				fi
				;;
			v )
				verbose_mode="$TRUE"
				show_message "Verbose mode enabled."
				;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help 2
		esac
		noOpt=0
	done
	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
	shift "$(( OPTIND - 1 ))"
	over_line "$script $version"
	exit
}

## Execution ##

main "$@"
