#!/usr/bin/env bash
##########################################################################
# Script Name  : install-ufw
# Description  : Installs and configures the UFW firewall.
# Dependencies : None
# Arguments    : See help()
# Author       : Copyright (C) Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 05 Oct 2022
# Updated      : 26 May 2026
# Comments     : Install & remove for Debian-based systems only.
#              : UFW should already be installed on Linux Mint & LMDE.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Load function library ##
# shellcheck source=/home/rick/bin/functionlib
source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

## Global Variables ##

readonly script="${0##*/}"
readonly version="2.0.26146"
EC=0

## Functions ##

help() {
	local errcode="${1:-1}"
	local -r updated="26 May 2026"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs UFW on Debian, BunsenLabs, and MX Linux systems.
UFW/GUFW is installed by default in Linux Mint, LMDE, and Ubuntu.

${green}Usage:${normal} $script [-adehinrs]
${orange}Available options:${normal}
  -a  Add rules for CUPS and SSH (XRDP if installed)
  -d  Delete rules
  -e  Toggle Enable/Disable UFW
  -h  Show this help message and exit
  -i  Install UFW on a Debian-based system
  -n  Add New rules
  -r  Remove UFW from a Debian-based system
  -s  UFW Status
_HELP_
  exit "$errcode"
}

install_ufw() {
  printf "Installing UFW (Uncomplicated Firewall)...\n"
  sudo apt-get install ufw -yy
  if ! installed ufw; then
    printf "%s UFW installation failed.\n" "$RED_ERROR" >&2
    EC="$E_INSTALLATION"
    return
  fi
  default_rules
  enable_ufw
  printf "UFW %s installed and configured.\n" "$(ufw_version)"
}

remove_ufw() {
  sudo_login 2
  printf "Removing UFW (Uncomplicated Firewall) version %s...\n" "$(ufw_version)"
  sudo ufw reset  # disable UFW and delete all active rules
  sudo  apt-get purge ufw
}

default_rules() {
  printf "Adding rules for CUPS, SSH, XRDP...\n"
  sudo sed -i '/IPV6=no/s/no/yes/' /etc/default/ufw
  sudo ufw allow 631 && printf "CUPS (port 631) allowed.\n"
  sudo ufw allow SSH && printf "SSH (port 22/tcp) allowed.\n"
  if installed xrdp; then
    sudo ufw allow 3389/tcp
    printf "XRDP (port 3389/tcp) allowed.\n"
  fi
}

new_rules() {
  local rule="deny foo"
  sudo ufw status
  printf "Add new rules in the following format:\n"
  printf "allow/deny <protocol> or allow/deny <port-number>\n"
  while [[ "$rule" != "" ]]; do
    read -rp "Rule to be added (done to exit): " rule
    [[ "$rule" != "" ]] && sudo ufw "$rule"
  done
}

delete_rules() {
  local rule="allow foo"
  sudo ufw status numbered
  while [[ "$rule" != "" ]]; do
    read -rp "Rule to be removed (by number): " rule
    [[ "$rule" != "" ]] && sudo ufw delete "$rule"
  done
}

enable_ufw() {
  printf "Enabling UFW...\n"
  sudo ufw enable
  sudo ufw status verbose
}

disable_ufw() {
  printf "Disabling UFW...\n"
  sudo ufw disable
  sudo ufw status
}

ufw_active() {
  grep -qw active < <(sudo ufw status) && return "$TRUE" || return "$FALSE"
}

ufw_version() {
  awk 'NR==1 {print $NF}' < <(/usr/sbin/ufw version)
}

main() {
  local noOpt opt optstr OPTARG OPTIND
  noOpt=1
  optstr=":adehinrs"
  while getopts "$optstr" opt; do
    case "$opt" in
      a )
        if installed ufw; then
          sudo_login 2
          default_rules
          ufw_active || enable_ufw
        else
          printf "UFW is not installed.\n" >&2
        fi
        ;;
      d )
        if installed ufw; then
          sudo_login 2
          delete_rules
        else
          printf "UFW is not installed.\n" >&2
        fi
        ;;
      e )
        if installed ufw; then
          sudo_login 2
          if ufw_active; then
            printf "UFW %s is enabled.\n" "$(ufw_version)"
            default_no "Disable UFW?" && disable_ufw
          else
            enable_ufw
          fi
        else
          printf "UFW is not installed.\n" >&2
        fi
        ;;
      h )
        help 0
        ;;
      i )
        if installed ufw; then
          printf "UFW %s is already installed.\n" "$(ufw_version)" >&2
        else
          sudo_login 2
          install_ufw
        fi
        ;;
      n )
        if installed ufw; then
          sudo_login 2
          new_rules
        else
          printf "UFW is not installed.\n" >&2
        fi
        ;;
      r )
        if installed ufw; then
          is_debian && remove_ufw
          printf "Not a Debian system. UFW was not removed.\n" >&2
        else
          printf "UFW is not installed.\n" >&2
        fi
        ;;
      s )
        if installed ufw; then
          sudo_login 2
          printf "UFW %s\n" "$(ufw_version)"
          sudo ufw status numbered
        else
          printf "UFW is not installed.\n" >&2
        fi
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$E_INVALID_ARG"
    esac
    noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit "$EC"
}

## Execution ##

main "$@"
