#!/usr/bin/env bash
#############################################################################
# Script Name  : install-flatpak
# Description  : Installs flatpak, Gnome Software plugin, and Flathub repository
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2020, Richard B. Romig, 01 Mar 2020
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     : Debian 10, Ubuntu 18.04, Mint 19.x
# TODO (Rick)  :
# License      : GNU General Public License, version 2
#############################################################################

### Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.1.10"
readonly _updated="04 Feb 2023"

## Functions ##

install_gnome_plugin() {
  # Install Gnome software plugin for flatpak
  echo "Installing Gnome software plugin for Flatpak ..."
  sudo apt install gnome-software-plugin-flatpak -yy
}

install_flathub() {
  # Install flathub repository
  echo "Installing Flathub repository ..."
  sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
}

## Execution ##

clear
echo "$_script v$_version ($_updated)"
echo "Installs Flatpak & Flathub repository."

if exists flatpak; then
  echo "Flatpak is already installed."  # Mint 18.3+, LMDE 3+, Peppermnt 10, MX 19
else
  ver_code=$(lsb_release -c | cut -f 2)
  case $ver_code in
    bullseye|buster|focal|jammy )
      # Debian 10/11, antiX 19.x, Ubuntu 20.04
      sudo apt update -qq
      sudo apt install flatpak -yy
      ;;
    bionic|cosmic|disco|eoam )
      # Ubuntu 18.04, 18.10, 19.04, 19.10
      sudo add-apt-repository ppa:alexlarsson/flatpak
      sudo apt update -qq
      sudo apt install flatpak -yy
      ;;
    * )
      die "Flatpak can't be installed using this script." 1 ;;
  esac
fi

install_gnome_plugin
install_flathub

leave "Flatpak and Flathub installed."
