#!/bin/bash
##########################################################################
# Script Name  : install-keepassxc
# Description  : Installs/removes KeePassXC from Flathub or distro repos
# Dependencies : none
# Arguments    : -d -f -h -m -r (see help function)
# Author       : Copyright (C) 2021, Richard B. Romig, 26 Jan 2021
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.3.2"
readonly _updated="12 Mar 2023"

## Functions ##

kpxc_ver() {
  dpkg -l | awk '$2 == "keepassxc" {print $3}' | sed 's/[+-].*//'
}

keepass_ver() {
  flatpak list | awk '/KeePassXC/ {print $3}'
}

flathub_keepassxc() {
  user_in_sudo
  sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  sudo flatpak install flathub org.keepassxc.KeePassXC
  printf "KeePassXC %s installed from flathub.\n" "$(keepass_ver)"
}

distro_keepassxc() {
  user_in_sudo
  sudo apt-get install keepassxc -yy
  printf "Keepassxc %s installed from distro repositories.\n" "$(kpxc_ver)"
}

remove_keepassxc() {
  user_in_sudo
  printf "Removing KeePassXC ...\n"
  if [[ -d "HOME/.var/app/org.keepassxc.KeePassXC" ]]; then
    sudo flatpak uninstall --noninteractive --assumeyes org.keepassxc.KeePassXC
  else
    if support_ppa; then
      sudo apt-add-repository --remove ppa:phoerious/keepassxc
      sudo rm /etc/apt/sources.list.d/phoerious-keepassxc-focal.list
      sudo apt-key del "D89C 66D0 E31F EA28 74EB  D205 6192 2AB6 0068 FCD6"
    fi
    sudo apt-get remove --purge keepassxc -yy
    [[ -d "$HOME/.config/keepassxc" ]] && rm -rf "$HOME/.config/keepassxc"
  fi
  printf "KeePassXC removed.\n"
}

move_vault() {
  local vault_dir="$HOME/Documents"
  printf "Moving password databases to ~/Documents...\n"
  find "$HOME/Documents/mosfanet/" -maxdepth 1 -type f -iname "*.kdbx" -print -exec mv {} "$vault_dir/" \;
  find "$HOME/Documents/mosfanet/" -maxdepth 1 -type f -iname "Rick_pwds*" -print -exec mv {} "$vault_dir/" \;
}

help() {
  errcode="${1:-2}"
  cat << END_HELP
Usage: $_script [OPTIONS]
OPTIONS:
  -d  Install KeePassXC from distribution repositories.
  -f  Install KeePassXC from flathub repositories.
  -h  Display help.
  -m  Move password vaults from ~/Documents/mosfanet to ~/Documents.
  -r  Remove KeePassXC from the system.
END_HELP
  exit "$errcode"
}

## Execution ##

echo "$_script v$_version ($_updated)"
echo "Installs KeePassXC password manager"
if [[ "$#" -eq 0 ]]; then
  printf "%sNo argument passed." "$red_error" >&2
  help 1
else
  optstr=":dfhmr"
  while getopts "$optstr" opt; do
    case "$opt" in
      d )
        exists keepassxc && leave "KeePassXC $(kpxc_ver) already installed."
        flatpak list | grep -qw KeePassXC && leave "KeePassXC $(keepass_ver) flatpak installed."
        distro_keepassxc
        ;;
      f )
        exists flatpak || leave "Flatpak is not installed."
        flatpak list | grep -qw KeePassXC && leave "KeePassXC $(keepass_ver) flatpak installed."
        exists keepassxc && remove_keepassxc
        flathub_keepassxc
        ;;
      h )
        help 0
        ;;
      m )
        move_vault
        ;;
      r )
        if exists keepassxc || flatpak list | grep -qw KeePassXC; then
          remove_keepassxc
        else
          leave "KeePassXC is not installed."
        fi
        ;;
      ? )
        printf "%sInvalid option -%s\n" "$red_error" "$OPTARG" >&2
        help 2
    esac
  done
fi
exit
