#!/usr/bin/env bash
##########################################################################
# Script Name  : install-ufw
# Description  : Installs and configures the UFW firewall.
# Dependencies : None
# Arguments    : See help()
# Author       : Copyright (C) Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 05 Oct 2022
# Updated      : 18 Jul 2025
# Comments     : Install & remove for Deian-based systems only.
#              : UFW should already be installed on Linux Mint & LMDE.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

## Global Variables ##

readonly script="${0##*/}"
readonly version="1.16.25199"

## Functions ##

help() {
	local errcode="${1:-2}"
	local -r updated="18 Jul 2025"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs UFW on Debian, BunsenLabs, and MX Linux systems.
UFW/GUFW is installed by default in Linux Mint, LMDE, and Ubuntu.

${green}Usage:${normal} $script [-adehinrs]

${orange}Available options:${normal}
  -a  Add rules for CUPS and SSH (XRDP if installed)
  -d  Delete rules
  -e  Toggle Enable/Disable UFW
  -h  Show this help message and exit
  -i  Install UFW on a Debian-based system
  -n  Add New rules
  -r  Remove UFW from a Debian-based system
  -s  UFW Status
_HELP_
  exit "$errcode"
}

exists_xrdp() {
  dpkg -l xrdp > /dev/null 2>&1 && return "$TRUE" || return "$FALSE"
}

install_ufw() {
  printf "Installing UFW (Uncomplicated Firewall)...\n"
  sudo apt-get install ufw -yy
}

remove_ufw() {
  printf "Removing UFW (Uncomplicated Firewall) version %s...\n" "$(ufw_version)"
  sudo ufw reset  # disable UFW and delete all active rules
  sudo  apt-get purge ufw
}

add_rules() {
  printf "Adding rules for CUPS, SSH, and XRDP...\n"
  sudo sed -i '/IPV6=no/s/no/yes/' /etc/default/ufw
  sudo ufw allow 631   # CUPS 631
  sudo ufw allow SSH   # SSH 22/tcp
  exists_xrdp && sudo ufw allow 3389/tcp  # XRDP
}

new_rules() {
  local rule="deny foo"
  sudo ufw status
  printf "Add new rules in the following format:\n"
  printf "allow/deny <protocol> or allow/deny <port-number>\n"
  while [[ "$rule" != "" ]]; do
    read -rp "Rule to be added (done to exit): " rule
    [[ "$rule" != "" ]] && sudo ufw "$rule"
  done
}

delete_rules() {
  local rule="allow foo"
  sudo ufw status numbered
  while [[ "$rule" != "" ]]; do
    read -rp "Rule to be removed (by number): " rule
    [[ "$rule" != "" ]] && sudo ufw delete "$rule"
  done
}

enable_ufw() {
  printf "Enabling UFW...\n"
  sudo ufw enable
  sudo ufw status verbose
}

disable_ufw() {
  printf "Disabling UFW...\n"
  sudo ufw disable
  sudo ufw status
}

ufw_active() {
  sudo ufw status | grep -qw active && return "$TRUE" || return "$FALSE"
}

ufw_version() {
  /usr/sbin/ufw version | awk '/ufw/ {print $NF}'
}

debian_system() {
  local codename
  codename=$(lsb_release --codename --short)
  case "$codename" in
    bookworm|bullseye|trixie|boron )
      return "$TRUE" ;;
    * )
      return "$FALSE"
  esac
}

main() {
  local noOpt opt optstr
  noOpt=1
  optstr=":adehinrs"
  while getopts "$optstr" opt; do
    case "$opt" in
      a )
        if dpkg -l | grep -qw ufw; then
          sudo_login 2
          add_rules
          ufw_active || enable_ufw
          printf "Rules for CUPS and SSH added.\n"
        else
          printf "UFW is not installed.\n" >&2
        fi
        ;;
      d )
        if dpkg -l | grep -qw ufw; then
          sudo_login 2
          delete_rules
        else
          printf "UFW is not installed.\n" >&2
        fi
        ;;
      e )
        if dpkg -l | grep -qw ufw; then
          sudo_login 2
          if ufw_active; then
            printf "UFW %s is enabled.\n" "$(ufw_version)"
            defult_no "Disable UFW?" && disable_ufw
          else
            enable_ufw
          fi
        else
          printf "UFW is not installed.\n" >&2
        fi
        ;;
      h )
        help 0
        ;;
      i )
        if debian_system; then
          if dpkg -l | grep -qw ufw; then
            printf "UFW %s is already installed.\n" "$(ufw_version)" >&2
          else
            sudo_login 2
            install_ufw
            add_rules
            enable_ufw
            printf "UFW %s installed and configured.\n" "$(ufw_version)"
          fi
        else
          printf "Not a Debian system.\n" >&2
        fi
        ;;
      n )
        if dpkg -l | grep -qw ufw; then
          sudo_login 2
          new_rules
        else
          printf "UFW is not installed.\n" >&2
        fi
        ;;
      r )
        if debian_system; then
          if dpkg -l | grep -qw ufw; then
            sudo_login 2
            remove_ufw
          else
            printf "UFW is not installed.\n" >&2
          fi
        else
          printf "Not a Debian system.\n" >&2
        fi
        ;;
      s )
        if dpkg -l | grep -qw ufw; then
          sudo_login 2
          printf "UFW %s\n" "$(ufw_version)"
          sudo ufw status numbered
        else
          printf "UFW is not installed.\n" >&2
        fi
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help 2
    esac
    noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
