#!/usr/bin/env bash
##########################################################################
# Script Name  : install-homebank
# Description  : Installs Homebank
# Dependencies : none
# Arguments    : none
# Author       : Copyright (C) 2018, Richard Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 29 Nov 2018
# Updated      : 30 Jan 2026
# Comments     : Available as a flatpak (preferred method)
#              : https://flathub.org/apps/details/fr.free.Homebank
#              : Linux Mint Sofware Manager
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 81
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="6.3.26030"

## Functions ##

help() {
	local errcode="${1:-1}"
	local updated="30 Jan 2026"
  cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs/Removes HomeBank Personal Finance Software.

${green}Usage:${normal} $script [option]
${orange}Available options:${normal}
  -f  install HomeBank from Flathub
  -h  Show this help message and exit
  -i  Install HomeBank from repository
  -r  Remove HomeBank
_HELP_
  exit "$errcode"
}

flatpak_homebank() {
  exists flatpak || return "$FALSE"
  grep -qw HomeBank <(flatpak list) && return "$TRUE" || return "$FALSE"
}

homebank_version() {
  local hb_ver
  if exists homebank; then
    hb_ver=$(homebank --version | cut -d' ' -f2)
  elif flatpak_homebank; then
    hb_ver=$(flatpak list | awk '/HomeBank/ {print $(NF-2)}')
  fi
  printf "%s" "$hb_ver"
}

install_flatpak_homebank() {
  printf "Install the HomeBank flatpak...\n"
  sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  flatpak install --user flathub fr.free.Homebank
  apply_preferences
  printf "HomeBank flatpak (%s) installed.\n" "$(homebank_version)"
}

remove_flatpak_homebank() {
  printf "Removing HomeBank flatpak (%s)...\n" "$(homebank_version)"
  flatpak uninstall --oninteractive --assumeyes fr.free.Homebank
  [[ -d "$HOME/.var/app/fr.free.Homebank" ]] && rm -rf "$HOME/.var/app/fr.free.Homebank"
  remove_configs
  printf "HomeBank has been removed.\n"
}

install_homebank() {
  sudo_login 2
  sudo apt-get install homebank -yyq
  exists homebank || die "Homebank installation failed." 1
  apply_preferences
  printf "HomeBank %s installed.\n" "$(homebank_version)"
}

remove_homebank() {
  printf "Removing HomeBank %s...\n" "$(homebank_version)"
  sudo_login 2
  sudo apt-get remove homebank -yy > /dev/null 2>&1
  remove_configs
  printf "HomeBank has been removed.\n"
}

apply_preferences() {
  local repository=~/Downloads/configs/homebank
  [[ -d ~/gitea/configs/homebank ]] && repository=~/gitea/configs/homebank
  if [[ ! -d "$repository" ]]; then
    printf "%s Configs repository not found!\n" "$RED_WARNING" >&2
    return
  fi
  local cfg_dir=~/.config
  flatpak_homebank && cfg_dir=~/.var/app/fr.free.Homebank/config
  [[ -d "$cfg_dir" ]] || mkdir -p "$cfg_dir"
  cp -v "$repository"/homebank/preferences "$cfg_dir"/homebank/
  printf "HomeBank preferences applied.\n"
}

remove_configs() {
  local cfg_dir=~/.config/homebank
  flatpak_homebank && cfg_dir=~/.var/app/fr.free.Homebank/config/homebank
  if default_no "Remove user configuration files?"; then
    printf "Removing user configuration files...\n"
    [[ -d "$cfg_dir" ]] && rm -rf "$cfg_dir"
    printf "User configuration files removed.\n"
  else
    printf "User configuations files left intact.\n"
  fi
}

main() {
  local noOpt opt optstr OPTARG OPTIND
  noOpt=1
  optstr=":fhir"
  while getopts "$optstr" opt; do
    case "$opt" in
      f )
        if exists homebank || flatpak_homebank; then
          printf "HomeBank %s is already installed.\n" "$(homebank_version)"
        else
          install_flatpak_homebank
        fi
        ;;
      h )
        help 0
        ;;
      i )
        if exists homebank || flatpak_homebank; then
          printf "HomeBank %s is already installed.\n" "$(homebank_version)"
        else
          install_homebank
        fi
        ;;
      r )
        if flatpak_homebank; then
          remove_flatpak_homebank
        elif exists homebank; then
          remove_homebank
        else
          printf "HomeBank is not installed.\n"
        fi
        ;;
      ? )
        printf "%s Invalid option: -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$E_INVALID_ARG"
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
