#!/usr/bin/env bash
###############################################################################
# Script Name  : install-audioapps
# Description  : installs audio applications and utilities
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2019, Richard B. Romig, MosfaNet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 01 Mar 2019
# Updated      : 02 Feb 2026
# Comments     :
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 81
fi

## Functions ##

install_audio_apps() {
  printf "\nInstalling audio applications and utilities from repositories.\n"
  sudo apt-get install -yy asunder audacity easytag lame mp3gain
}

list_installed_apps() {
  local app apps
  apps=( asunder audacity easytag lame mp3gain )
  printf "Audio applications installed:\n"
  for app in "${apps[@]}"; do
    exists "$app" && printf "\t%s\n" "${app^}"
  done
}

main() {
  local script="${0##*/}"
  local version="1.6.26033"
  sudo_login 2
  sudo apt-get update -qq
  printf "Installs audio applications on Debian/Ubuntu-based systems.\n"
  install_audio_apps
  list_installed_apps
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
