#!/usr/bin/env bash
#####################################################################
# Script Name  : ip-info
# Description  : Displays IP & network device information
# Dependencies : curl, iw, network-manager (nmcli)
# Arguments    : None
# Author       : Copyright (C) 2019, Richard Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 19 Feb 2019
# Updated      : 21 Jan 2026
# Comments     : Some systems require toot access to get ssid & signal strength.
#              : If necesary, add applicable hostnames to requires_sudo().
# TODO (rick)  : format printf statements for devices.
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#####################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 81
fi

## Functions ##

# Some systems may require root access for the iw command. Place these hostnames in the case statement.
requires_sudo() {
	local lhost="$1"
  case "$lhost" in
    foo-bar )
      return "$TRUE" ;;
    * )
      return "$FALSE"
  esac
}

check_dependencies() {
  local packages=( curl iw network-manager )
  check_packages "${packages[@]}"
}

show_public() {
  local public_ipv4
  public_ipv4=$(/usr/bin/curl -s ifconfig.me)     # http://ident.me
  if [[ "$public_ipv4" ]]; then
    printf "%12s: %s\n" "IPv4" "$public_ipv4"
  else
    printf "%37s\n" "No public IPv4 address found."
  fi
  local public_ipv6
  public_ipv6=$(/usr/bin/curl -s -6 icanhazip.com)
  if [[ "$public_ipv6" ]]; then
    printf "%13s: %s\n" "IPv6" "$public_ipv6"
  else
    sed 's/^/        /' <(printf "No public IPv6 address found.\n")
  fi
}

show_wired() {
  # Assumes only one active ethernet wired interface in the system.
  local eth_int eth_state eth_ip eth_mac
  eth_int=$(awk '/ethernet/ {print $1}' <(/usr/bin/nmcli dev))
  if [[ "$eth_int" ]]; then
    # interface data
    eth_state=$(cat "/sys/class/net/$eth_int/operstate")
    eth_ip=$(awk '/IP4.ADDRESS/ {print $NF}' <(/usr/bin/nmcli dev show "$eth_int") | sed 's/\/24//')
    eth_mac=$(awk '/GENERAL.HWADDR/ {print $NF}' <(/usr/bin/nmcli dev show "$eth_int"))
    # display status
   case "$eth_state" in
      up )
        printf "%16s: %s\n" "Ethernet" "$eth_ip"
        printf "%16s: %s\n" "Device" "$eth_int"
        printf "%16s: %s\n" "MAC" "$eth_mac"
        ;;
      down )
        printf "%16s: %s\n" "Ethernet" "Not connected"
        printf "%16s: %s\n" "Device" "$eth_int"
        printf "%16s: %s\n" "MAC" "$eth_mac"
        ;;
      unknown )
        printf "%16s: %s\n" "Ethernet" "Unknown state"
        printf "%16s: %s\n" "Device" "$eth_int"
        printf "%16s: %s\n" "MAC" "$eth_mac"
        ;;
      * )
        sed 's/^/        /' <(printf "No device found.\n")
    esac
  fi
}

show_wireless() {
  # Assumes only one active wireless interface in the system.
  local wifi_int wifi_state wifi_ip wifi_mac wifi_ssid wifi_sig
  wifi_int=$(awk '/wifi / {print $1}' <(/usr/bin/nmcli dev))
  if [[ "$wifi_int" ]]; then
    # interface data
    wifi_state=$(cat "/sys/class/net/$wifi_int/operstate")
    wifi_ip=$(awk '/IP4.ADDRESS/ {print $NF}' <(/usr/bin/nmcli dev show "$wifi_int") | sed 's/\/24//')
    wifi_mac=$(awk '/GENERAL.HWADDR/ {print $NF}' <(/usr/bin/nmcli dev show "$wifi_int"))
    if requires_sudo; then
      wifi_ssid=$(awk '/SSID/ {print $2}' <(sudo /sbin/iw dev "$wifi_int" link))
      wifi_sig=$(awk '/signal/ {print $2,$3}' <(sudo /sbin/iw dev "$wifi_int" link))
    else
      wifi_ssid=$( awk '/SSID/ {print $2}' <(/sbin/iw dev "$wifi_int" link))
      wifi_sig=$(awk '/signal/ {print $2,$3}' <(/sbin/iw dev "$wifi_int" link))
    fi
    [[ "$wifi_ssid" ]] || wifi_ssid="Not available"
    [[ "$wifi_sig" ]] || wifi_sig="Not available"
    # display status
    case "$wifi_state" in
      up )
        printf "%16s: %s\n" "Wireless" "$wifi_ip"
        printf "%16s: %s\n" "Device" "$wifi_int"
        printf "%16s: %s\n" "MAC" "$wifi_mac"
        printf "%16s: %s\n" "SSID" "$wifi_ssid"
        printf "%16s: %s\n" "Signal" "$wifi_sig"
        ;;
      down )
        printf "%16s: %s\n" "Wireless" "Not connected"
        printf "%16s: %s\n" "Device"  "$wifi_int"
        printf "%16s: %s\n" "MAC" "$wifi_mac"
        ;;
      unknown )
        printf "%16s: %s\n" "Wireless" "Unknown state"
        printf "%16s: %s\n" "Device" "$wifi_int"
        printf "%16s: %s\n" "MAC" "$wifi_mac"
        ;;
      * )
        sed 's/^/        /' <(printf "No device found.\n")
    esac
  fi
}

show_bridge() {
  local br_int br_state br_ip br_mac br_route
	br_int=$(awk '/bridge / {print $1}' <(/usr/bin/nmcli dev))
	if [[ "$br_int" ]]; then
    # interface data
    br_state=$(cat "/sys/class/net/$br_int/operstate")
    br_ip=$(awk '/vir/ && /brd/ {print $2}' <(ip addr show))
    br_mac=$(cat "/sys/class/net/$br_int/address")
    br_route=$(awk '/vir/ && /kernel/ {print $1}' <(ip route show))
    # display status
    case "$br_state" in
      up )
        printf "%16s: %s\n" "Bridge" "$br_ip"
        printf "%16s: %s\n" "Device"  "$br_int"
        printf "%16s: %s\n" "MAC"  "$br_mac"
	      printf "%16s: %s\n" "Subnet" "$br_route"
        ;;
      down )
        printf "%16s: %s\n" "Bridge" "Not connected"
        printf "%16s: %s\n" "Device"  "$br_int"
        printf "%16s: %s\n" "MAC"  "$br_mac"
        ;;
      unknown )
        printf "%16s: %s\n" "Bridge" "Unknown state"
        printf "%16s: %s\n" "Device"  "$br_int"
        printf "%16s: %s\n" "MAC"  "$br_mac"
        ;;
      * )
        sed 's/^/        /' <(printf "No device found.\n")
    esac
	fi
}

show_network() {
  local network_addr
  network_addr=$(awk '/kernel/ {print $1;exit}' <(ip route show))
  printf "%sLocal Network:%s\n" "$orange" "$normal"
  sed 's/^/        /' <(printf "%s\n" "$network_addr")
}

show_gateway() {
  local gateway_addr
  gateway_addr=$(awk 'NR==1 {print $3}' <(ip route get 1.2.3.4))
  printf "%sDefault Gateway:%s\n" "$orange" "$normal"
  sed 's/^/        /' <(printf "%s\n" "$gateway_addr")
}

show_dns() {
  local dns_addr
  dns_addr=$(awk '/IP4.DNS/ {print $NF}' <(/usr/bin/nmcli dev show) | sort -u)
  printf "%sDNS Servers:%s\n" "$orange" "$normal"
  sed 's/^/        /' <(printf "%s\n" "$dns_addr")
}

main() {
  local -r lhost="${HOSTNAME:-$(hostname)}"
  local -r script="${0##*/}"
  local -r version="4.0.26021"
  requires_sudo "$lhost" && sudo_login 2
  check_dependencies
  clear
  echo "${lightyellow}"
  box "IP Information - $lhost" "*"
  echo "${normal}"
  printf "%sPublic IP:%s\n" "$orange" "$normal"
  show_public
  printf "%sLocal IP:%s\n" "$orange" "$normal"
  show_wired
  show_wireless
  show_bridge
  show_network
  show_gateway
  show_dns
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
