#!/usr/bin/env bash
##########################################################################
# Script Name  : iru-marktext
# Description  : Installs, updates, and removes the Mark Text markdown editor.
# Dependencies : wget
# Arguments    : [-hiru] (See help function)
# Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 10 Jan 2022
# Updated      : 04 Feb 2026
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 81
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="4.23.26035"
readonly gh_url="https://github.com/marktext/marktext/releases"
DOTS_PID=
EC=0

## Functions ##

help() {
	local errcode="${1:-1}"
	local -r updated="04 Feb 2026"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs, configures, updates, removes the Mark Text markdown editor.

${green}Usage:${normal} $script [-hiru]
${orange}Available options:${normal}
  -h  Show this help message and exit.
  -i  Installs the Marktext markdown editor.
  -r  Removes the Marktext markdown editor from the system.
  -u  Updates the Marktext markdown editor to the latest GitHub release.
_HELP_
  exit "$errcode"
}

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
cleanup() {
  [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
}

marktext_version() {
  awk '/^ii/ {print $3}' <(dpkg -l marktext)
}

newest_version() {
  local new_ver
  wget -qO "$tmp_file" "$gh_url"
  new_ver=$(grep -Ev 'beta|-rc' <(awk -F'/' '/download/ && /amd64.deb/ {print $6;exit}' "$tmp_file") | sed 's/^v//')
  echo "$new_ver"
}

compare_versions() {
	local new_ver="$1"
	local cur_ver
  cur_ver=$(marktext_version)
  if [[ -z "$new_ver" ]]; then
    printf "%s No download available. Try again later." "$RED_ERROR" >&2
    EC="$E_DOWNLOAD"
    return
  elif [[ ! "$new_ver" > "$cur_ver" ]]; then
    printf "%sMarktext %s is the latest version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
    return
  fi
  printf "%sInstalled version of MarkText is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
  install_marktext "$new_ver"
}

install_marktext() {
  local new_ver="$1"
  local -r new_pkg="marktext-amd64.deb"
  if [[ -z "$new_ver" ]]; then
    printf "%s No download available. Try again later." "$RED_ERROR" >&2
    EC="$E_DOWNLOAD"
    return
  fi
  printf "Downloading Mark Text markdown editor (v %s) from the marktext GitHub repository..." "$new_ver"
  dots "." &
  DOTS_PID="$!"
  wget -q -P "$tmp_dir/" "$gh_url/download/v$new_ver/$new_pkg"
	kill_dots
  sudo_login 2
  printf "Installing Mark Text %s...\n" "$new_ver"
	sudo dpkg -i "$tmp_dir/$new_pkg"; sudo apt-get install --fix-broken
  exists markktext || die "Marktext installation failed!" 1
  if ! grep -q '^ii' <(dpkg -l markktext >/dev/null 2>&1); then
    printf "%s Marktext installation failed.\n" "$RED_ERROR" >&2
    EC="$E_INSTALLATION"
    return
	fi
  printf "Mark Text %s installed.\n" "$(marktext_version)"
}

remove_marktext() {
  sudo_login 2
  printf "Removing the Mark Text markdown editor...\n"
  sudo apt-get remove --purge marktext -yy
  [[ -L  ~/.config/marktext/preferences.json ]] && unlink  ~/.config/marktext/preferences.json
  find ~/.config -type d -name marktext -exec rm -rf {} \;
  printf "Mark Text markdown editor has been removed.\n"
}

marktext_config() {
  [[ "$EC" -ne 0 ]] && return
  printf "Applying MarkText preferences...\n"
	if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
		printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
    EC="$E_FILENOTFOUND"
		return
	fi
	[[ -d ~/.config/config_dir ]] || mkdir -p ~/.config/config_dir
  [[ -f ~/.config/marktext/preferences.json ]] && rm ~/.config//marktext/preferences.json
  [[ -d ~/gitea/configs ]] && ln -sv ~/gitea/configs/marktext/preferences.json ~/.config/marktext/preferences.json
  [[ -d ~/Downloads/configs ]] &&   ln -sv ~/Downloads/configs/marktext/preferences.json ~/.config/marktext/preferences.json
  printf "MarkText preferences applied.\n"
}

main() {
  local noOpt opt optstr new_ver OPTARG OPTIND
  check_package wget
  noOpt=1
  optstr=":hiru"
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        help 0
        ;;
      i )
        if exists marktext; then
          printf "Marktext %s is already installed.\n" "$(marktext_version)" >&2
        else
					tmp_file=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
					tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
          trap cleanup EXIT
          new_ver="$(newest_version)"
          printf "%sInstalling MarkText version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
          install_marktext "$new_ver"
          marktext_config
        fi
        ;;
      r )
        if exists marktext; then
          remove_marktext
        else
          printf "Marktext is not installed.\n" >&2
        fi
        ;;
      u )
        if exists marktext; then
					tmp_file=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
					tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
          trap cleanup EXIT
					printf "Marktext: Comparing current and newest versions...\n"
          new_ver="$(newest_version)"
          compare_versions "$new_ver"
        else
          printf "Marktext is not installed.\n" >&2
        fi
        ;;
      ? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$E_INVALID_ARG"
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit "$EC"
}

## Execution ##

main "$@"
