#!/usr/bin/env bash
##########################################################################
# Script Name  : iru-marktext
# Description  : Installs, updates, and removes the Mark Text markdown editor.
# Dependencies : gdebi, wget
# Arguments    : [-h] [-i] [-r] [-u] (See help function)
# Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 10 Jan 2022
# Updated      : 04 Jun 2025
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="4.13.25155"
readonly gh_url="https://github.com/marktext/marktext/releases"

## Functions ##

help() {
  local errcode updated
	errcode="${1:-2}"
	updated="04 Jun 2025"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs, configures, updates, removes the Mark Text markdown editor.

${green}Usage:${normal} $script [OPTION]

${orange}Available options:${normal}
  -c  Applies Marktext preferences.
  -h  Show this help message and exit.
  -i  Installs the Marktext markdown editor.
  -r  Removes the Marktext markdown editor from the system.
  -u  Updates the Marktext markdown editor to the latest version.
_HELP_
  exit "$errcode"
}

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
cleanup() {
  [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
}

check_dependencies() {
  local packages=( gdebi git wget )
  check_packages "${packages[@]}"
}

marktext_version() {
  dpkg -l marktext | awk '/ii/ {print $3}'
}

newest_version() {
  local new_ver
  wget -qO "$tmp_file" "$gh_url"
  new_ver=$(sed 's/\// /g' "$tmp_file" | grep -Ev 'beta|-rc' | awk '/download/ && /amd64.deb/ {print $7;exit}' | sed 's/^v//')
  echo "$new_ver"
}

compare_versions() {
  local cur_ver new_ver
  new_ver="$1"
  cur_ver=$(marktext_version)
  if [[ "$cur_ver" == "$new_ver" ]]; then
    printf "%sMarktext %s is the latest version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
  else
    printf "%sInstalled version of MarkText is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
    install_marktext "$new_ver"
  fi
}

install_marktext() {
  local new_ver new_pkg
  new_ver="$1"
  new_pkg="marktext-amd64.deb"
  printf "Downloading Mark Text markdown editor (v %s) from the marktext GitHub repository..." "$new_ver"
  dots "."
  wget -q -P "$tmp_dir/" "$gh_url/download/v$new_ver/$new_pkg"
  kill "$!";printf "done\n";tput cnorm
  sudo_login 2
  printf "Installing Mark Text %s...\n" "$new_ver"
	sudo dpkg -i "$tmp_dir/$new_pkg"; sudo apt-get install --fix-brokenq
  printf "Mark Text %s installed.\n" "$(marktext_version)"
}

remove_marktext() {
  local cfg_dir="$1"
  sudo_login 2
  printf "Removing the Mark Text markdown editor...\n"
  sudo apt-get remove --purge marktext -yy
  [[ -L "$cfg_dir/marktext/preferences.json" ]] && unlink "$cfg_dir/marktext/preferences.json"
  find "$HOME/".config -type d -name marktext -exec rm -rf {} \;
  printf "Mark Text markdown editor has been removed.\n"
}

marktext_config() {
  local repository cfg_dir
  cfg_dir="$1"
	repository=$(assign_cfg_repo)
  [[ -d "$cfg_dir" ]] || mkdir -p "$cfg_dir"
  printf "Applying MarkText preferences...\n"
  [[ -f "$cfg_dir/marktext/preferences.json" ]] && rm "$cfg_dir/marktext/preferences.json"
  ln -s "$repository/marktext/preferences.json" "$cfg_dir/marktext/preferences.json"
  printf "MarkText preferences applied.\n"
}

main() {
  local noOpt opt optstr new_ver cfg_dir
  check_dependencies
  cfg_dir="$HOME/.config/marktext"
  noOpt=1
  optstr=":chiru"
  while getopts "$optstr" opt; do
    case "$opt" in
      c )
        exists marktext || leave "Marktext is not installed."
        marktext_config "$cfg_dir"
      ;;
      h )
        help 0
      ;;
      i )
        exists marktext && leave "Marktext $(marktext_version) is already installed."
        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
        trap cleanup EXIT
        new_ver="$(newest_version)"
        printf "%sInstalling MarkText version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
        install_marktext "$new_ver"
        marktext_config "$cfg_dir"
      ;;
      r )
        exists marktext || leave "Marktext is not installed."
        remove_marktext "$cfg_dir"
      ;;
      u )
        exists marktext || leave "Marktext is not installed."
        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
        trap cleanup EXIT
        new_ver="$(newest_version)"
        [[ "$new_ver" ]] || die "No download available. Try again later." 1
        compare_versions "$new_ver"
      ;;
      ? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help 2
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
