#!/usr/bin/env bash
##########################################################################
# Script Name  : iru-bat
# Description  : Installs, updates, and removes the Bat utillity program.
# Dependencies : gdebi, wget git
# Arguments    : See the help function for details.
# Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 09 Jan 2022
# Updated      : 09 Feb 2026
# Comments     : Use install-batcat if distro version has same base version number as latest GitHub release.
#              : Mint 22 installs version 0.24.0 with the Ubuntu version appended.
#              : Debian 13 installs version 0.25.0 with the Debian version appended.
#              : LMDE 7 (stable) installs version 0.22.1-4.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 81
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="6.20.26040"
readonly gh_url="https://github.com/sharkdp/bat/releases"
DOTS_PID=
EC=0

## Functions ##

help() {
	local errcode="${1:-1}"
	local -r updated="04 Feb 2026"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs, updates, or removes the Bat utililty.

${green}Usage:${normal} $script [-hiru]
${orange}Available options:${normal}
  -h  Show this help message and exit
  -i  Installs the Bat utility.
  -r  Removes the Bat utility from the system.
  -u  Updates the Bat utility to the latest GitHub release.
_HELP_
  exit "$errcode"
}

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
cleanup() {
  [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
}

check_dependencies() {
  local packages=( git wget )
  check_packages "${packages[@]}"
}

bat_version() {
  awk '/^ii/ {print $3}' <(dpkg -l bat)
}

newest_version() {
  wget -qO "$tmp_file" "$gh_url"
  new_ver=$(grep -Ev 'beta|-rc' <(awk -F'/' '/download/ && /amd64.deb/ {print $6;exit}' "$tmp_file") | sed 's/^v//')
  echo "$new_ver"
}

compare_versions() {
  local new_ver="$1"
  local cur_ver
  cur_ver="$(bat_version)"
  if [[ -z "$new_ver" ]]; then
    printf "%s No download available. Try again later." "$RED_ERROR" >&2
    EC="$E_DOWNLOAD"
    return
  elif [[ ! "$new_ver" > "$cur_ver" ]]; then
    printf "%s Bat %s is the current version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
    return
  fi
  printf "%sInstalled version of Bat is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
  install_bat "$new_ver"
}

install_bat() {
  local cur_ver
  local new_ver="$1"
  local new_pkg="bat_${new_ver}_amd64.deb"
  if [[ -z "$new_ver" ]]; then
    printf "%s No download available. Try again later." "$RED_ERROR" >&2
    EC="$E_DOWNLOAD"
    return
  fi
  printf "Downloading Bat %s from the sharkdp GitHub repository..." "$new_ver"
  dots "." &
	DOTS_PID="$!"
  wget -q -P "$tmp_dir/" "$gh_url/download/v$new_ver/$new_pkg"
	kill_dots
  printf "Installing Bat %s...\n" "$new_ver"
  sudo_login 2
	sudo dpkg -i "$tmp_dir/$new_pkg"; sudo apt-get install --fix-broken
  cur_ver=$(bat_version)
  if ! grep -q '^ii' <(dpkg -l bat 2>/dev/null) || [[ "$cur_ver" != "$new_ver" ]]; then
    printf "%s Bat installation failed.\n" "$RED_ERROR" >&2
    EC="$E_INSTALLATION"
    return
  fi
  [[ -L ~/.local/bin/bat ]] && unlink ~/.local/bin/bat
  printf "Bat %s installed.\n" "$(bat_version)"
}

remove_bat() {
  sudo_login 2
  printf "Removing Bat %s...\n" "$(bat_version)"
  sudo dpkg --remove bat
  [[ -L ~/.config/bat/config ]] && unlink ~/.config/bat/config
  [[ -L ~/.local/bin/bat ]] && unlink ~/.local/bin/bat
  find ~/.config -type d -name bat -exec rm -rf {} \;
  printf "Bat and its configuration files have been removed.\n"
}

bat_config() {
  [[ "$EC" -ne 0 ]] && return
	[[ -d ~/.config/bat ]] || mkdir -p ~/.config/bat
	if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
		printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
    EC="$E_FILENOTFOUND"
		return
	fi
  printf "Applying Bat configuration...\n"
	[[ -f ~/.config/bat/config ]] && rm ~/.config/bat/config
  [[ -d ~/gitea/configs ]] && ln -sv ~/gitea/configs/bat/config ~/.config/bat/config
	[[ -d ~/Downloads/configs ]] && ln -sv ~/Downloads/configs/bat/config ~/.config/bat/config
  [[ -f /usr/bin/batcat ]] && ln -sv /usr/bin/batcat ~/.local/bin/bat
  printf "Bat %s configuration applied.\n" "$(bat_version)"
}

main() {
  local noOpt opt optstr new_ver OPTARG OPTIND
  noOpt=1
  optstr=":hiru"
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        help 0
        ;;
      i )
        if exists bat || exists batcat; then
          printf "Bat %s is already installed.\n" "$(bat_version)" >&2
        else
          check_dependencies
          tmp_file=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
          trap cleanup EXIT
					new_ver="$(newest_version)"
          printf "%sInstalling Bat version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
          install_bat "$new_ver"
          bat_config
        fi
        ;;
      r )
        if exist bat || exists batcat; then
          remove_bat
        else
          printf "Bat is not installed.\n" >&2
        fi
        ;;
      u )
        if exists bat || exists batcat; then
          check_dependencies
          tmp_file=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
          trap cleanup EXIT
					printf "Bat: Comparing current and newest versions...\n"
          new_ver="$(newest_version)"
          compare_versions "$new_ver"
        else
          printf "Bat is not installed.\n" >&2
        fi
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$E_INVALID_ARG"
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
  shift "$(( OPTIND - 1 ))"
	over_line "$script $version"
  exit "$EC"
}

## Execution ##

main "$@"
