#!/usr/bin/env bash
##########################################################################
# Script Name  : iru-fresh-editor
# Description  : Installs, updates, and removes the Fresh Editor.
# Dependencies : wget
# Arguments    : See the help function for details.
# Author       : Copyright (C) 2025, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 25 Dec 2025
# Updated      : 20 Jun 2026
# Comments     : Beginning with version 0.3.12, installs to /usr/bin/fresh
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify# it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or# (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of# MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib.bash
source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

help() {
  local -r script="$1"
  local -r version="$2"
	local -r errcode="${3:-1}"
	local -r updated="20 Jul 2026"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs, updates, or removes the Fresh Editor.

${green}Usage:${normal} $script [-hiru]
${orange}Available options:${normal}
  -h  Show this help message and exit
  -i  Installs the Fresh Editor.
  -r  Removes the Fresh Editor from the system.
  -u  Updates the Fresh Editor to the latest GitHub release.
_HELP_
  exit "$errcode"
}

# Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
# shellcheck disable=SC2317
cleanup() {
  [[ -d "$TMP_DIR" ]] && rm -rf "$TMP_DIR"
  [[ -f "$TMP_FILE" ]] && rm -f "$TMP_FILE"
}

fresh_version() {
  cut -d' ' -f2 < <(fresh --version)
}

convert_compare() {
  local newVer="$1"
  local curVer="$2"
  local newer="$FALSE"
	local new_arr=()
	local cur_arr=()
  local -i index
	IFS="." read -ra new_arr <<< "$newVer"
	IFS="." read -ra cur_arr <<< "$curVer"
	for (( index=0; index <=2; index++)) ; do
		if [[ "${new_arr[index]}" > "${cur_arr[index]}" ]]; then
      newer="$TRUE"
      break
    fi
	done
	return "$newer"
}

newest_version() {
  wget -qO "$TMP_FILE" "$gh_url"
  new_ver=$(sed 's/^v//' < <(awk -F'/' '/download/ && /x86/ {print $6;exit}' "$TMP_FILE"))
  echo "$new_ver"
  return 0
}

compare_versions() {
	local -r new_ver="$1"
  local -r gh_url="$2"
  local cur_ver
  cur_ver="$(fresh_version)"
  printf "Comparing current and newest versions...\n"
  if [[ -z "$new_ver" ]]; then
    printf "%s No download available. Try again later." "$RED_ERROR" >&2
    return "$E_DOWNLOAD"
  elif convert_compare "$new_ver" "$cur_ver"; then
    printf "%sInstalled version of Fresh-editor is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
    install_fresh "$new_ver" "$gh_url"
  else
    printf "%sFresh-editor %s is the current version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
  fi
  return 0
}

install_fresh() {
	local -r new_ver="$1"
	local -r gh_url="$2"
  local -r new_pkg="fresh-editor_${new_ver}-1_amd64.deb"
  if [[ -z "$new_ver" ]]; then
    printf "%s No download available. Try again later." "$RED_ERROR" >&2
    return "$E_DOWNLOAD"
  fi
  printf "Downloading Fresh-editor %s from the sinelaw GitHub repository..." "$new_ver"
  dots "." &
	DOTS_PID="$!"
  wget -q -P "$TMP_DIR/" "$gh_url/download/v$new_ver/$new_pkg"
	kill_dots
  printf "Installing Fresh-editor %s...\n" "$new_ver"
  sudo_login 2
	sudo dpkg -i "$TMP_DIR/$new_pkg"; sudo apt-get install --fix-broken
  if  [[ "$(fresh_version)" != "$new_ver" ]]; then
    printf "%s Fresh-editor installation failed.\n" "$RED_ERROR" >&2
    return "$E_INSTALLATION"
  fi
  printf "%sFresh-editor %s installed.%s\n" "$lightyellow" "$(fresh_version)" "$normal"
  return 0
}

remove_fresh() {
  sudo_login 2
  printf "Removing Fresh-editor %s...\n" "$(fresh_version)"
  sudo dpkg --remove fresh-editor
	find ~/ -maxdepth 3 -type d -path "$HOME/Downloads" -prune -o -path "$HOME/gitea" -prune -o -type d -name fresh -exec rm -rf {} \;
  find /usr/share -maxdepth 3 -type f,d -iname "fresh*" -exec rm -rf {} \;
  printf "Fresh-editor and its configuration files have been removed.\n"
  return 0
}

fresh_config() {
  local repository=~/Downloads/configs
  [[ -d ~/gitea/configs ]] && repository=~/gitea/configs
  if [[ ! -d "$repository" ]]; then
    printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
    return "$E_FILENOTFOUND"
  fi
	[[ -d ~/.config/fresh ]] || mkdir -p ~/.config/fresh
  printf "Applying Fresh-editor configuration...\n"
  cp -v "$repository/fresh/config.json" ~/.config/fresh/
  printf "Fresh-editor %s configuration applied.\n" "$(fresh_version)"
  return 0
}

main() {
  local -r script="${0##*/}"
  local -r version="2.8.26201"
	local -i exit_code=0
  local -r gh_url="https://github.com/sinelaw/fresh/releases"
  local opt new_ver OPTARG OPTIND
  local -i noOpt=1
  local -r optstr=":hiru"
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        help "$script" "$version" 0
        ;;
      i )
        if installed fresh-editor; then
          printf "Fresh-editor %s is already installed.\n" "$(fresh_version)" >&2
        else
          check_package wget
          TMP_FILE=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
          TMP_DIR=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
          trap cleanup EXIT
					new_ver="$(newest_version)"
          printf "%sInstalling Bat version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
          install_fresh "$new_ver" "$gh_url" && fresh_config
        fi
        ;;
      r )
        if installed fresh-editor; then
          remove_fresh
        else
          printf "Fresh-editor is not installed.\n" >&2
        fi
        ;;
      u )
        if installed fresh-editor; then
          check_package wget
          TMP_FILE=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
          TMP_DIR=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
          trap cleanup EXIT
          new_ver="$(newest_version)"
          compare_versions "$new_ver"
        else
          printf "Fresh-editor is not installed.\n" >&2
        fi
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$script" "$version" "$E_INVALID_ARG"
    esac
		exit_code="$?"
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
  shift "$(( OPTIND - 1 ))"
	over_line "$script $version"
  exit "$exit_code"
}

## Execution ##

main "$@"
