#!/usr/bin/env bash
##########################################################################
# Script Name  : iru-marktext
# Description  : Installs, updates, and removes the Mark Text markdown editor.
# Dependencies : gdebi, wget
# Arguments    : [-h] [-i] [-r] [-u] (See help function)
# Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 10 Jan 2022
# Updated      : 24 Aug 2024
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="4.5.24237"
readonly _updated="24 Aug  2024"
readonly gh_url="https://github.com/marktext/marktext/releases"
readonly cfg_dir="$HOME/.config/marktext"

## Functions ##

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
cleanup() {
  [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
}

check_dependencies() {
  local packages=( gdebi wget )
  check_packages "${packages[@]}"
}

marktext_version() {
  dpkg -l marktext | awk '/ii/ {print $3}'
}

newest_version() {
  wget -qO "$tmp_file" "$gh_url"
  new_ver=$(sed 's/\// /g' "$tmp_file" | grep -Ev 'beta|-rc' | awk '/download/ && /amd64.deb/ {print $7;exit}' | sed 's/^v//')
  echo "$new_ver"
}

compare_versions() {
  local cur_ver
  cur_ver=$(marktext_version)
  if [[ "$cur_ver" == "$new_ver" ]]; then
    echo "${lightyellow}Marktext $cur_ver is the current version. No update required.${normal}"
  else
    echo "${lightyellow}Installed version of MarkText is $cur_ver, updating to $new_ver...${normal}"
    install_marktext
  fi
}

install_marktext() {
  local new_pkg="marktext-amd64.deb"
  printf "Downloading Mark Text markdown editor (v %s) from the marktext GitHub repository..." "$new_ver"
  dots "."
  wget -q -P "$tmp_dir/" "$gh_url/download/v$new_ver/$new_pkg"
  kill "$!";printf "done\n";tput cnorm
  printf "Installing Mark Text %s...\n" "$new_ver"
  sudo gdebi -n "$tmp_dir/$new_pkg"
  dl_preferences
  printf "Mark Text %s installed.\n" "$(marktext_version)"
}

remove_marktext() {
  local cfg_bu_dir="$HOME/.config/backup/marktext"
  echo "Removing the Mark Text markdown editor..."
  sudo apt-get remove --purge marktext -yy
  [[ -d "$cfg_dir" ]] && rm -rf "$cfg_dir"
  [[ -d "$cfg_bu_dir" ]] && rm -rf "$cfg_bu_dir"
  echo "Mark Text markdown editor has been removed."
}

dl_preferences() {
  local json_file localip repository
  localip=$(local_ip)
  json_file="preferences.json"
  [[ -d "$cfg_dir" ]] && mkdir -p "$cfg_dir"
  printf "Applying MarkText preferences...\n"
  if [[ "$localip" == "16" ]]; then
    repository="HOME/gitea/configs/marktext"
    cp -v "$repository/$json_file" "$cfg_dir/"
  else
    repository="configs/raw/branch/main/marktext"
    curl -so "$cfg_dir/$json_file" "$Gitea_URL/$repository/$json_file"
  fi
  printf "MarkText %s applied.\n" "$json_file"
}

help() {
  local errcode="${1:-2}"
  cat << END_HELP
${orange}$_script${normal} $_version ($_updated)
Installs, configures, updates, removes the Mark Text markdown editor.

${green}Usage:${normal} $_script [OPTION]

${orange}Available options:${normal}
  -c  Applies Marktext preferences.
  -h  Displays help.
  -i  Installs the Marktext markdown editor.
  -r  Removes the Marktext markdown editor from the system.
  -u  Updates the Marktext markdown editor to the latest version.
END_HELP
  exit "$errcode"
}

## Execution ##

noOpt=1
optstr=":chiru"
while getopts "$optstr" opt; do
  case "$opt" in
    c )
      exists marktext || leave "Marktext is not installed."
      dl_preferences
    ;;
    h )
      help 0
    ;;
    i )
      exists marktext && leave "Marktext $(marktext_version) is already installed."
      tmp_file=$(mktemp) || die "Failed to create temporary file." 1
      tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
      trap cleanup EXIT
      sudo_login 2
      check_dependencies
      new_ver="$(newest_version)"
      echo "${lightyellow}Installing MarkText version $new_ver...${normal}"
      install_marktext
    ;;
    r )
      exists marktext || leave "Marktext is not installed."
      sudo_login 2
      remove_marktext
    ;;
    u )
      exists marktext || leave "Marktext is not installed."
      tmp_file=$(mktemp) || die "Failed to create temporary file." 1
      tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
      trap cleanup EXIT
      sudo_login 2
      check_dependencies
      new_ver="$(newest_version)"
      [[ "$new_ver" ]] || die "No download available. Try again later." 1
      compare_versions
    ;;
    ? )
      echo "$red_error Invalid option -${OPTARG}" >&2
      help 2
  esac
	noOpt=0
done
[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
shift "$(( OPTIND - 1 ))"
box "$_script v$_version"
exit
