#!/usr/bin/env bash
##########################################################################
# Script Name  : iru-vscodium
# Description  : Install, update, remove VSCodium editor.
# Dependencies : wget
# Arguments    : [-hiru] (See help function)
# Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 16 Jul 2022
# Updated      : 08 Jan 2026
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="3.3.26008"
readonly gh_url="https://github.com/VSCodium/vscodium/releases"
DOTS_PID=

## Functions ##

help() {
  local errcode updated
	errcode="${1:-2}"
	updated="08 Jan 2026"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs, configures, updates,  removes the VSCodium editor.

${green}Usage:${normal} $script [-hiru]
${orange}Available options:${normal}
  -h  Show this help message and exit.
  -i  Installs the VSCodium editor.
  -r  Removes the VSCodium editor from the system.
  -u  Updates the VSCodium editor to the latest GitHub release.
_HELP_
  exit "$errcode"
}

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
cleanup() {
  [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
}

codium_version() {
	awk '/^ii/ {print $3}' <(dpkg -l  codium)
}

newest_version() {
  local new_ver
  wget -qO "$tmp_file" "$gh_url"
  new_ver=$(awk -F'/' '/download/ && /amd64.deb/ {print $8;exit}' "$tmp_file" | grep -Ev 'beta|-rc' | sed 's/^v//')
  echo "$new_ver"
}

compare_versions() {
  local new_ver="$1"
  local cur_ver
  cur_ver=$(dpkg -l codium 2>/dev/null | awk '/ii/ {print $3}' | sed 's/[~+-].*//')
  if [[ -z "$new_ver" ]]; then
    printf "No download available. Try again later.\n" >&2
    return
  elif [[ ! "$new_ver" > "$cur_ver" ]]; then
    printf "%sVSCodium %s is the latest version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
    return
  fi
  printf "%sInstalled version of VSCodium is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
  install_vscodium "$new_ver"
}

install_vscodium() {
  local new_ver="$1"
  local new_pkg="codium_${new_ver}_amd64.deb"
  [[ -z "$new_ver" ]] && die "No download available. Try again later." 1
  printf "Downloading VSCodium %s from the VSCodium GitHub repository..." "$new_ver"
  dots "." &
  DOTS_PID="$!"
  wget -q -P "$tmp_dir/" "$gh_url/download/$new_ver/$new_pkg"
  kill_dots
  printf "Installing VSCodium %s...\n" "$new_ver"
  sudo_login 2
	sudo dpkg -i "$tmp_dir/$new_pkg"; sudo apt-get install --fix-broken
  exists codium || die "VSCodium installation failed!" 1
  printf "VSCodium %s successfully installed.\n" "$(codium_version)"
}

remove_vscodium() {
  sudo_login 2
  printf "Removing the VSCodium editor...\n"
  sudo dpkg --remove codium
  [[ -L ~/.config/VSCodium/User/settings.json ]] && unlink ~/.config/VSCodium/User/settings.json
  find ~/.config -maxdepth 2 -type d -name VSCodium -exec rm -rf {} \;
  printf "VSCodium editor has been removed.\n"
}

apply_settings() {
  printf "Applying VSCodium settings...\n"
  [[ -d ~/.config/VSCodium/User ]] && mkdir -p ~/.config/VSCodium/User
	if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
		printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
		return
	fi
  [[ -f ~/.config/VSCodium/User/settings.json ]] && rm ~/.config/VSCodium/User/settings.json
	[[ -d ~/gitea/configs ]] && ln -sv ~/gitea/configs/VSCodium/User/settings.json ~/.configVSCodium/User/settings.json
	[[ -d ~/Downloads/configs ]] && ln -sv ~/Downloads/configs/VSCodium/User/settings.json ~/.configVSCodium/User/settings.json
  printf "VSCodium settings applied.\n"
}

main() {
  local noOpt opt optstr new_ver OPTARG OPTIND
  noOpt=1
  optstr=":hiru"
  while getopts "$optstr" opt; do
	  case "$opt" in
		  h )
			  help 0
        ;;
		  i )
        if exists codium; then
          printf "VSCodium %s is already installed.\n" "$(codium_version)" >&2
        else
          tmp_file=$(mktemp) || die "Failed to create temporary file." 1
			    tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
			    trap cleanup EXIT
			    new_ver="$(newest_version)"
          printf "%sInstalling VSCodium %s...%s\n" "$lightyellow" "$new_ver" "$normal"
			    install_vscodium "$new_ver"
          apply_settings
        fi
        ;;
		  r )
        if exists codium; then
          remove_vscodium
        else
          printf "VSCodium is not installed.\n" >&2
        fi
        ;;
		  u )
        if exists codium; then
			    tmp_file=$(mktemp -q) || die "Failed to create temporary file." 1
			    tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
			    trap cleanup EXIT
			    new_ver="$(newest_version)"
			    compare_versions "$new_ver"
        else
          printf "VSCodium is not installed.\n" >&2
        fi
        ;;
		  ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
			  help 2
	  esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
