#!/usr/bin/env bash
##########################################################################
# Script Name  : iru-micro
# Description  : Installs, updates, and removes the Micro CLI text editor.
# Dependencies : curl wget
# Arguments    : [-b] [-h] [-i] [-r] [-s] [-u] (See help function)
# Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 10 Jan 2022
# Updated      : 03 Feb 2025
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

## Global Variables ##

script=$(basename "$0"); readonly script
readonly version="6.5.25034"
readonly gh_url="https://github.com/zyedidia/micro/releases"
readonly cfg_d="$HOME/.config/micro"

## Functions ##

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
cleanup() {
  [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
}

check_dependencies() {
  local packages=( git wget )
  check_packages "${packages[@]}"
}

assign_repo() {
	local localip repo
	localip=$(local_ip)
	repo="$HOME/Downloads/configs"
	case "$localip" in
		10|16|22 )
			repo="$HOME/gitea/configs" ;;
		* )
			[[ -d "$repo" ]] || git clone --quiet "$GITEA_URL/configs.git" "$repo"
	esac
	echo "$repo"
}

check_distro() {
  local codename
  codename=$(lsb_release -c -s)
  case "$codename" in
    bullseye ) return "$FALSE" ;;
    * ) return "$TRUE"
  esac
}

micro_version() {
  micro -version | awk '/Version/ {print $NF}'
}

newest_version() {
  wget -qO "$tmp_file" "$gh_url"
  if check_distro; then
    new_ver=$(sed 's/\// /g' "$tmp_file" | grep -Ev 'beta|-rc' | awk '/download/ && /linux/ {print $7;exit}' | sed 's/^v//')
  else
    new_ver="2.0.13"
  fi
  echo "$new_ver"
}

compare_versions() {
  local cur_ver
  cur_ver=$(micro_version)
  if [[ "$cur_ver" == "$new_ver" ]]; then
    printf "%sMicro %s is the current version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
    check_distro || printf "Bat %s is the latest version compatible with %s.\n" "$new_ver" "$(get_distribution)"
  else
    printf "%sInstalled version of Micro is %s, updating to %s...\n" "$lightyellow" "$cur_ver" "$normal"
    check_distro || printf "Bat %s is the latest version compatible with %s.\n" "$new_ver" "$(get_distribution)"
    install_micro
  fi
}

install_micro() {
  local new_pkg="micro-${new_ver}-linux64.tar.gz"
  printf "Downloading Micro %s from the zyedidia GitHub repository..." "$new_ver"
  dots "."
  wget -q -P "$tmp_dir/" "$gh_url/download/v$new_ver/$new_pkg"
  kill "$!";printf "done\n";tput cnorm
  printf "Installing Micro %s...\n" "$new_ver"
  tar -xzvf "$tmp_dir/$new_pkg" -C "$tmp_dir/"
  sudo cp -v "$tmp_dir/micro-$new_ver"/micro /usr/bin/
  sudo cp -v "$tmp_dir/micro-$new_ver"/micro.1 /usr/share/man/man1/
  check_package xclip
  printf "Micro %s installed.\n" "$(micro_version)"
}

remove_micro() {
  local cur_ver cfg_bu_d
  cur_ver=$(micro_version)
  cfg_bu_d="$HOME/.config/backup/micro"
  printf "Removing the Micro CLI text editor...\n"
  sudo dpkg --remove micro
  [[ -d "$cfg_d" ]] && rm -rf "$cfg_d"
  [[ -d "$cfg_bu_d" ]] && rm -rf "$cfg_bu_d"
  [[ -d /root/.config/micro ]] && sudo rm -rf /root/.config/micro
  printf "Micro %s and configuration files have been removed.\n" "$cur_ver"
}

apply_settings() {
  local json_file localip repository
	repository=$(assign_repo)
  json_file="settings.json"
  [[ -d "$cfg_d" ]] || mkdir -p "$cfg_d"
  printf "Applying Micro settings...\n"
  cp -v "$repository//micro/$json_file" "$cfg_d/"
  printf "Micro setttings applied.\n"
}

apply_bindings() {
  local json_file localip repository
	repository=$(assign_repo)
  json_file="bindings.json"
  [[ -d "$cfg_d" ]] || mkdir -p "$cfg_d"
  printf "Applying Micro keybindings...\n"
  cp -v "$repository/micro/$json_file" "$cfg_d/"
  printf "Micro keybindings applied.\n"
}

help() {
  local errcode updated
	errcode="${1:-2}"
	updated="03 Feb 2025"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs, configures, updates, or removes the Micro CLI text editor.

${green}Usage:${normal} $script [OPTION]

${orange}Available options:${normal}
  -b  Installs/updates the Micro key-bindings json file.
  -h  Displays help.
  -i  Installs the Micro CLI text editor.
  -r  Removes the Micro CLI text editor from the system.
  -s  Installs/updates the Micro settings json file.
  -u  Updates the Micro CLI text editor to the latest version.
_HELP_
  exit "$errcode"
}

main() {
  local noOpt opt optstr new_ver repository
  check_dependencies
	repository=$(assign_repo)
  noOpt=1
  optstr=":bhirsu"
  while getopts "$optstr" opt; do
    case "$opt" in
      b )
        exists micro || leave "Micro is not installed."
        apply_bindings
      ;;
      h )
        help 0
      ;;
      i )
        exists micro && leave "Micro $(micro_version) is already installed."
        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
        trap cleanup EXIT
        sudo_login 2
        new_ver="$(newest_version)"
        printf "%sInstalling Micro version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
        install_micro
        apply_settings
        apply_bindings
      ;;
      r )
        exists micro || leave "Micro is not installed."
        sudo_login 2
        remove_micro
      ;;
      s )
        exists micro || leave "Micro is not installed."
        apply_settings
      ;;
      u )
        exists micro || leave "Micro is not installed."
        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
        trap cleanup EXIT
        sudo_login 2
        new_ver="$(newest_version)"
        [[ "$new_ver" ]] || die "No download available. Try again later." 1
        compare_versions
      ;;
      ? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help 2
    esac
    noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script v$version"
  exit
}

## Execution ##

main "$@"
