#!/usr/bin/env bash
##########################################################################
# Script Name  : iru-fastfetch
# Description  : Install/udadate/remove FastFetch
# Dependencies : gdebi, wget
# Arguments    : See help() function
# Author       : Copyright © 2024 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 02 May 2024
# Last updated : 04 Feb 2026
# Comments     : .png logo does not work with Terminator.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 81
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="3.15.26035"
readonly gh_url="https://github.com/fastfetch-cli/fastfetch/releases"
DOTS_PID=
EC=0

## Functions ##

help() {
	local errcode="${1:-1}"
	local -r updated="04 Feb 2026"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs, configures, removes, updates FastFetch

${green}Usage:${normal} $script [-hiru]
${orange}Available options:${normal}
  -h  Show this help message and exit
  -i  Install Fastfetch
  -r  Remove Fastfetch
  -u  Update Fastfetch to the latest GitHub release
_HELP_
  exit "$errcode"
}

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
cleanup() {
	[[ -f "$tmp_file" ]] && rm "$tmp_file"
	[[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
}

ff_version() {
	fastfetch --version-raw
}

newest_version() {
	local new_ver
  wget -qO "$tmp_file" "$gh_url"
  new_ver=$(awk -F'/' '/download/ && /.deb/ {print $6}' "$tmp_file")
  echo "$new_ver"
}

compare_versions() {
	local new_ver="$1"
	local cur_ver
  cur_ver="$(ff_version)"
  if [[ -z "$new_ver" ]]; then
    printf "%s No download available. Try again later." "$RED_ERROR" >&2
    EC="$E_DOWNLOAD"
    return
  elif [[ ! "$new_ver" > "$cur_ver" ]]; then
		printf "%sFastFetch %s is the lastest version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
		return
	fi
	printf "%sThe installed version of FastFetch is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
	install_fastfetch "$new_ver"
}

install_fastfetch(){
	local new_ver="$1"
  local -r new_pkg="fastfetch-linux-amd64.deb"
  if [[ -z "$new_ver" ]]; then
    printf "%s No download available. Try again later." "$RED_ERROR" >&2
    EC="$E_DOWNLOAD"
    return
  fi
	sudo_login 2
  printf "Downloading FastFetch %s from the fastfetch-cli GitHub repository..." "$new_ver"
  dots "." &
	DOTS_PID="$!"
  wget -q -P "$tmp_dir/" "$gh_url/download/$new_ver/$new_pkg"
	kill_dots
  printf "Installing FastFetch %s...\n" "$new_ver"
  if ! grep -q '^ii' <(dpkg -l fastfetch >/dev/null 2>&1); then
    printf "%s Fastfetch installation failed.\n" "$RED_ERROR" >&2
    EC="$E_INSTALLATION"
    return
	fi
  printf "%sFastFetch %s installed.%s\n" "$lightyellow" "$(ff_version)" "$normal"
}

remove_fastfetch() {
	sudo_login 2
	printf "Removing FastFetch %s ...\n" "$(ff_version)"
	sudo dpkg --purge fastfetch
	find ~/ -maxdepth 3 -type d -path "$HOME/Downloads" -prune -o -path "$HOME/gitea" -prune -o -type d -name fastfetch -exec rm -rf {} \;
	printf "Fastfetch and its configuration files have been removed.\n"
}

fastfetch_config() {
  [[ "$EC" -ne 0 ]] && return
	local repository=~/Downloads/ccnfigs/fastfetch
	[[ -d ~/gitea/configs/fastfetch ]] && repository=~/gitea/configs/fastfetch
	if [[ ! -d "$repository" ]]; then
    printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
    EC="$E_FILENOTFOUND"
		return
  fi
	[[ -d ~/.config/fastfetch ]] || mkdir -p ~/.config/fastfetch
	[[ -d ~/.local/share/fastfetch/logos ]] || mkdir -p ~/.local/share/fastfetch/logos
	printf "Installing configuration and logo files...\n"
	if grep -q -E 'GM965|GL960' <(lspci); then
		cp -v "$repository"/config.jsonc.ascii ~/.config/fastfetch/config.jsonc
		cp -v /logo.txt ~/.local/share/fastfetch/logos/
	else
		cp -v "$repository"/config.jsonc ~/.config/fastfetch/
		cp -v ~"$repository"/logo.png ~/.local/share/fastfetch/logos/
	fi
	grep -qw gigi <(lsb_release -cs) && sed -i '/type/s/kitty-direct/kitty/' ~/.config/fastfetch/config.jsonc
	printf "Fastfetch configuration applied.\n"
}

main() {
  local noOpt opt optstr new_ver OPTARG OPTIND
	noOpt=1
	optstr=":hiru"
	while getopts "$optstr" opt; do
		case "$opt" in
			h )
				help 0
				;;
			i )
				if exists fastfetch; then
					printf "Fastfetch %s is already installed.\n" "$(ff_version)" >&2
				else
					check_package wget
					tmp_file=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
					tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
					trap cleanup EXIT
					new_ver="$(newest_version)"
					printf "%sInstalling Fastfetch version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
					install_fastfetch "$new_ver"
					fastfetch_config
				fi
				;;
			r )
				if exists fastfetch; then
					remove_fastfetch
				else
					printf "Fastfetch is not installed.\n" >&2
				fi
				;;
			u )
				if exists fastfetch; then
					check_package wget
					tmp_file=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
					trap cleanup EXIT
					printf "FastFetch: Comparing current and newest versions...\n"
					new_ver="$(newest_version)"
					compare_versions "$new_ver"
				else
					printf "Fastfetch is not installed.\n" >&2
				fi
				;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help "$E_INVALID_ARG"
		esac
		noOpt=0
	done
	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
	shift "$(( OPTIND - 1 ))"
	over_line "$script $version"
	exit "$EC"
}

## Execution ##

main "$@"
