#!/usr/bin/env bash
###############################################################################
# Script Name  : pwfin2main
# Description  : Synchronizes password database files with main PC
# Dependencies : scp (openssh-server)
# Arguments    : none
# Author       : Copyright (C) 2022 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 04 Mar 2022
# Updated      : 28 Jul 2026
# Version      : 6.3.26210
# Comments     : Not to be run from hp-800g2-sff (ip 10)
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

# shellcheck source=/home/rick/bin/functionlib.bash
source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

check_host() {
  local -r script="$1"
  local -r mhost="$2"
  local -r lhost="${HOSTNAME:-$(hostname)}"
  if [[ "$lhost" == "$mhost" ]]; then
    printf "%s cannot be run from %s\n" "$script" "$mhost" >&2
    return "$E_INVALID_HOST"
  fi
  return 0
}

copy_passwords() {
  local -r mhost="$1"
  local -r mhostip="10"
  local -r kdbx_d="$HOME/Documents"
  printf "Making a backup of Passwords.kdbx on %s\n" "$mhost"
  ssh rick@"$LOCALNET.$mhostip" cp -pv "$kdbx_d/Passwords.kdbx" "$kdbx_d/Passwords.$(date '+%y%m%d').kdbx"
  printf "Copying updated KeepassXC databases to %s\n" "$mhost"
  scp -p "$kdbx_d/Passwords.kdbx" "$kdbx_d/Passwords.old.kdbx" "$kdbx_d/Tina-passwords.kdbx"  rick@"$LOCALNET.$mhostip":Documents/
  return "$?"
}

main() {
  local -r script="${0##*/}"
  local -r version="6.3.26210"
  local -r mhost="hp-800g2-sff"
  local -i exit_code=0
  check_host "$script" "$mhost" && copy_passwords "$mhost"
  exit_code="$?"
  over_line "$script $version" "-"
  exit "$exit_code"
}

main "$@"
