#!/usr/bin/env bash
##########################################################################
# Script Name  : pwfin2main
# Description  : Synchronizes password database files with main PC
# Dependencies : scp (openssh-server)
# Arguments    : none
# Author       : Copyright (C) 2022 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 04 Mar 2022
# Updated      : 14 May 2024
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="4.10.24135"
readonly lhost="${HOSTNAME:-$(hostname)}"
readonly kdbx_d="$HOME/Documents"
readonly mhost="hp-800g2-sff"
readonly mhostip="10"

## Execution ##

box "$_script v$_version" "*"
# Ensure script is not being run from HP-800-G2-SFF (10)
[[ "$lhost" == "$mhost" ]] && leave "$_script cannot be run from $mhost."
printf "Making a backup of Passwords.kdbx on %s\n" "$mhost"
ssh rick@"$localnet.$mhostip" cp -pv "$kdbx_d/Passwords.kdbx" "$kdbx_d/Passwords.$(date '+%y%m%d').kdbx"
printf "Copying updated KeepassXC databases to %s\n" "$mhost"
scp -p "$kdbx_d/Passwords.kdbx" "$kdbx_d/Passwords.old.kdbx" "$kdbx_d/Tina-passwords.kdbx"  rick@"$localnet.$mhostip":Documents/
printf "MOTD: "
leave ""
