#!/usr/bin/env bash
#####################################################################
# Script Name  : laptop-utils
# Description  : Installs laptop utilities
# Dependencies : None
# Args         : None
# Author       : Richard Romig
# Email        : rick.romig@gmail.com
# Comments     : Based on a script by Joe Collins at EzeeLinux.com
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Funtions ##

main() {
  _script=$(basename "$0")
  local _version="v1.4.1"
  local _updated="16 Jan 2023"

  printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
  printf "\U1F4BB Installs laptop specific utilities:\n"
  printf " * Thermald - monitors and controls temperature.\n"
  printf " * ACPI - utility to check the state of ACPI devices.\n"
  printf " * TLP - advanced power management to maximize battery life.\n"
  printf " * Touchpad Indicator - utility to enable/disable the touchpad.\n\n"

  is_laptop || leave "System is not a laptop. The utilities were not installed."

  install_thermald
  install_acpi
  install_tlp
  install_touchpad_indicator
  util_status
}

installed() {
  local package="$1"
  dpkg -l | grep -qw "$package" && return "$TRUE" || return "$FALSE"
}

install_thermald() {
  if installed thermald; then
    printf "Thermald is already installed.\n"
  elif in_repos thermald; then
    user_in_sudo
    sudo apt-get install thermald -yy
    exists thermald && printf "Thermald installed.\n"
  else
    printf "Thermald is not installed.\n"
  fi
}

install_acpi() {
  if installed acpi; then
    printf "ACPI is already installed.\n"
  elif in_repos acpi; then
    user_in_sudo
    sudo apt-get install acpi -yy
    exists acpi && printf "ACPI installed.\n"
  else
    printf "ACPI is not installed.\n"
  fi
}

install_tlp() {
  if installed tlp; then
    echo "TLP is already installed."
  elif in_repos tlp; then
    user_in_sudo
    sudo apt-get install tlp tlp-rdw -yy
    tlp_service
    printf "TLP installed.\n"
  else
    printf "TLP is not installed.\n"
  fi
}

install_touchpad_indicator() {
  if installed touchpad-indicator; then
    printf "Touchpad Indicator is already installed.\n"
   elif in_repos touchpad-indicator; then
    user_in_sudo
    sudo apt-get install touchpad-indicator -yy
    printf "Touchpad Indicator installed.\n"
  else
    printf "Touchpad Indicator is not available.\n"
  fi
}

tlp_service() {
  if is_systemd; then
    user_in_sudo
    sudo systemctl enable tlp.service
    sudo systemctl start tlp.service
    sudo systemctl mask systemd-rfkill.service
    sudo systemctl mask systemd-rfkill.socket
    printf "TLP service enabled and started.\n"
  elif is_sysv; then
    user_in_sudo
    start tlp start
    printf "TLP service started.\n"
  else
    printf "Init system is not systemd or SysV.\n"
    printf "Manually start the TLP service.\n"
  fi
}

util_status() {
  printf "\nInstalled utilities:\n"
  installed thermald && printf "\tThermald\n"
  installed acpi && printf "\tACPI\n"
  installed tlp && printf "\tTLP\n"
  installed touchpad-indicator && printf "\tTouchpad Indicator\n"
}

## Execution ##

main
exit
