#!/usr/bin/env bash
##########################################################################
# Script Name  : laptoplid
# Description  : Settings to close laptop lid without suspend
# Dependencies : ~.bin/files/laptoplid.sed
# Arguments    : None
# Author       : Copyright (C) 2020, Richard B. Romig, 22 Oct 2020
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 22 Oct 2020
# Updated      : 27 May 2024
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="3.3.24148"
readonly logind_conf="/etc/systemd/logind.conf"
readonly sed_file="$HOME/bin/files/laptoplid.sed"

## Execution ##

clear
printf "%s v%s" "$_script" "$_version"
printf "Allows a laptop lid to be closed without going into suspend mode.\n\n"
is_laptop || leave "This system is not a laptop. $logind_conf was not modified."
[[ -f "$sed_file" ]] || die "A required file ($(basename "$sed_file")) was not found." 1
sudo_login 2
sudo sed -i.bak -f "$sed_file" "$logind_conf"
sudo systemctl restart systemd-logind.service
leave "$logind_conf modified. Backup (${logind_conf}.bak) created."
