#!/usr/bin/env bash
#############################################################################
# Script Name  : local-ip-up
# Description  : Scans local network to see which addresses are active.
# Dependencies : iputils-arping, avahi-daemon, avahi-utils, libnss-mdns
# Arguments    : none
# Author       : Richard B. Romig, 01 Dec 2019
# Email        : rick.romig@gmail.com
# Created      : 01 Dec 2019
# Updated      : 28 Jun 2025
# Comments     : Variables for IP range do not work, must be hard coded.
#              : Local host will not respond to arping.
#              : Local host will respond using arping in iputils-arping.
#              : Installing arping will uninstall iputils-arping & sudo required.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
#############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="4.9.25179"
SECONDS=0
COUNT=0

## Functions ##

help() {
	local errcode="${1:-2}"
	local updated="28 Jun 2025"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Scans local network to see which addresses are active.

${green}Usage:${normal} $script [-a] [-d] [-h] [-s]
${orange}Available options:${normal}
  -a  Scan entire network.
  -d  Scan DHCP assigned addresses.
  -h  Show this help message and exit.
  -s  Scan static addresses.
  ${orange}Note:${normal} Uses iputils-arping.
_HELP_
  exit "$errcode"
}

check_dependencies() {
  local packages=( avahi-daemon avahi-utils libnss-mdns iputils-arping )
  check_packages "${packages[@]}"
}

arping_check() {
  local addr="$1"
  arping -c 1 "$addr" | grep -E "0 response|0 packets received" > /dev/null 2>&1 && return 1 || return 0
}

scan_static_addresses() {
  local hname ip_addr
  for ip_addr in $LOCALNET.{1..25}; do
    if arping_check "$ip_addr"; then
      hname=$(avahi-resolve -a "$ip_addr" 2>/dev/null | awk '{print $NF}' | sed 's/\.local$//')
      printf "%s" "$ip_addr"
      if [[ -n "$hname" ]]; then
        printf "\t%s\n" "$hname"
      else
        case $ip_addr in
          "192.168.0.1" ) printf "\tGateway (TP Link AC1750)\n" ;;
          "192.168.0.2" ) printf "\tD-Link AP\n" ;;
          "192.168.0.3" ) printf "\tunassigned ip\n" ;;
          "192.168.0.4" ) printf "\tNASD97167 (QNAP NAS)\n" ;;
          "192.168.0.5" ) printf "\tunassigned ip\n" ;;
          "192.168.0.6" ) printf "\tRaspberry Pi 4\n" ;;
          "192.168.0.7" ) printf "\tunassigned ip\n" ;;
          "192.168.0.8" ) printf "\tunassigned ip\n" ;;
          "192.168.0.9" ) printf "\tunassigned ip\n" ;;
          "192.168.0.10" ) printf "\thp-800g2-sff (Main PC)\n" ;;
          "192.168.0.11" ) printf "\thp-6005 (Server)\n" ;;
          "192.168.0.12" ) printf "\te6500-deb (Dell laptop)\n" ;;
          "192.168.0.13" ) printf "\tprobook-6570b (HP laptop)\n" ;;
          "192.168.0.14" ) printf "\thp-8300 (Network test)\n" ;;
          "192.168.0.15" ) printf "\tlenovo-m91p (Lenovo PC)\n" ;;
          "192.168.0.16" ) printf "\thp-8300-usdt (Gitea Server)\n" ;;
          "192.168.0.17" ) printf "\thp-800-g1-usdt (Media PC)\n" ;;
          "192.168.0.18" ) printf "\tunassigned ip\n" ;;
          "192.168.0.19" ) printf "\thp-800-g1-dm (Desktop Mini)\n" ;;
          "192.168.0.20" ) printf "\tprobook-6570\n" ;;
          "192.168.0.21" ) printf "\thp-probook-6570 (Finance)\n" ;;
          "192.168.0.22" ) printf "\thp-850-g3 (i3)\n" ;;
          "192.168.0.23" ) printf "\thp-2560p (i3)\n" ;;
          "192.168.0.24" ) printf "\te-475m (Gateway laptop)\n" ;;
          "192.168.0.25" ) printf "\tunassigned ip\n" ;;
          * )
            printf "\tUnknown host\n"
        esac
      fi
      (( COUNT++ ))
    fi
  done
}

scan_dhcp_addresses() {
  local hname ip_addr
  for ip_addr in $LOCALNET.{100..250}; do
    if arping_check "$ip_addr"; then
      hname=$(avahi-resolve -a "$ip_addr" 2>/dev/null | awk '{print $NF}' | sed 's/\.local$//')
      printf "%s" "$ip_addr"
      if [[ -n "$hname" ]]; then
        printf "\t%s\n" "$hname"
      else
        printf "\tUnknown host\n"
      fi
      (( COUNT++ ))
    fi
  done
}

main() {
  local noOpt opt optstr
  noOpt=1
  optstr=":adhs"
  while getopts "$optstr" opt; do
    case "$opt" in
      a )
        check_dependencies
        tput civis
        echo $'\n'$"Scanning  the network ..."
        echo -e "${underline}${green}IP Address\tHostname${normal}"
        scan_static_addresses
        scan_dhcp_addresses
        tput cnorm
        ;;
      d )
        check_dependencies
        tput civis
        echo $'\n'$"Scanning DHCP addresses on the network ..."
        echo -e "${underline}${green}IP Address\tHostname${normal}"
        scan_dhcp_addresses
        tput cnorm
        ;;
      h )
        help 0
        ;;
      s )
        check_dependencies
        tput civis
        echo $'\n'$"Scanning static IP addresses on the network ..."
        echo -e "${underline}${green}IP Address\tHostname${normal}"
        scan_static_addresses
        tput cnorm
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help 2
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  printf "\n%d active addresses discovered in %s.\n\n" "$COUNT" "$(format_time SECONDS)"
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
