#!/usr/bin/env bash
##########################################################################
# Script Name  : meditation-timer
# Description  : Counts down remaining time of a meditation session.
# Dependencies : aplay (alsa-utils)
# Arguments    : Time in minutes to count down from. Optional volume setting (0-100%)
# Author       : Copyright (C) 2021, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 06 Jul 2021
# Updated      : 27 Jun 2025
# Comments     : Original script found on Reddit r/dharmmawheel, posted by u/Jhanna4
#              : Sound does not work with Pipewire audio.
# TODO (Rick)  : Work on getting sound functions to work on Pipewire.
# License      : GNU General Public License, version 2.0
##########################################################################

## Global Variables ##

script_dir=$(dirname "$(readlink -f "${0}")"); readonly script_dir
readonly TRUE=0
readonly FALSE=1

## Functions ##

check_alsa() {
  dpkg -l alsa-utils >/dev/null 2>&1 && return "$TRUE" || return "$FALSE"
}

# dpms_enabled() {
#   xset -q | grep -w Enabled || return "$TRUE" || return "$FALSE"
# }

is_valid_integer() {
  local value="$1"
  [[ "$value" =~ ^[0-9]+$ ]] || return "$FALSE"
  [[ "$value" -ge 0 || "$value" -le 100 ]] && return "$TRUE" || return "$FALSE"
}

input_value() {
  printf "%s Invalid argument\n" "$RED_ERROR" >&2
  printf "Please supply a value for minutes, only minutes, and only integers greater than 0.\n" >&2
  exit 2
}

get_volume() {
  # Get the cuurent volume setting (percentaage, ie 50%)
  local vol
  vol=$(amixer get Master | awk -F'[][]' 'END{print $2}')
  echo "$vol"
}

set_volume() {
  # Set the volume for sounds played or reset to original volume (voluume is a percentage, ie 60%)
  local vol="$1"
  amixer set Master "$vol" >/dev/null
}

play_sound() {
  # Play a sound as a background process.
  local sound="$1"
  /usr/bin/aplay "$sound" > /dev/null 2>&1 &
}

screensaver_off() {
  xset s off      # turns screensaver off
  xset s noblank  # set blanking off
  xset -dpms      # turns DPMS off
  tput civis      # hides cursor
}

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function.
# Shellcheck may incorrectly believe that code is unreachable if it's invoked by a variable or in a trap.
screensaver_on() {
  xset s on     # turns screesaver on
  xset s blank  # allows screen blanking
  xset +dpms    # turns DPMS on
  tput cnorm    # restores cursor
}

prep_countdown() {
  local count
  for count in {10..1}; do printf "\t%02d\r" "$count"; sleep 1; done
}

meditation_timer() {
  local hours interval min minutes seconds sec_rem
  min="$1"
  # local -r audio_file="$script_dir/files/Low-Wood-Block.wav"
  sec_rem=$(( 60 * min ))
  while [[ "$sec_rem" -gt 0 ]]; do
    sec_rem=$(( sec_rem - 1 ))
    interval="$sec_rem"
    seconds=$(( interval % 60 ))
    interval=$(( interval - seconds ))
    minutes=$(( interval % 3600 / 60 ))
    interval=$(( interval - minutes ))
    hours=$(( interval % 86400 / 3600 ))
    # interval=$(( interval - hours ))
    # days=$(( interval % 604800 / 86400 ))
    # interval=$(( interval - hours ))
    # weeks=$(( interval / 604800 ))
    printf "\t%02d:%02d:%02d\r" "$hours" "$minutes" "$seconds"
    # [[ $(( sec_rem % 300 )) -eq 0 && "$sec_rem" -gt 0 ]] && play_sound "$audio_file"
    sleep 1
  done
}

main() {
  trap screensaver_on EXIT
  local ovol
  local script="${0##*/}"
  local -r version="2.6.25180"
  local -r audio_file="$script_dir/files/Tibetan_bowl.wav"
  local meditation_time="${1:-20}"  # Default time is 20 minutes.
  [[ -n "${meditation_time//[0-9]/}" || "$meditation_time" -eq 0 ]] && input_value
  local vol="${2:-50}"  # Default volume setting is 50%.
  is_valid_integer "$vol" || vol="30"
  vol="${vol}%"   # pass volume as a percent.
  check_alsa || { printf "%s Audio utilities not installed. Audio will not function.\n" "$RED_WARNING" >&2; sleep 5; }
  clear
  # Capture original volume setting
  ovol=$(get_volume)
  # Set playback volume
  set_volume "$vol"
  printf "\n\t\U2638 Meditation Timer \U2638 \n\n"
  screensaver_off
  prep_countdown
  play_sound "$audio_file"
  meditation_timer "$meditation_time"
  play_sound "$audio_file"
  sleep 30
  set_volume "$ovol"
  printf "\n\n\U2638 %s v%s\n" "$script" "$version"
  printf "\UA9 2021-2025 Richard B. Romig\n"
  exit
}

## Execution ##

main "$@"
