#!/usr/bin/env bash
##########################################################################
# Script Name  : meditation-timer
# Description  : Counts down remaining time of a meditation session.
# Dependencies : aplay (alsa-utils)
# Arguments    : Time in minutes to count down from. Optional volume setting (0-100%)
# Author       : Copyright (C) 2021, Richard B. Romig, ludditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 06 Jul 2021
# Updated      : 11 Dec 2024
# Comments     : Original script found on Reddit r/dharmmawheel, posted by u/Jhanna4
#              : Sound does not work with Pipewire audio.
# TODO (Rick)  : Work on getting sound functions to work on Pipewire.
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

readonly sound_dir="$HOME/bin/files"
readonly tibet_bowl="Tibetan_bowl.wav"
# readonly wood_block="Low-Wood-Block.wav"

## Functions ##

check_alsa() {
  dpkg -l alsa-utils >/dev/null 2>&1 && return "$TRUE" || return "$FALSE"
}

is_valid_integer() {
  local value="$1"
  [[ "$value" =~ ^[0-9]+$ ]] || return "$FALSE"
  [[ "$value" -ge 0 || "$value" -le 100 ]] && return "$TRUE" || return "$FALSE"
}

input_value() {
  printf "%s Invalid argument\n" "$RED_ERROR" >&2
  printf "Please supply a value for minutes, only minutes, and only integers greater than 0.\n" >&2
  exit 2
}

get_volume() {
  # Get the cuurent volume setting (percentaage, ie 50%)
  local vol
  vol=$(amixer get Master | awk -F'[][]' 'END{print $2}')
  echo "$vol"
}

set_volume() {
  # Set the volume for sounds played or reset to original volume (voluume is a percentage, ie 60%)
  local vol="$1"
  amixer set Master "$vol" >/dev/null
}

play_sound() {
  # Play a sound as a background process.
  local sound="$1"
  /usr/bin/aplay "$sound" > /dev/null 2>&1 &
}

screensaver_off() {
  # Turn off screensaver and hide cursor.
  xset s off
  xset s noblank
  xset -dpms
  tput civis
}

# shellcheck disable=SC2317 # Don't warn about unrachable commands in this function.
# Shellcheck may incorrectly believe that code is unreachable if it's invoked by a variable or in a trap.
screensaver_on() {
  # Turn screensaver back on and restore cursor.
  xset s on
  xset s blank
  xset +dpms
  tput cnorm
}

countdown() {
  for i in {10..1}; do printf "\t%02d\r" "$i"; sleep 1; done
}

meditation_timer() {
  local hours interval min minutes seconds sec_rem
  min="$1"
  sec_rem=$(( 60 * min ))
  while [[ "$sec_rem" -gt 0 ]]; do
    sec_rem=$(( sec_rem - 1 ))
    interval="$sec_rem"
    seconds=$(( interval % 60 ))
    interval=$(( interval - seconds ))
    minutes=$(( interval % 3600 / 60 ))
    interval=$(( interval - minutes ))
    hours=$(( interval % 86400 / 3600 ))
    # interval=$(( interval - hours ))
    # days=$(( interval % 604800 / 86400 ))
    # interval=$(( interval - hours ))
    # weeks=$(( interval / 604800 ))
    printf "\t%02d:%02d:%02d\r" "$hours" "$minutes" "$seconds"
    # [[ $(( sec_rem % 300 )) -eq 0 && "$sec_rem" -gt 0 ]] && play_sound "$sound_dir/$wood_block"
    sleep 1
  done
}

main() {
  trap screensaver_on EXIT
  local meditation_time ovol vol script version
  script=$(basename "$0")
  version="2.2.24346"
  meditation_time="${1:-20}"  # Default time is 20 minutes.
  [[ -n "${meditation_time//[0-9]/}" || "$meditation_time" -eq 0 ]] && input_value
  vol="${2:-50}"  # Default volume setting is 50%.
  is_valid_integer "$vol" || vol="30"
  vol="${vol}%"   # pass volume as a percent.
  check_alsa || { printf "%s Audio utilities not installed. Audio will not function.\n" "$RED_WARNING" >&2; sleep 5; }
  clear
  # Capture original volume setting
  ovol=$(get_volume)
  # Set playback volume
  set_volume "$vol"
  printf "\n\t\U2638 Meditation Timer \U2638 \n\n"
  screensaver_off
  countdown
  play_sound "$sound_dir/$tibet_bowl"
  meditation_timer "$meditation_time"
  play_sound "$sound_dir/$tibet_bowl"
  sleep 30
  set_volume "$ovol"
  printf "\n\n\U2638 %s v%s\n" "$script" "$version"
  printf "\UA9 2021-2024 Richard B. Romig\n"
  exit
}

## Execution ##

main "$@"
