#!/usr/bin/env bash
#####################################################################
# Script Name  : mint-fortune
# Description  : modified version of packaged mint-fortune
# Dependencies : cowsay, fortune
# Arguments    : none
# Author       : Copyright (C) 2019, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 04 May 2019
# Updated      : 19 Jul 2025
# Comments     : does not check com.linuxmint.terminal show-fortunes
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#####################################################################

show_fortune() {
  local cow number range
  range=4
  number=$RANDOM
  # let "number %= $range"
  (( number %= range ))
  case $number in
    0 )  cow="default" ;;
    1 )  cow="tux" ;;
    2 )  cow="koala" ;;
    3 )  cow="moose" ;;
  esac

  range=2
  number=$RANDOM
  (( number %= range ))
  case $number in
    0 )  command="/usr/games/cowsay" ;;
    1 )  command="/usr/games/cowthink" ;;
  esac
  /usr/games/fortune | $command -f $cow
}

[[ -x "/usr/games/fortune" ]] && [[ -x "/usr/games/cowsay" ]] && show_fortune
