#!/usr/bin/env bash
###############################################################################
# Script Name  : mint-main
# Description  : Installs applications & utilities for main Linux Mint system
# Dependencies : gdebi, wget
# Arguments    : None
# Author       : Richard B. Romig, 26 July 2019
# Email        : rick.romig@gmail.com
# Comments     :
# TODO (rick)  : Rewrite using HP-6005 share.
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Variables ##

readonly _script=$(basename "$0")
readonly _version="2.1.1"
readonly _updated="21 Jun 2021"

readonly home_dir=$HOME
readonly start_dir=$PWD
tmp_dir=$(mktemp -d) || die "Failed to create temporary diectory!"

## Functions ##

cleanup() {
  [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
}

## Execution ##

trap cleanup EXIT

if [[ "$start_dir" != "$home_dir" ]]; then
  pushd "$home_dir" || die "pushd failed"
fi

# Check sudo access and start sudo timer

user_in_sudo

# Update apt cache

sudo apt update -qq

# Install gdebi & wget if not already installed

check_package gdebi
check_package wget

echo "$_script v$_version ($_updated)"
echo "Installs specific applications to my main Linux Mint system."

# Install mingw to cross compile for Windows
check_package mingw

# Install Google Chrome

pushd "$tmp_dir" || die "pushd failed"
echo "Downloading and installing Google Chrome."
wget https://dl.google.com/Linux/direct/google-chrome-stable_current_amd64.deb
sudo gdebi -n google-chrome-stable_current_amd64.deb
popd || die "popd failed"

if [[ "$start_dir" != "$home_dir" ]]; then
  popd || die "popd failed"
fi

# Installation complete

leave "Installation complete. Please reboot the computer."
