#!/usr/bin/env bash
###############################################################################
# Script Name  : mk-changelog
# Description  : Create a changelog file from a template
# Dependencies : none
# Arguments    : Project name
# Author       : Copyright © 2019 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 09 Apr 2019
# Updated      : 08 Aug 2026
# Version      : 2.4.26219
# Comment      : Should be run from the project's main directory.'
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

# shellcheck source=/home/rick/bin/functionlib.bash
source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

VERBOSE="$FALSE"

help() {
  local -r script="$1"
  local -r version="$2"
  local -ri errcode="${3:-1}"
  local -r updated="08 Aug 2026"
  cat << _HELP_
${orange}$script${normal} $version, updated: $updated
Creates a changelog file for a project.

${green}Usage:${normal} $script [-c project-name] [-h] [-vc project-name]
${orange}Available options:${normal}
  -c  Create a changelog file
      $script -c <project-name>
  -h  Show this help message and exit
  -v  Enable verbose mode (Must precede c flag)
      $script -vc <project-name>
_HELP_
  exit "$errcode"
}

show_message() {
	local -r message="$1"
	[[ "$VERBOSE" == "$TRUE" ]] && echo "$message"
  return 0
}

create_changelog() {
  local today script_dir
  local -r project="$1"
  today=$(date +"%d %B %Y")
  script_dir=$(dirname "$(readlink -f "${0}")")
  show_message "Importing data into changlog.md"
  sed -e '1d' \
    -e "s/<PROJECT>/$project/" \
    -e "s/<DATE>/$today/" "$script_dir/Templates/changelog.txt" > changelog.md
  printf "The changelog.md for %s has been created." "$$project"
  edit_view_quit CHANGELOG.md
  return 0
}

main() {
  local -r script="${0##*/}"
  local -r version="2.4.26219"
  local opt OPTARG OPTIND project_name
  local -i noOpt=1
  local -r optstr=":c:hv"
  while getopts "$optstr" opt; do
    case "$opt" in
      c )
        project_name="$OPTARG"
        if [[ -f CHANGELOG.md ]]; then
          printf "%s changelog.md already exists.\n" "$RED_ERROR" >&2
          help "$E_FILE_EXISTS"
        else
          show_message "Creating changelog for $project_name"
          create_changelog "$project_name"
        fi
        ;;
			h )
				help "$script" "$version" 0
			  ;;
			v )
				VERBOSE="$TRUE"
				show_message "Verbose mode enabled."
			  ;;
			: )
				printf "%s Must supply an argument to -%s.\n" "$RED_ERROR" "$OPTARG" >&2
				help "$script" "$version" "$E_MISSING_ARG"
        ;;
			? )
			  printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help "$script" "$version" "$E_INVALID_ARG"
    esac
    noOpt=0
  done
	if (( noOpt == 1 )); then
		printf "%s No argument passed.\n" "$RED_ERROR" >&2
		help "$script" "$version" "$E_MISSING_ARG"
	fi
	shift "$(( OPTIND - 1 ))"
	over_line "$script $version"
	exit
}

main "$@"
