#!/usr/bin/env bash
###############################################################################
# Script Name  : mk-conkyrc
# Description  : Configure .conkyrc from a template file
# Dependencies : upower
# Arguments    : None
# Author       : Richard Romig, 26 December 2018
# Email        : rick.romig@gmail.com
# Comment      : copies .conkyrc to archive file appended by hostname
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

# Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Check Dependencies ##

# upower is used to extract battery information
check_package upower

## Variables ##

readonly _script=$(basename "$0")
readonly _version="2.7.0"
readonly _updated="11 Oct 2022"
readonly template_dir="$HOME/bin/Templates"

# number of CPU cores or threads
ncpu=$(/usr/bin/nproc --all)

# Find device names
if [[ -x /usr/bin/nmcli ]]; then
  e_name=$(/usr/bin/nmcli dev | awk '/ethernet/ {print $1}')
  w_name=$(/usr/bin/nmcli dev | awk '/wifi/ {print $1}')
else
  e_name=$(ip ad show | awk '/: en/ {print $2}' | sed 's/:$//')
  w_name=$(ip ad show | awk '/: wl/ {print $2}' | sed 's/:$//')
fi
b_name=$(/usr/bin/upower -e | awk -F_ '/BAT/ {print $NF}')

# Set default names if not found
[[ -z "$e_name" ]] && e_name="eth0"
[[ -z "$w_name" ]] && w_name="wlan0"
[[ -z "$b_name" ]] && b_name="BAT0"

## Execution ##

printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
printf "Creates a .conkyrc script in your home directory from a template.\n"

# Check if distribution is antiX or MX Linux
if bunsenlabs || antix_mx; then
  leave "Conky is pre-installed. Use the Conky Manager to configure conky."
fi

# Display battery and network device names and number of CPU cores/threads
printf "Battery device name:\t%s\n" "$b_name"
printf "Ethernet device name:\t%s\n" "$e_name"
printf "Wireless device name:\t%s\n" "$w_name"
printf "CPU cores/threads:\t%s\n" "$ncpu"

# Plug device names into the template and create the ~/.conkyrc script
sed -e '1d' \
    -e "s/<BAT>/$b_name/g" \
    -e "s/<EN>/$e_name/g" \
    -e "s/<WL>/$e_name/g" "$template_dir/conkyrc" > "$HOME/.conkyrc"

# Adjust number of cores/threads displayed.
case "$ncpu" in
  1 ) sed -i '57,63d' "$HOME/.conkyrc" ;;
  2 ) sed -i '58,63d' "$HOME/.conkyrc" ;;
  3 ) sed -i '59,63d' "$HOME/.conkyrc" ;;
  4 ) sed -i '60,63d' "$HOME/.conkyrc" ;;
  5 ) sed -i '61,63d' "$HOME/.conkyrc" ;;
  6 ) sed -i '62,63d' "$HOME/.conkyrc" ;;
  7 ) sed -i '63d' "$HOME/.conkyrc" ;;
  * ) ;;
esac

printf "\n.conkyrc created and configured.\n"

edit_view_quit "$HOME/.conkyrc"

leave "Please reboot or log out and log in again to complete the installation."
