#!/usr/bin/env bash
###############################################################################
# Script Name  : mk-fortunes
# Description  : Create fortune files for the fortune program
# Dependencies : strfile (fortune-mod)
# Arguments    : fortune-cookie file (text)
# Author       : Copyright (C) 2019, Richard B. Romig, MosfaNet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Crated       : 04 May 2019
# Updated      : 05 Feb 2026
# Comments     :
# License      : GNU General Public License, version 2.0
## License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
 printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 81
fi

## Functions ##

help() {
  local errcode="${1:-1}"
  local updated="05 Feb 2026"
  cat << _HELP_
${orange}$script${normal} $version, updated: $updated
Creates fortune cookie files for the fortune program.

${green}Usage:${normal} $script <cookie-file>
${orange}Available options:${normal}
  -h --help Show this help message and exit
_HELP_
  exit "$errcode"
}

create_cookie_file() {
  local cookiefile="$1"
  local -r fortunes_d="/usr/share/games/fortunes"
  sudo_login 2
  printf "Creating %s.dat...\n" "$cookiefile"
  if strfile -c % "$cookiefile" "$cookiefile.dat"; then
    sudo cp "$cookiefile" "$cookiefile.dat" "$fortunes_d"/
    printf "Fortune cookie file created and copied to /%s\n" "$fortunes_d"
  else
    printf "Fortune cookie operation failed.\n"
    EC="$E_INFO"
  fi
}

main() {
  local script="${0##*/}"
  local version="2.1.26036"
  EC=0
  if [[ "$#" -eq 0 ]]; then
    printf "%s No argument passed." >&2 "$RED_ERROR"
    help "$E_MISSING_ARG"
  elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
    help 0
  else
    local cookiefile="$1"
    [[ -f "$cookiefile" ]] || { printf "%s %s not found.\n" "$RED_ERROR" "$cookiefile" >&2; help "$E_FILENOTFOUND"; }
    check_package fortune-mod
    create_cookie_file "$cookiefile"
	  over_line "$script $version"
	  exit "$EC"
  fi
}

## Execution ##

main "$@"
