#!/usr/bin/env bash
###############################################################################
# Script Name  : mk-fortunes
# Description  : Create fortune files for the fortune program
# Dependencies : strfile (fortune-mod)
# Arguments    : fortune-cookie file (text)
# Author       : Copyright (C) 2019, Richard B. Romig, MosfaNet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Crated       : 04 May 2019
# Updated      : 27 Feb 2025
# Comments     :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
 printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

help() {
  local errcode="${1:-2}"
  local updated="27 Feb 2025"
  cat << _HELP_
${orange}$script${normal} $version, updated: $updated
Creates fortune cookie files for the fortune program.

${green}Usage:${normal} $script <cookie-file>

${orange}Available options:${normal}
  -h --help Show this help message and exit
_HELP_
  exit "$errcode"
}

create_cookie_file() {
  local cookiefile="$1"
  local fortunes_d="/usr/share/games/fortunes"
  sudo_login 2
  printf "Creating %s.dat...\n" "$cookiefile"
  if strfile -c % "$cookiefile" "$cookiefile.dat"; then
    sudo cp "$cookiefile" "$cookiefile.dat" "$fortunes_d"/
    printf "Fortune cookie file created and copied to /%s\n" "$fortunes_d"
  else
    die "Fortune cookie operation failed." 1
  fi
}

main() {
  local cookiefile script version
  script=$(basename "$0")
  version="2.0.25058"
  if [[ "$#" -eq 0 ]]; then
    printf "%s No argument passed." >&2 "$RED_ERROR"
    help 2
  elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
    help 0
  else
    cookiefile="$1"
    [[ -f "$cookiefile" ]] || { printf "%s %s not found.\n" "$RED_ERROR" "$cookiefile" >&2; help 1; }
    check_package fortune-mod
    create_cookie_file "$cookiefile"
	  over_line "$script $version"
	  exit
  fi
}

## Execution ##

main "$@"
