#!/usr/bin/env bash
###############################################################################
# Script Name  : mk-readme
# Description  : Creates shell for a README.md file from a template
# Dependencies : sed
# Arguments    : name of project
# Author       : Richard B. Romig, 09 April 2019
# Email        : rick.romig@gmail.com
# Comment      :
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="2.0.1"
readonly _updated="21 Mar 2023"
readonly conf_dir="$HOME/.config/scripts"
readonly conf_file="$_script.conf"
readonly today=$(date +"%d %B %Y")

# Information to be inserted into README template
# For sed, forward slashes have to be escaped with backslashes

## Functions ##

create_conf() {
  [[ -d "$conf_dir" ]] || mkdir -p "$conf_dir"
  echo "Complete all fields"
  read -rp "Full name: " copy_holder
  read -rp "GitHub username: " github
  read -rp "Blog name: " blog_name
  read -rp "Blog title: " blog_url
  read -rp "Twitter name: " twitter_name
  read -rp "Primary email: " email_addr1
  read -rp "Alternate email: " email_addr2
  read -rp "Template diretory (full path): " template_dir

  echo "
  copy_holder='$copy_holder'
  github_url='$github'
  blog_name='$blog_name'
  blog_url='$blog_url'
  twitter_name='$twitter_name'
  email_addr1='$email_addr1'
  email_addr2='$email_addr2'
  template_dir='$template_dir'
  " > "$conf_dir/$conf_file"
}

usage() {
  local errcode="${1:-2}"
  echo "${orange}Usage:${normal} $_script <project-name>"
  echo "${orange}Example:${normal}  $_script my-project"
  exit "$errcode"
}

## Execution ##

## Source script configuration file ##

[[ -f "$conf_dir/$conf_file" ]] || create_conf
source "$conf_dir/$conf_file"

# Check arguments

if [[ $# -eq 0 ]]; then
  echo "${lightred}Error:${normal} No argment passed." >&2
  usage 2
elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
  echo "$_script v$_version ($_updated)"
  usage 0
else
  project=$1
fi

echo "$_script v$_version ($_updated)"
echo "Creating a README.md template for project $project"

# Fill in placeholders and create README.md

sed -e '1d' \
    -e "s/<PROJECT>/$project/" \
    -e "s/<GITHUB>/$github/" \
    -e "s/<BLOG>/$blog_name/" \
    -e "s/<BLOGURL>/$blog_url/" \
    -e "s/<TWITNAME>/$twitter_name/g" \
    -e "s/<EMAIL1>/$email_addr1/g" \
    -e "s/<EMAIL2>/$email_addr2/g" \
    -e "s/<AUTHOR>/$copy_holder/" \
    -e "s/<DATE>/$today/" "$template_dir/readme" > README.md
echo "The README.md for $project has been created."

edit_view_quit README.md

exit
