#!/usr/bin/env bash
###############################################################################
# Script Name  : mk-readme
# Description  : Creates shell for a README.md file from a template
# Dependencies : sed
# Arguments    : name of project
# Author       : Copyright © 2019 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | eick.romig@mymetronet.net
# Created      : 09 Apr 2019
# Updated      : 05 Feb 2026
# Comment      : Should be run from the project's main directory.'
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 81
fi

## Global Variables ##

script_dir=$(dirname "$(readlink -f "${0}")"); readonly script_dir
readonly script="${0##*/}"
readonly version="3.2.26036"
verbose_mode="$FALSE"

## Functions ##

help() {
  local errcode="${1:-2}"
  local updated="05 Feb 2026"
  cat << _HELP_
${orange}$script${normal} $version, updated: $updated
Creates a README file for a project.

${green}Usage:${normal} $script [-c project-name] [-h] [-vc project-name]
${orange}Available options:${normal}
  -c  Create a README file
      $script -c <project-name>
  -h  Show this help message and exit
  -v  Enable verbose mode (Must precede c flag)
      $script -vc <project-name>
_HELP_
  exit "$errcode"
}

show_message() {
	local message="$1"
	[[ "$verbose_mode" == "$TRUE" ]] && echo "$message"
}

create_readme() {
  local blog_name blog_url copy_holder email_addr1 email_addr2 today
  project="$1"
  copy_holder="Richard B. Romig"
  github="RickRomig"
  blog_name="Ricks Tech Stuff"
  blog_url="ricktech"
  email_addr1="rick.romig@gmail.com"
  email_addr2="rick.romig@mymetronet.net"
  today=$(date +"%d %B %Y")

  show_message "Importing data into README.md"
  # Information to be inserted into README template
  # For sed, forward slashes have to be escaped with backslashes
  sed -e '1d' \
    -e "s/<PROJECT>/$project/" \
    -e "s/<GITHUB>/$github/" \
    -e "s/<BLOG>/$blog_name/" \
    -e "s/<BLOGURL>/$blog_url/" \
    -e "s/<EMAIL1>/$email_addr1/g" \
    -e "s/<EMAIL2>/$email_addr2/g" \
    -e "s/<AUTHOR>/$copy_holder/" \
    -e "s/<DATE>/$today/" "$script_dir/Templates/readme.txt" > README.md
  printf "The README.md for %s$project has been created." "$$project"
  edit_view_quit README.md
}

main() {
  local noOpt opt optstr project_name OPTARG OPTIND
  noOpt=1
  optstr=":c:hv"
  while getopts "$optstr" opt; do
    case "$opt" in
      c )
        project_name="$OPTARG"
        if [[ -f README.md ]]; then
          printf "%s README.md already exists.\n" "$RED_ERROR" >&2
          help "$E_FILE_EXISTS"
        else
          show_message "Creating README for $project_name"
          create_readme "$project_name"
        fi
        ;;
			h )
				help 0
			  ;;
			v )
				verbose_mode="$TRUE"
				show_message "Verbose mode enabled."
			  ;;
			: )
				printf "%s Must supply an argument to -%s.\n" "$RED_ERROR" "$OPTARG" >&2
				help "$E_MISSING_ARG"
        ;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help "$E_INVALID_ARG"
    esac
    noOpt=0
  done
	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
	shift "$(( OPTIND - 1 ))"
	over_line "$script $version"
	exit
}

## Execution ##

main "$@"
