#!/usr/bin/env bash
###############################################################################
# Script Name  : mount-sshfs
# Description  : Mount or unmount a local SSHFS share.
# Dependencies : sshfs
# Arguments    : None
# Author       : Copyright (C) 2020 Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 18 May 2020
# Updated      : 07 Oct 2026
# Version      : 6.0.26280
# Comments     : Mount points are at ~/mnt/ (HOME directory)
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

# shellcheck source=/home/rick/bin/functionlib.bash
source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

help() {
	local -r script="$1"
	local -r version="$2"
	local -r updated="07 Oct 2026"
	cat <<- _HELP_
	${orange}$script${normal} $version, Updated $updated
	Mounts/Unmounts an SSHFS share.
	${green}Usage:${normal}
	Select the SSHFS share to mount from the menu.
	If the share is not already mounted, it will be mounted.
	If the share is currently mounted, you will be asked if you want to unmount the share.
	When unmounting the share, be sure you are not in the mount point.
_HELP_
	exit 0
}

cd_fail() {
	local share="$1"
	printf "%s The cd shell builtin failed.\n" "$RED_ERROR" >&2
	printf "The SSHFS share has not been unmounted.\n" >&2
	return 0
}

fail_msg() {
	local -r share="$1"
	local -r mount_point="$HOME/mnt"
	printf "Make sure you are not in the mountpoint and run the following command:\n" >&2
	printf "\t%sfusermount -u %s/%s/%s\n" "$orange" "$mount_point" "$share" "$normal"  >&2
	return 0
}

mount_share() {
	local -r octet="$1"
	local -r share="$2"
	ping -c3 "$LOCALNET.$octet" > /dev/null 2>&1 || die "$share at $LOCALNET.$octet is not online." "$E_NETWORK"
	[[ -d "$HOME/mnt/$share/" ]] || mkdir -p "$HOME/mnt/$share"
	printf "Mounting %s...\n" "$share"
	sshfs -o follow_symlinks rick@"$LOCALNET.$octet:$HOME" "$HOME/mnt/$share/"
	printf "Home directory at %s:\n" "$share"
	ls "$HOME/mnt/$share/"
	printf "%s at %s.%s has been mounted.\n" "$share" "$LOCALNET" "$octet"
	return 0
}

unmount_share() {
	local -r share="$1"
	if ! cd "$HOME"; then
		cd_fail "$share"
		fail_msg "$share"
		return "$E_DRIVE_ERROR"
	fi
	if fusermount -u "$HOME/mnt/$share/"; then
		printf "%s has been unmounted.\n" "$share"
		return 0
	fi
	printf "%s %s has not been unmounted." "$RED_ERROR" "$share" >&2
	fail_msg "$share"
	return "$E_DRIVE_ERROR"
}

mounted() {
	local -r share="$1"
	grep -q "$share" < <(mount) && return "$TRUE" || return "$FALSE"
}

handle_mount() {
	local -ir octet="$1"
	local -r share="$2"
	local -i ip
	ip=$(local_ip)
	if (( ip == octet )); then
		printf "%s Cannot mount/unmount local system.\n" "$RED_ERROR" >&2
		return "$E_DRIVE_ERROR"
	fi
	if ! mounted "$share"; then
		mount_share "$octet" "$share"
		return "$?"
	fi
	if default_yes "Unmount $share?"; then
		unmount_share "$share"
	else
		printf "%s left mounted.\n" "$share"
	fi
	return "$?"
}

select_share() {
	local -r share_list=(
		"10 hp-800g2-sff"
		"11 hp-6005"
		"12 e6500-deb"
		"13 probook-6570b"
		"14 hp-8300"
		"15 dell-9020"
		"16 hp-8300-usdt"
		"17 hp-800-g1-usdt"
		"18 satellite-c875"
		"19 hp-800-g1-dm"
		"20 probook-6570"
		"21 hp-probook-6570"
		"22 hp-850-g3"
		"23 hp-2560p"
		"24 e-475m"
	)
	local -i share_ip index
	local _opt share_name
	COLUMNS="60"
	PS3="Select a share to mount. ("$(( 1 + ${#share_list[@]} ))" to quit.) "
	select _opt in "${share_list[@]}"; do
		if (( REPLY == 1 + ${#share_list[@]} )); then
			printf "Exiting. No share selected.\n"
			break
		elif (( REPLY > 0 && REPLY <= ${#share_list[@]} )); then
			index=$(( REPLY - 1 ))
			break
		else
			printf "Invalid option. Choose 1 - %d. %d to quit.\n" "${#share_list[@]}" "$(( 1 + ${#share_list[@]} ))"
		fi
	done
	share_name=$(cut -d' ' -f2 <<< "${share_list[index]}")
	share_ip=$(cut -d' ' -f1 <<< "${share_list[index]}")
	printf "Share IP = %d\n" "$share_ip"
	printf "Share name: %s\n" "$share_name"
	handle_mount "$share_ip" "$share_name"
}

main() {
	local -r script="${0##*/}"
	local -r version="6.0.26280"
	local -i exit_code=0
	local share_name share_ip
	[[ "$1" == '-h' || "$1" == --help ]] && help "$script" "$version"
	check_package sshfs
	printf "Mount or unmount an SSHFS share.\n"
	select_share
	exit_code="$?"
	over_line "$script $version"
	exit "$exit_code"
}

main "$@"
