#!/usr/bin/env bash
##########################################################################
# Script Name  : mount-sshfs
# Description  : Mount or unmount an SSHFS share.
# Dependencies : sshfs
# Arguments    : None
# Author       : Copyright (C) 2020 Richard B. Romig, 18 May 2020
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     : Mount points are at ~/mnt/
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.4.1"
readonly _updated="12 Jan 2024"

## Functions ##

mount_share() {
  local octet="$1"
  local share="$2"
  ping -c3 "$localnet.$octet" > /dev/null 2>&1 || die "$share at $localnet.$octet is not online."
	[[ -d "$HOME/mnt/$share/" ]] || mkdir -p "$HOME/mnt/$share"
	printf "Mounting %s...\n" "$share"
	if [[ "$share" == "NASD97167" ]]; then
  	sshfs -o follow_symlinks rick@"$localnet.$octet:" "$HOME/mnt/$share/"
	else
		sshfs -o follow_symlinks rick@"$localnet.$octet:/home/rick" "$HOME/mnt/$share/"
	fi
	printf "Home directory at %s:\n" "$share"
	ls "$HOME/mnt/$share/"
	printf "%s at %s.%s has been mounted.\n" "$share" "$localnet" "$octet"
}

unmount_share() {
  local share="$1"
    cd "$HOME" || cd_fail
    if fusermount -u "$HOME/mnt/$share/"; then
      printf "%s has been unmounted.\n" "$share"
    else
      printf "%s %s has not been unmounted." >&2 "$red_error" "$share"
      fail_msg
    fi
}

mounted() {
	local share="$1"
	mount | grep -q "$share" && return "$TRUE" || return "$FALSE"
}

handle_mount() {
	local octet="$1"
  local share="$2"
  if mounted "$share"; then
		if default_yes "Unmount $share"; then
			unmount_share "$share"
		else
			printf "%s left mounted.\n" "$share"
		fi
	else
		mount_share "$octet" "$share"
	fi
}

cd_fail() {
  printf "%s The cd shell builtin failed.\n" "$red_error" >&2
  printf "The SSHFS share has not been unmounted.\n" >&2
  fail_msg
}

fail_msg() {
  printf "Make sure you are not in the mountpoint and run the following command:\n" >&2
  printf "\t%sfusermount -u \$HOME/mnt/%s/%s\n" "$orange" "$share" "$normal"  >&2
  exit 1
}

help() {
	errcode="${1:-2}"
	cat << END_HELP
${green}Usage:${normal} $_script [OPTION]
${orange}OPTIONS:${normal}
  -c  toggle mount/umount HP Compaq 6005 Pro SSF (file server)
  -e  toggle mount/umount HP EliteBook 850 G2 (laptop)
  -f  toggle mount/umount HP ProBook 6570b (Finance)
  -g  toggle mount/umount HP Compaq Elite 8300 USDT (Gitea Server)
  -h  help
  -l  toggle mount/umount Lenovo M91p (VM and media)
  -n  toggle mount/umount QNAP NAS (network attached storage)
$_script v$_version (Updated: $_updated)
END_HELP
	exit "$errcode"
}

## Execution ##

check_package sshfs

printf "Mount or unmount an SSHFS share.\n\n"

noOpt=1
optstr=":cefghln"
while getopts "$optstr" opt
do
	case "$opt" in
		c )
			share_name="HP-6005"
			ip_address=11
			handle_mount "$ip_address" "$share_name"
		;;
		e )
			share_name="EliteBook-850"
			ip_address=22
			handle_mount "$ip_address" "$share_name"
		;;
		f )
			share_name="HP-ProBook-6570b"
			ip_address=21
			handle_mount "$ip_address" "$share_name"
		;;
		g )
			share_name="Gitea-Server"
			ip_address=16
			handle_mount "$ip_address" "$share_name"
		;;
		h )
			help 0
		;;
		l )
			share_name="Lenovo-M91p"
			ip_address=15
			handle_mount "$ip_address" "$share_name"
		;;
		n )
			share_name="NASD97167"
			ip_address=4
			handle_mount "$ip_address" "$share_name"
		;;
		?)
			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
			help 2
	esac
	noOpt=0
done
[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
shift "$(( OPTIND - 1 ))"
leave "$_script v$_version ($_updated)"
