#!/usr/bin/env bash
##########################################################################
# Script Name  : mount-bu
# Description  : mounts/unmounts USB backup drive if not auto-detected.
# Dependencies : none
# Arguments    : [-h] [-m] [-s] [-u] (See help function)
# Author       : Copyright (C) 2022, Richard B. Romig, 04 Jul 2022
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 04 Jul 2022
# Updated      : 27 Jan 2026
# Comments     : For use with BU backup script.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 81
fi

## Variables ##

readonly script="${0##*/}"
readonly version="2.21.26027"
readonly mount_point="/media/$USER/BU_Drive"

## Functions ##

help() {
  local errcode updated
	errcode="${1:-1}"
	updated="27 Jan 2026"
	cat << _HELP_
  ${orange}$script${normal} $version, Updated $updated
  Mounts/Unmounts USB backup drive for the BU script.

  ${green}Usage:${normal} $script [-hmsu]
  ${orange}Availabel options:${normal}
    -h    Show this help message and exit
    -m    Mount USB Backup Drive (BU_Drive)
    -s    Status, is USB Backup Drive (BU_Drive) mounted?
    -u    Unmount USB Backup Drive (BU_Drive)
  ${green}NOTEs:${normal}
  - When prompted, enter only the drive, i.e., sdb1
  - If no argument is passed, displays status of the BU drive.
_HELP_
  exit "$errcode"
}

mount_bu() {
  local usbdrv
  usbdrv="$(awk '/BU_Drive/ {print $1}' <(lsblk -fs))"
  sudo_login 2
  printf "Mounting backup drive: /dev/%s to %s ...\n" "$usbdrv" "$mount_point"
  [[ -d "$mount_point" ]] || sudo mkdir -p "$mount_point"
  sudo mount /dev/"$usbdrv" "$mount_point"
  printf "Backup drive (/dev/%s) is mounted at %s\n" "$usbdrv" "$(awk '/BU_Drive/ {print $3}' <(mount))"
  notify-send -t 2000 -i "$HOME/.icons/usb-drive-fill.png" "BU_Drive" "is mounted"
}

umount_bu() {
  local usbdrv
  usbdrv=$(awk '/BU_Drive/ {print $1}' <(mount))
  sudo_login 2
  printf "Unmounting USB Backup drive at %s ...\n" "$mount_point"
  sudo umount "$mount_point"
  printf "BU_Drive (%s) is unmounted.\n" "$usbdrv"
  notify-send -t 2000 -i "$HOME/.icons/usb-drive-fill.png" "BU_Drive" "is unmounted"
}

bu_status() {
  printf "BU_Drive is "
  if grep -qw BU_Drive <(lsblk); then
    printf "mounted.\n"
    notify-send -t 2000 -i "$HOME/.icons/usb-drive-fill.png" "BU_Drive" "is mounted"
    return "$TRUE"
  else
    printf "not mounted.\n"
    notify-send -t 2000 -i "$HOME/.icons/usb-drive-fill.png" "BU_Drive" "is not mounted"
    return "$FALSE"
  fi
}

main() {
  local noOpt opt optstr OPTARG OPTIND
  grep -qw 'usb' <(lsblk -S -o TRAN) || die "BU_Drive not attached." "$E_DRIVE_ERROR"
  noOpt=1
  optstr=":hmsu"
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        help 0
        ;;
      m )
        if bu_status; then
          printf "No further action necessary.\n"
        else
          mount_bu
        fi
        ;;
      s )
        bu_status
        ;;
      u )
        if bu_status; then
          umount_bu
        else
          printf "No further action necessary.\n"
        fi
        ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help "$E_INVALID_ARG"
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { bu_status; help 0; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script $version"
}

## Execution ##

main "$@"
