#!/usr/bin/env bash
##########################################################################
# Script Name  : no-snaps
# Description  : Enable/disable Snaps in Debian/Ubuntu-based systems.
# Dependencies : None
# Arguments    : [-d] [-e] [-h] [-r] [-s] (See help function)
# Author       : Copyright (C) 2020, Richard B. Romig, MosfaNet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 30 Jun 2020
# Updated      : 29 Jun 2025
# Comments     : See EZNix snapkill script
#              : /home/rick/Downloads/Utilities/snapkill.d/snapkill
# TODO (Rick)  : Figure out what remove_snaps() does.
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

# Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="3.4.25180"
readonly pref_file="/etc/apt/preferences.d/nosnap.pref"

## Functions ##

help() {
	local errcode="${1:-2}"
	local updated="29 Jun 2025"
	cat << _HELP_
${green}Usage:${normal} $script [-d] [-e] [-h] [-s]
${orange}OPTIONS:${normal}
  -d    Disable the installation of snapd and snap packages.
  -e    Enable the installation of snapd and snap packages.
  -h    Show this help message and exit.
  -s    Status of snapd and snap package installation.
$script v$version, updated $updated
_HELP_
  exit "$errcode"
}

check_snap_installed() {
  printf "Snap is "
  if exists snap; then
    printf "installed.\n"
  else
    printf "not installed.\n"
  fi
}

snap_packages() {
  [[ "$(snap list)" ]] && return "$TRUE" || return "$FALSE"
}

snaps_enabled() {
  if [[ -f "$pref_file" ]]; then
    grep -q '^# Package:' "$pref_file" && return "$TRUE" || return "$FALSE"
  else
    return "$TRUE"
  fi
}

enable_snaps() {
  is_systemd || die "SystemD is required for Snaps." 1
  if [[ -f "$pref_file" ]]; then
    if grep -q '^Package:' "$pref_file"; then
      sudo sed -i '/^Package/s/^/# /;/^Pin/s/^/# /' "$pref_file"
      printf "\nInstallation of Snapd and Snap packages is now enabled.\n"
    else
      printf "\nInstallation of Snapd and Snap packages is already enabled by %s.\n" "$pref_file"
    fi
  else
    printf "\n%s does not exist. Installation of Snapd and Snap packages is enabled by default." "$pref_file"
  fi
}

disable_snaps() {
  snap_packages && diehard "Snap packages are installed." "Remove all Snaps before disabling  Snap."
  if [[ -f "$pref_file" ]]; then
    if grep -q '^# Package:' "$pref_file"; then
      sudo sed -i '/Package/s/^# //;/Pin/s/^# //' "$pref_file"
      printf "\nInstallation of Snapd and Snap packages is now disabled.\n"
    else
      printf "\nInstallation of Snapd and Snap packages is already disabled.\n"
    fi
  else
    create_nosnaps
    printf "%s has been created. Installation of Snapd and Snap packages is now disabled.\n" "$pref_file"
  fi
}

create_nosnaps() {
  cat << _NOSNAPS_ sudo tee "$pref_file" > /dev/null
# To prevent repository packages from triggering the installation of Snap,
# this file forbids snapd from being installed by APT.
# For more information: https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html

Package: snapd
Pin: release a=*
Pin-Priority: -10
_NOSNAPS_
}

main() {
  local noOpt opt optstr
  printf "Enables or disables the installation of Snapd and Snap packages.\n"
  check_snap_installed
  noOpt=1
  optstr=":dehs"
  while getopts "$optstr" opt; do
    case "$opt" in
      d )
        sudo_login 2
        snaps_enabled && disable_snaps
       ;;
      e )
        sudo_login 2
        snaps_enabled || enable_snaps
       ;;
      h )
        help 0
       ;;
      s )
        printf "\nStatus of snapd and snap packages: "
        snaps_enabled && printf "Snaps are enabled.\n" || printf "Snaps are disabled.\n"
        ;;
      ? )
        printf "\n%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help 2
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  leave "$script v$version"
}

## Execution ##

main "$@"
