#!/usr/bin/env bash
##########################################################################
# Script Name  : nosleep
# Description  : Script to disable sleep and hiberation on Debian-based systems
# Dependencies : None
# Arguments    : None
# Author       : Copyright © 2023 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 18 Jul 2023
# Last updated : 18 Jul 2023
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.1.0"
readonly _updated="18 Jul 2023"
readonly sleep_file="/etc/systemd/sleep.conf"
readonly sed_file="${HOME}/bin/files/nosleep.sed"

## Execution ##

printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
printf "Disables sleep and hiberation on Debian-based systems.\n"

[[ -f "$sed_file" ]] || die "A required files ($(basename "$sed_file")) was not found." 1
sudo_login
sudo sed -i.bak -f "$sed_file" "$sleep_file"
leave "$sleep_file modified. Backup (${sleep_file}.bak) created."
exit
