#!/usr/bin/env bash
##########################################################################
# Script Name  : numfiles
# Description  : displays number of files and directories in current directory
#              : and how much disk space the directory uses.
# Dependencies : none
# Arguments    : none
# Author       : Copyright (C) 2018, Richard Romig, MosfaNet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 22 Nov 2018
# Updated      : 19 Jul 2025
# Comment      :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

num_files() {
	local ndirs nfiles size
	ndirs=$(find . -type d | wc -l)
	nfiles=$(find . -type f | wc -l)
	size=$(du -ch | awk '$2 == "total" {print $1}')

	printf "%s contains:\n" "$PWD"
	printf "%d " "$(( ndirs - 1 ))"
	(( ndirs != 1 )) && printf "directories " || printf "directory "
	printf "and %d " "$nfiles"
	(( nfiles != 1 )) && printf "files.\n" || printf "file.\n"
	printf "Disk spaced used: %s\n" "$size"
}

main() {
	local script="${0##*/}"
	local version="3.1.25200"
	num_files
	over_line "$script $version"
	exit
}

## Execution ##

	main "$@"
