#!/usr/bin/env bash
##########################################################################
# Script Name  : openbox-keys
# Description  : Displays keybindings from ~/.xbindkeysrc
# Dependencies : none
# Arguments    : none
# Author       : Richard B. Romig, 07 Aug 2021
# Email        : rick.romig@gmail.com
# Comments     : Xbindkeys is independent of window manager & desktop environment
# TODO (Rick)  : Display in a dialog box center screen
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Variables ##

readonly script=$(basename "$0")
readonly version="0.1.3"
readonly updated="19 Dec 2021"
readonly bindkey_path=$HOME"/.xbindkeysrc"
readonly sed_file="$HOME/bin/files/xbindkey.sed"

## Execution ##

clear
[[ -f "$bindkey_path" ]] || die "$bindkey_path not found" 1
[[ -f "$sed_file" ]] || die "A required file ($(basename "$sed_file")) not found." 2
sed -nf "$sed_file" "$bindkey_path" | less
leave "$script v$version ($updated)"
