#!/usr/bin/env bash
##########################################################################
# Script Name  : openbox-keys
# Description  : Displays keybindings from ~/.xbindkeysrc
# Dependencies : none
# Arguments    : none
# Author       : Richard B. Romig, 07 Aug 2021
# Email        : rick.romig@gmail.com
# Created      : 07 Aug 2021
# Last updated : 03 Oct 2024
# Comments     : Xbindkeys is independent of window manager & desktop environment
# TODO (Rick)  : Display in a dialog box center screen
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

main() {
  local bindkey_path sed_file script version
  script=$(basename "$0"); script
  version="1.4.24277"
  bindkey_path=$HOME"/.xbindkeysrc"
  sed_file="$HOME/bin/files/xbindkey.sed"

  clear
  [[ -f "$bindkey_path" ]] || die "$bindkey_path not found" 1
  [[ -f "$sed_file" ]] || die "A required file ($(basename "$sed_file")) not found." 2
  sed -nf "$sed_file" "$bindkey_path" | less
  leave "$script v$version"
}

## Execution ##

main "$@"
