#!/usr/bin/env bash
##########################################################################
# Script Name  : pingit
# Description  : Checks if a host is on the local network
# Dependencies : ping
# Arguments    : Last octet of target computer's IP address
# Author       : Copyright © 2023 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 2023
# Updated      : 24 Jun 2026
# Comments     : Assumes a /24 (Class C) network
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib
source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

## Global Variables ##

readonly script="${0##*/}"
readonly version="3.9.26175"
EC=0

## Functions ##

help() {
	local errcode="${1:-1}"
	local updated="24 Jun 2026"
	cat << _HELP_
${orange}$script${normal} $version ($updated)
Pings an IP address on the local network.

${green}Usage:${normal} $script [last-octet] [OPTION]
${orange}Available options${normal}
  1-254        Ping local address ending with that octet.
  -h | --help  Show this help message and exit.

${orange}Example:${normal} $script 42
${orange}Note:${normal}
  1. Address must be an integer in the range of 1 to 254, representing the last octet of the target address.
  2. Assumes a Class C (CIDR /24) network.
_HELP_
  exit "$errcode"
}

validIP() {
  local octet="$1"
  local re="^[0-9]+$"
  if [[ -z "$octet" ]]; then
    printf "%s No argument passed. No host IP.\n" "$RED_ERROR" <&2
    EC="$E_MISSING_ARG"
  elif [[ $1 =~ $re ]] 2>/dev/null; then
    # Argument is an integer value
    if [[ "$octet" -gt 0 && "$octet" -lt 255 ]]; then
      printf "%s.%s is a valid IP address.\n" "$LOCALNET" "$octet"
      EC=0
    else
      printf "%s %s.%s is not a valid IP address.\n" "$RED_ERROR" "$LOCALNET" "$octet" <&2
      EC="$E_INVALID_ARG"
    fi
  else
    printf "%s Invalid argument - %s.\n" "$RED_ERROR" "$octet" <&2
    EC="$E_INVALID_ARG"
  fi
  return "$EC"
}

pingIP() {
  local localip hostip
  hostip="$1"
  localip="$(local_ip)"
  # Attempt to ping the target IP address
  if [[ "$localip" == "$hostip" ]]; then
    printf "\n%s.%s is the computer you're pinging from.\n" >&2 "$LOCALNET" "$hostip"
    EC="$E_INVALID_ARG"
    return "$EC"
  fi
  ping -c 5 "$LOCALNET.$hostip"
  EC="$?"
  return "$EC"
}

main() {
	[[ "$1" = "-h" || "$1" = "--help" ]] && help "$EC"
  local hostip="$1"
  # validIP "$hostip" # Sets EC and displays status message
  # [[ "$EC" -ne 0 ]] && help "$EC"
  # pingIP "$hostip"  # Sets EC and displays information
  if validIP "$hostip"; then
    pingIP "$hostip"
  else
    help "$?"
  fi
  over_line "$script $version"
  exit "$EC"
}

## Execution ##

main "$@"
