#!/usr/bin/env bash
##########################################################################
# Script Name  : purge-rc
# Description  : Purges config files from packages in the 'rc' state
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2020, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | eick.romig@mymetronet.net
# Created      : 27 Sep 2020
# Updated      : 17 Feb 2026
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

list_rc_packages() {
  printf "Packages in the 'rc' state:\n"
  awk '/^rc/ {print $1,$2}' <(dpkg --list) | sort -r
}

purge_rc_packages() {
  local rcpkg
  printf "\nThese packages are in the remove/deinstall state with only the config files.\n"
  if yes_or_no "Are you sure you want to purge the config files for these packages?"; then
    sudo_login 2
    printf "\n%sPurging obsolete configuration files...%s\n" "$green" "$normal"
    # Can't use process substituion for this.
    for rcpkg in $(dpkg --list | awk '/^rc/ {print $2}'); do
      sudo apt remove --purge "$rcpkg" -yy
    done
  else
    printf "\nNo action taken. No packages were purged.\n"
  fi
}

list_headers() {
  printf "\n%sInstalled linux headers and images:%s\n" "$green" "$normal"
  awk '/linux-image/ || /linux-headers/ {print $2}' <(dpkg --list) | sort -r
}

main() {
  local script="${0##*/}"
  local -r version="4.12.26048"
  if grep -q '^rc' <(dpkg --list); then
    list_rc_packages
    purge_rc_packages
  else
    printf "%sNo packages in the 'rc' state to be purged.%s\n" "$green" "$normal"
  fi
  list_headers
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
