#!/usr/bin/env bash
###############################################################################
# Script Name  : randpic
# Description  : Copies random image file from ~/Pictures to ~/tmp/pics
# Dependencies : imagemagick
# Arguments    : None
# Author       : Copyright (C) 2019, Richard Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 02 June 2019
# Updated      : 18 Aug 2024
# Comments     :
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

##  Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="3.6.24231"
readonly tmp_pics=$HOME"/tmp/journal"

## Functions ##

# check_package and leave functions and colors declared in functionlib

valid_folder() {
  local folder="$1"
  case "$folder" in
    album-art|DCIM|Facebook|Tech-pics|unsorted|wallpaper|web-site-pics/Zipped )
      return "$FALSE"
    ;;
    * )
      return "$TRUE"
  esac
}

valid_image() {
  local filename="$1"
  local ext="${filename##*.}"
  ext="${ext,,}"
  case $ext in
    bmp|gif|jpeg|jpg|png|tiff )
      return "$TRUE"
    ;;
    * )
      return "$FALSE"
  esac
}

## Execution ##

# Create temporary picture directory if it doesn't already exist
[[ -d "$tmp_pics" ]] || mkdir -p "$tmp_pics"

check_package imagemagick
clear
while true; do
  # Randomly select an image folder from ~/Pictures/
  pic_dir=$(find ~/Pictures -maxdepth 1 -type d | shuf -n1)
  sel_dir=$(basename "$pic_dir")
  valid_folder "$sel_dir" || continue

  # Choose a random image file from the selected folder
  random_file=$(find "$pic_dir" -maxdepth 1 -type f | shuf -n1)
  pic_file="$(basename "$random_file")"
  valid_image "$pic_file" || continue

  # Accept or reject selected file
  clear
  box "Random Image Selector ($_script v$_version)"
  echo -e "Selects a random image from ~/Pictures\n"
  echo "${blue}Selected image: ${orange}$sel_dir/$pic_file${normal}"
  cp -p "$pic_dir/$pic_file" "$tmp_pics"
  /usr/bin/display -geometry +600+20 "$tmp_pics/$pic_file" &
  pic_pid="$!"
  echo $'\n'$"${blue}Options:${normal}"
  COLUMNS=12
  options=( "Accept the selected image and select another image." \
    "Accept the selected image and exit." \
    "Reject the selected image and select another image." \
    "Reject the selected image and exit." \
    "Delete the selected image and select another image." )
  PS3="Chose an option: "
  select _opt in "${options[@]}"; do
    case $REPLY in
      1 )
        echo $'\n'$"${blue}Accepted image:${normal} $sel_dir/$pic_file"
        echo $'\n'$"Selecting another random image..."
        kill $pic_pid
        sleep 2
        break
      ;;
      2 )
        echo -e "\n${blue}Accepted image:${normal} $sel_dir/$pic_file\n"
        kill $pic_pid
        leave ""
      ;;
      3 )
        echo $'\n'$"${blue}Rejected image:${normal} $sel_dir/$pic_file"
        kill $pic_pid
        echo $'\n'$"Selecting another random image..."
        rm "$tmp_pics/$pic_file"
        sleep 2
        break
      ;;
      4 )
        echo -e "\n${blue}Rejected image:${normal} $sel_dir/$pic_file\n"
        kill $pic_pid
        rm "$tmp_pics/$pic_file"
        leave ""
      ;;
      5 )
        echo -e $'\n'$"${blue}Image deleted:${normal} $sel_dir/$pic_file"
        kill $pic_pid
        echo $'\n'$"Selecting another random image..."
        rm "$tmp_pics/$pic_file"
        rm "$pic_dir/$pic_file"
        sleep 2
        break
      ;;
      * )
        echo $'\n'$"${lightred}Invalid option. Try again.${normal}"
    esac
  done
done
