#!/usr/bin/env bash
###############################################################################
# Script Name  : refresh-net
# Description  : Refresh network connections
# Dependencies : systemctl (if systemd), service (if sysvinit), strings
# Args         : None
# Author       : Copyright (C) 2025, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : Unknown
# Updated      : 30 May 2026
# Comment      :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
###############################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib
source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

## Functions ##

restart_network() {
  local init_sys
  init_sys=$(awk 'match($0, /(systemd|sysvinit)/) { print toupper(substr($0, RSTART, RLENGTH));exit; }' < <(strings /sbin/init))
  printf "Restarting network...\n"
  case "$init_sys" in
    "SYSTEMD" )
      sudo systemctl restart NetworkManager.service ;;
    "SYSVINIT" )
      sudo service network-manager restart ;;
    * )
      printf "Init system is undetermined.\n"
      return
  esac
  sleep 3
}

main() {
	local script="${0##*/}"
  local version="2.3.26150"
  sudo_login 2
  check_package strings
  restart_network
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
