#!/usr/bin/env bash
###############################################################################
# Script Name  : ren-space
# Description  : replaces spaces with underscores in filenames in the current
#                directory
# Dependencies : rename, egrep
# Args         : None
# Author       : Richard Romig
# Email        : rick.romig@gmail.com
# Created      : Unknown
# Updated      : 07 Jun 2024
# Comment      :
# License      : GNU General Public License, version 2.0
###############################################################################

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="1.4.24159"

## Execution ##

echo "$_script v$_version  - renames filenames containing spaces."

# check for filenames containing spaces
find . -maxdepth 1 -type f | grep -q " " && rename -v 's/ /_/g' ./* || echo "No filenames containing spaces found."

exit
