#!/usr/bin/env bash
###############################################################################
# Script Name  : ren-space
# Description  : replaces spaces with underscores in filenames in the current
#                directory
# Dependencies : rename, egrep
# Args         : None
# Author       : Richard Romig
# Email        : rick.romig@gmail.com
# Comment      :
# License      : GNU General Public License, version 2.0
###############################################################################

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="1.0.4"
readonly _updated="17 Oct 2023"

## Execution ##

echo "$_script v$_version  - renames filenames containing spaces."
echo "Copyright 2018-2022, Richard Romig"
echo -e "Last updated: $_updated\n"

# check for filenames containing spaces

find . -maxdepth 1 -type f | grep -q " " && rename -v 's/ /_/g' ./* || echo "No filenames containing spaces found."

exit
