#!/usr/bin/env bash
###############################################################################
# Script Name  : ren-space
# Description  : replaces spaces with underscores in filenames in the current
#                directory
# Dependencies : None
# Args         : None
# Author       : Richard Romig
# Email        : rick.romig@gmail.com
# Created      : Unknown
# Updated      : 03 Oct 2024
# Comment      :
# License      : GNU General Public License, version 2.0
###############################################################################

set -eu

main() {
  local script version
  script=$(basename "$0")
	version="1.5.24277"
	echo "$script v$version  - renames filenames containing spaces."
	# check for filenames containing spaces in the current directory
	find . -maxdepth 1 -type f | grep -q " " && rename -v 's/ /_/g' ./* || echo "No filenames containing spaces found."
	printf "%s v%s\n" "$script" "$version"
	exit
}

## Execution ##

main "$@"
