#!/usr/bin/env bash
#############################################################################
# Script Name  : rename-host
# Description  : Changes the system hostname
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2019, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 06 Nov 2019
# Updated      : 11 Jul 2025
# Comments     : Changes the hostname in both /etc/hostname and /etc/hosts.
#              : Rules based on hostname(7) man page
#              : Hostname length limited to 5-15 characters for NETBIOS compatibility.
#              : old_host & new_host variables are global for convenience.
#              : May get a “unable to resolve host” error after changing hostname in /etc/hosts. It will go away after reboting.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
#############################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="6.0.25192"
readonly old_host="${HOSTNAME:-$(hostname)}"
declare -l new_host=""

## Functions ##

hostname_rules() {
  cat << _RULES_

${lightblue}Hostname Rules${normal}
  ${orange}*${normal} 5-15 characters (for NETBIOS compatibility)
  ${orange}*${normal} a-z, 0-9, - (hyphen)
  ${orange}*${normal} lowercase (uppercase will be converted)
  ${orange}*${normal} no special characters (except a hyphen)
  ${orange}*${normal} first character cannot be a hyphen or a digit
  ${orange}*${normal} last character cannot be a hyphen
_RULES_
}

get_new_hostname() {
  local minlen=5
  local maxlen=15
  while true; do
    printf "\nCurrent hostname is %s\n\n" "$old_host"
    read -rp "Enter new hostname (Enter to cancel): " new_host
    # Check new hostname against the rules
    case "$new_host" in
      -* )
        printf "\n%sHostname cannot begin with a hypen.%s\n" "$orange" "$normal" >&2
        hostname_rules
        continue
        ;;
      *- )
        printf "\n%sHostname cannot end with a hyphen.%s\n" "$orange" "$normal" >&2
        hostname_rules
        continue
        ;;
      [0-9]* )
        printf "%s\nHostname cannot begin with a digit.%s\n" "$orange" "$normal" >&2
        hostname_rules
        continue
        ;;
      *[^a-zA-Z0-9-]* )
        printf "\n%sHostname cannot contain any special characters.%s\n" "$orange" "$normal" >&2
        hostname_rules
        continue
        ;;
      '' )
        printf "Rename hostname canceled. No changes made.\n"
        over_line "$script $version"
        exit
    esac
    if [[ ${#new_host} -le "$minlen" || ${#new_host} -gt "$maxlen" ]]; then
      printf "\n%sHostname must be between %d and %d characters.%s\n" "$orange" "$minlen" "$maxlen" "$normal" >&2
      hostname_rules
      continue
    fi

    # Compare new hostname with the old hostname
    if [[ "$new_host" == "$old_host" ]]; then
      printf "%sHostnames are the same.%s\n" "$orange" "$normal" >&2
      hostname_rules
      continue
    else
      printf "\n%s%s is a valid hostname.%s\n" "$green" "$new_host" "$normal"
      break
    fi
  done
}

change_hostname() {
  printf "\nChanging the hostname from %s to %s ...\n" "$old_host" "$new_host"
  sudo sed -i "s/$old_host/$new_host/" /etc/hosts
  sudo hostnamectl set-hostname "$new_host"
  printf "Hostname successfully changed. Reboot to ensure the change takes effect.\n"
  # sudo systemctl restart systemd-resolved.service
}

main() {
  sudo_login 2
  printf "Renames the system hostname.\n"
  hostname_rules
  get_new_hostname
  change_hostname
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
