#!/usr/bin/env bash
##########################################################################
# Script Name  : resize-pics
# Description  : Resizes and changes the compression of images/
# Dependencies : imagemagick
# Arguments    : none
# Author       : Copyright (c) 2022, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com
# Created      : 22 Jun 2022
# Updated      : 23 Jun 2024
# Comments     : Must be run from the working directory.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

## Functions ##

find_images() {
  local images
  images=$(find . -maxdepth 1 -type f -iname "*.jpg")
  [[ "$images" ]] && return "$TRUE" || return "$FALSE"
}

resize_pics() {
  local img
  [[ -d ./modpics ]] || mkdir -p ./modpics
  for img in *.jpg; do
    convert "$img" -resize 800x800 modpics/"${img%}"
  done
  convert 'modpics/*.jpg[800x>]' -quality 90 -set filename:base "%[basename]" "modpics/%[filename:base].jpg"
}

main() {
  local script version
  script=$(basename "$0")
  version="1.3.24277"
  find_images || die "No JPEG images in current directory to process." 1
  check_package imagemagick
  resize_pics
  leave "$script v$version"
}

## Execution ##

main "$@"
