#!/usr/bin/env bash
##########################################################################
# Script Name  : resize-pics
# Description  : Resizes and changes the compression of images/
# Dependencies : imagemagick
# Arguments    : none
# Author       : Copyright (c) 2022, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 22 Jun 2022
# Updated      : 08 Sep 2025
# Comments     : Must be run from the working directory.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

# set -eu

## Functions ##

find_images() {
  local images
  images=$(find . -maxdepth 1 -type f -iname "*.jpg" | wc -l)
  [[ "$images" -gt 0 ]] && return "$TRUE" || return "$FALSE"
}

resize_pics() {
  local size image
  size="$1"
  [[ -d ./resized ]] || mkdir -p ./resized
  for image in *.jpg; do
    convert "$image" -resize "$size"x"$size" resized/"${image%}"
  done
}


main() {
	local script="${0##*/}"
  local version="1.4.25251"
	local size="${1:-800}"
  find_images || die "No JPEG images in current directory to process." 1
  check_package imagemagick
  resize_pics "$size"
  leave "$script $version"
}

## Execution ##

main "$@"
