#!/usr/bin/env bash
###############################################################################
# Script Name  : rm-tilde
# Description  : Remove backup files with trailing ~ (tilde)
# Dependencies : find, rm
# Arguments    : None
# Author       : Richard Romig
# Email        : rick.romig@gmail.com
# Comment      :
# License      : GNU General Public License, version 2.0
###############################################################################

_script=$(basename "$0"); readonly _script
readonly _version="1.2.4"
readonly _updated="18 Mar 2024"

nbu=$(find . -maxdepth 1 -type f -regex '\./.*~$'  | wc -l)

printf "Removing %s '~' backup " "$NBU"
(( nbu == 1 )) && printf "file.\n" || printf "files.\n"
(( nbu != 0 )) && find ./ -maxdepth 1 -type f -regex '\./.*~$' -print -exec rm {} \;
printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"

exit
