#!/usr/bin/env bash
##########################################################################
# Script Name  : rm-tilde
# Description  : Remove backup files with trailing ~ (tilde)
# Dependencies : find
# Arguments    : None
# Author       : Copyright © 2025 Richard Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : unknown
# Updated      : 26 Mar 2026
# Comment      :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Functions ##

remove_tilde() {
	local nbu
	nbu=$(wc -l < <(find . -maxdepth 1 -type f -regex '\./.*~$'))
	printf "Removing %d '~' backup " "$nbu"
	(( nbu == 1 )) && printf "file.\n" || printf "files.\n"
	(( nbu != 0 )) && find . -maxdepth 1 -type f -regex '\./.*~$' -print -exec rm {} \;
}

main() {
	local -r script="${0##*/}"
	local -r version="3.1.26085"
	remove_tilde
	printf "%s %s\n" "$script" "$version"
	exit
}

## Execution ##

main "$@"
