#!/usr/bin/env bash
#############################################################################
# Script Name  : set-resume
# Description  : Set the RESUME environment variable after update-initramfs error
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2019, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 12 Nov 2019
# Updated      : 14 Jul 2025
# Comments     : Extracts swap partition UUID from output of /sbin/blkid
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

print_message() {
  cat << _MESSAGE_
  Set RESUME environment variable after an update-initramfs error message.
  The error message wil be similar to:
  I: The initramfs will attempt to resume from /dev/sda2
  I: (UUID=09e25397-4a2c-4fb0-a605-a7013eecb59c)
  I: Set the RESUME variable to override this.

_MESSAGE_
}

get_swap_uuid() {
  local swap_uuid
  if antix_mx; then
    swap_uuid=$(/sbin/blkid | awk -F\" '/swap/ {print $4}')
  else
    swap_uuid=$(/sbin/blkid | awk -F\" '/swap/ {print $2}')
    [[ "$swap_uuid" == "LABEL=swap" ]] && swap_uuid=$(/sbin/blkid | awk -F\" '/swap/ {print $3}')
  fi
  printf "%s" "$swap_uuid"
}

set_resume() {
  local swap_uuid
  printf "\nExtracting the swap partition UUID using /sbin/blkid ...\n"
  swap_uuid=$(get_swap_uuid)
  if [[ "$swap_uuid" ]]; then
    local -r resume_path="/etc/initramfs-tools/conf.d/resume"
    sudo_login 2
    printf "\nSWAP UUID: %s\n" "$swap_uuid"
    printf "\nSetting the RESUME environment variable...\n"
    printf "RESUME=UUID=%s\n" "$swap_uuid" | sudo tee "$resume_path" > /dev/null
    printf "\nUpdating initramfs ...\n"
    sudo update-initramfs -u -k all
  else
    printf "No UUID for swap found.\n" >&2
  fi
}

main() {
  local script="${0##*/}"
  local -r version="6.1.25195"
  print_message
  set_resume
  over_line "$script $version" "-"
  printf "Reboot the system for the change to take affect.\n"
  exit
}

## Execution ##

main "$@"
