#!/usr/bin/env bash
###############################################################################
# Script Name  : sftpin
# Description  : Connects to host computer via sftp
# Dependencies : sftp (openssh-client)
# arguments    : Last octet of target host's IP address
# Author       : Copyright (C) 2017, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 08 Dec 2017 (Joe Collins)
# Updated      : 20 Ju1 2025
# Comments     : Based on script by Joe Collins.
#              : LOCALNET and valid_ip() are declared in functionlib
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="2.3.25201"

## Functions ##

help() {
  local errcode="${1:-2}"
  local updated="20 Ju1 2025"
  cat << _HELP_
${orange}$script${normal} $version ($updated)
Log in to a remote server using Secure File Transfer Protocol (SFTP).

${green}Usage:${normal} $script <last_octet>
${orange}Example:${normal} $script 15
Argument is the last octet of the remote server's IP address.
Assumes a /24 network.
_HELP_
  exit "$errcode"
}

main() {
  local hostip
  if [[ $# -eq 0 ]]; then
    printf "%s No argument passed.\nEnter last octet of remote server's IP address.\n" "$RED_ERROR" >&2
    help 2
  elif [[ "$1" == "-h" || "$1" == "--help" ]]; then
    help 0
  else
    valid_ip "$1" && hostip="$1"
    /usr/bin/sftp "$LOCALNET.$hostip"
  fi
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
