#!/usr/bin/env bash
###############################################################################
# Script Name  : sftpin
# Description  : Connects to host computer via sftp
# Dependencies : sftp (openssh-client)
# arguments    : Last octet of target host's IP address
# Author       : Copyright (C) 2023, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : unknown
# Updated      : 16 Oct 2024
# Comments     : Based on script by Joe Collins.
#              : LOCALNET and valid_ip() are declared in functionlib
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

script=$(basename "$0"); readonly script
readonly version="2.3.24290"

## Functions ##

help() {
  local errcode updated
  errcode="${1:-2}"
  updated="16 Oct 2024"
  cat << _HELP_
${orange}$script${normal} $version ($updated)
Log in to a remote server using Secure File Transfer Protocol (SFTP).

${green}Usage:${normal} $script <last_octet>

${orange}Example:${normal} $script 15
Argument is the last octet of the remote server's IP address.
Assumes a /24 network.
_HELP_
  exit "$errcode"
}

main() {
  local hostip
  if [[ $# -eq 0 ]]; then
    printf "%s No argument passed.\nEnter last octet of remote server's IP address.\n" "$RED_ERROR" >&2
    help 2
  elif [[ "$1" == "-h" || "$1" == "--help" ]]; then
    help 0
  else
    valid_ip "$1" && hostip="$1"
    /usr/bin/sftp "$LOCALNET.$hostip"
  fi
  over_line "$script v$version"
  exit
}

## Execution ##

main "$@"
