#!/usr/bin/env bash
###############################################################################
# Script Name  : sftpin
# Description  : Connects to host computer via sftp
# Dependencies : sftp
# arguments    : Last octet of target host's IP address
# Author       : Richard Romig
# Email        : rick.romig@gmail.com
# Comment      : Based on script by Joe Collins, EzeeLinux.com
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="2.0.2"
readonly _updated="14 Feb 2022"

# localnet is declared in functionlib

## Execution ##

echo "$_script v$_version ($_updated)"
echo "Log in to a remote server using Secure File Transfer Protocol (SFTP)."

# Assign IP address to HOSTIP

valid_ip "$1" && hostip="$1"

/usr/bin/sftp "$localnet.$hostip"

exit
