#!/usr/bin/env bash
#####################################################################
# Script Name  : show-cron
# Description  : Shows when anacron jobs were last run and displays
#              : crontabs for all normal users and root.
# Dependencies : anacron, cron, crontab
# Arguments    : None
# Author       : Copyright (C) 2018, Richard Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 06 Mar 2018
# Updated      : 16 Aug 2026
# Version      : 6.8.26228
# Comments     : Requires sudo privileges
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

# shellcheck source=/home/rick/bin/functionlib.bash
source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

anacron_jobs() {
  local -r interval="$1"
  local -r cron_dir="/etc/cron.$interval"
  local -i count
  count=$(wc -l < <(find "$cron_dir" -maxdepth 1 -type f -iname \*))
  (( count > 0 )) && return "$TRUE" || return "$FALSE"
}

print_anacron_jobs() {
  local -r interval="$1"
  local -r cron_dir="/etc/cron.$interval"
  awk -F/ '{print $NF}' < <(find "$cron_dir" -maxdepth 1 -type f -iname \*)
  return 0
}

list_anacron_jobs() {
  local -r interval="$1"
  local cron_spool
  cron_spool=$(sudo cat /var/spool/anacron/cron."$interval")
  printf "\n%sAnacron %s:%s Last run on %s\n" "$orange" "${interval^}" "$normal" "$cron_spool"
  if anacron_jobs "$interval"; then
    print_anacron_jobs "$interval"
  else
    printf "No jobs scheduled.\n"
  fi
  return 0
}

show_anacron() {
  local interval intervals
  intervals=( daily weekly monthly )
  for interval in "${intervals[@]}"; do list_anacron_jobs "$interval"; done
  return 0
}

show_user_cron() {
  local -i max_users num_users
  local norm_user
  num_users=$(awk -F: '$3 >= 1000 && !($1 == "nobody" && $3 == 65534) {SUM+=1} END {print SUM}' /etc/passwd)
  local -i index=1000  # starting point for regular users
  max_users=$(( num_users + index ))

  while [[ "$index" -le "$max_users" ]]; do
    norm_user="$(awk -v pat="$index" -F: '$0~pat{print $1}' /etc/passwd)"
    if [[ "$norm_user" ]]; then
      printf "\n%sCron jobs for %s:%s\n" "$orange" "${norm_user^}" "$normal"
      grep -v '^#' < <(sudo crontab -l -u "$norm_user") | awk '{print $1,$2,$3,$4,$5"|"$6}' | column -ts "|"
    fi
    (( index++ ))
  done
  return 0
}

show_root_cron() {
  printf "\n%sCron jobs for root:%s\n" "$orange" "$normal"
  grep -v '^#' < <(sudo crontab -l) | awk '{print $1,$2,$3,$4,$5"|"$6}' | column -ts "|"
  return 0
}

main() {
  local -r script="${0##*/}"
  local -r version="6.8.26228"
  local -r lhost="${HOSTNAME:-$(hostname)}"
  sudo_login 0
  clearscreen
  printf "%s%sAnacron and Cron Jobs for %s%s\n" "$bold" "$green" "$lhost" "$normal"
  show_anacron
  show_user_cron
  show_root_cron
  over_line "$script $version" "-"
  exit
}

main "$@"
