#!/usr/bin/env bash
###############################################################################
# Script Name  : sshin
# Description  : Connects to host computer via SSH
# Dependencies : ssh (openssh-client)
# Arguments    : Last octet of target host's IP address
# Author       : Copyright (C) 2017, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 07 Oct 2017  (Joe Collins' original script)
# Updated      : 08 Jun 2026
# Comments     : Based on a script by Joe Collins.
#              : LOCALNET and valid_ip() are declared in functionlib
#              : X11 forwarding should be enabled in /etc/ssh/sshd_config
#              : An invalid IP will exit the script with error code from valid_ip() in functionlib
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
###############################################################################

## Source function library ##
# shellcheck source=/home/rick/bin/functionlib
source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

# Variables

readonly script="${0##*/}"
readonly version="3.1.26159"

## Functions ##

help() {
  local errcode="${1:-1}"
  local updated="08 Jun 2026"
  cat << _HELP_

${orange}$script${normal} $version ($updated)
Log in to a remote server using Secure Shell (SSH).

${green}Usage:${normal} $script [last-octet [X]] [-h | --help]
${orange}Example:${normal} $script 15
${orange}Example:${normal} $script 11 X
First argument is the last octet of the remote server's IP address.
Second argment X|x enables X11 forwarding. Any other argument will connect via SSH without X11 forwarding.
Assumes a /24 network.
_HELP_
  exit "$errcode"
}

connect_ssh() {
  local hostip="$1"
  local x_opt="${2::1}"
  if valid_ip "$hostip"; then
    case "${x_opt^}" in
      X )
        printf "Connecting with X11 forwarding enabled.\n"
        /usr/bin/ssh -X "$LOCALNET.$hostip"
        ;;
      * )
        printf "Connecting without X11 forwarding enabled.\n"
        /usr/bin/ssh "$LOCALNET.$hostip"
    esac
  else
    help "$?"
  fi
}

main() {
  local hostip="$1"
  local x_opt="${2:-z}"
  [[ "$1" == "-h" || "$1" == "--help" ]] && help 0
  [[ "$hostip" ]] || read -rp "Enter last octet of remote server's IP address. " hostip
  connect_ssh "$hostip" "$x_opt"
  over_line "$script $version"
  exit
}

# Execution

main "$@"
