#!/usr/bin/env bash
##########################################################################
# Script Name  : sshlocal
# Description  : connect to remote servers via SSH using the .local domain
# Dependencies : OpenSSH, OpenSSH_server, fzf
# Arguments    : X or x to enable X11 forwarding
# Author       : Copyright © 2025 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 14 Feb 2025
# Updated      : 03 Aug 2026
# Version      : 4.2.26215
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

# shellcheck source=/home/rick/bin/functionlib.bash
source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

connect_server() {
	local -r server="${1}.local"
	printf "%sConnecting to %s ...%s\n" "$lightyellow" "$server" "$normal"
	ssh "$server"
	return 0
}

connect_server_x() {
	local -r server="${1}.local"
	printf "%sConnecting to %s (X11 forwarding) ...%s\n" "$lightyellow" "$server" "$normal"
	ssh -X "$server"
	return 0
}

select_server() {
	local -r local_host="${HOSTNAME:-$(hostname)}"
	local FMENU="fzf --header=$script \
           --layout=reverse \
           --exact \
           --border=bold \
           --border=rounded \
           --margin=5% \
           --color=dark \
           --height=95% \
           --info=hidden \
           --header-first \
           --bind change:top \
           --prompt"
local -r servers=(
		hp-800g2-sff
		hp-6005
		e6500-deb
		probook-6570b
		hp-8300
		dell-9020
		hp-8300-usdt
		hp-800-g1-usdt
		hp-800-g1-dm
		probook-6570
		hp-probook-6570
		hp-850-g3
		hp-2560p e-475m
	)
	local server
	server=$($FMENU "Choose the remote server: " < <(printf "%s\n" "${servers[@]}"))
	[[ "$local_host" == "$server" ]] && { printf "Attempting to connect to local client.\n" >&2; return "$E_INVALID_HOST"; }
	[[ "$server" ]] || { printf "No server selected.\n"; return "$E_MISSING_ARG"; }
	if default_no "Enable X11 forwarding?"; then
		printf '\e[A\e[K'
		connect_server_x "$server"
	else
		printf '\e[A\e[K'
		connect_server "$server"
	fi
	return 0
}

main() {
	local -r script="${0##*/}"
	local -r version="4.2.26215"
	local -i exit_code=0
	check_package fzf
	clearscreen
	select_server
	exit_code="$?"
  over_line "$script $version"
	exit "$exit_code"
}

main "$@"
