#!/usr/bin/env bash
#############################################################################
# Script Name  : sync-home
# Description  : Synchronize ~/Documents/homepage with ~/Dropbox/homepage
# Dependencies : rsync
# Arguments    : none
# Author       : Copyright © 2019 Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 24 Sep 2019
# Updated      : 19 Jan 2026
# Comments     : Creates a compressed tar archive of the folder's contents.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

check_host() {
	local -r main_host="$1"
	local -r local_host="${HOSTNAME:-$(hostname)}"
	[[ "$local_host" == "$main_host" ]] && return "$TRUE" || return "$FALSE"
}

remove_bu_files() {
	local -r homepage_d="$1"
  printf "\nRemoving backup files (if any)...\n"
  find "$homepage_d"/ -type f -regex '\./.*~$' -print -delete
  find "$homepage_d"/ -maxdepth 2 -type f -name "*.bak" -exec rm -v {} \;
}

archive_homepage() {
	local archive homepage_d archive_d
	homepage_d="$1"
	archive_d="$2"
	archive="homepage-$(date +%y%m%d).tar.gz"
	[[ -d "$archive_d" ]] || mkdir -p "$archive_d"
	printf "\nBacking up %s...\n" "$homepage_d"
	tar -czvf "$archive_d/$archive" -C "$HOME/gitea" homepage
	printf "\nRemoving archives more than three months old...\n"
	find "$archive_d" -mtime +90 -print -delete
}

sync_dropbox() {
	local -r archive_d="$1"
	local -r homepage_d="$2"
	local -r dropbox_d="$HOME/Dropbox/homepage"
	[[ -d "$dropbox_d" ]] || return
	printf "\nSynchronizing %s with %s...\n" "$homepage_d" "$dropbox_d"
	rsync -av --delete --exclude '.git' --exclude '.gitignore' "$homepage_d"/ "$archive_d"/ "$dropbox_d"
}

main() {
	local -r script="${0##*/}"
	local -r version="6.12.26019 "
	local -r main_host="hp-800g2-sff"
	local -r homepage_dir="$HOME/gitea/homepage"
	local -r archive_dir="$HOME/Downloads/archives/homepage"
	printf "Archiving homepage files...\n"
	if check_host "$main_host"; then
		check_package rsync
		remove_bu_files "$homepage_dir"
		archive_homepage "$homepage_dir" "$archive_dir"
		sync_dropbox "$homepage_dir" "$archive_dir"
	else
		printf "%sScript must be run from %s.\n" "$RED_WARNING" "$main_host" >&2
	fi
	over_line "$script $version" "-"
	exit
}

## Execution ##

main "$@"
