#!/usr/bin/env bash
###############################################################################
# Script Name  : syncrick
# Description  : A script to sync data main PC and main laptop.
# Dependencies : rsync
# Arguments    : none, addresses hard coded.
# Author       : Copyright (C) 2023, Richard Romig 12 Mar 2023
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     : Uses a configuration file to store hostnames & IP addresses.
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="3.0.9"
readonly _updated="15 Oct 2023"
readonly local_host="${HOSTNAME:-$(hostname)}"
readonly conf_dir="$HOME/.config/scripts"
readonly conf_file="$_script.conf"

## Functions ##

create_conf() {
  [[ -d "$conf_dir" ]] || mkdir -p "$conf_dir"
  echo "Complete all fields"
  read -rp "Main hostname: " main_host
  read -rp "IP address (last octect): " main_ip
  read -rp "Laptop hostname: " lap_host
  read -rp "IP adddress (last octet): " lap_ip
  read -rp "Wireless IP (last octet): " wifi_ip

  echo "
  main_host='$main_host'
  main_ip='$main_ip'
  lap_host='$lap_host'
  lap_ip='$lap_ip'
  wifi_ip='$wifi_ip'
  " > "$conf_dir/$conf_file"
}

transfer_status() {
  # Exit script if transfer fails.
  xfr_status="$1"
  (( xfr_status != 0 )) && die "A transfer failed! Check network status." "$xfr_status"
}

sync_script() {
  local hostip="$1"

  echo $'\n'$"${orange}Syncing aliases...${normal}"
  rsync -avh --delete /home/"$USER"/.bash_aliases "$localnet.$hostip":
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing script configuration files...${normal}"
  rsync -avh --delete /home/"$USER"/.config/scripts/ "$localnet.$hostip":.config/scripts/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Password Databases...${normal}"
  rsync -avh --delete /home/"$USER"/Documents/Passwords* "$localnet.$hostip":Documents/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing homepage directory...${normal}"
  rsync -avh --delete /home/"$USER"/Documents/homepage/ "$localnet.$hostip":Documents/homepage/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing .local/share/doc ...${normal}"
  rsync -avh --delete /home/"$USER"/.local/share/doc/ "$localnet.$hostip":.local/share/doc/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing MOSFANET...${normal}"
  rsync -avh --delete /home/"$USER"/Documents/mosfanet/ "$localnet.$hostip":Documents/mosfanet/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Work..${normal}"
  rsync -avh --delete /home/"$USER"/Work/ "$localnet.$hostip":Work/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Templates...${normal}"
  rsync -avh --delete /home/"$USER"/Templates/ "$localnet.$hostip":Templates/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Pictures/wallpaper...${normal}"
  rsync -avh --delete /home/"$USER"/Pictures/wallpaper/ "$localnet.$hostip":Pictures/wallpaper/
  exit_status="$?"
  transfer_status "$exit_status"

  # Sync repositories
  echo $'\n'$"${orange}Syncing Gitea repositories...${normal}"
  rsync -avh --delete /home/"$USER"/gitea/ "$localnet.$hostip":gitea/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Projects repositories...${normal}"
  rsync -avh --delete /home/"$USER"/Projects/ "$localnet.$hostip":Projects/
  exit_status="$?"
  transfer_status "$exit_status"

  # Sync personal files.
  echo $'\n'$"${orange}Syncing Audio Books...${normal}"
  rsync -avh --delete /home/"$USER"/Audiobooks/ "$localnet.$hostip":Audiobooks/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Blogs...${normal}"
  rsync -avh --delete /home/"$USER"/Documents/Blogs/ "$localnet.$hostip":Documents/Blogs/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Dreams...${normal}"
  rsync -avh --delete /home/"$USER"/Documents/Dreams/ "$localnet.$hostip":Documents/Dreams/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Journals...${normal}"
  rsync -avh --delete /home/"$USER"/Documents/Journals/ "$localnet.$hostip":Documents/Journals/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Quotes...${normal}"
  rsync -avh --delete /home/"$USER"/Documents/Quotes/ "$localnet.$hostip":Documents/Quotes/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Tech Videos...${normal}"
  rsync -avh --delete /home/"$USER/Videos/Tech/" "$localnet.$hostip":Videos/Tech/
  exit_status="$?"
  transfer_status "$exit_status"
}

## Execution ##

SECONDS=0

printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"

[[ -f "$conf_dir/$conf_file" ]] || create_conf
source "$conf_dir/$conf_file"

# Check host
if [[ "$local_host" == "$main_host" ]]; then
  if ping -c 3 "$localnet.$lap_ip" >/dev/null 2>&1; then
    printf "Syncing %s to %s ...\n" "$main_host" "$lap_host"
    sync_script "$lap_ip"
    printf "\n%s synced with %s.\n" "$lap_host" "$main_host"
  elif ping -c 3 "$localnet.$wifi_ip" >/dev/null 2>&1; then
    printf "Syncing %s to %s ...\n" "$main_ip" "$lap_host"
    sync_script "$wifi_ip"
    printf "\n%s synced with %s.\n" "$lap_host" "$main_host"
  else
    printf "\n%s is not on the netwwork.\n" "$lap_host"
  fi
elif [[ "$local_host" == "$lap_host" ]]; then
  if ping -c 3 "$localnet.$main_ip" >/dev/null 2>&1; then
    printf "Syncing %s to %s ...\n" "$lap_host" "$main_host"
    sync_script "$main_ip"
    printf "\n%s synced with %s.\n" "$main_host" "$lap_host"
  else
    printf "\n%s is not on the netwwork.\n" "$main_host"
  fi
else
  die "Invalid client. $_script must be run from $main_host or $lap_host."
fi

box "$_script completed in $(format_time $SECONDS)"
exit
