#!/usr/bin/env bash
##########################################################################
# Script Name  : sync-repos
# Description  : Synchronize local Git repositories
# Dependencies : rsync
# Arguments    : See help() function for available options.
# Author       : Copyright © 2025 Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail | rick.romig@mymetronet.net
# Created      : 10 Aug 2025
# Updated      : 03 Aug 2026
# Version      : 3.6.26215
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
###############################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

# shellcheck source=/home/rick/bin/functionlib.bash
source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

help() {
	local -r script="$1"
	local -r version-"$2"
	local -ri errcode="${3:-1}"
	local -r updated="03 Aug 2026"
	cat << _HELP_
${orange}$script${normal} $version, Upated: $updated
Synchronixe Git repositories and work directories between local computers.

${green}Usage:${normal} $script [-ghlm]
${orange}Available options:${normal}
	-g	Synchronize git repositories to Gitea server.
	-h	Show this help message and exit.
	-l	Synchronize git repositories to HP 850 G3.
	-m	Synchronize git repositories to HP 800 G2.
_HELP_
  exit "$errcode"
}

valid_host() {
	local -r local_host="$1"
	case "$local_host" in
		hp-800g2-sff|hp-850-g3 )
			return "$TRUE" ;;
		* )
			return "$FALSE"
	esac
}

transfer_status() {
  local -i xfr_status="$1"
	if [[ "$xfr_status" -gt 0 ]]; then
		printf "%s A transfer failed. Code: %d. Check network status.\n" "$RED_ERROR" "$xfr_status" >&2
		return "$xfr_status"
	fi
	printf "Transfer successful\n"
	return 0
}

transfer() {
  local -ri host_ip="$1"
	local -r remote_host="$2"
  local -i ip_addr
  ip_addr="$(local_ip)"
  # Skip local machine:
  if [[ "$ip_addr" == "$host_ip" ]]; then
    printf "%sSkipping %s (local client)%s\n\n" "$green" "$remote_host" "$normal"
    return "$E_INVALID_HOST"
  fi
  # Check for machines and sync if on-line:
  printf "%sChecking for %s...%s\n" "$green" "$remote_host" "$normal"
  if ping -c 3 "$LOCALNET.$host_ip" >/dev/null 2>&1; then
    printf "...Syncing to %s\n" "$remote_host"
    sync_script "$host_ip"
    printf "\n... %s Synced!\n\n" "$remote_host"
  else
    printf "\n...Skipping %s! Not on network.\n\n" "$remote_host"
  fi
	return 0
}

sync_script() {
	local -ri hostip="$1"

  printf "\n%sSyncing Git Repositories...%s\n" "$orange" "$normal"
  rsync -avh --delete "$HOME"/gitea/ "$LOCALNET.$hostip":gitea/
  transfer_status "$?"

  printf "\n%sSyncing Projects Repositories...%s\n" "$orange" "$normal"
  rsync -avh --delete "$HOME"/Projects/ "$LOCALNET.$hostip":Projects/
  transfer_status "$?"

	printf "\n%sSyncing Deb Packages...%s\n" "$orange" "$normal"
	rsync -avh --delete "$HOME"/debpkgs/  "$LOCALNET.$hostip":debpkgs/
  transfer_status "$?"

  printf "\n%sSyncing ~/Work/dev/ ...%s\n" "$orange" "$normal"
  rsync -avh --delete "$HOME"/Work/dev/ "$LOCALNET.$hostip":Work/dev/
  transfer_status "$?"

	return 0
}

main() {
	local -r script="${0##*/}"
	local -r version="3.6.26215"
	local -i exit_code=0
	local -r local_host="${HOSTNAME:-$(hostname)}"
	local opt OPTARG OPTIND
	local -i noOpt="1"
	local -r optstr=":ghlm"
	valid_host "$local_host" || { printf "%s Invalid host: %s\n" "$RED_ERROR" "$local_host" >&2; help "$E_INVALID_ARG"; }
	check_package rsync
	while getopts "$optstr" opt; do
		case "$opt" in
			g ) transfer "16" "hp-8300-usdt" ;;
			h ) help "$script" "$version" 0 ;;
			l ) transfer "22" "hp-850-g3" ;;
			m ) transfer "10" "hp-800g2-sff" ;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help "$script" "$version" "$E_INVALID_ARG"
		esac
		exit_code="$?"
		noOpt=0
	done
	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
	shift "$(( OPTIND - 1 ))"
	over_line "$script $version"
	exit "$exit_code"
}

main "$@"
