#!/usr/bin/env bash
##########################################################################
# Script Name  : syncfin
# Description  : Synchronize files between main PC and finance laptop.
# Dependencies : none
# Arguments    : none
# Author       : Copyright (C) 2022 Richard B. Romig, 11 Mar 2022
# Email        : rick.romig@gmail.com
# Comments     : Uses a configuration to store hostnames and IP addresses.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

readonly _script=$(basename "$0")
readonly _version="0.2.1"
readonly _updated="10 Jan 2023"
readonly config_dir="$HOME/.config/scripts"
readonly config_file="$_script.conf"
readonly local_host="$(uname -n)"

## Functions ##

create_config() {
  [[ -d "$config_dir" ]] || mkdir -p "$config_dir"
  echo "Complete all fields"
  read -rp "Main hostname: " main_host
  read -rp "Main IP (last octect): " main_ip
  read -rp "Finance hostname: " fin_host
  read -rp "Finance IP (last octet): " fin_ip

  echo "
  main_host='$main_host'
  main_ip='$main_ip'
  fin_host='$fin_host'
  fin_ip='$fin_ip'
  " > "$config_dir/$config_file"
}

transfer_status() {
  # Exit script if transfer fails.
  xfr_status="$1"
  (( xfr_status != 0 )) && die "A transfer failed! Check network status."
}

transfer() {
  # Check remote host and sync if on line:
  if [[ "$local_host" == "$main_host" ]]; then
    if ping -c 3 "$localnet.$fin_ip" >/dev/null 2>&1; then
      echo "Syncing $main_host to $fin_host ..."
      sync_main
      echo $'\n'$"$fin_host synced with $main_host."
    else
      echo $'\n'$"... $fin_host is not on the network."
    fi
  else
    if ping -c 3 "$localnet.$main_ip" >/dev/null 2>&1; then
      echo "Syncing $fin_host to $main_host ..."
      sync_fin
      echo $'\n'$"$main_host synced with $fin_host."
    else
      echo $'\n'$"... $main_host is not on the network."
    fi
  fi
}

sync_fin() {
  echo  $'\n'$"${orange}Syncing Finance directory...${normal}"
  rsync -avzh --delete /home/"$USER"/Documents/Finance/ "$localnet.$main_ip":Documents/Finance/
  exit_status="$?"
  transfer_status "$exit_status"

  echo  $'\n'$"${orange}Syncing HomeBank directory...${normal}"
  rsync -avzh --delete /home/"$USER"/Documents/HomeBank/ "$localnet.$main_ip":Documents/HomeBank/
  exit_status="$?"
  transfer_status "$exit_status"

  echo  $'\n'$"${orange}Syncing HomeBank Archives..${normal}"
  rsync -avzh --delete /home/"$USER"/Downloads/archives/homebank/ "$localnet.$main_ip":Downloads/archives/homebank/
  exit_status="$?"
  transfer_status "$exit_status"
}

sync_main() {
  local vault_dir="$HOME/.local/share/doc"
  echo $'\n'$"${orange}Syncing bash aliases...${normal}"
  rsync -avzh --delete /home/"$USER"/.bash_aliases "$localnet.$fin_ip":
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing bin directory...${normal}"
  rsync -avzh --delete  --exclude '.git' /home/"$USER"/bin/ "$localnet.$fin_ip":bin/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing script configuration files...${normal}"
  rsync -avzh --delete /home/"$USER"/.config/scripts/ "$localnet.$fin_ip":.config/scripts/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing homepage directory...${normal}"
  rsync -avzh --delete /home/"$USER"/homepage/ "$localnet.$fin_ip":homepage/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Password Databases...${normal}"
  rsync -avzh --delete "$vault_dir/"/Rick_pwds* "$vault_dir/"/Passwords* "$localnet.$fin_ip":"$vault_dir/"/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Templates directory...${normal}"
  rsync -avzh --delete /home/"$USER"/Templates/ "$localnet.$fin_ip":Templates/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing wallpaper directory...${normal}"
  rsync -avzh --delete /home/"$USER"/Pictures/wallpaper/ "$localnet.$fin_ip":Pictures/wallpaper/
  exit_status="$?"
  transfer_status "$exit_status"
}

## Execution ##

SECONDS=0

printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"

[[ -f "$config_dir/$config_file" ]] || create_config
source "$config_dir/$config_file"

# Check arguments
if [[ "$local_host" == "$main_host" || "$local_host" == "$fin_host" ]]; then
	transfer
else
	die "Invalid client. $_script must be run from $main_host or $fin_host."
fi

box "$_script completed in $(format_time $SECONDS)"

exit
