#!/usr/bin/env bash
##########################################################################
# Script Name  : sync-i3
# Description  : Synchronizes key config files with main system.
# Dependencies : rsync
# Arguments    : None
# Author       : Copyright (C) 2022, Richard B. Romig, 01 Oct 2022
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     :
# TODO (Rick)  : Reconsider purpose. Do I want to sync i3 configs to config repo?
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.1.4"
readonly _updated="06 Jul 2023"
readonly fhost="hp-850-g3"
readonly lhost="${HOSTNAME:-$(hostname)}"
readonly mhost="hp-800g2-sff"
readonly mhostip=10
localip=$(local_ip); readonly localip

## Functions ##

sync_i3() {
  local cfg_dir="$HOME/.config/i3"
  local remote_destination="gitea/configs/i3"
  printf "\nSynchronizing i3 configuration files...\n"
  rsync -avh --delete "$cfg_dir/" "$localnet.$mhostip:$remote_destination/"
}

sync_kitty() {
  local cfg_dir="$HOME/.config/kitty"
  local remote_destination="gitea/configs/kitty"
  printf "\nSynchronizing kitty configuration files...\n"
  rsync -avh --delete "$cfg_dir/" "$localnet.$mhostip:$remote_destination/"
}

sync_rofi() {
  local cfg_dir="$HOME/.config/rofi"
  local remote_destination="gitea/configs/rofi"
  printf "\nSynchronizing rofi configuratinon files...\n"
  rsync -avh --delete "$cfg_dir/" "$localnet.$mhostip:$remote_destination/"
}

sync_bumblebee() {
  local cfg_dir="$HOME/.config/bumblebee-status"
  local remote_destination="gitea/configs/bumblebee-status"
  printf "\nSynchronizing bumblebee themes...\n"
  rsync -avh --delete "$cfg_dir" "$localnet.$mhostip:$remote_destination/"
}

main() {
  sync_i3
  sync_bumblebee
  sync_kitty
  sync_rofi
}

## Execution ##

printf "%-12s %s at %s.%s\n" "Local Host:" "$lhost" "$localnet" "$localip"
printf "Remote Host: %s at %s.%s\n" "$mhost" "$localnet" "$mhostip"
[[ "$lhost" != "$fhost" ]] && die "$_script must be run from $fhost."
main
printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
exit
