#!/usr/bin/env bash
###############################################################################
# Script Name  : SyncIt
# Description  :  A script to sync to local machines on SSH enabled network
# Dependencies : rsync,ip
# Arguments    : Last octet of the local network address
# Author       : Richard Romig, Joe Collins
# Email        : rick.romig@gmail.com
# Comments     : Based on script by Joe Collins at EzeeLinux.com
#              : LOCALNET is declared in functionlib
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

# Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

readonly _script=$(basename "$0")
readonly _version="2.6.5"
readonly _updated="11 Mar 2022"

## Functions ##

transfer_status() {
  # Exit script if transfer fails.
  xfr_status="$1"
  (( xfr_status != 0 )) && die "A transfer failed! Check network status."
}

sync_script() {
  # Start syncing folders

  echo $'\n'$"${orange}Syncing aliases...${normal}"
  rsync -avzh --delete /home/"$USER"/.bash_aliases "$localnet.$hostip":
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing bin...${normal}"
  rsync -avzh --delete /home/"$USER"/bin/ "$localnet.$hostip":bin/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing debpkgs...${normal}"
  rsync -avzh --delete /home/"$USER"/debpkgs/ "$localnet.$hostip":debpkgs/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Projects...${normal}"
  rsync -avzh --delete /home/"$USER"/Projects/ "$localnet.$hostip":Projects/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing homepage...${normal}"
  rsync -avzh --delete /home/"$USER"/homepage/ "$localnet.$hostip":homepage/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing MOSFANET...${normal}"
  rsync -avzh --delete /home/"$USER"/Documents/mosfanet/ "$localnet.$hostip":Documents/mosfanet/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Blogs...${normal}"
  rsync -avzh --delete /home/"$USER"/Documents/Blogs/ "$localnet.$hostip":Documents/Blogs/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Dreams...${normal}"
  rsync -avzh --delete /home/"$USER"/Documents/Dreams/ "$localnet.$hostip":Documents/Dreams/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Finance...${normal}"
  rsync -avzh --delete /home/"$USER"/Documents/Finance/ "$localnet.$hostip":Documents/Finance/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing HomeBank...${normal}"
  rsync -avzh --delete /home/"$USER"/Documents/HomeBank/ "$localnet.$hostip":Documents/HomeBank/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing HomeBank archives...${normal}"
  rsync -avzh --delete /home/"$USER"/Downloads/archives/homebank/ "$localnet.$hostip":Downloads/archives/homebank/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Journals...${normal}"
  rsync -avzh --delete /home/"$USER"/Documents/Journals/ "$localnet.$hostip":Documents/Journals/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Work...${normal}"
  rsync -avzh --delete /home/"$USER"/Work/ "$localnet.$hostip":Work/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Templates...${normal}"
  rsync -avzh --delete /home/"$USER"/Templates/ "$localnet.$hostip":Templates/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Pictures/wallpaper...${normal}"
  rsync -avzh --delete /home/"$USER"/Pictures/wallpaper/ "$localnet.$hostip":Pictures/wallpaper/
  exit_status="$?"
  transfer_status "$exit_status"
}

all_done() {
  print_line "-" 27
  echo "- All directories synced! -"
  print_line "-" 27
  leave "Script completed in $(format_time $SECONDS)"
}

## Execution ##

# Start timer
SECONDS=0

# Assign IP address to HOSTIP
valid_ip "$1" && hostip="$1"

echo "${bold}${orange}$_script: Synchronizing directories to $localnet.$hostip${normal}"
echo "Version $_version ($_updated)"

case $hostip in
  1|2|3|4|5|6|7|8|9|16 )
    echo -n "${orange}Warning!${normal} $localnet.$hostip is a restricted address."
    echo -e " Access denied.\n"
    exit ;;
  * )
    sync_script
    all_done ;;
esac

exit
