#!/usr/bin/env bash
###############################################################################
# Script Name  : SyncIt
# Description  : A script to sync to local machines on SSH enabled network
# Dependencies : rsync
# Arguments    : Last octet of the local network address
# Author       : Copyright (C) 2017, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 08 Dec 2017 (original script downloaded from EzeeLinux.com)
# Last updated : 04 Feb 2025
# Comments     : Based on script by Joe Collins.
#              : LOCALNET is declared in functionlib
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

# Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

## Global Variables ##

SECONDS=0

## Functions ##

transfer_status() {
  local xfr_status="$1"
  # Exit script if transfer fails.
  (( xfr_status != 0 )) && die "A transfer failed! Check network status."
}

sync_script() {
  local exit_status hostip
  hostip="$1"

  echo $'\n'$"${orange}Syncing aliases...${normal}"
  rsync -avh --delete /home/"$USER"/.bash_aliases "$LOCALNET.$hostip":
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing bin...${normal}"
  rsync -avh --delete --exclude '.git' /home/"$USER"/bin/ "$LOCALNET.$hostip":bin/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing debpkgs...${normal}"
  rsync -avh --delete /home/"$USER"/debpkgs/ "$LOCALNET.$hostip":debpkgs/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Projects...${normal}"
  rsync -avh --delete --exclude '.git' /home/"$USER"/Projects/ "$LOCALNET.$hostip":Projects/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing homepage...${normal}"
  rsync -avh --delete --exclude '.git' /home/"$USER"/homepage/ "$LOCALNET.$hostip":homepage/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing MOSFANET...${normal}"
  rsync -avh --delete /home/"$USER"/Documents/mosfanet/ "$LOCALNET.$hostip":Documents/mosfanet/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Work...${normal}"
  rsync -avh --delete /home/"$USER"/Work/ "$LOCALNET.$hostip":Work/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Templates...${normal}"
  rsync -avh --delete /home/"$USER"/Templates/ "$LOCALNET.$hostip":Templates/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Pictures/wallpaper...${normal}"
  rsync -avh --delete /home/"$USER"/Pictures/wallpaper/ "$LOCALNET.$hostip":Pictures/wallpaper/
  exit_status="$?"
  transfer_status "$exit_status"
}

## Execution ##

main() {
  local host_ip script version
  script=$(basename "$0")
  version="3.0.25035"
  valid_ip "$1" && host_ip="$1"
  check_package rsync
  echo "${bold}${orange}Synchronizing directories to $LOCALNET.$host_ip${normal}"
  case "$hostip" in
    1|2|3|4|5|6|7|8|9 )
      printf "%s %s.%s is a restricted address. Access denied.\n" "$RED_WARNING" "$LOCALNET" "$host_ip" ;;
    * )
      sync_script "$host_ip"
      printf "All directories synced!\n"
  esac
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
