#!/usr/bin/env bash
##########################################################################
# Script Name  : sync2vm
# Description  : Synchronize .bash_aliases, ~/bin to VM
# Dependencies : rsync
# Arguments    : none
# Author       : Richard B. Romig, 08 Feb 2022
# Email        : rick.romig@gmail.com
# Comments     : Run frmo KVM/QEMU VM on 192.168.122.0 network
#              : Copy script to ~/.local/bin on virtual machine.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.1.5"
readonly _updated="26 Oct 2022"
readonly host_ip="$localnet.1"

## Functions ##

transfer_status() {
  # Exit script if transfer fails.
  xfr_status="$1"
  (( xfr_status != 0 )) && die "A transfer failed! Check network status."
}

sync_script() {
	printf "\n%sSyncing .bash_aliases ...%s\n" "$orange" "$normal"
	rsync -avh --delete rick@"$host_ip":.bash_aliases "$HOME/"
	exit_status="$?"
	transfer_status "$exit_status"
	printf "\n%sSyncing bin directory ...%s\n" "$orange" "$normal"
	rsync -avh --delete --exclude '.git' rick@"$host_ip":bin/ "$HOME/bin/"
	exit_status="$?"
	transfer_status "$exit_status"
}

all_done() {
  box "All directories synced!" "-"
  leave "Script completed in $(format_time $SECONDS)"
}

## Execution ##

[[ "$localnet" != "192.168.122" ]] && die "Must be run from a KVM/QEMU virtual machine."
check_package rsync
SECONDS=0
box "$_script v$_version ($_updated)"
sync_script
all_done
leave ""
