#!/usr/bin/env bash
###############################################################################
# Script Name  : SyncIt
# Description  : A script to sync to local machines on SSH enabled network
# Dependencies : rsync
# Arguments    : Last octet of the local network address
# Author       : Richard Romig, Joe Collins
# Email        : rick.romig@gmail.com
# Created      : unknown
# Last updated : 15 Oct 2024
# Comments     : Based on script by Joe Collins.
#              : LOCALNET is declared in functionlib
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

# Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

SECONDS=0

## Functions ##

transfer_status() {
  local xfr_status="$1"
  # Exit script if transfer fails.
  (( xfr_status != 0 )) && die "A transfer failed! Check network status."
}

sync_script() {
  local exit_status hostip
  hostip="$1"

  echo $'\n'$"${orange}Syncing aliases...${normal}"
  rsync -avh --delete /home/"$USER"/.bash_aliases "$LOCALNET.$hostip":
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing bin...${normal}"
  rsync -avh --delete /home/"$USER"/bin/ "$LOCALNET.$hostip":bin/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing debpkgs...${normal}"
  rsync -avh --delete /home/"$USER"/debpkgs/ "$LOCALNET.$hostip":debpkgs/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Projects...${normal}"
  rsync -avh --delete /home/"$USER"/Projects/ "$LOCALNET.$hostip":Projects/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing homepage...${normal}"
  rsync -avh --delete /home/"$USER"/homepage/ "$LOCALNET.$hostip":homepage/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing MOSFANET...${normal}"
  rsync -avh --delete /home/"$USER"/Documents/mosfanet/ "$LOCALNET.$hostip":Documents/mosfanet/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Blogs...${normal}"
  rsync -avh --delete /home/"$USER"/Documents/Blogs/ "$LOCALNET.$hostip":Documents/Blogs/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Dreams...${normal}"
  rsync -avh --delete /home/"$USER"/Documents/Dreams/ "$LOCALNET.$hostip":Documents/Dreams/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Finance...${normal}"
  rsync -avh --delete /home/"$USER"/Documents/Finance/ "$LOCALNET.$hostip":Documents/Finance/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing HomeBank...${normal}"
  rsync -avh --delete /home/"$USER"/Documents/HomeBank/ "$LOCALNET.$hostip":Documents/HomeBank/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing HomeBank archives...${normal}"
  rsync -avh --delete /home/"$USER"/Downloads/archives/homebank/ "$LOCALNET.$hostip":Downloads/archives/homebank/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Journals...${normal}"
  rsync -avh --delete /home/"$USER"/Documents/Journals/ "$LOCALNET.$hostip":Documents/Journals/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Work...${normal}"
  rsync -avh --delete /home/"$USER"/Work/ "$LOCALNET.$hostip":Work/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Templates...${normal}"
  rsync -avh --delete /home/"$USER"/Templates/ "$LOCALNET.$hostip":Templates/
  exit_status="$?"
  transfer_status "$exit_status"

  echo $'\n'$"${orange}Syncing Pictures/wallpaper...${normal}"
  rsync -avh --delete /home/"$USER"/Pictures/wallpaper/ "$LOCALNET.$hostip":Pictures/wallpaper/
  exit_status="$?"
  transfer_status "$exit_status"
}

all_done() {
  box "All directories synced!" "-"
  leave "Script completed in $(format_time $SECONDS)"
}

## Execution ##

main() {
  local host_ip script version
  script=$(basename "$0")
  version="2.8.24289"

  echo "${bold}${orange}Synchronizing directories to $LOCALNET.$host_ip${normal}"
  valid_ip "$1" && host_ip="$1"
  case $hostip in
    1|2|4|5|6|7|8|9 )
      printf "%s %s.%s is a restricted address. Access denied.\n" "$RED_WARNING" "$LOCALNET" "$host_ip"
      exit 1
    ;;
    * )
      sync_script "$host_ip"
      all_done
  esac
  over_line "$script v$version"
  exit
}

## Execution ##

main "$@"
