#!/usr/bin/env bash
#############################################################################
# Script Name  : sync-home
# Description  : Synchronize ~/Documents/homepage with ~/Dropbox/homepage
# Dependencies : rsync zip
# Arguments    : none
# Author       : Copyright © 2023 Richard B. Romig, 24 Sep 2019
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comments     : Creates a zipped archive of the folder's contents.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
#############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091,SC2088

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.5.1"
readonly _updated="28 Apr 2023"
readonly homepage_dir=$HOME"/Documents/homepage"
readonly dropbox_dir=$HOME"/Dropbox/homepage/"

## Functions ##

check_dependencies() {
  local packages=( rsync zip )
  check_packages "${packages[@]}"
}

remove_bu_files() {
  printf "Removing backup files (if any)...\n"
  find "$homepage_dir"/ -name "*~" -delete
  find "$homepage_dir"/ -maxdepth 1 -type f -name "*.bak" -exec rm{} \;
}

update_zip_file() {
  printf "Updating homepage archive...\n"
  rm "$homepage_dir"/homepage.zip
  zip -q "$homepage_dir"/homepage.zip "$homepage_dir"/*
}

## Execution ##

check_dependencies
SECONDS=0
printf "%s v%s (%s)\n\n" "$_script" "$_version" "$_updated"
remove_bu_files
update_zip_file
printf "Synchronizing ~/Documents/homepage with ~/Dropbox/homepage...\n"
rsync -av --delete "$homepage_dir"/ "$dropbox_dir"/
printf "\nScript completed in %s\n" "$(format_time $SECONDS)"
exit
