#!/usr/bin/env bash
##########################################################################
# Script Name  : system-info
# Description  : Gathers system information and writes to a file in home directory
# Dependencies : dmidecode, hdparm, lshw, tune2fs, nvme-cli, ieee-data, wmctrl
# Arguments    : none
# Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 15 Jul 2022
# Updated:     : 24 Jan 2026
# Comments     : Should be run locally, not remotely.
#              : Will not get desktop session info in an SSH connection.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##
if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

check_dependencies() {
	local packages=( lshw ieee-data wmctrl )
  check_packages "${packages[@]}"
  [[ -b /dev/sda ]] && check_package hdparm
  [[ -c /dev/nvme0 ]] && check_package nvme-cli
}

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by a variable name or in a trap.
cleanup() {
  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
  [[ -f "$hd_data" ]] && rm -f "$hd_data"
}

save_info() {
  local main_host="hp-800g2-ssf"
  printf "\n"
  if default_yes "Save system information to ~/${info_file##*/}"; then
    printf "Writing system information to ~/%s\n" "${info_file##*/}"
    cp -v "$tmp_file" "$info_file"
    chmod 664 "$info_file"
    default_yes "Copy ${info_file##*/} to $main_host?" && send_to_main
  else
    printf "System information was not written to ~/%s\n" "${info_file##*/}"
  fi
}

send_to_main() {
  local main_ip ip_addr
  ip_addr=$(local_ip)
  main_ip="10"
  [[ "$ip_addr" != "$main_ip" ]] && scp -p "$info_file" rick@"$LOCALNET.$main_ip":Documents/mosfanet/Computers/info/
}

rename_mnt_pt() {
  local ts_drv _opt
  # ts_drv=$(mount | awk '/timeshift/ {print $3}' | cut -d' ' -f1)
  ts_drv=$(awk '/timeshift/ {print $3}' <(mount))
  printf "\nRename the mountpoint for %s to:\n" "$ts_drv"
  PS3="Select the appropriate mountpoint: "
  select _opt in "/home" "/data" "/ (root)" "/run/timeshift/backup"; do
    case $REPLY in
      1 )
        sed -i '/timeshift/s/run\/timeshift\/backup/home/' "$tmp_file"
        printf "%s mountpoint changed to /home\n" "$ts_drv"
        break ;;
      2 )
        sed -i '/timeshift/s/run\/timeshift\/backup/data/' "$tmp_file"
        printf "%s mountpoint changed to /data\n" "$ts_drv"
        break ;;
      3 )
        sed -i '/timeshift/s/run\/timeshift\/backup//' "$tmp_file"
        printf "%s mountpoint changed to /\n" "$ts_drv"
        break ;;
      4 )
        printf "%s mountpoint left as is." "$ts_drv"
        break ;;
      * )
        printf "%s Invalid choice! Select 1, 2, 3, or 4\n" >&2 "$RED_ERROR"
    esac
  done
}

ff_fix() {
  local _opt options hd_ff
  printf "Form factor not displayed in Hard Disk Information.\n" >&2
  PS3="Select form factor: " >&2
  options=( "2.5 inch" "3.5 inch" "less than 1.8 inch" "ignore")
  select _opt in "${options[@]}"; do
    case "$REPLY" in
      1 )
        hd_ff="2.5 inch"
        break ;;
      2 )
        hd_ff="3.5 inch"
        break ;;
      3 )
        hd_ff="less than 1.8 inch"
        break ;;
      4 )
        :
        break ;;
      * )
        printf "%s Invalid choice! Choose 1, 2, 3, or 4\n" >&2 "$RED_ERROR"
    esac
  done
  echo "$hd_ff"
}

mfg_info() {
  local dmi_dir mfg_version mfg_serial
	dmi_dir="/sys/class/dmi/id"
	mfg_version=$(< $dmi_dir/product_version)
	[[ "${mfg_version// }" ]] || mfg_version="Not specified"
	mfg_serial=$(sudo cat $dmi_dir/product_serial)
	[[ "${mfg_serial// }" ]] || mfg_serial="Not specified"
	printf "%-14s %s\n" "Manufacturer:" "$(< $dmi_dir/sys_vendor)"
	printf "%-14s %s\n" "Product name:" "$(< $dmi_dir/product_name)"
	printf "%-14s %s\n" "Version:" "$mfg_version"
	printf "%-14s %s\n" "Serial number:" "$mfg_serial"
}

os_info() {
  local desktop root_part created_date
  desktop="$DESKTOP_SESSION"
  [[ "$desktop" == "bunsenlabs" || "$desktop" == "lightdm-xsession" ]] && desktop=$(awk '/Name/ {print $2}' <(wmctrl -m))
  root_part=$(awk '$NF == "/" {print $1}' <(df -P))
	created_date=$(awk '/created:/ {print $(NF-2),$(NF-3),$NF}' <(sudo /usr/sbin/tune2fs -l "$root_part"))
	printf "\n%-19s %s\n" "Operating System:" "$(uname -o)"
	printf "%-19s %s\n" "Distribution:" "$(get_distribution)"
  printf "%-19s %s\n" "Desktop:" "${desktop^}"
	printf "%-19s %s\n" "Filesystem created:" "$created_date"
}

cpu_info() {
  local arch model threads
  model=$(awk -F: '/Model name:/ {print $NF}' <(/usr/bin/lscpu) | sed 's/^[[:space:]]*//g;s/([^)]*)//g')
  arch=$(awk '/Architecture:/ {print $NF}' <(/usr/bin/lscpu))
  threads=$(awk 'NR == 5 {print $NF}' <(/usr/bin/lscpu))
	printf "\n%-9s %s, %s, %s threads \n" "CPU:" "$model" "$arch" "$threads"
}

memory_info() {
  local mem_max mem_type phys_mem
	phys_mem=$(awk '/System/ {print $(NF-2)}' <(sudo /usr/bin/lshw -class memory -short -quiet) | sed 's/GiB/ GB/')
	# mem_type=$(awk '/Type:/ {print $NF; exit}' <(sudo dmidecode --type 17))
  mem_type=$(awk 'NR == 16 {print $NF}' <(sudo dmidecode --type 17))
	# mem_max=$(awk -F: '/Capacity/ {print $NF; exit}' <(sudo dmidecode --type 16))
  mem_max=$(awk -F: 'NR == 10 {print $NF}' <(sudo dmidecode --type 16) | sed 's/^ //')
	printf "%-9s %s %s (%s maximum)\n" "Memory:" "$phys_mem" "$mem_type" "$mem_max"
}

graphics_info() {
	printf "%-9s %s\n" "Graphics:" "$( awk -F: '/VGA/ {print $NF}' <(/usr/bin/lspci) | sed 's/^ //')"
}

mac_mfgr() {
  local mac_addr mfgr oui_addr oui_file
  mac_addr="${1^^}"
  oui_file="/usr/share/ieee-data/oui.csv"
	oui_addr=$(cut -d ':' -f1,2,3 <<< "$mac_addr" | sed 's/://g')
  mfgr=$(grep -m 1 "$oui_addr" "$oui_file" | cut -d',' -f3 )
  [[ "$mfgr" ]] || mfgr="Unknown"
  echo "$mfgr"
}

wired_info() {
  local eth_int ethernet_dev e_mac e_man
	eth_int=$(awk '/name: e/ {print $NF}' <(sudo /usr/bin/lshw -class network -quiet))
	if [[ "$eth_int" ]]; then
		ethernet_dev=$(awk -F: '/Ethernet controller/ {print $NF}' <(/usr/bin/lspci) | sed 's/^ //')
		e_mac=$(< /sys/class/net/"${eth_int}"/address)
		e_man=$(mac_mfgr "$e_mac")
		printf "\nEthernet: %s\n" "$ethernet_dev"
    printf "%15s %s\n" "Device name:" "$eth_int" "MAC address:" "$e_mac" "Manufacturer:" "$e_man"
	fi
}

wireless_info() {
  local wifi_int wireless_dev w_mac w_man
	wifi_int=$(awk '/name: w/ {print $NF}' <(sudo /usr/bin/lshw -class network -quiet))
	if [[ "$wifi_int" ]]; then
		wireless_dev=$(awk -F: '/Network controller/ {print $NF}' <(/usr/bin/lspci) | sed 's/^ //')
		w_mac=$(< /sys/class/net/"${wifi_int}"/address)
		w_man=$(mac_mfgr "$w_mac")
		printf "\nWireless: %s\n" "$wireless_dev"
	  printf "%15s %s\n" "Device name:" "$wifi_int" "MAC address:" "$w_mac" "Manufacturer:" "$w_man"
	fi
}

ssd_hd_info() {
  local disk hd_ff hd_rpm model
	printf "\nHard Disk Information:\n"
	for disk in /dev/sd[a-z]; do
		sudo hdparm -I "${disk}" 2>/dev/null | tee "$hd_data" > /dev/null
    printf "%s\n" "$(sed 's/\/dev\///;s/:$//' <(grep -w dev "$hd_data"))"
    model="$(sed 's/^ *//g' <(awk -F: '/Model/ {print $NF}' "$hd_data"))"
    vendor="$(get_vendor "$model")"
    printf "   %-15s%s\n" "Vendor:" "$vendor"
    printf "   %-15s%s\n" "Model Number:" "$model"
    printf "   %-15s%s\n" "Serial Number:" "$(sed 's/^ *//g' <(awk -F: '/Serial N/ {print $NF}' "$hd_data"))"
    printf "   %-15s%s\n" "Capacity:" "$(awk '/GB/ {print $(NF-1),$NF}' "$hd_data" | tr -d '()')" # sed 's/[)(]//g')"
    hd_ff=$(sed 's/^ //' <(awk -F: '/Form Factor/ {print $NF}' "$hd_data"))
    [[ "$hd_ff" ]] || hd_ff=$(ff_fix)
    printf "   %-15s%s" "Form Factor:" "$hd_ff"
    hd_rpm=$(sed 's/^ //' <(awk -F: '/Rotation/ {print $NF}' "$hd_data"))
    case "$hd_rpm" in
      [0-9]* ) printf " %s-rpm Hard Disk Drive\n" "$hd_rpm" ;;
      * ) printf " %s\n" "$hd_rpm"
    esac
	done
}

nvme_info() {
  local nvme_data devline model
  printf "\nNVMe Information:\n"
  nvme_data=$(sudo /usr/sbin/nvme list | tail -n+3)
  for devline in "${nvme_data[@]}"; do
    printf "%s\n" "$(echo "$devline" | awk '/dev/ {print $1}' | cut -d'/' -f3)"
    model="$(echo "$devline" | awk '/dev/ {print $4,$5}' | sed 's/ [0-9].*$//')"
    printf "   %-15s%s\n" "Vendor:" "$(get_vendor "$model")"
    printf "   %-15s%s\n" "Model Number:" "$model"
    printf "   %-15s%s\n" "Serial Number:" "$(echo "$devline" | awk '/dev/ {print $3}')"
    printf "   %-15s%s\n" "Capacity:" "$(echo "$devline" | awk '/dev/ {print $(NF-7),$(NF-6)}')"
  done
}

# shellcheck disable=SC2001
# See if you can use ${variable//search/replace} instead. (This eliminates all whitespace in the string)
get_vendor() {
  local model="${1^^}"
  local id
	declare -rA vendor_list=(
		[CS]="PNY"
		[CT]="Crucial"
		[DT]="HGST (Hitachi)"
		[HD]="Toshiba"
		[MD]="Toshiba"
		[MG]="Toshiba"
		[MK]="Toshiba"
		[MQ]="Toshiba"
		[HS]="Samsung"
		[HT]="HGST (Hitachi)"
		[MT]="Micron"
		[SD]="SanDisk"
		[ST]="Seagate"
		[WD]="Western Digital"
	)
  model="$(sed 's/[[:space:]]*$//' <(echo "$model"))"
  [[ "$model" =~ [[:space:]]+ ]] && model="$(cut -d' ' -f2 <(echo "$model"))"
  id="$(cut -c1-2 <(echo "$model"))"
	printf "%s" "${vendor_list[$id]}"
}

partition_info() {
	printf "\nPartition Information:\n"
	/usr/bin/lsblk -o NAME,SIZE,TYPE,ROTA,MOUNTPOINT,MODEL,SERIAL
}

battery_info() {
  local battery_name battery_path battery_data battery_serial
  printf "\nBattery Information:\n"
  battery_name=$(find /sys/class/power_supply/ -name "BAT*" | awk -F/ '/BAT/ {print $5}')
  if [[ "$battery_name" ]]; then
    battery_path="/sys/class/power_supply/$battery_name"
    battery_data=$(< "$battery_path"/uevent)
    battery_serial=$(awk -F= '/SERIAL/ {print $NF}' <(echo "$battery_data"))
    [[ -z "$battery_serial" || "$battery_serial" == " " ]] && battery_serial="Not specified"
    printf "%s\n" "$battery_name"
    printf "   %-15s%s\n" "Manufacturer:" "$(awk -F= '/MANUFACTURER/ {print $NF}' <(echo "$battery_data") | sed 's/^ //')"
    printf "   %-15s%s\n" "Model name:" "$(awk -F= '/MODEL/ {print $NF}' <(echo "$battery_data"))"
    printf "   %-15s%s\n" "Serial number:" "$battery_serial"
    printf "   %-15s%s\n" "Technology:" "$(awk -F= '/TECHNOLOGY/ {print $NF}' <(echo "$battery_data"))"
  else
    printf "No battery detected\n"
  fi
}

main() {
  local -r script="${0##*/}"
  local -r version="5.1.26024"
  local -r lhost="${HOSTNAME:-$(hostname)}"
  local -r info_file="$HOME/$lhost.info"

  tmp_file=$(mktemp -q) || die "Failed to create temporary file." 1
  trap cleanup EXIT
  sudo_login 2
  check_dependencies
  clear
  {
	  printf "System information for %s, as of %(%d %B %Y)T\n\n" "$lhost"
	  mfg_info
	  os_info
	  cpu_info
	  memory_info
	  graphics_info
	  wired_info
	  wireless_info
    if [[ -b /dev/sda ]]; then
      hd_data=$(mktemp -q) || die "Failed to create temporary file." 1
      ssd_hd_info
    fi
    [[ -c /dev/nvme0 ]] && nvme_info
	  partition_info
	  is_laptop && battery_info
	  printf "\n%s v%s\n" "$script" "$version"
  } | tee "$tmp_file"

  # Change lsblk timeshift mountpoint to normal partition name.
  grep -q '/run/timeshift/backup' "$tmp_file" && rename_mnt_pt
  # Save system info to file in the home directory?
  save_info
  exit
}

## Execution ##

main "$@"
