#!/usr/bin/env bash
#####################################################################
# Script Name  : system-status
# Description  : Displays a snapshot of system resources
# Dependencies : jq, lm-sensors, sensors
# Arguments    : none
# Author       : Copyright (C) 2018,Richard Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 17 Nov 2018
# Updated      : 23 Jan 2026
# Comments     : Inspired by Joe Collins and Luke Smith
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#####################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

check_drivetemp() {
  grep -qw drivetemp <(sensors) || sudo modprobe drivetemp
  grep -qw drivetemp /etc/modules || echo drivetemp | sudo tee -a /etc/modules
  printf "drivetemp module - [OK]\n"
  sleep 1
  printf '\e[A\e[K'
}

check_dependencies() {
  local packages=( jq lm-sensors )
  check_packages "${packages[@]}"
  # Check drivetemp modules for SATA drives.
  [[ -b /dev/sda ]] && check_drivetemp
}

memory_usage() {
	printf "\n%sMemory usage:%s %s\n" "$orange" "$normal" "$(awk '/^Mem:/ {print $3 " / " $2}' <(/usr/bin/free -h) | sed 's/i//g')"
  printf "%sProcess%s\t\t%sPercentage%s\n" "$underline" "$normal" "$underline" "$normal"
	ps axch -o cmd:15,%mem --sort=-%mem | head -n 5
}

cpu_usage() {
  local cores cpu_usage cpu_use
  cores="$(grep -c "^processor" /proc/cpuinfo)"
  cpu_usage="$(awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}' <(ps aux))"
  cpu_use="$((${cpu_usage/\.*} / ${cores:-1}))"
	printf "\n%sCPU usage: %s%s%%\n" "$orange" "$normal" "$cpu_use"
  printf "%sProcess%s\t\t%sPercentage%s\n" "$underline" "$normal" "$underline" "$normal"
  ps axch -o cmd:15,%cpu --sort=-%cpu | head -n 5
}

cpu_temperature(){
  local sensor_json="$1"
	if grep -q 'k10temp-pci-00c3' <(echo "$sensor_json"); then
		printf "%-10s%2.1f\U2103 \n" "CPU:" "$(jq -r '."k10temp-pci-00c3"."temp1"."temp1_input"' <(echo "$sensor_json"))"
	elif grep -q 'dell_smm-virtual-0' <(echo "$sensor_json"); then
		printf "%-10s%2.1f\U2103 \n" "CPU:" "$(jq -r '."dell_smm-virtual-0"."CPU"."temp1_input"' <(echo "$sensor_json"))"
	elif grep -q 'Package id 0' <(echo "$sensor_json"); then
		printf "%-10s%2.1f\U2103 \n" "CPU:" "$(jq -r '."coretemp-isa-0000"."Package id 0"."temp1_input"' <(echo "$sensor_json"))"
	elif grep -q 'Core 0' <(echo "$sensor_json"); then
		printf "%-10s%2.1f\U2103 \n" "CPU:" "$(jq -r '."coretemp-isa-0000"."Core 0"."temp2_input"' <(echo "$sensor_json"))"
  else
    printf "%-10sNot available\n" "CPU:"
	fi
}

gpu_temperature() {
  # Only machines 10, 12, and 22 display GPU temperature.
  local sensor_json="$1"
  if grep -q 'nouveau-pci-0100' <(echo "$sensor_json"); then
    printf "%-10s%2.1f\U2103 \n" "GPU:" "$(jq -r '."nouveau-pci-0100"."temp1"."temp1_input"' <(echo "$sensor_json"))"
  elif grep -q 'pch_skylake-virtual-0' <(echo "$sensor_json"); then
    printf "%-10s%2.1f\U2103 \n" "GPU:" "$(jq -r '."pch_skylake-virtual-0"."temp1"."temp1_input"' <(echo "$sensor_json"))"
  else
    printf "%-10sNot available\n" "GPU:"
  fi
}

nvme_temperature() {
	local drive drv_name sensor_json
  sensor_json="$1"
	for drive in /dev/nvme0n[0-9]; do
		drv_name=$(awk -F/ '{print $NF}' <(echo -n "$drive"))
		if grep -q 'nvme-pci-0300' <(echo "$sensor_json"); then
			printf "%-10s%2.1f\U2103 \n" "$drv_name:" "$(jq -r '."nvme-pci-0300"."Composite"."temp1_input"' <(echo "$sensor_json"))"
    else
      printf "%-10sNot available\n" "$drv_name:"
		fi
	done
}

sata_temperature() {
	local drive drv_name sensor_json
  sensor_json="$1"
	for drive in /dev/sd[a-z]; do
		drv_name=$(awk -F/ '{print $NF}' <(echo -n "$drive"))
		if grep -q 'drivetemp-scsi-0-0' <(echo "$sensor_json"); then
			printf "%-10s%2.1f\U2103 \n" "$drv_name:" "$(jq -r '."drivetemp-scsi-0-0"."temp1"."temp1_input"' <(echo "$sensor_json"))"
		elif grep -q 'drivetemp-scsi-1-0' <(echo "$sensor_json"); then
			printf "%-10s%2.1f\U2103 \n" "$drv_name:" "$(jq -r '."drivetemp-scsi-1-0"."temp1"."temp1_input"' <(echo "$sensor_json"))"
		elif grep -q 'drivetemp-scsi-2-0' <(echo "$sensor_json"); then
			printf "%-10s%2.1f\U2103 \n" "$drv_name:" "$(jq -r '."drivetemp-scsi-2-0"."temp1"."temp1_input"' <(echo "$sensor_json"))"
    else
      printf "%-10sNot available\n" "$drv_name:"
		fi
	done
}

disk_usage() {
	printf "\n%sDisk usage:%s\n" "$orange" "$normal"
  sed -n '1p;/^\//p' <(/usr/bin/df -hT -x fuse.portal)
}

show_header() {
  local local_host="${HOSTNAME:-$(hostname)}"
  printf "%s%sSystem Status%s\n" "$bold" "$lightyellow" "$normal"
  printf "%s%-16s%s\n" "$orange" "Computer name:" "$local_host"
  printf "%-16s%s\n" "Distribution:" "$(get_distribution)"
  printf "%-16s%s%s\n" "Kernel version:" "$(uname -sr)" "$normal"
}

show_footer() {
  local last_boot up_time
  local -r script="${0##*/}"
  local -r version="6.13.26023"
  last_boot=$(awk '{print $(NF-1),$NF}' <(/usr/bin/who -b))
  up_time=$(cut -d' ' -f2- <(/usr/bin/uptime -p))
  printf "\n%sUp since:%s %s (%s)\n" "$orange" "$normal" "$last_boot" "$up_time"
  over_line "$script $version"
  exit
}

main() {
  check_dependencies
  local sensor_json
  sensor_json="$(sensors -j 2>/dev/null)"
  show_header
  memory_usage
  cpu_usage
	printf "\n%sTemperatures:%s\n"  "$orange" "$normal"
  cpu_temperature "$sensor_json"
  gpu_temperature "$sensor_json"
  [[ -c /dev/nvme0 ]] && nvme_temperature "$sensor_json"
  [[ -b /dev/sda ]] && sata_temperature "$sensor_json"
  disk_usage
  show_footer
}

## Execution ##

main "$@"
