#!/usr/bin/env bash

# Up -- Debian/Ubuntu Update Tool (Version 1.3)
# Advanced command to fully update system: "up" Adding the option "--clean" will
# remove orphaned packages and auto-clean the apt cache. (January, 2018)
# Adding the option "--remove" will just reomve orphaned packages.
# By Joe Collins www.ezeelinux.com (GNU/General Public License version 2.0)
# Modified to use functionlib functions by R. Romig
# 07-10-21 - Added command to purge leftover files after old kernel removal.
# 02-23-22 - Replaced if-elif... with while getopts and case statements.
# ...And way we go!

##### Added by R. Romig #####
## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

# Check for less utility and install if needed:

check_package less  # Added by R. Romig
###################

# Set BASH to quit script and exit on errors:

set -e

## Functions ##

upgrade() {
  echo "${greeen}Starting full system update...${normal}"
  sudo apt update
  sudo apt full-upgrade -yy
}

clean() {
  echo "${greeen}Removing apt cache packages that can no longer be downloaded...${normal}"
  sudo apt autoclean
}

remove() {
  echo "${greeen}Removing orpahned packages...${normal}"
  sudo apt autoremove -yy
  echo "${greeen}Purging obsolete linux kernel configuration files...${normal}"
  # Purge obsolete linux kernel configuration files
  # sudo apt remove --purge "$(dpkg -l | grep -E '^rc' | awk '{print $2}')" -yy
  for i in $(dpkg -l | grep "^rc" | awk '{print $2}'); do sudo apt remove --purge "$i" -yy; done
}

leave_up() {
  print_line "-" 20 # Added by R. Romig
  echo "- Update Complete! -"
  print_line "-" 20 # Added by R. Romig
  echo "Script completed in $(format_time $SECONDS)"  # Added by R. Romig
  exit
}

up_help() {
  less << EOF

 Up -- Debian/Ubuntu Update Tool (Version 1.3)  -help

 Up is a tool that automates the update procedure for Debian and Ubuntu based
 Linux systems.

 Press "q" to exit this Help page.

 Commands:
    up -r = full system update. Will update the apt cache and then perform a
    full distribution update.

    up -r = full system update with orphaned packages removed.
    up -c = full system update with full cleanup.

    Adding the "-c" option will invoke the apt commands to search for and
    remove locally cached packages that are no longer in the repositories and
    remove orphaned packages that are no longer needed by programs.

    The "-r" option only removes orphaned packages, leaving the apt cache alone.

    up -h = shows this help page.

 By Joe Collins www.ezeelinux.com (GNU/General Public License version 2.0)
 Additional modifications by Rick Romig

 Disclaimer:

 THIS SOFTWARE IS PROVIDED BY EZEELINUX “AS IS” AND ANY EXPRESS OR IMPLIED
 WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
 EVENT SHALL EZEELINUX BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 POSSIBILITY OF SUCH DAMAGE.

EOF
}

## Execution ##

SECONDS=0 # Added by R. Romig

# Tell 'em who we are...

echo "Up -- Debian/Ubuntu Update Tool (Version 1.3++)"

# Replaced Joe's nested if-elif-else construct with getopts - R. Romig

if [[ $# -eq 0 ]]; then
  echo "${lightred}ERROR:${normal} No argument passed." >&2
  up_help
  exit 1
else
  optstr=":chru"
  while getopts "$optstr" opt; do
    case "$opt" in
      c )
        upgrade
        remove
        clean
        leave_up ;;
      h )
        up_help
        exit ;;
      r )
        upgrade
        remove
        leave_up ;;
      u )
        upgrade
        leave_up ;;
      ? )
        echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
        up_help
        exit 2 ;;
    esac
  done
fi
# Default action if no options given
# upgrade
# leave_up # Added by R. Romig
