#!/usr/bin/env bash
###############################################################################
# Script Name  : up
# Description  : Debian/Ubuntu Update Tool (Version 1.3)
# Dependencies : none
# Arguments    : -c -f -h -r -u (See up_help for more info)
# Author       : Copyright (C) 2023, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
# Created      : 29 Mar 2023
# Last updated : 21 Apr 2023
# Comments     : Original scrlipt by Joe Collins www.ezeelinux.com
#              : Heavily modified by Rick Romig
# TODO (Rick)  : 
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

set -e

## Functions ##

upgrade() {
  printf "%sStarting full system update...%s\n" "${green}" "${normal}"
  if exists nala; then
    run_nala
  else
    sudo apt update
    sudo apt full-upgrade -yy
  fi
}

clean() {
  printf "%sRemoving apt cache packages that can no longer be downloaded...%s\n" "${green}" "${normal}"
  sudo apt autoclean
}

remove() {
  printf "%sRemoving orpahned packages...%s\n" "${green}" "${normal}"
  sudo apt autoremove -yy
  rcpkgs=$(dpkg -l | awk '/^rc/ {print $2}' | wc -l)
  if [[ "$rcpkgs" -gt 0 ]]; then
    printf "%sPurging obsolete linux kernel configuration files...%s\n" "${green}" "${normal}"
    for i in $(dpkg -l | grep "^rc" | awk '{print $2}'); do sudo apt remove --purge "$i" -yy; done
  fi
}

run_nala() {
  printf "Running nala...\n"
  sudo nala upgrade
  printf "\n"
}

leave_up() {
  box "Update Complete!" "*"  # Added by R. Romig
  printf "Script completed in %s\n" "$(format_time $SECONDS)"
  exit
}

up_help() {
  less << EOF

 Up -- Debian/Ubuntu Update Tool (Version 2.0)

 Up is a tool that automates the update procedure for Debian and Ubuntu based  Linux systems.

 Press "q" to exit this Help page.

 Commands:
    up -u = full system update. Update the apt cache & perform a full distribution update.
    up -f = full system update with full cleanup.
    up -c = full system update with cleanup of the apt cache.
    up -r = full system update with only orphaned packages removed.
    up -h = shows this help page.

 Original scrlipt by Joe Collins, www.ezeelinux.com (GNU/General Public License version 2.0)
 Additional modifications by Rick Romig, MosfaNet

 Disclaimer:

 THIS SOFTWARE IS PROVIDED BY EZEELINUX “AS IS” AND ANY EXPRESS OR IMPLIED
 WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
 EVENT SHALL EZEELINUX BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 POSSIBILITY OF SUCH DAMAGE.

EOF
}

## Execution ##

readonly _version="2.1"
SECONDS=0 # Added by R. Romig

printf "Up -- Debian/Ubuntu Update Tool (Version %s)\n" "$_version"
printf "(Joe Collins and Rick Romig\n)"

noOpt=1
optstr=":cfhru"
while getopts "$optstr" opt; do
  case "$opt" in
    c )
      upgrade
      clean
      leave_up
    ;;
    f )
      upgrade
      remove
      clean
      leave_up
    ;;
    h )
      up_help
      exit
    ;;
    r )
      upgrade
      remove
      leave_up
    ;;
    u )
      upgrade
      leave_up
    ;;
    ? )
      printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
      up_help
      exit 2
  esac
  noOpt=0
done
# Default action if no options given
[[ "$noOpt" = 1 ]] && { upgrade; leave_up; }
