#!/usr/bin/env bash
##########################################################################
# Script Name  : upper2lower
# Description  : Renames uppercase in filenames to lowercase
# Dependencies : rename
# Args         : --all, --help, filename(s) to be renamed
# Author       : Copyright © 2018, Richard Romig
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 2018
# Updated      : 07 Feb 2026
# Comment      :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

readonly script="${0##*/}"
readonly version="3.5.26038"
EC=0

## Functions ##

help() {
	local errcode="${1:-1}"
	local updated="07 Feb 2026"
	cat << _HELP_
${orange}$script${normal} $version, Upated: $updated
Renames filenames in the current directory to all lowercase.

${green}Usage:${normal} $script [--all] [--help] [filename1] ...
${orange}Options:${normal}
  --all    Change all files in the current directory to lowercase.
  --help   Show this help message and exit
One or more filenames may be entered to be renamed.
$script filename.txt	# Rename filename to lowercase
$script Filename1.txt Filename2.txt	# Rename Filename1 and Filename2 to lowercase
_HELP_
  exit "$errcode"
}

upper_to_lower() {
	local filename="$1"
	if [[ -f "$filename" ]]; then
		rename -v 'y/A-Z/a-z/' "$filename"
	else
		printf "%s %s not found.\n" "$RED_ERROR" "$filename" >&2
		EC="$E_FILENOTFOUND"
	fi
}

lc_all() {
	printf "Renaming all files in the current directory to lowercase.\n"
	find . -maxdepth 1 -type f -exec rename -v 'y/A-Z/a-z/' {} + | sed 's/\.\///g'
}

lc_one() {
	local file_name
	file_name="$1"
	printf "Renaming %s to lowercase.\n" "$file_name"
	upper_to_lower "$file_name"
}

lc_selected() {
	printf "Renaming selected files to lowercase.\n"
	for file_name in "$@"; do
		upper_to_lower "$file_name"
	done
}

main() {
	local file_name
	if [[ $# -eq 0 ]]; then
		printf "%s No argument passed.\n" "$RED_ERROR" >&2
		help "$E_MISSING_ARG"
	elif [[ $# -eq 1 ]]; then
		case "$1" in
			-a|--all )
				lc_all
				;;
			-h|--help )
				help 0
				;;
			-* )
				printf "%s Invalid argument, %s\n" "$RED_ERROR" "$1" >&2
				help "$E_INVALID_ARG"
				;;
			* )
				file_name="$1"
				lc_one "$file_name"
		esac
	else
		lc_selected "$@"
	fi
	over_line "$script $version"
	exit "$EC"
}

## Execution ##

main "$@"
