#!/usr/bin/env bash
###############################################################################
# Script Name  : verify-iso
# Description  : Verifies SHA1, SHA256, SHA512, and MD5 checksums of ISO files
# Dependencies : fzf
# Arguments    : none (-h or --help for usage and requirements)
# Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Crated       : 09 Apr 2022
# Updated      : 09 Aug 2026
# Version      : 13.2.26221
# Comments     : Each ISO file must have its own checksum file.
#              : Checksum file must be one line only for ISO being checked.
#              : Checksum files must have one of the following extensions:
#              : .md5, sha1, .sha256, or .sha512
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
################################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

# shellcheck source=/home/rick/bin/functionlib.bash
source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

readonly FMENU="fzf --header=Verifiy-ISO \
  --layout=reverse \
  --exact \
  --border=bold \
  --border=rounded \
  --margin=5% \
  --color=dark \
  --height=95% \
  --info=hidden \
  --header-first \
  --bind change:top \
  --prompt"
SPIN_PID=

help() {
	local -r script="$1"
	local -r version="$2"
	local -ri errcode="${3:-1}"
	local -r updated="08 Aug 2026"
	cat << _HELP_
${orange}$script${normal} $version, Updated: $updated
Verifies SHA1/SHA256/SHA512/MD5 checksums for ISO files.
${green}Usage:${normal} $script [-h | --help ]
${orange}Available options:${normal}
  -h | --help  Show this help message and exit
${orange}Requirements:${normal}
  * Checksum files must be a single line specifically for the ISO file you wish to check.
  * Checksum files must have a file extension of .md5, .sha1, .sha256, or .sha512.
  * The basename of the checksum file should match the basename name of the ISO (without the extension).

_HELP_
  exit "$errcode"
}

select_directory() {
	local -r iso_dir="$1"
	local dist_d selected_dir
	local iso_dirs=()
	for dist_d in $iso_dir; do
		if [[ -L "$iso_dir" ]]; then
			iso_dirs+=("$(sort -d < <(find -L "$dist_d" -maxdepth 2 -type d -print))")
		else
			iso_dirs+=("$(sort -d < <(find "$dist_d" -maxdepth 2 -type d -print))")
		fi
	done
	selected_dir=$($FMENU "Select distribution directory: " < <(printf "%s\n" "${iso_dirs[@]}"))
	printf "%s" "$selected_dir"
	return 0
}

select_iso() {
	local -r iso_d="$1"
	local selected_iso
	local iso_files=()
	for iso_files in $iso_d; do
		iso_files+=("$(sort -d < <(find "$iso_d" -type f -name "*.iso" -printf "%f\n"))")
	done
	selected_iso=$($FMENU "Select ISO file: " < <(printf "%s\n" "${iso_files[@]}"))
	printf "%s" "$selected_iso"
	return 0
}

select_checksum() {
	local -r iso_d="$1"
	local selected_chksum
	local chksum_files=()
	for chksum_files in $iso_d; do
		[[ -d "$iso_d" ]] && chksum_files+=("$(sort -d < <(find "$iso_d" -type f \( -name "*.md5" -or -name "*.sha*" \) -printf "%f\n"))")
	done
	selected_chksum=$($FMENU "Select Checksum file: " < <(printf "%s\n" "${chksum_files[@]}"))
	printf "%s" "$selected_chksum"
	return 0
}

verify_checksums() {
	local -r iso="$1"
	local -r checksum="$2"
	local -r ext="${checksum##*.}"
	local iso_sum chk_sum
	printf "Verifying checksums.\n"
	spin &
  SPIN_PID="$!"
	case "$ext" in
		md5 )
			iso_sum=$(awk '{print $1}' < <(/usr/bin/md5sum "$iso")) ;;
		sha1 )
			iso_sum=$(awk '{print $1}' < <(/usr/bin/sha1sum "$iso")) ;;
		sha256 )
			iso_sum=$(awk '{print $1}' < <(/usr/bin/sha256sum "$iso")) ;;
		sha512 )
			iso_sum=$(awk '{print $1}' < <(/usr/bin/sha512sum "$iso")) ;;
	esac
	chk_sum=$(awk '{print $1}' "$checksum")
  kill_spin
  printf '\e[A\e[K'	# removes 'Verifying checksums' line
	printf "ISO checksum:\n\t%s\n" "$iso_sum"
	printf "%s checksum:\n\t%s\n" "${ext^^}" "$chk_sum"
	[[ "$iso_sum" == "$chk_sum" ]] && return "$TRUE" || return "$FALSE"
	return 0
}

status_msg() {
  local -ri status="${1:-0}"
  if [[ "$status" -eq 0 ]]; then
		printf "%sThe checksums match.%s\n" "$green" "$normal"
		return 0
  else
		printf "%sThe checksums do not match.%s\n" "$lightred" "$normal"
		printf "Verify checksum with the ISO download site.\n"
		return "$E_FILE_ERROR"
  fi
}

check_checksum() {
  local -r file="$1"
	local lines
  lines=$(wc -l < "$file")
  [[ "$lines" -eq 1 ]] && return "$TRUE" || return "$FALSE"
}

check_extension() {
	local -r chksum_ext="${1##*.}"
	case "$chksum_ext" in
		md5|sha1|sha256|sha512 ) return "$TRUE" ;;
		* ) return "$FALSE"
	esac
}

verify_iso() {
	local checksum isofile iso_dir
	local -r isoDir=~/Downloads/ISO
	# Select ISO, ISO file, and checksum file...
	[[ -d "$isoDir" ]] || { printf "%s The main ISO directory not found.\n" "$RED_ERROR" >&2; return "$E_FILENOTFOUND"; }
	iso_dir=$(select_directory "$isoDir")
	[[ "$iso_dir" ]] || { printf "%s No ISO directory selected.\n" "$RED_ERROR" >&2; return "$E_MISSING_ARG"; }
	isofile=$(select_iso "$iso_dir")
	[[ "$isofile" ]] || { printf "%s No ISO file selected.\n" "$RED_ERROR" >&2; return "$E_MISSING_ARG"; }
	checksum=$(select_checksum "$iso_dir")
	[[ "$checksum" ]] || { printf "%s No checksum file selected.\n" "$RED_ERROR" >&2 return "$E_MISSING_ARG"; }
	# Dipslay selected information...
	printf "Verifies SHA1/SHA256/SHA512/MD5 checksums for ISO files.\n"
	printf "\n%-18s %s\n" "Selected Distro:" "${iso_dir##*/}"
	printf "%-18s %s\n" "Selected ISO:" "$isofile"
	printf "%-18s %s\n\n" "Selected Checksum:" "$checksum"
	# Check if checksum file extension is correct and checksum is a single line...
	if ! check_extension "$checksum"; then
		printf "%s Invalid checksum extension.\nExtension must be one of the following: .md5 .sha1 .sha256 .sha512\n" "$RED_ERROR" >&2
		return "$E_INVALID_ARG"
	fi
	if ! check_checksum "$iso_dir/$checksum"; then
		printf "%s Too many lines in checksum file.\n" "$RED_ERROR" >&2
		printf "Reduce the file to a single line corresponding to the selected ISO.\n" >&2
		return "$E_FILE_ERROR"
	fi
	# Check ISO and checksum files...
	verify_checksums "$iso_dir/$isofile" "$iso_dir/$checksum"
	local -i status="$?"
	status_msg "$status"
}

main() {
	local -r script="${0##*/}"
	local -r version="13.2.26221"
	local -i exit_code=0
	[[ "$1" == "-h" || "$1" == "--help" ]] && help "$script" "$version" 0;
	check_package fzf
	verify_iso
	exit_code="$?"
  over_line "$script $version" "-"
	exit "$exit_code"
}

main "$@"
