#!/usr/bin/env bash
###############################################################################
# Script Name  : vidcam-check
# Description  : Checks for Webcam
# Dependencies : None
# Arguments    : None
# Author       : Copyright © 2021 Richard Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 2021
# Updated      : 03 Oct 2024
# Comment      :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

vid_cam() {
  /usr/bin/lsusb | grep -iqsw Webcam && return "$TRUE" || return "$FALSE"
}

main() {
  local script version
  script=$(basename "$0")
  version="2.2.24277"
  printf "Checks to see if a web cam is available.\n"
  if vid_cam; then
    printf "Available Webcams:\n"
    /usr/bin/lsusb | grep -iw Webcam | cut -d' ' -f7-
  else
    printf "No attached webcam found.\n"
  fi
  over_line "$script v$version" "-"
  exit
}

## Execution ##

main "$@"
