#!/usr/bin/env bash
###############################################################################
# Script Name  : vidcam-check
# Description  : Checks for Webcam
# Dependencies : None
# Arguments    : None
# Author       : Copyright © 2021 Richard Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Comment      :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.2.0"
readonly _updated="19 May 2023"

## Functions ##

vid_cam() {
  /usr/bin/lsusb | grep -qs Webcam && return "$TRUE" || return "$FALSE"
}

## Execution ##

printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
printf "Checks to see if a web cam is available.\n"
if vid_cam; then
  printf "Available Webcams:\n"
  /usr/bin/lsusb | grep -w Webcam | cut -d' ' -f7-
else
  printf "No attached webcam found.\n"
fi
exit
