#!/usr/bin/env bash
###############################################################################
# Script Name  : webcam-check
# Description  : Checks for Webcam & displays Webcam information
# Dependencies : None
# Arguments    : None
# Author       : Copyright © 2021 Richard Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 2021
# Updated      : 01 Jul 2025
# Comment      :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

webcam_present() {
  /usr/bin/lsusb | grep -iqsw Webcam && return "$TRUE" || return "$FALSE"
}

main() {
  local script version
  script="${0##*/}"
  version="4.0.25182"
  if webcam_present; then
    /usr/bin/lsusb | grep -iw Webcam
  else
    printf "No webcam found.\n"
  fi
  over_line "$script $version" "-"
  exit
}

## Execution ##

main "$@"
