#!/usr/bin/env bash
##########################################################################
# Script Name  : webcam-check
# Description  : Checks for Webcam & displays Webcam information
# Dependencies : None
# Arguments    : None
# Author       : Copyright © 2021 Richard Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 2021
# Updated      : 21 Jun 2026
# Comment      :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
##########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
##########################################################################

## Load function library ##
# shellcheck source=/home/rick/bin/functionlib
source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }

main() {
  local -r script="${0##*/}"
  local -r version="4.5.26172"
  grep -iw webcam < <(/usr/bin/lsusb) || printf "No webcam found.\n"
  over_line "$script $version" "-"
  exit
}

main "$@"
