#!/usr/bin/env bash
##########################################################################
# Script Name  : write-iso
# Description  : Copies an ISO file to a USB drive using dd
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2023, Richard B. Romig, 18 Feb 2023
# Email        : rick.romig@gmail.com | rick.romig@mykmetronet.net
# Comments     : Run script from directory containing the ISO file.
#              : Testing indicates USB drive should not be unmounted.
# TODO (Rick)  :
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091,SC2034

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="0.2.5"
readonly _updated="23 Jul 2023"

## Functions ##

write_dd() {
	local iso="$1"
	local usb="$2"
  # Assumes no other removable media is mounted to /media/$USER
 	printf "Writing %s to /dev/%s...\n" "$iso_file" "$usb_drive"
	if sudo dd if="$iso" of="/dev/$usb" bs=16M status=progress oflag=sync; then
	  printf "%s written to /dev/%s.\n" "$iso" "$usb"
  else
    printf "%s write to /dev/%s failed.\n" "$iso" "$usb" >&2
  fi
}

## Execution ##

printf "%s v%s (%s)\n" "$_script" "%_version" "$_updated"
printf "Writes ISO to a USB drive.\n"
[[ $(lsblk -S -o TRAN | grep 'usb') = *usb* ]] || die "No USB drive connected." 1

# List ISO files and select
printf "\nAvailable ISO files in %s:\n" "$PWD"
ls ./*.iso > /dev/null 2>&1 || diehard "No ISO files found." "Change to a directory containing ISO files."
find ./ -maxdepth 1 -type f -name "*.iso" -print | sed 's/\.\///'
read -rp "ISO file to write: " iso_file

# List devices and select
printf "\nChoose a USB drive:\n"
lsblk -o NAME,SIZE,TYPE,HOTPLUG | awk '/disk/ {print $1,$2,$4}'
printf "A '1' in the 3rd column indicates the drive is a removable device (USB).\n"
read -rp "USB device to write to (sdX): " usb_drive
printf "You selected /dev/%s. If you continue, all data will be erased from this device.\n\n" "$usb_drive"
echo -e "Answer 'yes' only if you are ${bold}${orange}ABSOLUTELY${normal} sure you want to proceed.\n"

while true; do
  read -rp "Write $iso_file to /dev/$usb_drive? " yn
  case "$yn" in 
    yes )
      user_in_sudo
      write_dd "$iso_file" "$usb_drive"
      break
    ;;
    no )
      printf "Operation canceled. No action taken.\n"
      break
    ;;
    * )
      printf "%s Invalid choice. Enter yes or no.\n" "$red_error" >&2
  esac
done
exit
