#!/usr/bin/env bash
##########################################################################
# Script Name  : write-iso
# Description  : Writes an ISO image to a USB drive using dd
# Dependencies : fzf
# Arguments    : see help function
# Author       : Copyright (C) 2023, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 18 Feb 2023
# Updated      : 06 Sep 2026
# Version      : 14.4.26249
# Comments     : Testing indicates USB drive needs to be mounted.
#              : To test without writing to USB drive, dnter -d or --dryrun option to enable a dry run.
#              : After a dryrun, USB drive will remain mounted.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
################################################################################
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
###############################################################################

# shellcheck source=/home/rick/bin/functionlib.bash
source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }

readonly FMENU="fzf --header=Write-ISO \
  --layout=reverse \
  --exact \
  --border=bold \
  --border=rounded \
  --margin=5% \
  --color=dark \
  --height=95% \
  --info=hidden \
  --header-first \
  --bind change:top \
  --prompt"
DRYRUN="$FALSE"

help() {
	local -r script="$1"
	local -r version="$2"
	local -ri errcode="${3:-1}"
	local -r updated="06 Sep 2026"
	cat << _HELP_
${orange}$script${normal} $version, Upated: $updated
Writes an ISO image to a USB drive

${green}Usage:${normal} $script [OPTION]
${orange}Available options:${normal}
  -d | --dryrun  Enable Dry Run simulation
  -h | --help    Show this help message and exit
_HELP_
  exit "$errcode"
}

select_directory() {
	local -r isoDir="$1"
	local dist_d selected_dir
	local iso_dirs=()
	for dist_d in $isoDir; do
		if [[ -L "$isoDir" ]]; then
			iso_dirs+=("$(sort -d < <(find -L "$dist_d" -maxdepth 2 -type d -print))")
		else
			iso_dirs+=("$(sort -d < <(find "$dist_d" -maxdepth 2 -type d -print))")
		fi
	done
	selected_dir=$($FMENU "Select distribution directory: " < <(printf "%s\n" "${iso_dirs[@]}"))
	printf "%s" "$selected_dir"
	return 0
}

select_iso() {
	local -r iso_d="$1"
	local selected_iso
	local iso_files=()
	for iso_files in $iso_d; do
		iso_files+=("$(sort -d < <(find "$iso_d" -type f -iname "*.iso" -printf "%f\n"))")
	done
	selected_iso=$($FMENU "Select ISO file: " < <(printf "%s\n" "${iso_files[@]}"))
	printf "%s" "$selected_iso"
	return 0
}

select_usb() {
	local usb_device
	usb_device=$(awk '$2 == "disk" && $1 == "1" {print $2,$3,$4,$5}' < <(lsblk -o HOTPLUG,TYPE,NAME,SIZE,LABEL) | $FMENU "Select the USB drive to write to: ")
	usb_device=$(awk '{print $2}' <<< "$usb_device")
	echo "$usb_device"
	return 0
}

mount_usb() {
	local -r mount_name="$1"
	local -r usbpart="$2"
	[[ -d "/media/$USER/$mount_name" ]] || sudo mkdir -p "/media/$USER/$mount_name"
	sudo mount "/dev/$usbpart" "/media/$USER/$mount_name" 2>/dev/null
	printf "USB drive /dev/%s is mounted at /media/$USER/%s\n" "$usbpart" "$mount_name"
	return 0
}

unmount_usb() {
	local -r mount_name="$1"
	local -r usbpart="$2"
	sudo umount "/dev/$usbpart" && printf "USB drive unmounted.\n" # /media/$USER/"$mount_name"
	[[ -d "/media/$USER/$mount_name" ]] && sudo rmdir "/media/$USER/$mount_name"
	pgrep -x nemo >/dev/null && nemo --quit	# If Nemo is running, close it.
	printf "It's now safe to remove the USB drive.\n"
	return 0
}

list_usb_contents() {
	local -r usbpart="$1"
	local drvlabel
	drvlabel=$(awk -v pat="$usbpart" -F/ '$0 ~ pat {print $NF}' < <(lsblk))
	printf "\nContents of /dev/%s:\n" "$usbpart"
	printf "Disk label: %s\n" "$drvlabel"
	ls -F "/media/$USER/$drvlabel"
	return 0
}

simulate_dd() {
	local -r iso="$1"
	local -r usb="$2"
	local -r mount_name="$3"
	printf "\n%sPerforming a dryrun simulation.\n" "$orange"
	printf "The ISO will NOT be written to USB drive.%s\n" "$normal"
	printf "\nWriting %s to /dev/%s (%sSIMULATED%s) ...\n" "${iso##*/}" "$usb" "$lightyellow" "$normal"
	dd if="$iso" of=/dev/null bs=16M status=progress
	printf "%s written to /dev/%s (%sSIMULATED%s)\n" "${iso##*/}" "$usb" "$lightyellow" "$normal"
	return 0
}

write_dd() {
	local -r iso="$1"
	local -r usb="$2"
	local -r mount_name="$3"
	printf "\nWriting %s to /dev/%s...\n" "${iso##*/}" "$usb"
	if sudo dd if="$iso" of="/dev/$usb" bs=16M status=progress oflag=sync; then
	  printf "%s written to /dev/%s.\n" "${iso##*/}" "$usb"
		return 0
	else
		printf "%s %s write to /dev/%s failed.\n" "$RED_ERROR" "$iso" "$usb"
		return "$E_FILE_ERROR"
	fi
}

select_iso_usb() {
	local -r isoDir="$1"
	local iso_dir iso_file usb_device
	iso_dir=$(select_directory "$isoDir")
	[[ "$iso_dir" ]] || { printf "%s No ISO directory selected.\n" "$RED_ERROR" >&2; return "$E_MISSING_ARG"; }
	iso_file=$(select_iso "$iso_dir")
	[[ "$iso_file" ]] || { printf "%s No ISO file selected.\n" "$RED_ERROR" >&2; return "$E_MISSING_ARG"; }
	usb_device=$(select_usb)
	[[ "$usb_device" ]] || { printf "%s No USB drive selected.\n" "$RED_ERROR" >&2; return "$E_MISSING_ARG"; }
	write_iso "$iso_dir/$iso_file" "$usb_device"
	return "$?"
}

write_iso() {
	local -r isofile="$1"
	local -r usbdevice="$2"
	local -i code=0
	local usbpart usbsize mount_name
	usbsize=$(awk -v pat="$usbdevice" '$0~pat{print$4;exit}' < <(lsblk))
	printf "%-16s %s\n" "Selected ISO:" "${isofile##*/}"
	printf "%-16s /dev/%s [%s]\n" "Selected device:" "$usbdevice" "$usbsize"
	# Mount selected USB drive if not already mounted.
	usbpart="${usbdevice}1"
	if grep -q "$usbpart" < <(mount) >/dev/null 2>&1; then
		mount_name=$(grep "$usbpart" < <(lsblk) | cut -d'/' -f4- )
	else
		sudo_login 2
		mount_name="$(date +%y%b%d)"
		mount_usb "$usbpart"
	fi
	# List contents of USB drive
	list_usb_contents "$usbpart" # "$mount_name"
	# Simulate dd write of ISO to USB drive
	if [[ "$DRYRUN" == "$TRUE" ]]; then
		simulate_dd "$isofile" "$usbdevice" "$mount_name"
		return "$code"
	fi
	# Confirm action or cancel actual dd write of ISO to USB drive
	printf "\n%sIf you continue, ALL data will be erased from device %s.%s\n\n" "$orange" "$usbdevice" "$normal"
	printf "Answer 'yes' only if you are %s%sABSOLUTELY%s sure you want to proceed.\n\n" "$bold" "$orange" "$normal"
	if yes_or_no "Write ${isofile##*/} to /dev/$usb_device?"; then
		sudo_login 2
		write_dd "$isofile" "$usbdevice" "$mount_name"
		code="$?"
		grep -q "/dev/$usbpart" < <(mount) > /dev/null 2>&1 && unmount_usb "$mount_name" "$usbpart"
	else
		printf "Operation canceled. No action taken.\n"
	fi
	return "$code"
}

main() {
	local -r script="${0##*/}"
	local -r version="14.4.26249"
	local -i exit_code=0
	local -r isoDir=~/Downloads/ISO
	case "$1" in
		-h | --help ) help "$script" "$version" 0 ;;
		-d | --dryrun ) DRYRUN="$TRUE" ;;
		* ) printf "Invalid option (ignored)\n"
	esac
	box "$script $version" "-"
	printf "Writes an ISO image to a USB drive.\n\n"
	check_package fzf
	[[ $(grep 'usb' < <(lsblk -S -o TRAN)) = *usb* ]] || die "No USB drive connected." "$E_NOT_DETECTED"
	[[ -d "$isoDir" ]] || die "Main ISO directory not found." "$E_FILENOTFOUND"
	select_iso_usb "$isoDir"
	exit_code="$?"
	over_line "$script $version"
	exit "$exit_code"
}

main "$@"
