#!/usr/bin/env bash
###############################################################################
# Script Name  : yt-dl-audio
# Description  : Download mp3 audio from YouTube.com to current directory
# Dependencies : yt-dlp
# Arguments    : Video URL or ID number
# Author       : Copyright © 2019, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 14 Nov 2019
# Updated      : 28 Jun 2024
# Comments     : Accepts both full URLs and video id's such as AQcQgfvfF1M
#              : Downloads to current working directory
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
  exit 1
fi

## Variables ##

_script=$(basename "$0"); readonly _script
readonly _version="2.1.24180"
readonly _updated="28 Jun 2024"

## Functions

help() {
  local errcode="${1:-2}"
  cat << END_HELP
${orange}$_script${normal} $_version, Updated: $_updated
Downloads mp3 audio from YouTube videos to current working diretory.

${green}Usage:${normal} $_script [OPTION] [video-url] [video-ID]

${orange}Available options:${normal}
  -h | --help  Show this help text.

$_script https://www.youtube.com/watch?v=8hLlU0EML4U
$_script 8hLlU0EML4U

END_HELP
  exit "$errcode"
}


check_dependencies() {
  if [ -x /usr/local/bin/yt-dlp ]; then
    printf "yt-dlp [OK]\n"
    sleep 2
  else
    die "yt-dlp is not installed." 1
  fi
}

## Execution ##

check_dependencies

# Check arguments
if [[ "$#" = 0 ]]; then
  echo "${lightred}Error:${normal} No argument passed." >&2
  help 2
elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
  help 0
elif [[ "$1" =~ ^https?:\/\/.* ]]; then
  # match by regex, starts with http:// or https://
  url=$*
else
  # match by video ID
  url="https://www.youtube.com/watch?v=$*"
fi

# Execution

clear
box "$_script v$_version" "*"
under_line "* YouTube Audio Download *" "*"
echo $'\n'$"Downloading mp3 audio for $url"
echo "Destination: $PWD"
if /usr/local/bin/yt-dlp --add-metadata -xic --embed-thumbnail --restrict-filename --audio-format mp3 --output "%(title)s.%(ext)s" "$url"; then
  leave "Download successful."
else
  die "Download failed." "$?"
fi
