#!/usr/bin/env bash
#####################################################################
# Script Name  : z-backup
# Description  : local backup of /etc, /home, and /data/installations
#              : to a designated folder on a second internal drive.
# Dependencies : rsync
# Arguments    : none
# Author       : Copyright (C) 2020, Richard Romig, 07 Jun 2020 
# Email        : rick.romig@gmail.com
# Comment      : Automatically limits log size to 30 entries.
# Last updated : 19 Nov 2023 - version 1.1.2
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
#####################################################################

set -e

log_date=$(date +"%a|%F|%R")
log_dir="/var/log"
log_file="backup.log"
err_log="/data/backup/error.log"

rm -f /data/backup/Local\ Backup* >/dev/null 2>&1
{
  printf "%s|" "$log_date"
  if rsync -aH --delete /etc /home /data/backup/ 2> "$err_log"; then
    printf "successful\n"
    touch /data/backup/"Local Backup was successful: $(date +%F)"
  else
    printf "had errors %d\n" "$?"
    touch /data/backup/"Local Backup had errors: $(date +%F)"
  fi
  sync
} >> /var/log/backup.log 2>&1

log_len=$(wc -l "$log_dir/$log_file" | cut -d' ' -f1)
[[ "$log_len" -gt 30 ]] && sed -i '1d' "$log_dir/$log_file"

exit
