#!/usr/bin/env sh
###############################################################################
# Script Name  : z-clean-tmp v1.1
# Description  : Removes files from /tmp accessed more than 2 days prior
# Dependencies : find
# Arguments    : None
# Author       : Richard B. Romig, 31 July 2019 (Updated 16 May 2021)
# Email        : rick.romig@gmail.com
# Comments     : Only deletes files in /tmp that are not owned by root.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

set -e

/usr/bin/find /tmp -type f \( ! -user root \) -atime +2 -delete

exit
