#!/usr/bin/env bash
###############################################################################
# Script Name  : z-clean-tmp v1.2
# Description  : Removes files from /tmp accessed more than 2 days prior
# Dependencies : find
# Arguments    : None
# Author       : Copyright (C) 2019, Richard B. Romig, 31 July 2019
# Email        : rick.romig@gmail.com
# Comments     : Only deletes files in /tmp that are not owned by root.
# Last updated : 19 Nov 2023
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

set -euo pipefail

/usr/bin/find /tmp -type f \( ! -user root \) -atime +2 -delete

exit
