#!/usr/bin/env bash
###############################################################################
# Script Name  : z-defrag
# Description  : Script to check defrag condition on spinning drives.
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2021-2023, Richard B. Romig
# Email        : rick.romig@gmail.com
# Comments     : Do not run this e4defrag on SSD or NVME drives.
#              : anacron job: Copy to /etc/cron.monthly as root (or sudo) user
#              : cron job: Copy to /usr/local/bin or /opt/bin as root (or sudo) user
# Last updated : 19 Nov 2023 Version 1.2.6
# License      : GNU General Public License, version 2.0
###############################################################################

set -euo pipefail

log_dir="/var/log"
log_file="defrag.log"
host_name=$(/usr/bin/uname -n)

{
	printf "Defrag Report: %s\n\n" "$(date '+%a %F %R')"
	case "$host_name" in
		hp-800-g1-usdt|hp-probook-6570|e-475m|hp-mini-110 )
			printf "SSD - e4defrag not run.\n"
		;;
		hp-860-g3 )
			printf "NVMe - e4defrag not run.\n"
		;;
		hp-6005 )
			/usr/sbin/e4defrag -c / /home /data
		;;
		hp-800g2-sff )
			printf "/dev/sda is an SSD, e4defrag not run.\n\n"
			/usr/sbin/e4defrag -c /home
		;;
		* )
			/usr/sbin/e4defrag -c / /home
	esac
	printf "\n"
} > "$log_dir/$log_file" 2>&1
[[ -f "$log_dir/$log_file" ]] && sed -i '/^e4defrag/d;/0-30/d;/^ Done/d' "$log_dir/$log_file"
exit
