#!/usr/bin/env sh

set -e

# Script to defrag / and /home partitions.
# Do not run on an SSD.
# Place in /etc/cron.monthly/ for anacron.
# Place in /usr/local/bin/ or /opt/bin/ for cron.
# Last updated: 05 May 2021
# Version 0.9.9
# License : GNU General Public License, version 2.0

log_dir="/var/log"
log_file="defrag.log"

{
  printf "Defrag log: %s\n" "$(date '+%a %F %R')"
  printf "%s\n\n" "$(/usr/bin/uname -n)"
  if [ ! -b /dev/sda ]; then
  	echo "No SATA devices exist on this system.";
  else
    for i in /dev/sd[a-z]; do
    	d=$(basename "$i")
    	if [ "$(cat /sys/block/"${d}"/queue/rotational)" = 0 ]; then
    		d=$(echo "$d" | tr [a-z] [A-Z])
    		printf "%s:\n\tSSD - defrag not run\n" "$d"
    	elif [ "$(cat /sys/block/"${d}"/queue/rotational)" = 1 ]; then
    		d=$(echo "$d" | tr [a-z] [A-Z])
    		printf "%s:\n" "$d"
    		if [ -d '/' ] && [ -d /home ]; then
        	/usr/sbin/e4defrag -c / /home
      	elif [ -d /home ]; then
       		/usr/sbin/e4defrag -c /home
      	elif  [ -d /data ]; then
        	/usr/sbin/e4defrag -c /data
      	else
       		/usr/sbin/e4defrag -c /
      	fi
    	fi
	  done
	fi	  
	printf "\n"
} > "$log_dir/$log_file" 2>&1
# Cleanup log file.
sed -i '/^e4defrag/d;/0-30/d;/^ Done/d' "$log_dir/$log_file"
exit
