#!/bin/sh

set -e

# Update Script
# anacron job: Copy to /etc/cron.weekly as root (or sudo) user
# cron job: Copy to /usr/local/bin or /opt/bin as root (or sudo) user
# Last updated 16 Mar 2023
# License : GNU General Public License, version 2.0

check_flatpak() {
  printf "\\n*** Flatpak ***\\n"
  flatpak update --system --noninteractive --force-remove --assumeyes
}

exists() {
  command -v "$1" > /dev/null 2>&1 && return 0 || return 1
}

log_dir="/var/log"
log_file="update.log"
sed_file="/usr/share/misc/updatelog.sed"

{
  printf "Update started at: %s\\n" "$(date '+%a %F %T')"
  printf "\\n*** Checking for updates ***\\n"
  /usr/bin/apt-get update
  nupd=$(apt-get -s dist-upgrade | grep "^[[:digit:]]\+ upgraded" | cut -d' ' -f1)
  if [ "$nupd" -eq 1 ]; then
    printf "%d package can be upgraded.\\n" "$nupd"
  elif [ "$nupd" -gt 1 ]; then
    printf "%d packages can be upgraded.\\n" "$nupd"
  else
    printf "All packages are up to date.\\n"
  fi
  if [ "$nupd" -gt 0 ]; then
    printf "\\n*** Installing updates ***\\n"
    DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get dist-upgrade -yy
  else
    printf "\\nNothing to update.\\n"
  fi
  printf "\\n*** Cleaning APT cache ***\\n"
  /usr/bin/apt-get autoclean
  printf "\\n*** Removing orphaned packages ***\\n"
  DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get autoremove -yy
  printf "\\n*** Purging obsolete configuration files ***\\n"
  rcpkgs=$(dpkg -l | awk '/^rc/ {print $2}' | wc -l)
  if [ "$rcpkgs" -gt 0 ]; then
    # /usr/bin/apt-get remove --purge "$(dpkg -l | awk '/^rc/ {print $2}')" -yy
    for rcpkg in $(dpkg -l | awk '/^rc/ {print $2}'); do
      DEBIAN_FRONTEND=noninteractive apt-get remove --purge "$rcpkg" -yy
    done
  else
    printf "No files to be purged found.\\n"
  fi
  exists flatpak && check_flatpak
  printf "\\nCompleted at: %s\\n" "$(date '+%a %F %T')"
} > "$log_dir/$log_file" 2>&1

# Clean up log file.
if exists flatpak; then
  sed -i -f "$sed_file" "$log_dir/$log_file"
else
  sed -i '/Reading database/d' "$log_dir/$log_file"
fi
