#!/usr/bin/env bash
###############################################################################
# Script Name  : z-ytdlp-update
# Description  : Updates youtube-dl automatically using anacron
# Dependencies : anacron, yt-dlp (downloaded from GitHub)
# Arguments    : None
# Author       : Copyright (C) 2023, Richard B. Romig, 20 Jun 2023
# Email        : rick.romig@gmail.com
# Comments     : copy as root to /etc/cron.daily
# Last updated : 27 Nov 2023
# License      : GNU General Public License, version 2.0
###############################################################################

set -euo pipefail


# Variables
log_dir="/var/log"
log_file="ytdlpup.log"
# sed_file="/usr/share/misc/ytdlp-uplog.sed"
log_date=$(date '+%F|%R')
update_status=$(/usr/local/bin/yt-dlp --update | awk '/Latest version/ {print $3}' | sed 's/stable@//')
[[ -z "$update_status" ]] && update_status="Update unavailable"

printf "%s|%s\n" "$log_date" "$update_status" >> "$log_dir/$log_file" 2>&1
# sed -i -f "$sed_file" "$log_dir/$log_file"
# Remove top entry if more than 30 entries.
log_len=$(wc -l "$log_dir/$log_file" | cut -d ' ' -f1)
[[ "$log_len" -gt 30 ]] && sed -i '1d' "$log_dir/$log_file"

exit
