#!/bin/sh
###############################################################################
# Script Name  : z-ytdlupdate
# Description  : Updates youtube-dl automatically using anacron
# Dependencies : anacron, awk, sed, youtube-dl
# Arguments    : None
# Author       : Richard B. Romig, 18 July 2019
# Email        : rick.romig@gmail.com
# Comments     : copy as root to /etc/cron.daily
# Last updated : 16 Mar 2023
# License      : GNU General Public License, version 2.0
###############################################################################

set -e

# Variables
log_dir="/var/log"
log_file="ytdlup.log"
sed_file="/usr/share/misc/ytdluplog.sed"
log_date=$(date '+%F|%R')
update_status=$(/usr/local/bin/youtube-dl --update)

# Run youtube-dl update
printf "%s|%s\n" "$log_date" "$update_status" >> "$log_dir/$log_file" 2>&1
# Format log file for column command.
sed -i -f "$sed_file" "$log_dir/$log_file"
# Remove top entry if more than 30 entries.
log_len=$(wc -l "$log_dir/$log_file" | cut -d ' ' -f1)
[ "$log_len" -gt 30 ] && sed -i '1d' "$log_dir/$log_file"

exit
