#!/usr/bin/env bash
###############################################################################
# Script Name  : zz-clean
# Description  : Clean apt cache and remove orphaned packages & obsolete config files.
# Dependencies : None
# Arguments    : None
# Author       : Copyright © 2024, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
# Created      : 28 Dec 2024
# Last updated : 28 Dec 2024
# Comments     : Anacron - copy to /etc/cron.monthly/
#              : Cron - copy to /usr/local/bin/ or /opt/bin/
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

set -eu

purge_configs() {
  local rcpkg
  if dpkg --list | grep -q '^rc'; then
    for rcpkg in $(dpkg -l | awk '/^rc/ {print $2}'); do
      printf "Purging %s...\n" "$rcpkg"
      DEBIAN_FRONTEND=noninteractive apt-get remove --purge "$rcpkg" -yy
    done
  else
    printf "No packages in the 'rc' state to be purged.\n"
  fi
}

autoremove_packages() {
  local npkgs
  npkgs=$(apt-get autoremove -s | grep "^[[:digit:]]\+ upgraded" | cut -d' ' -f6)
  if [[ "$npkgs" -gt 0 ]]; then
    DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get autoremove -yy
  else
    printf "No packages to be removed.\n"
  fi
}

main() {
  local log_dir log_file log_date
  log_dir="/var/log"
  log_file="clean.log"
  log_date=$(date '+%a %F %R')

  {
    printf "Autoclean log: %s\n" "$log_date"
    printf "\nCleaning APT cache...\n"
    DEBIAN_FRONTEND=noninteractive apt-get autoclean
    printf "\nRemoving orphaned packages...\n"
    autoremove_packages
    printf "\nPurging obsolete configuration files\n"
    purge_configs
  } > "$log_dir/$log_file" 2>&1
  exit
}

main "$@"
